# https://docs.netlify.com/configure-builds/ignore-builds/

[build]
  command = "./scripts/build.sh"
  ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF publish"

[cache]

  [[cache.paths]]
    path = "node_modules"

[[headers]]
  for = "/*.xml"

  [headers.values]
    Content-Type = "application/xml; charset=utf-8"
    X-Content-Type-Options = "nosniff"

[[headers]]
  for = "/fonts/*"

  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/images/*"

  [headers.values]
    Cache-Control = "public, max-age=604800, immutable"

[[headers]]
  # This pattern matches any file ending in .css at any level
  for = "/styles/giscus/*.css"

  [headers.values]
    Access-Control-Allow-Origin = "https://giscus.app"

# use my own domain as fediverse handle
# see: https://fed.brid.gy/docs#fediverse-enhanced
[[redirects]]
  from = "/.well-known/host-meta*"
  to = "https://fed.brid.gy/.well-known/host-meta:splat"
  status = 302
[[redirects]]
  from = "/.well-known/webfinger*"
  to = "https://fed.brid.gy/.well-known/webfinger"
  status = 302