#+title: Zine#11
#+INDEX: zine!#11
#+date: <2024-10-07 Mon>
#+lastmod: <2024-10-07 Mon 17:56>
#+author: Spike Leung
#+email: l-yanlei@hotmail.com
#+description: ""
#+tags: zine
#+OPTIONS: toc:1
#+LANGUAGE: zh-CN

* News | Article
:PROPERTIES:
:CUSTOM_ID: 8606934b-eb0a-4d3e-9c56-ae1c852345cb
:END:

** [[https://www.thepsmiths.com/p/review-math-from-three-to-seven-by][REVIEW: Math from Three to Seven, by Alexander Zvonkin]]
:PROPERTIES:
:CUSTOM_ID: cbb48ed5-d62d-4d39-a717-a274e8080097
:END:

#+begin_quote
兹冯金对孩子和成人同样有效的一个方法是，反复重复一些事情，让重复之间间隔很长时间。

这和我自己想弄明白一件事时，会认真思考一段时间，然后出去散步或洗澡的道理是一样的。

你是在劫持认知的集中模式和扩散模式之间的相互作用。

如果每次重复时，你都能从不同的角度来解决问题，那么效果会更好，这样你的潜意识就会有新的材料来咀嚼。
#+end_quote

#+begin_quote
这只是为人父母的普遍经历的极端版本。

从第二个孩子出生的那一刻起，有时甚至在他们出生之前，他们就开始告诉你，你对第一个孩子的人生轨迹所产生的影响是多么微不足道。

他们之间的差异，尽管你们所做的一切几乎都是一样的，却证明了养育孩子的过程实际上是一个无能为力的过程，是一个看着新生命发现并向世界展示自己的过程。

从某种程度上说，这使得正在发生的事情更具有戏剧性--你培养出的不是一个可以编程的白板，而是一个外星智慧生物，它将创造出一个全新的宇宙。
#+end_quote

** [[https://voidzero.dev/posts/announcing-voidzero-inc][Announcing VoidZero - Next Generation Toolchain for JavaScript]]
:PROPERTIES:
:CUSTOM_ID: e7b07542-91f3-496d-be8e-2fba8d735efe
:END:

Vue 的作者尤雨溪宣布了一家新公司 VoidZero 的成立，目前已经筹集了 460 万美元的种子基金，计划打造下一代 JavaScript 工具链。

他们目前交付出来的产品有： [[https://oxc.rs/][Oxc]]， [[https://vitest.dev/][vitest]]， [[https://rolldown.rs/][Rolldown]] 。

感兴趣还可以看看 [[https://viteconf.org/24/replay][ViteConf 2024 Replay]]。

** [[https://papanotes.com/the-best-4-ever-spent][The best $4 ever spent]]
:PROPERTIES:
:CUSTOM_ID: bf337071-3cb9-4036-b021-c4d2b48aa363
:END:

#+begin_quote
"Let's take the bus home!" my daughter said.

What a terrible idea. It would take an hour and two busses to get there, and I would most certainly get a call to come and pick up the car as soon as we'd arrive home. Terrible.

"Ok, let's do it," said I reluctantly. I know how much my daughter enjoys riding the bus. We never do it, so every time feels special.

Seeing how happy she was, it was all worth it—best $4 I've ever spent.

What's something a bit counter-intuitive you could do to delight your child this week?

P.S.: When we finally got home, it was, as anticipated, time to pick up the car. I was planning on taking a taxi but ... Sophie asked if we could ride the bus back there. No regrets!
#+end_quote

虽然乘坐公交时间长也比较麻烦，但是女儿开心，就值了。

** [[https://erikbern.com/2024/09/27/its-hard-to-write-code-for-humans.html][It's hard to write code for computers, but it's even harder to write code for humans]]
:PROPERTIES:
:CUSTOM_ID: 7bee7a6a-ef75-480b-b599-824d597ff576
:END:

#+begin_quote
Feynman famously said: Imagine how much harder physics would be if electrons had feelings.
#+end_quote

#+begin_quote
Getting started shouldn't be an afterthought after you built the product. Getting started is the product!

入门不应该是在构建产品之后才考虑的问题。入门就是产品！

...

Make it possible for users to use your product on their laptop in a couple of minutes, tops.

让用户在几分钟内就能在笔记本电脑上使用您的产品。
#+end_quote

产品要让使用者能快速上手，要是需要配置一堆东西，花半天时间，可能不少用户会放弃使用。

#+begin_quote
Too many programming books and tutorials are like “let’s build a house starting from scratch, brick by brick” when what I want to “here is a functioning house, let’s learn about it by changing something and then seeing what happens”

太多的编程书籍和教程就像“让我们从头开始，一砖一瓦地建造一座房子”，而我想要的是“这里是一座正常运转的房子，让我们通过改变一些东西来了解它，然后看看会发生什么”。
#+end_quote

#+begin_quote
The sad but true part of programming is, the default mode is that you're fixing an error of some sort. This means that users are going to spend the majority of the time with your tool trying to figure out what's not working.

编程的可悲但真实的一面是，默认模式是你在修复某种错误。这意味着用户在使用工具的过程中，大部分时间都在试图找出问题所在。

- Developers getting to success faster are happy developers. They will like your tool. 更快获得成功的开发人员是快乐的开发人员。他们会喜欢你的工具。
- Developers banging their heads against errors are sad developers. They will blame your tool. 在错误面前磕头的开发人员是可悲的开发人员。他们会指责你的工具。

Put code snippets in the exceptions. Emit helpful warnings when users are likely to do something weird. Do what you got to do to make the user succeed.

在异常中加入代码片段。在用户可能做出奇怪举动时发出有用的警告。尽你所能让用户成功。
#+end_quote

如果使用你工具的人总是碰到问题，而且也没有足够的反馈告诉用户如何解决问题，用户就会有很多挫败感，从而放弃使用这个工具。

相反，给用户足够的反馈，尽可能地帮助他们顺利地使用你的工具，用户就会快乐地继续使用你的工具。

#+begin_quote
Every new conceptual thing you have to understand before using the tool makes is a new friction point. If it's 2-3 things, that's fine. But no one is going to bother learning 8 new concepts.

在使用工具之前，你必须了解的每一个新概念东西都是一个新的摩擦点。如果是 2-3 个东西，那还好。但是没有人会去费心学习 8 个新概念。
#+end_quote

避免概念过载，降低用户的心智负担。关于心智负担，可以看看 [[https://github.com/zakirullin/cognitive-load][Cognitive Load is what matters]]。

#+begin_quote
Somewhat related to the previous point, let's say in your framework you introduce a thing that takes some values and evalutes to a new values. What do you call it? A compute node? A valuator? A frobniscator?

No! You call it a function!

与前一点有些关联的是，假设在你的框架中引入了一个东西，它可以获取一些值并求值到一个新值。你怎么称呼它？计算节点？估值器？估值器？

不！你称之为函数！

If it walks like a duck, and it quacks like a duck, it probably is a duck.

如果它走起路来像鸭子，叫起来也像鸭子，那么它可能就是一只鸭子。

Calling it a function means you latch onto a users pre-existing mental model of what a function does. Which will save you like, 90% of the explanation of how to think about this object.

将其称为函数意味着你抓住了用户关于函数作用的已有心智模型。这将省去 90% 的解释工作，让你知道如何看待这个对象。
#+end_quote

#+begin_quote
Unless defaults apply in 97%+ of the time, and unless magic applies 99% of the time, be careful about introducing it. These are not exact numbers obviously, but my point is, you need to be very very judicious.

除非在 97% 以上的情况下使用默认设置，除非在 99% 的情况下使用特殊方法，否则在引入时一定要小心谨慎。这些显然不是精确的数字，但我想说的是，你需要非常非常谨慎。
#+end_quote

#+begin_quote
I sometimes think the challenge of designing for the 1st time user is similar to making a pop song. The producer will listen to the song a thousand times. But still the 999th time they hear it, they need to imagine what it sounds like to a person that hears it the first time, which seems… super hard.

我有时认为，为第一次使用的用户进行设计所面临的挑战与制作一首流行歌曲类似。制作人会听上千遍这首歌。但在第 999 次听到这首歌时，他们仍需要想象第一次听到这首歌的人听起来是什么感觉，这似乎......超级困难。
#+end_quote

** [[https://sohl-dickstein.github.io/2022/11/06/strong-Goodhart.html][Too much efficiency makes everything worse: overfitting and the strong version of Goodhart's law]]
:PROPERTIES:
:CUSTOM_ID: 33e97d24-1075-487f-a4ff-ae85b02b2005
:END:

#+begin_quote
Increased efficiency can sometimes, counterintuitively, lead to worse outcomes. This is true almost everywhere. We will name this phenomenon the strong version of Goodhart's law. As one example, more efficient centralized tracking of student progress by standardized testing seems like such a good idea that well-intentioned laws mandate it. However, testing also incentivizes schools to focus more on teaching students to test well, and less on teaching broadly useful skills. As a result, it can cause overall educational outcomes to become worse.

效率的提高有时会导致更糟糕的结果，这与直觉相反。

这种情况几乎无处不在。我们将这种现象命名为古德哈特定律的强力版本。

举例来说，通过标准化测试对学生的进步进行更有效的集中跟踪似乎是个好主意，以至于用心良苦的法律对此做出了规定。

然而，考试也会激励学校把更多精力放在教学生如何考好考试上，而不是教学生掌握广泛有用的技能。

因此，它可能会导致整体教育成果变得更糟。
#+end_quote

#+begin_quote
Any observed statistical regularity will tend to collapse once pressure is placed upon it for control purposes.

一旦出于控制目的对其施加压力，任何观察到的统计规律性都会趋于崩溃。

[[https://www.wikiwand.com/en/articles/Goodhart%27s_law][Goodhart's law]]
#+end_quote

** [[https://arxiv.org/abs/2008.06030][On the design of text editors]]
:PROPERTIES:
:CUSTOM_ID: c41ff442-f9fe-41f0-b826-c640dc2a3887
:END:

一篇论文，作者提出了一些编辑器的设计思路。

其中，将注释放到左边，让注释更明显的设计感觉不错。

** [[http://literateprogramming.com/index.html][Literate Programming]]
:PROPERTIES:
:CUSTOM_ID: 5d75b436-2b28-4216-9b3d-79e177927b78
:END:

文学编程，我理解就是反转注释和代码的重要性，不再编写包含文档的代码，而是编写包含代码的文档。

#+begin_quote
I believe that the time is ripe for significantly better documentation of programs, and that we can best achieve this by considering programs to be works of literature. Hence, my title: "Literate Programming."

我认为，大幅改进程序文档的时机已经成熟，而将程序视为文学作品是实现这一目标的最佳途径。因此，我的标题是"文学编程"。

Let us change our traditional attitude to the construction of programs: Instead of imagining that our main task is to instruct a computer what to do, let us concentrate rather on explaining to human beings what we want a computer to do.

让我们改变传统的程序设计态度：与其认为我们的主要任务是指导计算机做什么，不如让我们集中精力向人类解释我们希望计算机做什么。

-- Donald Knuth. "Literate Programming (1984)" in Literate Programming. CSLI, 1992, pg. 99.
#+end_quote

** [[https://www.gov.uk/service-manual/technology/using-progressive-enhancement][Building a robust frontend using progressive enhancement]]
:PROPERTIES:
:CUSTOM_ID: cb677ed6-cfba-4528-8835-1ec206f7a5ca
:END:

#+begin_quote
Progressive enhancement is a way of building websites and applications based on the idea that you should make your page work with HTML first.

Only after this can you add anything else like Cascading Style Sheets (CSS) and JavaScript.

渐进增强是一种构建网站和应用程序的方法，它基于这样一种理念，即首先要让页面使用 HTML 运行。

然后才能添加其他内容，如 CSS 和 JavaScript。
#+end_quote

文章提出了一些建议，主要是为了让页面稳健，不容易出错。

#+begin_quote
Progressive enhancement means building the interface of a website or application in layers. If the user’s browser only supports HTML they get content and forms. If the user’s browser also supports styles and fonts the application looks better. If it can run JavaScript the user gains extra interactions. Only the core HTML though is required in order to meet users’ basic needs.

渐进增强意味着分层构建网站或应用程序的界面。

如果用户的浏览器只支持HTML，他们就会得到内容和表单。

如果用户的浏览器还支持样式和字体，应用程序就会看起来更好。

如果它能运行 JavaScript ，用户就能获得额外的交互。

满足用户的基本需求只需要核心的 HTML。

-- [[https://technology.blog.gov.uk/2016/09/19/why-we-use-progressive-enhancement-to-build-gov-uk/][Why we use progressive enhancement to build GOV.UK]]
#+end_quote

** [[https://jimmyhmiller.github.io/raised][Being Raised by the Internet]]
:PROPERTIES:
:CUSTOM_ID: 09978065-e69b-4f32-a931-2fd45f4d38aa
:END:

#+begin_quote
They may not have set out to share out of altrusitic motivations. I am certain they never intended to inspire a 12 year-old kid to find a better life. But it doesn't matter their motivations. They changed my life. All I can say is thank you. Thank you for sharing your work. Thank you for your blogs posts, your tutorials, thank you for your slashdot comments, for your posts on digg. No matter how small your contribution, it mattered to me. You changed my life. Thank you.

他们也许并不是出于利他主义的动机才开始分享的。

我确信他们从未想过要激励一个 12 岁的孩子去寻找更美好的生活。

但他们的动机并不重要。他们改变了我的生活。我只能说谢谢你们。

感谢你们分享自己的作品。感谢你们的博客文章、教程，感谢你们在 slashdot 上的评论，感谢你们在 digg 上的文章。

无论你的贡献有多小，对我来说都很重要。你们改变了我的生活。谢谢你们。

#+end_quote
** [[https://eslint.org/blog/2024/10/eslint-json-markdown-support/][ESLint now officially supports linting of JSON and Markdown]]
:PROPERTIES:
:CUSTOM_ID: 5dcb3a64-f7ee-4508-9d23-2e88cac028b0
:END:

Eslint 现在可以 lint JSON 和 Markdown 了，真不错。


* Tutorial
:PROPERTIES:
:CUSTOM_ID: ceaa3772-1d1c-47a7-8442-23c200c0aee1
:END:

** [[https://www.linuxfromscratch.org/index.html][Linux From Scratch]]
:PROPERTIES:
:CUSTOM_ID: dc6a5940-40d8-4507-b8f6-9f6bf4a34cb0
:END:

#+begin_quote
Linux From Scratch (LFS) is a project that provides you with step-by-step instructions for building your own custom Linux system, entirely from source code.
#+end_quote

** [[https://shipit.dev/posts/from-utterances-to-giscus.html][Moving from utterances to giscus]]
:PROPERTIES:
:CUSTOM_ID: 3bf6ebeb-407f-40a7-959e-9698c853a1a9
:END:

前阵子将评论系统从 utterances 换成了 giscus，参考了这篇文章。

原来 utterances 生成的 issues 可以批量转换成 giscus 的 discussions。（参考 [[https://docs.github.com/en/discussions/managing-discussions-for-your-community/managing-discussions#converting-issues-based-on-labels][Converting issues based on labels]]）

** [YouTube][[https://www.youtube.com/watch?v=JUS6EPMbk0U&ab_channel=devongovett][Bundling Past, Present, and Future]]
:PROPERTIES:
:CUSTOM_ID: b7dfedce-fc19-419d-8ff2-9c882ecf9f54
:END:

关于 bundle 工具的过去、现在和未来。

** [[https://janhesters.com/blog/unleash-javascripts-potential-with-functional-programming][Unleash JavaScript's Potential with Functional Programming]]
:PROPERTIES:
:CUSTOM_ID: 25e8360e-494b-463c-93f9-5f82792710ef
:END:

JS 函数式编程入门，非常多的概念，准备好一杯咖啡再慢慢看吧 :P


* Code
:PROPERTIES:
:CUSTOM_ID: 57a0714e-8292-4263-ae9b-b1a6c90920c5
:END:

** [[https://frontendmasters.com/blog/whats-the-difference-between-htmls-dialog-element-and-popovers/][What’s the Difference Between HTML’s Dialog Element and Popovers?]]
:PROPERTIES:
:CUSTOM_ID: ee7789d2-c274-4310-85e9-0e706a439e15
:END:

[[https://developer.mozilla.org/en-US/docs/Web/HTML/Element/dialog][<dialog>]] 和 [[https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/popover][popover]] 的详尽比较。

** [[https://www.smashingmagazine.com/2024/09/how-manage-dangerous-actions-user-interfaces/][How To Manage Dangerous Actions In User Interfaces]]
:PROPERTIES:
:CUSTOM_ID: b0b382b1-dd1a-485e-ae35-def138056baf
:END:

对于页面上的“危险操作”，如何设计交互。

#+begin_quote
Therefore, a dangerous action does not necessarily mean deleting something.

Some examples may include the following:

- Sending an email
- Placing an order
- Publishing a post
- Making a bank transaction
- Granting or revoking permissions.
- ...
#+end_quote

一种常见的交互是 Modal，在使用 Modal 的时候最好详细描述操作的影响，而不是仅仅一句“你确定吗”，让人摸不着头脑。

有时只是让用户确认还不够，可能还需要用户输入一些内容才允许完成操作，例如 GitHub 删除 Repo 时的交互。

此外文中还提到了其他方法：

- Danger Zone
- Inline Guards
- Two-factor Authorization Confirmation
- Second-person Confirmation (类似 Pull request，需要另一个人的审批)
- ...

最后作者还补充了一个交互更好的例子。

** [[https://css-tricks.com/how-to-make-a-scroll-to-select-form-control/][How to Make a “Scroll to Select” Form Control]]
:PROPERTIES:
:CUSTOM_ID: 5ff9a057-d34d-4264-8bae-1dc4d42feae7
:END:

作者实现了一种滚动选择元素的组件，类似 select。

用到了 [[https://developer.mozilla.org/en-US/docs/Web/CSS/overscroll-behavior][overscroll-behavior]]，[[https://developer.mozilla.org/en-US/docs/Web/CSS/scroll-snap-type][scroll-snap-type]]，[[https://developer.mozilla.org/en-US/docs/Web/API/Intersection_Observer_API][Intersection Observer API]] 等。

** [[https://www.smashingmagazine.com/2024/09/svg-coding-examples-recipes-writing-vectors-by-hand/][SVG Coding Examples: Useful Recipes For Writing Vectors By Hand]]
:PROPERTIES:
:CUSTOM_ID: afb66483-43c3-4d60-80fa-5ba1c8e47ac7
:END:

结合 JS 去绘制 SVG，将一些 SVG 的变量抽离出来定义，用 JS 计算，这样手写 SVG 就会相对容易一点。

** [YouTube][[https://www.youtube.com/watch?v=tnSzkAiiQ4w&ab_channel=KevinPowell][Dynamic numbering with CSS counters]]
:PROPERTIES:
:CUSTOM_ID: 28f911bd-aa0a-43c2-b19b-eabf65f7a674
:END:

关于 [[https://developer.mozilla.org/en-US/docs/Web/CSS/counter][counter()]] 的一些用法，但是其实 [[https://developer.mozilla.org/en-US/docs/Web/CSS/list-style][list-style]] 也能实现类似的功能。

** [[https://9elements.com/blog/building-the-perfect-logo-strip/][Building the Perfect Logo Strip]]
:PROPERTIES:
:CUSTOM_ID: cb991bb2-e4ac-42ef-9e53-cbc869f07dbf
:END:

logo 的高度宽度都不太相同，当把多个 logo 放在一起做成 logo 条的时候，如何让不同 logo 保持视觉上的平衡？

文章提出一种基于 logo 长宽比调整高度的方法。


* Cool Bit
:PROPERTIES:
:CUSTOM_ID: a02c4e6d-baef-49d1-af6e-fa8b3322afb7
:END:

** [[https://2019.makemepulse.com/][make meplse]]
:PROPERTIES:
:CUSTOM_ID: 93ccf744-5e2b-4aba-a356-26d5f8d9055f
:END:

一个手绘风格的网站，画风，音乐，交互都不错。

** [[https://codepen.io/ivorjetski/pen/jOgEyPO][CSS Music Video - No Images - Pure Code.]]
:PROPERTIES:
:CUSTOM_ID: 3ef5295c-9b19-48d8-a04c-23c31d3c4796
:END:

一个用 CSS 实现的音乐视频。

** [[https://aschmelyun.com/blog/getting-my-daily-news-from-a-dot-matrix-printer/][Getting my daily news from a dot matrix printer]]
:PROPERTIES:
:CUSTOM_ID: 541db713-e60c-4238-88ef-d274398ca56e
:END:

作者不想每天看屏幕，恰好买了一个点阵打印机（像是打印发票用的打印机），就想着能不能把每天想看的头条打印在一张纸上。

** [[https://noise.jake.fun/][noise]]
:PROPERTIES:
:CUSTOM_ID: 81c5f800-7afb-4a90-89cc-53baccf06b77
:END:

在屏幕不同的位置，会得到不同频率的噪声。

** [[https://simonwillison.net/2024/Sep/29/notebooklm-audio-overview/][NotebookLM’s automatically generated podcasts are surprisingly effective]]
:PROPERTIES:
:CUSTOM_ID: 59fcaaa5-4723-4559-9762-5c0c740eb2f3
:END:

Google 的一个产品，将一些资料喂给它，它可以生成一段很逼真的播客。

** [[https://github.com/mitoma/kashiki2][炊紙 kashikishi]]
:PROPERTIES:
:CUSTOM_ID: c414c8b4-fe80-4b2e-8965-18c38e80aa71
:END:

炊紙(kashikishi) is a text editor that utilizes GPU to edit text in a 3D space.

编辑交互看起来不错，不过目前只能作为一个方便的记事本，不具备打开和编辑任意文件的功能。


* Tool | Library
:PROPERTIES:
:CUSTOM_ID: f1b02a57-b2c6-4efe-9762-e4168f16d0ff
:END:

** [[https://open-source-license-chooser.toolsnav.top/zh/][开源许可证选择器]]
:PROPERTIES:
:CUSTOM_ID: 1c4cd4bc-c86e-41e1-865a-a49d13b3284c
:END:

通过几个选项，找到满足你需要的许可证。

** [[https://vectorcraftr.com/][vectorcraftr]]
:PROPERTIES:
:CUSTOM_ID: e17e41da-e999-4eb7-969f-d3ce991669ae
:END:

一些免费的插画，种类比较多。

** [[https://github.com/DoneDeal0/superdiff][Superdiff]]
:PROPERTIES:
:CUSTOM_ID: ed6ba413-ab0f-46a0-8a9c-6b152df56cd1
:END:

Superdiff compares two arrays or objects and returns a full diff of their differences in a readable format.

** [[https://github.com/steveukx/git-js][Simple Git]]
:PROPERTIES:
:CUSTOM_ID: 66fb91bb-2830-4dca-89c3-9e6204fe2ab2
:END:

A light weight interface for running git commands in any node.js application.

** [[https://github.com/bokub/gradient-string][gradient-string]]
:PROPERTIES:
:CUSTOM_ID: e6123a0a-7081-420a-a3ef-9e73e661dbc7
:END:

Beautiful color gradients in terminal output.

** [[https://placeholderjs.com][Ridiculously simple and lightweight placeholders]]
:PROPERTIES:
:CUSTOM_ID: 005f3907-07c0-44eb-87fb-43c036a649a7
:END:

图片占位工具，类似的还有 [[https://temp.im/][temp.im]]。

** [[https://github.com/evanwashere/mitata][mitata]]
:PROPERTIES:
:CUSTOM_ID: 7130a670-b812-45a1-8a99-9fcb8d9b73d3
:END:

mitata is a powerful JavaScript benchmarking library with ascii visualizations, automatic garbage collection, and built-in confirmation bias

** [[https://datavizcatalogue.com/index.html][The Data Visualisation Catalogue]]
:PROPERTIES:
:CUSTOM_ID: 93d90ee8-e63d-40da-b2c7-ea0e1048ac63
:END:

网站提供了很多图表，并进行分类和解释。

当有一些数据需要可视化，但是不清楚用什么图表比较合适的时候可以参考一下。


* 推荐博客
:PROPERTIES:
:CUSTOM_ID: 650e97b6-ea90-4a86-86a7-12b0ea08563c
:END:

** [[https://www.ftium4.com/ux-weekly-204.html][体验碎周报]]
:PROPERTIES:
:CUSTOM_ID: 40c9ada6-e713-4c3e-98b5-a6185088460d
:END:

周报会分享一些用户体验相关的内容，还不错。


* Music
:PROPERTIES:
:CUSTOM_ID: 504db34e-a272-48f1-812b-d8f3d18c143c
:END:

前阵子看了《[[https://www.bilibili.com/video/BV1WZxLe6EmA/][为什么他们的歌总是让人难过?Radiohead伤心三部曲 第二集丨HOPICO]]》，又把 [[https://music.163.com/#/artist?id=99384][Radiohead]] 找出来听了听。

很喜欢他们那张《[[https://music.163.com/#/album?id=1720842][In Rainbows]]》，器乐和旋律带来的听感很丰富。

如果你想听听他们所有的专辑，我将他们整理成了歌单《[[https://music.163.com/#/playlist?id=12659122911][Radiohead]]》，按照专辑的发布年份倒序排列。
