#+title: Weekly#29
#+INDEX: weekly!#29
#+date: <2025-03-16 Sun>
#+lastmod: <2025-03-16 Sun 17:30>
#+author: Spike Leung
#+email: l-yanlei@hotmail.com
#+description: "Weekly info collected by Spike Leung"
#+keywords: "Weekly News Code Music"
#+tags: weekly
#+OPTIONS: toc:1
#+LANGUAGE: zh-CN
#+startup: content indent

* News | Article
** [[https://simonwillison.net/2025/Mar/11/using-llms-for-code/][Here’s how I use LLMs to help me write code]]

[[https://github.com/simonw][Simon Willison]] 整理了一些他使用 LLM 的经验和技巧，推荐一看。

#+begin_details
#+html: <summary>摘录</summary>


- 设定合理的期望

  LLM 说到底还是通过预测可能的 token 返回结果，所以它们还是会出错。

  不用因为它们时而出错而弃而不用，也不要完全相信它们返回的结果，利用它们来增强自己的能力。

- 注意 LLM 的训练截止日期

  问 LLM 一些训练截止日期之后的东西，因为它们的训练内容里没有，所以它们可能不熟悉，回答更容易出错。

  可以考虑让它们使用 [[https://boringtechnology.club/][“老旧” 一些的技术]]实现功能，它们对于这些技术的训练内容足够多，效果往往都不差。

- 上下文为王

  #+begin_quote
  要从 LLM 中获得良好的效果，大部分技巧都在于管理其上下文，即当前对话中的文本。

  ...

  您可以利用以前的回复也是上下文的一部分这一优势。

  对于复杂的编码任务，请尝试让 LLM 先编写一个较简单的版本，检查其是否有效，然后再重复编写更复杂的实现。

  ...

  我最喜欢的代码提示技巧之一是插入几个与我想要构建的内容相关的完整示例，然后提示 LLM 将它们作为新项目的灵感来源。
  #+end_quote

- 向它们询问方向

  可以问 LLM 一些开放性问题，作为初始研究阶段的一部份，找到一些开始的方向。

  例如 “我想做的事情可行吗？有哪些可能的实现方式？哪些方案是最好的？JavaScript 中有哪些有用的拖放库，给我构建 demo 展示它们的使用。”

- 告诉它们应该怎么做

  给 LLM 写好函数定义，描述清楚函数的实现，然后让 LLM 去实现。

  #+begin_quote
  我可以自己编写这个函数，但我需要花费 15 分钟来查找所有细节并使代码正常工作。Claude 在 15 秒内就完成了。

  我发现 LLM 对函数签名的响应非常好，就像我在这里使用的签名一样。

  我充当函数设计者，LLM 则按照我的要求构建主体。

  如果您对此的反应是 “敲代码肯定比写一大段说明要快”，我只能告诉您，我的确不再适合写代码了。

  代码需要正确。

  自然语言有很大的空间来使用捷径、变幻莫测、错别字，以及在你记不住名字的情况下说 “使用那个流行的 HTTP 库” 之类的话。

  优秀的代码 LLM 善于填补空白。

  他们也不像我那么懒惰 ⸺ 他们会记得捕获可能出现的异常，添加准确的文档说明，并在代码中注释相关类型。

  [[https://simonwillison.net/2025/Mar/11/using-llms-for-code/#:~:text=I%20could%20write,the%20relevant%20types.][Source]]
  #+end_quote

- 你必须测试它们写了什么！

  #+begin_quote
  作为一名软件开发人员，你的责任是提供可运行的系统。

  如果你没有看到它运行，它就不是一个工作系统。

  您需要在加强人工质量保证习惯方面进行投资。

  [[https://simonwillison.net/2025/Mar/11/using-llms-for-code/#:~:text=Your%20responsibility%20as%20a%20software%20developer%20is%20to%20deliver%20working%20systems.%20If%20you%20haven%E2%80%99t%20seen%20it%20run%2C%20it%E2%80%99s%20not%20a%20working%20system.%20You%20need%20to%20invest%20in%20strengthening%20those%20manual%20QA%20habits.][Source]]
  #+end_quote

- 记住，这是一次对话

  第一次对话得到的结果可能不是很好，那就持续对话就好了，LLM 不会像人一样抱怨。

  #+begin_quote
  我偶尔会从第一次提示中获得很好的结果 ⸺ 我练习得越多，获得的结果就越多 ⸺ 但我预计至少需要几次跟进。

  我经常在想，这是否是人们忽略的关键诀窍之一 ⸺ 糟糕的初始结果并不是失败，而是将模型推向你真正想要的方向的起点。

  [[https://simonwillison.net/2025/Mar/11/using-llms-for-code/#:~:text=Occasionally%20I%E2%80%99ll%20get,you%20actually%20want.][Source]]
  #+end_quote

- Vibe-coding 是一种很好的学习方法

  #+begin_quote
  一个多月前，Andrej Karpathy 创造了 “vibe-coding” 这一术语，并一直沿用至今：

  有一种新的编码方式，我称之为 “vibe-coding”，在这种编码方式中，你完全屈服于活力 (vibes)，拥抱指数，甚至忘记代码的存在。

  [...]

  我要求的都是最蠢的东西，比如 “把侧边栏的填充减少一半”，因为我懒得去找。

  我总是 “全盘接受” (accpet all)，不再阅读差异。

  当我收到错误信息时，我会直接复制粘贴，不加任何注释，通常这样就能解决问题。

  安德烈认为，这 “对于周末的一次性项目来说还不错”。

  这也是探索这些模型性能的绝佳方式，而且非常有趣。

  学习 LLMs 的最佳方法就是与它们玩耍。

  向它们抛出荒诞的想法并进行振动编码，直到它们几乎可以工作为止，这是一种真正有用的方法，可以加快你建立直觉的速度，让你知道什么可行，什么不可行。

  [[https://simonwillison.net/2025/Mar/11/using-llms-for-code/#:~:text=Andrej%20Karpathy%20coined,and%20what%20doesn%E2%80%99t][Source]]
  #+end_quote
#+end_details

** [[http://11spades.net/posts/on-naming-things/][On Naming Things]]

编码中命名是一件让人头疼的事，一般而言，会使用名称作为描述，描述对应的变量或者函数。

但是变量和函数的功能可能会发生变化，可能会导致命名的描述不再准确，甚至造成误解。

#+begin_quote
例如，在命名一个可变变量或一个抽象链上的高级函数时，对象的性质有可能随着时间的推移而偏离其描述。

事实上，我非常确信这一点：每当你使用一个描述作为能够变化的事物的名称时，你就是在告诉自己一个最终的谎言，而在这个谎言被识破之前，你所拥有的时间是该对象及其依赖关系所经历的变化的频率和幅度的函数。

将来要解决这个问题，代价可能会很高，也可能不会很高。

如果你在很多地方都调用了这个名称，或者这个名称的选择使得查找和替换操作会返回很多不相关的匹配结果，那么重构依赖于这个名称的逻辑可能会很麻烦。

[[https://11spades.net/posts/on-naming-things/#:~:text=But%20these%20benefits,that%20depends%20thereupon][Source]]
#+end_quote

对此，作者的建议是减少变量和函数的复杂度，让它们尽可能简单、原子化，从而减少它们变化的可能性。

#+begin_quote
我们有几种方法可以避免这种繁琐的重构。

最明显的就是限制需要命名的对象在目的和组成方面的复杂性。

具有原子目的的精益对象通常会经历较少和较小的实用特性变化，这反过来又意味着我们的债务会更少，需要偿还的次数也会更少。

顺便提一下，应用这一原则还能避免使用过于冗长、近乎可憎的名称，如 RemoteConnectorFactoryFactoryConfigurerFactory，同时还能让你不必在脑海中映射这些令人发指的名称的含义。

因此，当你遇到一个对象确实应该有一个描述性的名称，但却莫名其妙地很难命名，或者虽然可以命名，但却必须重命名很多次时，就毁掉它，另辟蹊径吧。

[[https://11spades.net/posts/on-naming-things/#:~:text=We%20have%20a,a%20new%20way][Source]]
#+end_quote

** [[https://mislav.net/2014/02/hidden-documentation/][Every line of code is always documented]]

作者给了几行代码，执行了一些操作，但是不知道为什么要执行。

代码没有注释，所幸通过 =git blame= 查看提交记录的时候，上面有很完整的说明。

因此作者认为，应该注重提交信息的编写，这也是补充代码信息的重要一环。

我自己维护历史项目也有这样的感受，有时看到一些奇怪的代码，或者我想知道某个改动是从什么时候引入的、对应的需求版本是什么，我就会通过 =git blame= 查看对应的提交信息。

通过提交信息，我能找到对应的版本，进而找到对应的需求文档，或许我就能知道某些代码逻辑为什么会存在。

把提交信息写好，描述清楚为什么，将来的读者肯定会对这样的提交信息心存感激的。

关于提交信息，你还可以看看：

- [[https://dhwthompson.com/2019/my-favourite-git-commit][My favourite Git commit]]
- [[https://who-t.blogspot.com/2009/12/on-commit-messages.html][On commit messages]]
- [[https://cbea.ms/git-commit/][How to Write a Git Commit Message]]
- [[https://taxodium.ink/git-lint-practice.html][Git 的校验实践]]

#+begin_quote
请记住，你今天所做的一切都将进入项目的历史，并永远留在那里。

为了更好地对待与你一起工作的其他人（即使是一个人的项目，也包括 3 个月后的你自己），请在提交时遵守以下基本规则：

- 在撰写提交信息时，一定要像向坐在旁边的同事解释变更一样，因为他根本不知道发生了什么。

  [[http://robots.thoughtbot.com/5-useful-tips-for-a-better-commit-message][按照 Thoughtbot 的提示来编写更好的提交信息]]：

  + 为什么需要做出这种改变？

  + 它是如何解决这一问题的？

  + 这种变化有什么副作用？

  + 考虑加入链接 (相关文档，相关讨论，issue 等)

- 避免在一次提交中出现无关的改动。

  您可能在同一个文件中发现了一个错别字或进行了微小的代码重构，但除非它们直接相关，否则请不要将它们与主要更改记录在一起。

- 推送前一定要清理历史。如果提交尚未被共享，[[https://mislav.net/2013/02/merge-vs-rebase/][就可以安全地将其 rebase]]。

[[https://mislav.net/2014/02/hidden-documentation/#:~:text=Being%20on%20the%20right%20side%20of%20history][Source]]
#+end_quote

** [[https://www.tibinotes.com/p/practical-ux-for-startups-surviving][Practical UX for startups surviving without a designer]]

有时候开发产品可能请不到设计师，如何保证产品的 UX 呢？

作者建议是借鉴竞争对手的设计，跟随大众的设计，而不要自己从头开始设计。

另外在设计的时候，要思考设计的目的是什么，不要为了设计而设计，而应该切实解决用户问题。

#+begin_quote
如果您要设计一个注册页面，目标就不仅仅是 “两个文本字段和一个注册按钮”。

而是真正的目标，比如 “让注册尽可能轻松”。

[[https://www.tibinotes.com/p/practical-ux-for-startups-surviving#:~:text=If%20you%27re%20designing%20a%20sign%2Dup%20page%2C%20the%20goal%20isn%E2%80%99t%20just%20%22two%20text%20fields%20and%20a%20sign%2Dup%20button.%22%20It%E2%80%99s%20something%20real%2C%20like%3A%20%22Make%20signing%20up%20as%20effortless%20as%20possible.%22][Source]]
#+end_quote

#+begin_quote
真实用户的行为并不像你希望的那样。他们匆忙、跳过指令、分心。

经常问：会出什么问题？

- 一个字段一个字段地看：如果用户匆忙操作而出错，会发生什么情况？
- 然后放大：在整个流程中会发生什么？

如果你能让不耐烦和分心的用户顺利体验，其他用户就不会有任何问题。

糟糕的用户体验并不总是丑陋的设计：它往往只是让用户感到困惑，不知道哪里出了问题，也不知道如何解决。

[[https://www.tibinotes.com/p/practical-ux-for-startups-surviving#:~:text=Real%20users%20don%E2%80%99t,to%20fix%20it.][Source]]
#+End_quote

#+begin_quote
- 颜色要简单。一个主色调、一个辅助色调和一个重点色调。[[https://coolors.co/][Coolors]] 就是一个很好的小工具。
- 使用用户熟悉的语言，而不是开发人员熟悉的语言。不要说 “数据库错误”，而要说 “我们无法保存您的更改”。

[[https://www.tibinotes.com/p/practical-ux-for-startups-surviving#:~:text=Keep%20your%20colours,save%20your%20changes.%22][Source]]
#+end_quote

#+begin_quote
初创企业需要快速发展，完美主义，尤其是美学方面的完美主义往往是不必要的。

如果你不是设计师，但你需要把事情做得更好，那就把重点放在可用性上，而不是新颖性上。

简洁明了的用户流程永远胜过新颖但令人困惑的流程。

有时你需要新颖性，但要问清楚自己：“我们究竟在哪里需要与众不同？”

复制别人的设计不仅仅是简单的复制，这是利用其他公司为你培训用户。

当你遵循既定模式时，用户已经知道该做什么，你就不必从头开始教他们。

在核心价值上进行创新；对于其他一切，坚持行之有效的做法。

[[https://www.tibinotes.com/p/practical-ux-for-startups-surviving#:~:text=Startups%20need%20to,to%20what%20works.][Source]]
#+end_quote

** [[https://persevering.substack.com/p/super-crispy-svg-icons][Super Crispy SVG Icons]]

文章讲述了作者创建几个图标的过程，包括设计到最终的导出。

看起来很简单的图标，但是做好需要处理不少细节。

#+begin_quote
我总是不愿意把图标像纸屑一样撒得到处都是。

我深信文字是最清晰的，只有当我觉得图标真的能为用户增加清晰度时，我才会添加图标。

[[https://persevering.substack.com/p/super-crispy-svg-icons#:~:text=I%E2%80%99m%20always%20reticent%20to%20sprinkle%20icons%20everywhere%20like%20confetti.%20I%E2%80%99m%20a%20big%20believer%20that%20text%20is%20clearest%20and%20I%20try%20to%20only%20add%20icons%20if%20I%20feel%20they%20really%20add%20clarity%20for%20the%20user][Source]]
#+end_quote

#+begin_quote

#+CAPTION: 图片中有 2 组图形，每一组都有正方形，圆形，三角形。左侧的一组，所有图形的尺寸是一样的，但圆形从视觉上看起来会比正方形小。右侧一组，圆形的尺寸要比正方形大一些，从视觉上看它们才是一样大的。
https://substackcdn.com/image/fetch/w_1456,c_limit,f_auto,q_auto:good,fl_progressive:steep/https%3A%2F%2Fsubstack-post-media.s3.amazonaws.com%2Fpublic%2Fimages%2Fe0501218-baef-4d25-b76d-8b2377038f40_1456x420.png

相同尺寸的圆形总感觉比同尺寸的正方形略小， 为了让灯泡看起来与其他图标大小大致相同，它实际上需要更大一些。

我将其描述为视觉重量，这绝对是一门艺术而非科学。

[[https://persevering.substack.com/p/super-crispy-svg-icons#:~:text=I%E2%80%99m%20always%20a,art%20than%20science.][Source]]
#+end_quote

** [[https://norahsakal.com/blog/mcp-vs-api-model-context-protocol-explained/][What is Model Context Protocol (MCP)? How it simplifies AI integrations compared to APIs]]

一篇 MCP 扫盲文章，文章中还将 MCP 和 API 进行了对比。

#+CAPTION: MCP 架构图
https://norahsakal.com/assets/images/mcp_overview-641a298352ff835488af36be3d8eee52.png

MCP 就像是一个 USB 接口，你可以将 MCP Server 插上去，从而获得 MCP Server 提供的功能和能力。

例如 GMail MCP Server 可以通过操作邮件相关的能力。

本地数据，网络搜索，远程服务等也都可以通过 MCP Server 提供。

一个 USB 接口只能插入一个设备，类似的，MCP Server 和 MCP Client 的关系也是一对一的。

（可能是因为 MCP 是双向通讯，双向通讯的对象需要一对一？）

但是只要你机器性能足够，你可以拥有很多个接口，建立很多 MCP 连接。

你可以写 MCP Client 去和 MCP Server 交互，但是感觉很可能我们都不需要写，而都是通过 LLM 应用 （MCP Host）作为入口使用。

我们通过 LLM 应用描述需求，LLM 应用创建 MCP Client 和对应的 MCP Server 连接完成相关工作，再将结果返回给我们。

除了 MCP，我最近还看到 2 个提议 [[https://docs.wild-card.ai/agentsjson/introduction][agents.json]] 和 [[https://llmstxt.org/][/llms.txt]]。

简单来说，它们像是专门给 LLM 准备的站点地图（也像 robot.txt），告诉 LLM 内容怎么找，可以怎么用。

agents.json 用于提供 API 的站点地图。

API 是为开发者设计的，开发人员自己看文档，写对应的 API 调用。

#+CAPTION: 传统 API 调用
https://mintlify.s3.us-west-1.amazonaws.com/wildcard/static/TraditionalFlowDiagram.png

但是对于 LLM，它不知道 API 之间是怎么关联的，参数格式也可能不清楚。

#+CAPTION: LLM 客户端调用 API
https://mintlify.s3.us-west-1.amazonaws.com/wildcard/static/AirgapFlowDiagram.png

agents.json 就是为了填补这个空缺，让 LLM 知道怎么调用 API。

#+CAPTION: LLM 客户端结合 agents.json 调用 API
https://mintlify.s3.us-west-1.amazonaws.com/wildcard/static/LlmWorksDiagram.png

/llms.txt 用于提供网站内容的站点地图。

它提供网站简要的背景信息、指导和指向详细 markdown 文件的链接。

你可以看看 [[https://answerdotai.github.io/fasthtml/llms.txt][FastHTML 的 /llms.txt]] 参考一下。

** [[https://dynomight.net/noise/][My stupid noise journey]]

作者对噪音很敏感，他搬家之后，邻居和附近公园的噪音对他影响很大。

身边的人建议他搬家或者试试降噪耳机，但是他认为降噪耳机治标不治本，他想从根本上减少噪音的影响。

他尝试了各种办法，如耳罩，隔音耳塞等，效果都不好，就这样过了 2 年多，直到他第一次使用降噪耳机，惊呼 yyds。

#+begin_quote
所以让我们回顾一下：我有一个问题。

解决我问题的终极方案是做最明显的事情。

但我说服自己这不会有效，花了两年时间尝试其他一切。

或者，好吧，情况比那更糟。

我忽视了显而易见的事情，因为我认为我在使用第一性原理思维。

但那些第一性原理是什么呢？

当然，我对声音的工作原理了解得不多，只是对分子相互撞击的模糊概念。

我也不理解主动噪声取消是如何工作的，除了使用麦克风和扬声器创造破坏性干涉的广泛概念。

我想那些模糊的想法是正确的。

但它们极其肤浅，以至于几乎无法预测任何事情。

我不仅太无知，无法从第一性原理出发，我也太无知，无法判断其他人是否知道他们在说什么。

同时，实际上并不需要第一性原理思维，因为测试非常快速且便宜。

你在几秒钟内就知道噪音是否被阻挡，在几个小时内就知道你是否感到舒适。

当实验如此简单时，花费无数小时进行理论推导是荒谬的。

[[https://dynomight.net/noise/#:~:text=So%20let%E2%80%99s%20review,are%20so%20easy][Source]]
#+end_quote

** [[https://ghuntley.com/tradecraft/][Yes, Claude Code can decompile itself. Here's the source code.]]

作者用 Claude 反编译了一个 5 MB 左右的源码，虽然过程不算容易，但最终还是成功了。

发布的代码一般会经过混淆和压缩，减少体积，也避免别人查看页面源码时轻易找到程序的一些漏洞。

但是现在有了 LLM，它很擅长处理文字，只要它能处理的上下文足够大，知道源码是通过什么混淆过来的，它或许就能轻松将其还原回去。

#+begin_quote
现在，一个敏锐的头脑应该已经意识到上述内容的含义，但我还是要说出来。

使用上述技术，你可以在几个小时内清理任何现有软件。

所有那些在上一个繁荣时期筹集了大量资金的 “源代码可用” 创始人现在都陷入困境。

因为任何人都可以利用上述技术在几个小时内重新实现他们的“专有功能”，从而以更低的运营成本启动竞争对手的初创公司。

[[https://ghuntley.com/tradecraft/#:~:text=Now%2C%20a%20sharp,operating%20costs][Source]]
#+end_quote

** [[https://steveklabnik.com/writing/choosing-languages/][Choosing Languages]]

作者是一个在社区中有一定影响力的人，又一次他嘲讽另一个作者用 JS 写 CLI 工具，导致对方感到难受。

之后作者道歉并反省了自己的行为，他认为自己去嘲讽别人，部分原因可能是因为从众心理。

因为他身边的人都是 Rails 社区的，社区中存在一种蔑视文化，看不起 JS 和 NodeJS。

#+begin_quote
但在我生活中的那个时候，实际上并不是这样。

我在 Rails 团队工作，我在会议上发言，人们在阅读我的博客和推文。

我是一个“影响者”，无论好坏。但我还没有真正内化我生活中的这种变化。

因此，我并不真正理解，如果我批评某件事，那将是成千上万的人看到的。

对我来说，我只是史蒂夫。

这种情况发生在我们谈论 “取消文化” 以及所有这些事情之前，但当人群来找我的时候，我意识到：他们其实是对的。

我确实在表现得像个混蛋，我不应该那样。我决心不再像那样做一个混蛋。

[[https://steveklabnik.com/writing/choosing-languages/#:~:text=But%20at%20that,that%20ever%20again.][Source]]
#+end_quote

** [[https://mirawelner.com/posts/checkout.html][Can we communally deprecate git checkout?]]

作者呼吁大家放弃 =git checkout= ，而替换成 =git switch= 和 =git restore= 。

原因是 =git checkout= 代表的含义过于复杂，除非对 git 非常熟悉，不然很容易产生困惑。

#+begin_quote
Git checkout 似乎故意让这个命令变成一个绝对的灾难。

官方的 git 文档将 =git checkout= 描述为一个 “切换分支或恢复工作树文件” 的功能。

这已经是两件几乎没有关系的事情，而且这还不是这个庞大、超负荷的命令所能做的全部。

我认为更全面的描述应该是：

“它可以让你从一个分支移动到另一个分支，或者创建一个新的分支并将你移动到该分支，或者将特定文件恢复到 n 次提交之前的版本。

它还可以在恢复已暂存文件到它们被暂存时的版本时，删除所有未暂存的文件，或者它可以创建一个分离的 HEAD 状态。”

这到底是什么意思？这甚至不是一个连贯的句子！

为什么人们决定让一个命令执行 Git 的所有功能？这是什么疯狂？

[[https://mirawelner.com/posts/checkout.html#:~:text=Git%20checkout%20seems,is%20this%20madness%3F][Source]]
#+end_quote

** [[https://www.bentasker.co.uk/posts/blog/security/seducing-a-romance-scammer.html][My Scammer Girlfriend: Baiting A Romance Fraudster]]

作者去追寻女性交友诈骗邮件的过程，非常长的文章，感兴趣可以看看。

* Tutorial | Resource

** [[https://javascriptgametutorials.com/][JavaScript Game Tutorials]]

JS 编写游戏的教程，目前的教程主要是用 [[https://threejs.org/][three.js]] 实现的。

** [[https://okaydev.co/articles/dive-into-webgpu-part-1][Dive Into WebGPU—Part 1]]

WebGPU 教程。

实现的效果挺炫酷的，但是我的电脑打开网页很卡，估计对资源要求比较高。

** [[https://chrisnicholas.dev/blog/how-to-write-exceptional-documentation][How to write exceptional documentation]]

关于如何写好文档的教程。

作者将文档分成了几类，它们分别回答不同的问题：

- 快速入门 (Quickstart) :: 我该如何设置它？
- 教程 (Tutorials) :: 我该如何有效使用它？
- 使用指南 (How-to guides) :: 我该如何解决特定问题？
- 解释 (Explanations) :: 它是如何工作的？
- 示例 (Examples) :: 我可以用它做什么？
- 模版 (Templates) :: 我如何在生产中使用它？
- API 参考 (API reference) :: 我如何知道有什么可用的 API？

** [[https://stevelosh.com/blog/2013/09/teach-dont-tell/][Teach, Don't Tell]]

一篇关于如何写好文档的文章。（我真的挺喜欢看这类文章的，想学习更多写好文档的技巧，也想写出高质量的文档。）

#+begin_quote
技术文档的目的是带领一个从未见过你的项目的人，教会他们成为该项目的专家用户，并在他们成为专家后给予支持。

[[https://stevelosh.com/blog/2013/09/teach-dont-tell/#:~:text=The%20purpose%20of%20technical%20documentation%20is%20to%20take%20someone%20who%20has%20never%20seen%20your%20project%2C%20teach%20them%20to%20be%20an%20expert%20user%20of%20it%2C%20and%20support%20them%20once%20they%20become%20an%20expert.][Source]]
#+end_quote

#+begin_quote
如果你想把一个从未弹过吉他的人变成一个杰出的吉他手，你该怎么做？

你教他们。

如果你想把一个高中生培养成计算机科学家，你该怎么做？

你教他们。

如果你想把一个从未见过你的库的程序员培养成它的专家用户，你该怎么做？

你教他们！

吉他课程通常是面对面、一对一地由老师教授的。

计算机科学通常由教授在教室里教授。

编程库的使用通常通过文档来教授。

如果文档的目标是将新手转变为专家，那么文档必须进行教学。

你应该把你的文档视为一节课（或一系列课程），因为这就是它的本质。
#+end_quote

#+begin_quote
没有什么能替代面对面坐下来教会某人的经历。

/如果你想写出更好的文档，你需要练习教学。/

我不是在谈论写出课程计划或任何如此正式的东西。

你有爱好（不是编程）吗？如果有的话，花几个小时在周末教一个朋友关于它的知识。

你将获得一些教学的实践，而他们将学到一些新东西。

不要过于夸张。你不需要给某人颁发学位，你只需要稍微练习一下教学。

你需要练习用你的话语重新连接某人神经元的艺术。

一旦你开始教授某件事情（即使是简单的事情），你可能会意识到，尽管你自己知道怎么做，但教别人却要困难得多。

当你和某人面对面工作时，这一点显而易见。

当你告诉他们如何在吉他上弹奏 C 大调和弦，而他们只发出一声窒息的尖叫时，很明显你需要放慢速度，讲解如何正确按压弦。

作为程序员，我们几乎从未收到关于我们文档的这种反馈。

我们看不到另一端的人因为缺少我们认为显而易见的东西而感到无助和困惑。

面对面地教导某人可以帮助你学会预见这种情况，这将对你的用户在你撰写文档时大有裨益。
#+end_quote

#+begin_quote
教师帮助学生的最佳方式是自然地帮助学生。

教师应该站在学生的角度，理解学生的情况，试图理解学生心中发生的事情，并提出一个问题或指出一个可能已经出现在学生脑海中的步骤。

这，正是教学的核心。这就是它。这就是你该怎么做。

...

当你想教某人时，你需要站在他们的角度，和他们一起走这条路。

牵着他们的手，引导他们绕过危险的障碍，跌倒时接住他们。

不要把他们抱着走。绝对不要只是把他们开车送到目的地！

这个过程需要这样进行：

1. 先弄清楚他们已经知道什么。
2. 弄清楚你希望他们在你完成后知道什么。
3. 找到一个可以使状态 1 稍微接近状态 2 的单一想法或概念。
4. 引导学生朝着那个想法前进。
5. 重复直到状态 1 变为状态 2。

我经常看到文档非常仔细地考虑了第 2 步，然后只是将其作为上帝的宣告呈现给读者。

这不是教学。这是在告知。

人们不是通过被告知来学习的，而是通过被教导来学习的。
#+end_quote

** [[https://www.evanmiller.org/statistical-formulas-for-programmers.html][Statistical Formulas For Programmers]]

作者整理了一些他认为比较有用的统计学的公式。

* Code Related
** [[https://devblogs.microsoft.com/typescript/typescript-native-port/][A 10x Faster TypeScript]]

TypeScript 使用 GO 进行了重写，使得 TS 的构建速度缩短了 10 倍，Cool！

TS 团队计划在 6.x 版本引入一些 breaking changes，以与即将发布的 GO 实现版本（7.x）保持一致。

** [[https://www.hillelwayne.com/post/javascript-puzzle/][A Perplexing Javascript Parsing Puzzle]]

#+begin_src javascript
  x
  = 1
  x
  --> 0
#+end_src

在浏览器中，这里会打印什么？

我觉得可能是 1 ，或者会报错。你觉得呢？

你可以在浏览器控制台执行看看，是不是符合你的预期。

如果好奇为什么，可以看看原文，挺有趣的。

** [[https://harrisonbroadbent.com/blog/cool-native-html-elements/][Cool native HTML elements you should already be using]]

一些 HTML 元素的介绍，如 =<dialog>= ， =<details>= ， =<datalist>= 。

** [[https://evilmartians.com/chronicles/better-web-video-with-av1-codec][How to make web videos way smaller in 2025 using the AV1 codec]]

文章介绍了如何使用 [[https://en.wikipedia.org/wiki/AV1][AV1]] 减少视频大小，同时保证视频的质量。

#+begin_quote
首先，让我们放大并注意到，在处理静态图像时，无需三思而后行：选择所有浏览器都支持的 WebP、JPEG 或 PNG，或者尝试使用谷歌为较新浏览器开发的更紧凑的 AVIF。

您几乎总是可以确定，扩展名为 =.png= 的图像文件确实是 PNG（除非使用了一些肮脏的黑客手段，如 imgproxy 等工具）。

现在，视频文件的情况就比较棘手了。文件扩展名（ =.mp4= 、 =.wmv= 、 =.webm= 或 =.mov= ）仅代表容器，而一个视频文件最多可使用三种不同的格式：

- 视频编解码器 (Video codecs) ::

  确定视频的压缩策略；

  这是在质量和数量之间进行权衡的地方。

  网络上流行的视频编解码器有 H.264、HEVC、VP9 和现在的 AV1。
- 音频编解码器 (Audio codecs) ::

  对音频也是如此。

  如果视频没有声音，可以不用。

  常用的编解码器有 MP3、Opus 和 AAC。
- 容器 (Containers) ::

  容器可存储视频（由某种视频编解码器压缩）和音频流（由某种音频编解码器压缩），还可添加字幕和元信息等额外细节。

  常用的容器有 MP4、MOV 和 WebM。

因此，当您看到 =.mp4= 扩展名时，唯一可以确定的是 MP4 容器被用来打包文件。

编解码器的选择完全取决于创建者：可以是 H.264/AAC，也可以是 AV1/Opus，或者其他。

[[https://evilmartians.com/chronicles/better-web-video-with-av1-codec#:~:text=First%20up%2C%20let%E2%80%99s,or%20something%20else.][Source]]
#+end_quote

** [[https://www.bram.us/2025/03/11/view-transitions-border-radius/][View Transitions Applied: Smoothly animating a border-radius with a View Transition]]

使用 View Transition 实现 border 的平滑过渡。

** [[https://css-tricks.com/grouping-selection-list-items-together-with-css-grid/][Grouping Selection List Items Together With CSS Grid]]

使用 grid 对列表选中元素分组，从而更容易区分什么被选中，什么未选中，效果看起来不错。

** [[https://codepen.io/glitchworker/pen/jENZGOV?editors=1000][Bubbles Background Animation]]

CSS 实现的动态背景。

** [[https://www.bram.us/2025/03/11/view-transitions-border-radius][View Transitions Applied: Smoothly animating a border-radius with a View Transition]]

使用 View Transition 实现 border-radius 的平滑过渡。

** [[https://www.debugbear.com/blog/lazy-load-background-images-intersection-observer][Lazy Load Background Images with the IntersectionObserver API]]

文章介绍了如何用 [[https://developer.mozilla.org/en-US/docs/Web/API/IntersectionObserver][IntersectionObserver]] 实现图片懒加载。

原理是 IntersectionObserver 可以检测元素之间的重叠，就可以判断图片和某部分 [[https://developer.mozilla.org/en-US/docs/Glossary/Viewport][viewport]]（浏览器窗口）重叠的时候再加载。

IntersectionObserver 是独立于浏览器主线程运行的，因此不会阻塞主线程，相比监听 scroll，change，resize 等，性能更好。

* Cool Bit

** [[https://www.fourmilab.ch/gravitation/foobar/][Bending Spacetime in the Basement]]

作者在地下室设计了一个实验，去观察物体之间的引力，探索万有引力。

牛顿发现了万有引力，推动了启蒙运动及随后的科技发展，作者就好奇为什么牛顿之前的人没有发现？

在阿基米德的年代，能否通过相同的实验发现万有引力？

#+begin_quote
好吧，人到中年固然有其弊端，但至少你可以开展这样的项目，而不用担心被“妈妈！开尔文在地下室弯曲时空！”的喊声扼杀在萌芽状态。

记住 “大人” (grownup) 和 “长大了” (grown up) 之间的区别很重要。

让我们这些 “大人” (grownup) 去地下室弯曲时空吧。

[[https://www.fourmilab.ch/gravitation/foobar/#:~:text=Well%2C%20middle%20age,some%20serious%20spacetime][Source]]
#+end_quote

#+begin_quote
如果引力与电磁力相比不是如此微弱，你就不会在阅读这一页；

正是因为将你身体中的原子结合在一起的电磁力轻易地战胜了地球的引力，

你和所有其他固体物体才不会塌陷成一滩水，最终合并成一个完美的球体（实际上，由于旋转，略呈椭球形）。

[[https://www.fourmilab.ch/gravitation/foobar/#:~:text=If%20gravity%20were,to%20rotation)%20planet.][Source]]
#+end_quote

#+begin_quote
在物理学家和工程师的工具箱里，有一把万能大锤，那就是微分测量法。

换句话说，不要担心某样东西的绝对值，只担心你能测量到的东西之间的差值。

例如，维修高压输电线的电线工通常的做法是在不切断电源的情况下，从起重机升起的绝缘筐中进行作业。

只要线路工与地面是绝缘的，那么只有他的手和他正在工作的线路之间的电压差才是最重要的；

将篮子固定在线路上后，电压差为零，就像是修理接地导体一样。

现在，如果他在高于地电位 20 万伏的导体上工作时，碰巧触碰到了接地的铁塔，那将是非常糟糕的一天。

诀窍在于保持微小的差异。

你可以在 100 万伏的电压下生活一辈子，只要你周围的一切都接近这个值，即使在原则上，你也不可能发现绝对电势。

这就是所有物理力都是规整不变的结果：绝对值不存在，只有差异才重要。

[[https://www.fourmilab.ch/gravitation/foobar/#:~:text=One%20of%20the%20great,exist%E2%80%94only%20differences%20matter][Source]]
#+end_quote

#+begin_quote
引力的普遍性意味着宇宙中的每个物体都在相互吸引的网络中相互关联；宇宙对引力是透明的。

最遥远的星系对你施加引力，就像你对它们施加引力一样——虽然可以肯定地说这种引力微不足道，但依然存在。

[[https://www.fourmilab.ch/gravitation/foobar/#:~:text=The%20universality%20of%20gravitation%20means%20that%20every%20object%20in%20the%20universe%20is%20interlinked%20in%20a%20web%20of%20mutual%20attraction%3B%20the%20universe%20is%20transparent%20to%20gravitation.%20The%20most%20distant%20galaxies%20exert%20a%20pull%20on%20you%2C%20as%20you%20do%20upon%20them%E2%80%94immeasurably%20tiny%20to%20be%20sure%2C%20but%20present%20just%20the%20same.][Source]]
#+end_quote

** [[https://www.chiark.greenend.org.uk/~sgtatham/quasiblog/putty-icons/][Iconography of the PuTTY tools]]

有人好奇 PuTTY 的图标由来，给作者发了邮件，于是作者写了篇文章来回答。

作者讲述了 PuTTY 许多图标的由来和演变过程，挺有趣的。

#+begin_quote
有时我会收到一封邮件，询问一个问题，当我回答完这个问题时，我意识到这个问题值得写成一篇博文。

这一次，我在开始打字之前就知道这将是一个这样的问题，因为这个问题既有平面设计的角度，也有技术的角度。

所以我有很多话要说。

[[https://www.chiark.greenend.org.uk/~sgtatham/quasiblog/putty-icons/#:~:text=Sometimes%20I%20receive,lot%20to%20say][Source]]
#+end_quote

#+begin_quote
#+OPTIONS: PuTTY 的图标
https://www.chiark.greenend.org.uk/~sgtatham/quasiblog/putty-icons/putty-original.png

我觉得我没有仔细考虑过设计。

因为我需要一个图标，所以我就把它画下来了。

两台电脑的画风在 90 年代很常见：一个系统盒放在一个 CRT 显示器下面，右端有一个软盘驱动器。

它们之间用闪电连接，暗示着它们之间的电气通信。

[[https://www.chiark.greenend.org.uk/~sgtatham/quasiblog/putty-icons/#:~:text=I%20don%E2%80%99t%20think,be%20immediately%20understandable][Source]]
#+end_quote

** [[https://forum.cursor.com/t/cursor-told-me-i-should-learn-coding-instead-of-asking-it-to-generate-it-limit-of-800-locs/61132][Cursor told me I should learn coding instead of asking it to generate it]]

有人使用 Cursor 的时候碰到了一个回复：我不能帮你写代码，你应该自己写，这样能确保你理解相关逻辑。

假如有一天人工智能统治世界，人类请它们干活也会碰到类似回复？哈哈。

** [[https://www.americanscientist.org/404][American Scientist 404]]

这个 404 页面蛮有趣的。

* Tool | Library
** [[https://github.com/addyosmani/filter][addyosmani/filter: Filter - Web Image Editor]]

网页版本的图像编辑工具。可以对图片裁剪，设置滤镜和水印。

** [[https://www.i18ncode.com/en][I18n Code]]

将 JSON，markdown，text 的内容翻译成其他语言的工具。

** [[https://github.com/Chenyu-otf/chenyuluoyan_thin][辰宇落雁體]]

一款还不错的手写字体。

** [[https://github.com/suitenumerique/docs][docs]]

#+begin_quote
一个可扩展的协作笔记、维基和文档平台。

使用 Django 和 React 构建。

Notion 或 Outline 的开源替代品。
#+end_quote

* Emacs
- [[https://sachachua.com/blog/2014/04/emacs-beginner-resources/][Emacs beginner resources]] [[https://sachachua.com/blog/][Sacha Chua]] 整理的一些 Emacs 入门教程。
- [[https://www.masteringemacs.org/article/introduction-magit-emacs-mode-git][An introduction to Magit, an Emacs mode for Git]] magit 是我目前用过的最好的 git 管理工具，没有之一。
  学会了一个新方法 =magit-file-dispatch= (=C-c M-g=)，针对当前 buffer 的相关 magit 指令。

* 一些话 | 摘抄

** [[https://articles.data.blog/2024/03/30/jeff-bezos-when-the-data-and-the-anecdotes-disagree-the-anecdotes-are-usually-right/][Jeff Bezos: When the data and the anecdotes disagree, the anecdotes are usually right.]]

#+begin_quote
当数据和轶事出现分歧时，轶事通常是正确的。

这通常不是因为数据收集错误。

通常是你没有测量正确的东西。

[[https://articles.data.blog/2024/03/30/jeff-bezos-when-the-data-and-the-anecdotes-disagree-the-anecdotes-are-usually-right/#:~:text=Jeff%20Bezos%3A%20%E2%80%9CI,the%20right%20thing][Source]]
#+end_quote

** [[https://allenpike.com/2025/javascript-fatigue-ssr][JavaScript Fatigue Strikes Back]]


#+begin_quote
采用任何新依赖项——无论是框架、库还是其他工具——都伴随着风险。

我们押注于新工具带来的速度提升，并能抵消其维护成本。

如果一个框架华而不实，过于复杂，或者维护不善，无法满足需求，我们就会陷入困境。

因此，真正厉害的人会[[https://mcfunley.com/choose-boring-technology][选择那些枯燥、简单、维护良好的技术]]：

谁也不想成为第一个因为使用 X 框架而遇到 Y 问题的团队，或者成为最后一个使用非主流技术导致项目停滞的团队。

[[https://allenpike.com/2025/javascript-fatigue-ssr#:~:text=When%20we%20choose,more%20modern%20toys.][Source]]
#+end_quote
** [[https://z.arlmy.me/posts/MastodonArchives/2025/MastodonTootsArchives_20250308/][Toots 2025 Mar.2 - Mar.8]]

#+begin_quote
故事，也是时间的另一个名字。

[[https://z.arlmy.me/posts/MastodonArchives/2025/MastodonTootsArchives_20250308/#:~:text=%E6%9C%BA%E6%A0%B8%20GCORES-,%E6%95%85%E4%BA%8B%EF%BC%8C%E4%B9%9F%E6%98%AF%E6%97%B6%E9%97%B4%E7%9A%84%E5%8F%A6%E4%B8%80%E4%B8%AA%E5%90%8D%E5%AD%97%E3%80%82,-Mar.3][Source]]
#+end_quote
** [[https://www.aha.io/engineering/articles/rails-views-web-components-react][Rails views, web components, React. Why make a choice?]]

#+begin_quote
更重要的不是哪种方法更胜一筹，而是要了解这些技术的发展是为了解决不同的问题。

真正的问题不是 “哪一种最好？”，而是 “哪一种最适合这一特定功能？”

[[https://www.aha.io/engineering/articles/rails-views-web-components-react#:~:text=The%20bigger%20picture%20isn%27t%20about%20which%20approach%20wins%20%E2%80%94%20it%27s%20about%20understanding%20that%20these%20technologies%20evolved%20to%20solve%20different%20problems.%20The%20real%20question%20isn%27t%2C%20%22Which%20one%20is%20best%3F%22%20but%20rather%2C%20%22Which%20one%20is%20best%20for%20this%20specific%20feature%3F%22][Source]]
#+end_quote
** [[https://takeonrules.com/2025/03/10/and-dark-enough-to-spare/][And Dark Enough to Spare]]

#+begin_quote
在这漆黑的夜里，一个人已经开始入睡，但还没有开始新的一天；这一天还远着呢。

此时此地，在这个无人问津的时间空间里，思绪像未受束缚的伤口一样淌着血，像墨水一样洒在纸上。

随着墨黑的夜幕划过炽热的心灵，意识的印记也随之熊熊燃烧。

这里位于北纬 42 度附近，冬夜漫长。

当我们滴答滴答地迈向春分时节，白昼的增长速度越来越快。

一旦进入春天，就会放慢脚步，但仍会绵延至至日。

我会怀念那些孤独的黑暗时刻，但知道它们会在绕太阳一圈后再次出现，我又感到欣慰。

[[https://takeonrules.com/2025/03/10/and-dark-enough-to-spare/#:~:text=This%20dark%20of,around%20the%20sun][Source]]
#+end_quote
** [[https://interjectedfuture.com/visual-programming-is-stuck-on-the-form/][Visual programming is stuck on the form]]

#+begin_quote
当你弄清楚低层次的东西时，用户界面就会自然而然地到位。

[[https://interjectedfuture.com/visual-programming-is-stuck-on-the-form/#:~:text=When%20you%20figure%20out%20the%20low%2Dlevel%20stuff%2C%20the%20UI%20all%20falls%20into%20place][Source]]
#+end_quote

#+begin_quote
如果一个设计是好的，那么它的外观、感觉和功能就是其功能、代数和理性的赤裸表达——它的内在本质。

设计一个形式时，不应该凭空想象。你必须从侧面入手，先解决其功能。

一旦功能——内在本质、内部一致性和代数——被确定，形式将自然而然地出现。

[[https://interjectedfuture.com/visual-programming-is-stuck-on-the-form/#:~:text=If%20a%20design,consequence%20of%20it][Source]]
#+end_quote

文章始于对 [[https://youtu.be/cBYudbaqHAk?t=6660][Lu Wilson 分享的 CellPond]] 的感触，推荐去看看这个视频。

然后我还搜索了一下 [[https://github.com/TodePond][Lu Wilosn]]，他的 [[https://github.com/TodePond/GulfOfMexico][Gulf of Mexico]] 也很好玩。

#+begin_quote
这一切只是一些愚蠢的乐趣，所以我只是想鼓励你们也享受一点傻乎乎的乐趣。

（像 DreamBerd 这样的）糟糕的想法，也可以变得受欢迎，所以不要担心你的。

[[https://www.youtube.com/watch?v=52vmjZnxJb8&ab_channel=TodePond][Perfect programming language]] (Gulf of Mexico)
#+end_quote

Gulf of Mexico 甚至还有 [[https://www.youtube.com/watch?v=QRKnrFEjDF0&ab_channel=TodePond][Vision Pro 版本]]。

** [[https://www.theverge.com/23650428/colorblindness-design-ui-accessibility-wordle][Designing for colorblindness]]

#+begin_quote
因为红色和绿色是色轮上相对的互补色，它们已成为每个想要表示对立的设计师的默认颜色：真与假，高与低，停与走。

不方便的是，这也是最容易被色盲人士混淆的两种颜色。

我希望世界上每位设计师都能理解这一点，并将对立颜色改为红色和蓝色。

但我知道这不会发生：文化意义根深蒂固。

[[https://www.theverge.com/23650428/colorblindness-design-ui-accessibility-wordle#:~:text=Because%20red%20and,is%20too%20ingrained.][Source]]
#+end_quote

#+begin_quote
设计中的可及性是一种同理心：试图超越你个人的视角，去理解那些在这种情况下，字面上与您看世界的方式不同的其他人。

[[https://www.theverge.com/23650428/colorblindness-design-ui-accessibility-wordle#:~:text=Accessibility%20in%20design%20is%20a%20form%20of%20empathy%3A%20trying%20to%20reach%20beyond%20your%20own%20personal%20perspective%20to%20try%20to%20understand%20other%20people%20who%2C%20in%20this%20case%2C%20very%20literally%20don%E2%80%99t%20see%20the%20world%20the%20same%20way%20you%20do.][Source]]
#+end_quote

** [[https://hyponymo.us/2013/01/29/100-percent-unemployment/][100% Unemployment]]

#+begin_quote
我以写软件为生，越来越相信我的工作很快会被外包——在几年或几十年内。

它不会去印度或中国的开发者那里。或者可能会，但这并不是我关心的。

相反，我的工作将被外包到数据中心。

我在专业上所做的一切，从阅读和反馈规格到估算开发时间表，再到架构设计、编写代码和编写单元测试，以及审查他人的代码，这些所有事情都将受到自动化的影响。

当然，我们现在无法做到这一点，价格再高也不行。

但技术的最前沿不断进步，企业有巨大的经济动机用更便宜的东西取代我和我的同事；

对我来说，仅这一点就足以让人相信这种可能性。

[[https://hyponymo.us/2013/01/29/100-percent-unemployment/#:~:text=I%20write%20software,to%20the%20possibility][Source]]
#+end_quote

#+begin_quote
让我们记住，我们对那些目前无法为社会做出贡献的人是多么糟糕。

迟早我们将不得不面对这个问题：在一个大多数人没有经济价值的世界中，我们如何定义个人的价值？

[[https://hyponymo.us/2013/01/29/100-percent-unemployment/#:~:text=Let%20us%20keep%20in%20mind%20how%20poorly%20we%20treat%20those%20who%20cannot%20currently%20contribute%20to%20society.%20Sooner%20or%20later%20we%20will%20have%20to%20face%20this%20question%3A%20how%20do%20we%20define%20personal%20worth%20in%20a%20world%20where%20most%20people%20have%20no%20economic%20value%3F][Source]]
#+end_quote

** [[https://zh.wikipedia.org/wiki/%E5%85%AC%E6%B0%91%E8%AB%96%E5%A3%87_(%E6%8D%B7%E5%85%8B)][公民論壇 (捷克)]]

#+begin_quote
哈维尔为公民论坛亲定了八条对话规则：

1. 对话的目的是寻求真理，不是为了斗争；
2. 不做人身攻击；
3. 保持主题；
4. 辩论时要用证据；
5. 不要坚持错误不改；
6. 要分清对话与只准自己讲话的区别；
7. 对话要有记录；
8. 尽量理解对方。
#+end_quote

* 多媒体
** 视频
- [[https://www.bilibili.com/video/BV1eoQwYPEeu][我的人生目标，就是和你维持现状！｜北海道旅拍]] (04:44)
- [[https://www.bilibili.com/video/BV1uEQuYVEjX][台湾：一本名为青春的纪念册]] (27:38)
- [[https://www.bilibili.com/video/BV1i3QVYeEpx][热烈欢迎胡彦斌！他来了他来了，他带着最近“上头”的东西走来了！从数码到穿戴应有尽有！]] (24:36)
  #+begin_quote
  我自己觉得，人生如果过不好，就是因为你会看自己太多的不足，我觉得一定要去看到自己特别棒的地方，要肯定自己。
  #+end_quote
- [[https://www.bilibili.com/video/BV1P6QSYnERz][用滑动方块的碰撞次数来计算圆周率]] (23:37)
- [[https://www.bilibili.com/video/BV1FEXzYUEuK][陶喆从未曝光过的新专 demo!丨HOPICO X 陶喆丨未曝光的音轨]] (24:12)
- [[https://www.bilibili.com/video/BV1LFQDYqEKn][流行100年，胶片还会陪我们多久？]] (13:22)
** 博客

* Music
