#+title:  Emacs 中配置 .authinfo.gpg
#+INDEX:  Emacs 中配置 .authinfo.gpg
#+date: <2025-02-27 Thu>
#+lastmod: <2025-02-27 Thu 20:41>
#+author: Spike Leung
#+email: l-yanlei@hotmail.com
#+description: ""
#+tags: blog
#+LANGUAGE: zh-CN
#+startup: content indent

之前我写过一篇[[https://taxodium.ink/translation-in-emacs.html][在 Emacs 中集成翻译插件]]的文章，插件依赖一些 LLM 服务，LLM 服务需要配置对应的 API key，它们是定义在 =~/.authinfo= 中的。

但是 ~/.authinfo 是未加密的，如果泄露了，那么我的 API key 就会泄露被滥用，所以我觉得还是需要对它做一层加密。

这篇文章我会分享如何在 ~/.authinfo 中定义 API key、如何使用 [[https://www.gnupg.org/documentation/manuals/gnupg/index.html][GnuPG]] 对 ~/.authinfo 加密，以及如何配置 Emacs 从加密后的 =~/.authinfo.gpg= 中读取 API key。

* authinfo

#+begin_quote
有些连接到其他服务的 Emacs 软件包需要身份验证，由于反复提供相同的用户名和密码可能会令人烦恼，Emacs 通过 [[https://www.gnu.org/software/emacs/manual/html_mono/auth.html][auth-source]] 库提供了持久化信息。

默认情况下，身份验证信息来自 =~/.authinfo= 或 =~/.authinfo.gpg= 或 =~/.netrc= 文件。

这些文件的语法与 ftp 程序中的 netrc 文件类似，如下所示：

machine /mymachine/ login /myloginname/ password /mypassword/ port /myport/

[[https://www.gnu.org/software/emacs/manual/html_node/emacs/Authentication.html][Source]]
#+end_quote

Emacs 是通过 auth-source 去实现身份验证的，一般将验证信息(例如 API Key)存储在这三个文件中:

- ~/.authinfo
- ~/.authinfo.gpg (加密)
- ~/.netrc

而验证信息的格式是：

#+begin_verse
*machine* mymachine *login* myloginname *password* mypassword *port* myport
#+end_verse

其中:

- *machine* 服务器，DNS 名称或 IP 地址，在 auth-source-search[fn:1] 查询中称为 =:host= 。
- *login* 是用户名，在 auth-source-search 查询中称为 =:user= 。也可以使用 login 和 account 。
- *port* 是连接端口或协议，在 auth-source-search 查询中称为 =:port= 。
- *password* 就是对应的密钥，或者 API key 之类的

一些例子：

#+begin_example
machine localhost login spike port sudo password xxxx
machine 192.168.100.100 login root port ssh password xxxx
machine api.deepseek.com login apikey password xxxx
machine api.siliconflow.cn login apikey password xxxx
machine openrouter.ai login apikey password xxxx
machine openrouter.ai/api login apikey password xxxx
#+end_example

一些插件可能会基于 machine 或者 login 去查找密钥，具体如何设置就需要看插件是如何读取的。

例如 [[https://github.com/Elilif/emacs-immersive-translate/tree/main][emacs-immersive-translate]] 是这样读取的:

[[https://github.com/Elilif/emacs-immersive-translate/blob/1d00d558363985fa988fc40cd5093bfc6926d83e/immersive-translate.el#L197-L212][immersive-translate-api-key]]:
#+begin_src lisp
(defun immersive-translate-api-key (host user)
  "Lookup api key in the auth source.

By default, `immersive-translate-chatgpt-host' is used as HOST
and \"apikey\" as USER in Chatgpt backend.
\"fanyi-api.baidu.com\" is used as HOST and
`immersive-translate-baidu-appid' as USER in Baidu backend."
  (if-let ((secret (plist-get (car (auth-source-search
                                    :host host
                                    :user user
                                    :require '(:secret)))
                              :secret)))
      (if (functionp secret)
          (encode-coding-string (funcall secret) 'utf-8)
        secret)
    (user-error "No %s found in the auth source" user)))
#+end_src

[[https://github.com/Elilif/emacs-immersive-translate/blob/1d00d558363985fa988fc40cd5093bfc6926d83e/immersive-translate-chatgpt.el#L109C6-L111C66][immersive-translate-chatgpt.el]] 中设置 ChatGPT 的密钥:

#+begin_src lisp
  ;; ...其他代码
  ("Authorization" . ,(concat "Bearer " (immersive-translate-api-key
                                         immersive-translate-chatgpt-host
                                         "apikey"))))))
  ;; ...其他代码
#+end_src

可以看到，emacs-immersive-translate 基于 :host 和 :user 去查找的：

- =:host= (machine) 是 =immersive-translate-chatgpt-host= ，默认是 api.openai.com
- =:user= (login) 是 =apikey=

所以按照默认配置，当你获取到 openai 的 API key 后，要这样配置:

#+begin_example
machine api.openai.com login apikey password your_openai_api_key
#+end_example

* GnuPG 加密

我对 GnuPG 研究得不多，简单分享一下如何创建 gpg 密钥，如何加密文件。

1. 创建 gpg 密钥

执行 =gpg --full-generate-key= ，按照提示完成创建即可。

创建完成后可以通过 =gpg --list-keys= 查看当前得密钥，例如我执行后会得到：

#+begin_example
/home/spike/.gnupg/pubring.kbx
------------------------------
pub   rsa4096 2025-02-27 [SC]
      1BAF5568B6AFD3DB367B865B50AC4C6F1FD4B1CF
uid           [ultimate] SpikeLeung <l-yanlei@hotmail.com>
sub   rsa4096 2025-02-27 [E]
#+end_example

其中:

- =1BAF5568B6AFD3DB367B865B50AC4C6F1FD4B1CF= 是指纹(fingerprint)[fn:2]
- =[ultimate] SpikeLeung <l-yanlei@hotmail.com>= 是 uid
- =l-yanlei@hotmail.com= 是和这个 gpg 密钥关联的邮箱

2. 加密文件

=gpg -e -r "SpikeLeung" ~/.authinfo= 或者 =gpg -e -r "l-yanlei@hotmail.com" ~/.authinfo=

其中， =-e= 表示加密， =-r= 指定使用哪个 user-id，对应的是上面 uid 中的内容，你可以用名字或者邮箱。

加密成功的话，就会在当前目录生成一个带有 =.gpg= 后缀的加密文件 =~/.authinfo.gpg= 。

* 配置 Emacs 读取 ~/.authinfo.gpg

原来 ~/.authinfo 是未加密的，Emacs 里可以随便访问，现在加密了，那么在访问前就要先解密才能访问了。

为了让 Emacs 能够解密 gpg 加密的文件，我们需要让 Emacs 能够读取 gpg 密钥，然后用密钥去解密。

我们需要用到 [[https://www.gnu.org/software/emacs/manual/html_node/auth/The-Unix-password-store.html][The Unix password store (pass)]]，这是一个简单的密码管理程序。

* Refs

* Footnotes
[fn:1]auth-source-search 是 Emacs 中的一个函数，可以基于条件查询返回基于 auth-source 定义的密钥。

[fn:2]更详细的解释可以看 [[https://davesteele.github.io/gpg/2014/09/20/anatomy-of-a-gpg-key/][Anatomy of a GPG Key]]
