#+title: 胃镜检查
#+INDEX: 胃镜检查
#+date: <2024-10-16 Wed>
#+lastmod: <2024-10-16 Wed 11:30>
#+author: Spike Leung
#+email: l-yanlei@hotmail.com
#+description: ""
#+tags: blog

前阵子吞咽不舒服，感觉有异物感，而且牵扯到右边胸部上方疼痛。

不知道怎么了，以往有过咽喉炎，顶多就嗓子痛，现在有异物感且会牵扯疼痛感觉很异常。

去检查了耳鼻喉科，医生就说是咽喉炎，牵扯的地方不属于耳鼻喉他不管，可以看看消化内科。

消化内科也看了，但是食管是在喉咙正下方的，而不是胸部，医生也没啥建议，遂做了一个胃镜先检查一下。

预约好了胃镜，胃镜前一天的晚上九点就不能进食了，当天不能喝水，应该都是为了避免胃部有东西影响观察。

我做的是普通胃镜，不需要麻醉。

当天，做之前医生会给一瓶[[https://baike.baidu.com/item/%E7%9B%90%E9%85%B8%E8%BE%BE%E5%85%8B%E7%BD%97%E5%AE%81%E8%83%B6%E6%B5%86/1370268][盐酸达克罗宁胶浆]]喝下去，是一种局部麻醉的药物，喝完之后慢慢会有一种喉咙干涩的感觉，久了只能感觉到喉咙入口的一点点吞咽感。

做胃镜是躺在床上的，向左侧侧睡，双脚蜷缩。

做之前医生会给你戴上一个咬合的工具，是一个空心的圆柱体，避免嘴巴闭合用的。

接着医生会伸进去一根挺长的黑色管子，顶部是摄像头，粗细大概和喝珍珠奶茶的吸管差不多。

伸进去之后开始就会很难受，医生会让你用鼻子吸气，嘴巴呼气，口水不要吞咽，直接流到床上，床上会铺一些纸，避免弄脏。

越往下伸，到了胃，就感觉有好多气体出来，打了不少隔，而且会很想吐，止不住的收缩喉咙和胃。

医生会提醒不要吐，好好呼吸，我只能努力尝试去恢复呼吸，大口吸气呼吸让自己平稳下来。

如果中间发现一些息肉，还会伸进去一个活检钳去采样。

所幸整体的时间不是很长，应该就几分钟。

留了不少的口水，还有反胃的一些不知道是胃液还是啥，泛黄的液体。

总体来说挺难受的，有种受刑被逼供的感觉。

胃镜看不出来啥，又做了 CT，好像都没什么大问题，可能是胃液反流引起的一些问题，开了些药看看后续如何。

不舒服是从 10 月 8 日开始出现，到今天也没吃什么药，也开始好转了，异物感消失了，只是还有一点疼痛，牵扯感也很弱了。

年纪大了，加上平时运动少，饮食比较随意，作息也比较乱，身体开始出现很多问题。

还是身体要紧，好好锻炼，好好活着。

* 不太准确的费用明细

| 项目             | 费用 |
|------------------+------|
| 耳鼻喉挂号       |   50 |
| +耳鼻喉药物(没买)+ |  200 |
| 消化内科挂号     |   25 |
| 胃镜             |  480 |
| 胸部 CT          |  500 |
| 消化内科的药物   |  230 |
|------------------+------|
| 合计             | 1285 |
#+TBLFM: @>$2=vsum(@2$2..@7$2)-@3$2

大部分费用通过医保支付，个人支付 200 多左右。
