#+title: 武汉两日游
#+date: 2021-09-28T19:00:04+08:00
#+lastmod: 2021-09-28T19:00:04+08:00
#+draft: false
#+keywords[]:
#+description: ""
#+tags[]: travel
#+categories[]: 游记
* 出发 & 火车
  因为一些原因离职了，将要从上海去往广东，又一时无法入职，就想着不如沿着南下的路到没去过的城市走走。

  时间比较充足，就买了时间长的硬卧，晚上出发，第二天早上到，正好去吃顿热干面当早餐。
  本来买的是中铺，恰好碰到一个买了上铺，手又受伤缝针的女生，于是和她换了一下，到了另一个车厢的上铺。

  久违地坐长途火车，内心还是有些兴奋。小时候也曾坐二十多个小时的硬卧去上海，也是兴奋不已。看着车窗外
  不断变化的风景、看一本书消磨时光、用奶茶粉冲一杯香浓的奶茶、躺在硬卧上听着匡当匡当的声音，感受车
  身的晃动、期待着会和某个人认识聊天……都是关于火车的印象。

  记得小时候坐火车时，在火车站买了本叫《萼叶盛宴》的书，关于吸血鬼的，看了一路看完了，书中提到一首
  Eagles 的歌 「Waiting in the Weeds」， 后来反反复复听了很多遍。记得有一次隔间有个女生，一路上老是
  在放「不怕不怕」，"mayiya hei, mayiya hu, mayiya hei hei ~"，一路被洗脑，以至于现在还记得。

  关于火车，很喜欢余光中在《记忆像铁轨一样长》中的描述:

  #+begin_quote
  滚滚疾转的风火轮上，现代哪吒的心情，有时是出发的兴奋，有时是回程的慵懒，有时是午晴的遐思，有时是夜雨的寂寞。
  大玻璃窗招来豪阔的山水，远近的城村；窗外的光景不断，窗内的思绪不绝，真成了情景交融。
  尤其是在长途，终站尚远，两头都搭不上现实，这是你一切都被动的过渡时期，可以绝对自由地大想心事，任意识乱流。
  #+end_quote

  文中附带的一首诗也很喜欢, 土耳其诗人塔朗吉 (Cahit Sitki Taranci) 的 《火车》：

  #+begin_quote
  去什么地方呢？这么晚了，

  美丽的火车，孤独的火车？

  凄苦是你汽笛的声音，

  令人记起了许多事情。

  为什么我不该挥手舞手巾呢？

  乘客多少都跟我有亲。

  去吧，但愿你一路平安，

  桥都坚固，隧道都光明。
  #+end_quote

  也许对于火车的钟情，是因为即将远行的期待，分别时站台上的不舍，或是“两头都搭不上现实”的自由吧。

  夜深了，爬到上铺休息，再一次睡上铺，觉得上铺确实不太好。尽管便宜一些，但是空间狭小，由于空调
  在上铺，躺下时一直被空调的风吹着也不舒服（也许倒过来睡会好些？），不过凑合着一晚也就过去了。

* 热干面
  第二天一早，火车到达了武汉。来武汉怎能不吃一碗热干面？之前看 /盗月社/ 去武汉时，在 /舞台社区/ 吃了碗热干面，
  打算也去打个卡。然而在舞台社区附近绕了一圈没找着，就在一个看着也蛮多人光顾的店点了一碗。老板问要不要辣，
  寻思着自己能吃辣便说要，谁知道放的辣椒油不是一般的辣……也体会到了有的人吃不了辣的痛苦。
  不过面的味道还是不错的，裹满了酱的面，看着也很诱人。

  吃面时，有个大妈不知怎么跌倒了，被自行车压着，边上一个吃面的大叔便上去搭把手扶了起来，感到了人情的温暖。

* 东湖
  早餐过后，打算去湖南省博物馆逛逛，不巧当天是周一，博物馆闭馆，想预约第二天，但也早被约满了。本想着我是
  工作日出来逛，景点应该人比较少才对，但博物馆未来七天的票都预约满了，只好放弃。出游还是得提前至少七天做好
  准备才行。所幸对面的美术馆没啥人预约，预约好等明天过来逛，便往附近的东湖去了。

  东湖的面积比西湖还要大，边上就是武汉大学，华中科技大学，博物馆等，计划着逛一圈东湖，结果时太高估自己了，
  走了一段时间便走不动了。

  觉得湖都大同小异，西湖，玄武湖，东湖，都是漫步的好地方，都有大片的荷花，以及一些雕像，一些亭子，一次一两百的游船等。

  比较有趣的是遇到了一个大爷，他架着三脚架，用手机加长焦镜头在拍松鼠。他准备了一些坚果，放到树干的一个凹洞里，就等着
  松鼠跑下来吃。松鼠也是很机警，在树上上蹿下跳。大爷招着手，模仿着雌松鼠的声音，招呼着松鼠去吃。过了会，试探过一阵
  的松鼠就会跑到凹洞那，抓着坚果啃，大爷便趁机录下视频，说到时要做一个"东湖故事"。和大爷聊了聊，除了拍松鼠，他还
  拍过不少的鸟类，鸟妈妈张开翅膀护着自己的崽，两只鸟争食，一只鸟啄石头，“以石会友”，鸟儿怎么筑巢等等。真是羡慕大爷
  退休后的闲情雅致。

* 民宿小憩
  逛了小半天的东湖，走的真是够累了，决定回住处歇会儿，等到傍晚时分，去 /黄鹤楼/ 和 /长江大桥/ 看看夜景。
  路上看到有 /茶颜悦色，没想到在长沙之外也有/ ，点了杯攻略推荐的幽兰拿铁，路边随便打包了分卤面，便回去歇着了。

  住的是一个在汉江路地铁站附近的民宿，叫「FDK的民宿」，空间蛮大d的，有投影，附近似乎是比较繁华的地段，但民宿里的插座
  不知道是不是有限制，充电比较慢。

  歇到将近五点，出发去黄鹤楼。

* 长江大桥
  因为去的比较晚，黄鹤楼已经停止检票了。不过本来也不是很渴望上去，觉得楼和湖也一样，各处的也差不多，花几十块钱进去，
  尽是些商业化的建筑，上个楼看看也就没啥了……倒是想起了句诗，"日暮乡关何处是，烟波江上使人愁"，以前的昵称便是从
  诗句里提取的。

  既然黄鹤楼上不了，就直奔长江大桥，夜晚的江景应该很不错吧。路上经过了 /户部巷/ ，似乎是条小吃街，估摸着
  和上海豫园老街差不多，也没兴趣往里逛。

  走了十几分钟，总算走到长江大桥边上了。一条蓝色的大桥，跨过宽广的长江，笔直地连到了对岸，偶尔一辆列车从桥中穿行而过。
  听着江水拍岸的涛声，客船的引擎声，凉快的江风拂面而过，对岸是五彩斑斓的建筑，美丽的江景！

  在大桥边上，有很多对拍婚纱照的新人，有的还点了烟花，拍出来应该会挺好看的吧~

  时间还早，就沿着江边散散步吧。听着 Jacob Montague 的专辑 《North Winds》，吹着凉快的江风，看那宽广的长江，心情
  真是舒畅。沿路有人摆摊射气球，有跳广场舞的大妈，有人放着五彩斑斓的风筝，也有摆桌子喝茶的人，还有吹着萨克斯的小乐队……
  五星红旗在江风的拉扯下，迎风飘扬，不禁哼起了歌，"五星红旗迎风飘扬，胜利歌声多么嘹亮……"。

  以前心情不好时会到滨江大道遛一遛，看着宽广的江，吹着凉快的风，心情多少会明亮一些。长江沿岸丝毫不逊色上海的滨江大道和外滩，
  夜景也是很华丽，觉得是来武汉不可错过的地方。

  走累了便到渡口坐轮渡到对岸，由于长江宽广，渡江要十来分钟，可以在江中尽情欣赏两岸的夜景。夜里的票价要十块钱，白天似乎只要一
  块五。

* 神雕侠侣卤菜
  到对岸后，便去觅食，还是去打卡盗月社视频出现的店，神雕侠侣卤菜。视频里拍的藕汤似乎很好喝的样子，可惜走半天来到店里，因为季节
  没到，店里还没有藕汤，要过了十月后才有。不过来都来了，就随便吃点吧。点了些卤菜和一份凉面，卤菜味道还是蛮不错的，香，辣。凉面
  就和平时吃的凉皮味道差不多，不过是凉皮换成面了。尽管打卡失败，但看到视频里出现过的阿姨，还是有点神奇的感觉，阿姨也还是像视频
  中那样，开心的样子。

  饭后又点了杯茶颜悦色，买了点啤酒，看了利物浦的英超第六轮重播（这场比赛真是精彩），一天就结束了。

* 湖北省美术馆
  尽管做了点攻略，但也不知道武汉还有什么好逛的去处。大学因为疫情，也不对外开放，计划着逛一逛美术馆，就结束武汉之行了。

  美术馆最近在陈列刘依闻的油画作品，也介绍了他的生平。还有一个数字美术相关的主题展，里头是些看不懂的抽象的作品，例如有一幅是 +打印+
  画了 81 个格子，有一幅是 81 个格子里分别填写 1, 2……81，不太能理解想表达的内容。还有一层是固定展览，
  展示了湖北美术从民国时期到改革开发这段时间的变化。

  上了个厕所出来还被阿姨说了一顿，因为手没甩干，水滴到外面了。确实是会给阿姨添加打扫的工作呢，以后还是要注意一下。

* 结束
  逛完美术馆，还想着看看白天的长江，来到了江滩公园，看到有人在长江游泳，不知是不是打算渡江，佩服。

  尽管没去什么地方，不觉间便傍晚了，武汉也没啥想去的地方了，武汉之行就此结束了。留了点遗憾，没能喝上藕汤，希望下次来能吃到吧。

  乘上开往长沙的火车，再见，武汉。
