#+title: 长沙两日游
#+date: 2021-10-01T14:50:31+08:00
#+lastmod: 2021-10-01T14:50:31+08:00
#+draft: false
* 住
  来到长沙后，在 /五一广场/ 附近找了个叫 /新友缘/ 酒店，位置较好。五一广场距离长沙站和长沙南站都不是很远，
  附近就是太平街，黄兴广场，都是繁华的地方。酒店里还有投影仪，买点夜宵啤酒，看球看电影都不错。

* 岳麓山
  之前看视频，看到岳麓山有滑道，坐着一个小车，像滑滑梯一样滑下来，便也想去尝试一下。我是从岳麓山的正门进去的，
  一路沿着宽敞的马路走上去，甚至走过了岳麓山最高点都全然不知。最高点也就 300 多米，那里有一个商业区域，正好
  是缆车上下站的附近，有很多吃喝的店。山顶和我的期望不大一样，我期望能在山顶，俯视长沙，看湘江橘子洲，然而山顶
  就是个商业区，很多树木遮挡了视线。滑道就在山顶附近，但是还有很多地方没走，又不想就这样下山，便放弃了滑道，
  继续往前。走到一个岔口，看到一个介绍:

  #+begin_quote
  岳麓山，其山脉属南岳衡山，古人把岳麓山列为南岳七士二峰之一，称灵麓峰。南北朝刘宋时 《南岳记》载
  “南岳周围八百里，回雁为首，岳麓为足。” 故名岳𨤳。

  据史料记载：游山者渡江而来，上岸过柳堤牌楼口，
  沿梅堤古官道，过咏归桥，濯清池，自卑亭 (清代康熙二十七年修)，先游岳麓书院。出院后过仙巢吹香亭，
  即循此山脊之道登山，自“道中庸〞达 “极高明” 登高一望。于是怀抱恢廓，自卑顿消，继续攀登，则可达赫曦台，睹禹王碑。
  禹王碑被称为 “岳麓之奇当无最此己”。

  岳麓山上山古道，原经爱晚亭攀青枫峡，峡谷峻险难上，行人视为畏途。1917年春，黄克强先生灵柩自沪运湘，国葬麓山，始筑马路绕出峡外。
  解放后迭经加修，更为平坦。大马路代替了陡峭山路，古游道自此没落。值2019年春，长沙市岳麓区政府投资重修，重现古道风彩。
  重修后古游道分两段： 一段为文化步道，全长1.0KM，自卑亭、湖南大学历史建筑群、东方红广场等，人文风光，钟灵毓秀。
  一段为历史步道，全长2.0KM，爱晚亭、极高明亭、道中庸亭、禹王碑等麓山古韵，积厚流光．
  #+end_quote

  也就是说从正门走的大马路是后来修的，方便游客上山。以前的人上山是从另一条古道上的。那既然来一趟，总得走走这条古道。
  古道比大路有趣，就是常见的登山步道，一阶一阶的楼梯，阶梯是些看着古朴的石头。跟着介绍里说的路径下山，很快就走到了 /禹王碑/ ，
  这里有个大平台，作为观景台来说，要比山顶的风光好的多。继续下行，经过 /极高明/ ， /道中庸/ ， 路过一些烈士墓碑，来到 /爱晚亭/,
  /岳麓书院/ 。总的来说，古道也没啥看的，但比大马路要有趣一些。从古道下山出去，就是 /湖南大学/ 了。

  如果再来一次岳麓山，我想我会选择从湖南大学的古道上山，然后再坐滑道下山，两全其美。

  至于湖南大学，也是挺有特色的。不像常见的大学，有一个封闭起来的大学园区，湖南大学的教学楼和周边
  的建筑混为一体，出门便是车水马龙的街道，只是每座楼的入口都需要刷卡进入。

* 东(冬)瓜山
  爬山下来也饿了，之前的同事推荐过一个有很多好吃的地方 —— /冬瓜山/ , 也有叫 /东瓜山/ 。跟着导航，穿越了几条漆黑的巷子，总算是
  来到了冬瓜山一条巷，全都是人和各种店铺，挂着五光十色的招牌，相当的热闹。巷子里大部分都是烧烤，炸物，人来车往。按照热评，
  吃了 /幸福的味道/ 的桃子，很脆，味道独特; /丹丹热卤/ ， 点了份四合一卤菜，味道也不错，又辣又香；吃了 /盟重烧烤/ ， 味道也不错，但
  感觉量有点点少。还有很多看着好吃的店，然而独自旅行，无法都去尝试了。

* Whatever 咖啡
  酒饱饭足，也该回去休息了。跟着导航骑着自行车，小心的前行，不知觉来到一个小巷，见到一家装修比较独特的小店。犹豫了会儿，还是
  决定进去店里看看。

  原来是一家咖啡店，店铺的装修基本是橙红色，奶白色，绿色，看着很舒服。咖啡店是由两个年轻的帅小伙开的，店里
  放着非常经典的摇滚歌曲。很兴奋的发现，老板也是 Beatles 的乐迷，墙上挂了很多 Beatles 的黑胶唱片，还有 Queen，Blur，David Bowie...
  都是我很喜欢的乐队和歌手。点了杯冰的手冲咖啡，咖啡的容器也蛮特别的，瓶子外面凹进去一个口用来放冰块，给咖啡降温同时又不会冲淡
  咖啡的味道。店里充满了细节，很多有趣的手办（歌手相关的），老式的拨杆开关，老式的挂历，藏在墙边的摇摇乐游戏（25 摇一次，根据号码得
  一杯手冲咖啡）……总之，来过便会感受到这是一间很用心经营的咖啡店。临走时，老板还送了一杯量的咖啡豆给我回去尝试。

  偶然地经过这家店，真是个惊喜。如果还有机会去长沙，也一定要再来咖啡店坐坐。
* 橘子洲
  在长沙的第二天，又是睡到了中午起来。预约的博物馆错过了，便打算去橘子洲走走。橘子洲是湘江里的一个小岛，乘地铁很容易就来到了。
  景区里是免费的，坐游览车则要几十块。也没什么可去的地方，便想着花些时间步行看看。沿着湘江边，迎着热乎乎的阳光，听着 Beatles 的
  专辑，慢悠悠地走着。走了一会儿，看到有个大叔在湘江里游泳，从对岸游到橘子洲。上岸后，路人都说佩服，但也表示担心，万一溺水人可就
  没了。看他内裤后有个方块鼓起来，问了下，原来是放了块泡沫，也许多少能在溺水时给到一些帮助吧。心里祈祷大叔安全，便继续往前，到尽头就看到了
  标志性的 /毛泽东青年艺术雕塑/ 。拍了照打了卡，也已经是日暮时分了，就到湘江边欣赏日落，看太阳渐渐隐没在岳麓山后。

  对于游客，主要就是想看看毛泽东青年艺术雕塑吧。对于本地人来说，橘子洲更像是一个公园，平时散步的地方。

* 太平街
  太平街在五一广场附近，也是条美食街，四处是臭豆腐，糖油粑粑，各种摊子，店铺。里面有贾谊故居， 就是《过秦论》的作者，汉代名士。
  看了看他的年表，他在 22 岁的时候，就写出了 《过秦论》，并且身居高位，活到了 33 岁。反观自己，也二十多了，却没有什么成绩。也许对于
  那时的人来说，寿命没有那么长，会更努力的在有生之年去实现价值吧。假如知道自己的寿命，是否会活得更尽力一些呢?

* 特色美食
  说到长沙的特色美食，自然是臭豆腐，糖油粑粑，还有茶颜悦色（等）。这些小吃茶饮，真的遍地都是，走几十米就有一间卖臭豆腐或者茶颜悦色的。
  吃过后，长沙的臭豆腐确实要比外面吃到的好吃，外层酥脆，里面多汁，有点辣。看了做豆腐的过程，将豆腐炸得鼓起来，然后从中间戳开，浇上
  一些汤汁和配料，所以吃起来会觉得汁水丰富。至于茶颜悦色，特色就是排队的人多，味道确实比平时喝的奶茶好喝些，店里的周边也不错。

  除了上面这些，嗦粉似乎也是湖南的一个特色。长沙也有喝多嗦粉的地方，其中看 /绵阳料理/ 时了解到一个叫 /馨陀粉店/ 的地方，据说早上十点就会卖完了，
  可见很受欢迎。然而连续两天都睡过了，没能吃上，临走的当天，终于赶了个早来到店里。人确实不少，络绎不绝。点上一碗粉，加点剁椒，蒜蓉，
  酸豆角等等，味道真是不错。早上能吃上这么一碗，也是让人精神满满，就是吃完有点辣...

* The End
  就两三天的游玩感受下来，觉得长沙其实景点不是特别多，但是吃喝真的是遍地都是，人来人往，非常的热闹，充满了烟火气。有机会的话，再来吧！
