#+title: About Feeds
#+INDEX: About Feed
#+date: <2025-04-10 Thu>
#+lastmod: <2025-04-10 Thu 23:11>
#+author: Spike Leung
#+email: l-yanlei@hotmail.com
#+description: ""
#+tags: blog
#+LANGUAGE: zh-CN

还在完善中... ˊ_​>ˋ

* 什么是订阅源 (feed)？（又称 RSS）

订阅源 (feed) 是一种规范，其中以 [[https://zh.wikipedia.org/zh-tw/RSS][RSS(Really Simple Syndication)]] 最广为人知，此外还有 [[https://zh.wikipedia.org/wiki/Atom_(%E6%A8%99%E6%BA%96)][Atom]] 规范。

人们可以发布订阅源，然后感兴趣的读者可以订阅他们发布的订阅源。

你可以想象成订杂志/报纸，在你订阅之后，每当有更新，你就会收到新的内容，想看什么你就订阅什么，你也可以自己发布让别人订阅。

或者类比成视频网站的关注，当你关注了一个 UP 主，他更新了你就会收到通知，同样的，你也可以成为 UP 主，发布你的内容。

一般来说，RSS 大多会出现在博客和新文网站里，当你看到一个这样的按钮：

#+begin_export html
<img src="/images/about-feeds/orange-square.svg">
#+end_export

就意味着网站上存在 RSS 订阅源，你可以点击按钮找到 feed 链接进行订阅。

当您只订阅一个网站时，您可能会觉得没有节省多少时间。

但是当您最终订阅 10 个或 20 个网站时，您会发现您的新闻阅读器将成为您获取新闻和了解最新信息的常用场所。

你不需要经常从书签里找到那些你喜欢看的网站，只要打开订阅应用程序，你订阅的都在那里等着你。

您不会错过任何内容，没有算法会决定从您的订阅源中删除内容。

想要停止接收？只需取消订阅该订阅源即可。

* 如何获取订阅应用程序？

要订阅，你需要有一个应用程序去记录订阅源，解析订阅源的内容。

它感觉有点像电子邮件应用程序，因为它有一个包含所有最新内容的收件箱。

有许多不同的新闻阅读器应用程序可供选择。

在您的手机或笔记本电脑上安装一个应用程序， 或者通过网站使用新闻阅读器应用程序。

以下是一些订阅源应用：

- [[https://follow.is][Folo]] - 免费，目前还在测试阶段，如果你需要的话可以找我要邀请码。

  而且除了能订阅文章，还能订阅视频，图片等，可玩性比较高。

  支持 web/android/iOS/macOS/windows/linux。
- [[https://github.com/FreshRSS/FreshRSS][FreshRSS]] - 一个可以自己部署的服务，简单够用。应该只支持 web 访问。
- [[https://feedly.com][Feedly]] - 免费提供最多 100 个订阅。支持 web/android/iOS。
- [[https://www.inoreader.com][Inoreader]] - 免费提供最多 150 个订阅。支持 web/android/iOS。
- [[https://github.com/skeeto/elfeed][elfeed]] & [[https://github.com/remyhonig/elfeed-org][elfeed-org]] - 如何你是一个 Emacs 用户，你可以使用 elfeed，简单够用。

选择哪个并不重要，因为这些应用都可以很容易地导出您的订阅列表，并在将来将它们移动到另一个应用程序。

选择一个你喜欢的就好了，如果你实在不知道怎么选，就用 [[https://follow.is][Folo]] 吧。

* 如何使用我的订阅应用程序订阅订阅源？

您需要订阅源 URL。

要获得此 URL，请转到您要订阅的网站并找到该 RSS 链接或订阅源图标。

然后...

- 在桌面上，右键单击链接并选择 “复制链接地址” 或类似选项。
- 在移动设备上，点击并按住链接直到出现菜单。选择 “复制链接” 或类似选项。

然后转到您的新闻阅读器应用程序，并寻找一个功能，其名称类似于：

- “订阅”
- “添加网络订阅源”
- 或者可能是一个 “+” 图标

并粘贴订阅源 URL。

这就好啦！｡:.ﾟヽ(*´∀`)ﾉﾟ.:｡

您现在可以在您的新闻阅读器中阅读最新内容。

* 接下来做什么？

- 寻找更多阅读内容！这里有一些订阅源你可以看看，如果你用 Folo 也可以直接在里面探索。
  + [[https://blogroll.org][Blogroll]] 和 [[https://ooh.directory][ooh.directory]] 这两个都是手工整理的博客目录，按主题组织。
  + 后续补充更多
- 开始你自己的博客！
  + [[https://getblogging.org][Get Blogging!]] 是一个关于开始博客的实用指南。
  + 后续补充更多
- 不要局限于中文内容！你可以用 [[https://immersivetranslate.com/zh-Hans/][沉浸式翻译]] 帮助你在浏览器和手机上阅读，你的视野可以更宽广！

* 谁制作了这个网站？

[[https://aboutfeeds.com][About Feeds]] 是来自 ([[https://interconnected.org][Matt Webb]]) 的一个免费网站。

作者创建这个网站是因为第一次使用网络订阅源很难，他想解决这个问题。[fn:1]

而我看到后觉得很棒，然后翻译了一下加入到自己的博客，也稍微做了一些适合中文读者的修改。

您是网站所有者吗？

请考虑在您的订阅源链接或 RSS 图标旁边添加一个 [[https://aboutfeeds.com][帮助！什么是订阅源？]] 的链接。[fn:2]

如果您有权访问代码，请使用 [[https://github.com/genmon/aboutfeeds/blob/main/tools/pretty-feed-v3.xsl][pretty-feed.xsl]][fn:3] 设置您的订阅源样式，使其对新用户友好。

要贡献或提供反馈，请 [[https://github.com/genmon/aboutfeeds][在 GitHub 上的 About Feeds 存储库上发起讨论]]。[fn:4]

* Licence

文中的订阅图标来自 [[https://commons.wikimedia.org/wiki/File:Feed-icon.svg][Wikimedia Commons]] 并且遵循 [[https://www.mozilla.org/en-US/MPL/1.1/][Mozilla Public License Version 1.1]] 协议下使用。

* Footnotes
[fn:1] [[https://aboutfeeds.com/why][阅读关于为什么这个网站存在的原因。]]
[fn:2] 或者你也可以指向我写的 [[file:about-feeds.org][About Feeds]]。
[fn:3] 作者使用的是 RSS，如果你是用 Atom，你可以参考我的 [[https://github.com/Spike-Leung/taxodium/blob/org-publish/publish/styles/pretty-feed-v3.xsl][pretty-feed-v3.xsl]]。
[fn:4] 如果有能力，让我们一起去把作者这个仓库弄好吧，使其支持 Atom 和多语言。
