#+title: Weekly#12
#+INDEX: weekly!#12
#+date: <2024-10-10 Thu>
#+lastmod: <2024-10-10 Thu 20:45>
#+author: Spike Leung
#+email: l-yanlei@hotmail.com
#+description: ""
#+tags: weekly

* News | Article

** [[https://rxjourney.com.ng/all-we-really-have-in-this-world-is-ourselves][All We Really Have in This World Is Ourselves]]

#+begin_quote
但问题是：到了下午 4 点，我就会脱下大衣，告诉他们我要回家了。

只有当我正在进行一场精彩的谈话或享受同事们的陪伴时，我才会在下午 4 点之后继续工作。

我不会为了做更多的工作而加班，因为最终，没有我，工作也会继续。

我的同事会向我的家人表示慰问，并在社交媒体上发表对我的赞美之词，但很快，他们就会一切照旧。

我不会在没有报酬的情况下自杀式地加班。

生活是残酷的。生活是悲伤的。生活是孤独的。

有时，在家里，我只是想哭。
#+end_quote

看着作者的文字，觉得有些悲伤。

前阵子还看到一个帖子:  [[https://v2ex.com/t/1078509][父母不在了，是不是就四海为家了？]]，也是让人感到孤独和悲伤。

* Tutorial

** [[https://evilmartians.com/chronicles/oklch-in-css-why-quit-rgb-hsl][OKLCH in CSS: why we moved from RGB and HSL]]

一篇关于 [[https://developer.mozilla.org/en-US/docs/Web/CSS/color_value/oklch][oklch()]] 的文章，对于为什么用，怎么用解释的很详细，也对比了和其他语法的差别。

#+begin_quote
=H= is the hue angle.

It goes from 0 to 360, through red 20, yellow 90, green 140, blue 220, purple 320 and then back to red.

You can use Roy G. Biv mnemonic by giving around 50° to each letter.
#+end_quote

其中关于如何记住色轮的值，作者提到了 [[https://www.wikiwand.com/en/articles/ROYGBIV][ROYGBIV]] 的方法，觉得还不错。

我觉得 "*R* ead  *O* ut  *Y* our  *G* ood  *B* ook  *I* n  *V* erse" 这句话还比较容易记忆。

* Code

* Cool Bit

* Tool | Library

** [[https://chromewebstore.google.com/detail/aria-devtools/dneemiigcbbgbdjlcdjjnianlikimpck][ARIA DevTools]]

检查页面 ARIA(Accessible Rich Internet Applications) 的 Chrome 插件。

** [[https://chromewebstore.google.com/detail/kimi-%E6%B5%8F%E8%A7%88%E5%99%A8%E5%8A%A9%E6%89%8B/caejcfciegnnnepdhaopdogngbmojodl][Kimi 浏览器助手]]

Chrome 插件，可以集成 Kimi，选择内容询问。

** [[https://zeli.app/zh][zeli]]

HackerNews AI 版，会翻译标题，以及对文章内容做摘要。

可以看看作者的帖子： [[https://v2ex.com/t/1078143][因为每天都会读 Hacker News 和 AI 论文，我做了一个工具]]。

** [[https://search.luxirty.com/][Luxirty Search]]

#+begin_quote
一个搜索引擎，基于 Google，屏蔽内容农场，无广告，无跟踪，干净，简洁，快。
#+end_quote

* Music
