#+title: Weekly#18
#+INDEX: weekly!#18
#+date: <2024-11-21 Thu>
#+lastmod: <2024-11-21 Thu 10:03>
#+author: Spike Leung
#+email: l-yanlei@hotmail.com
#+description: "Weekly info collected by Spike Leung"
#+keywords: "Weekly News Code Music"
#+tags: weekly
#+OPTIONS: toc:1
#+LANGUAGE: zh-CN

* News | Article

** [[https://1q43.blog/post/5322][幸福的积分]]


** [[https://mp.weixin.qq.com/s/srhomWF5Oni1wtTkcnPtIg][这个看似羞耻的小动作，谁做谁快乐]]

#+begin_quote
在亲密的强关系之外，那些点头之交的弱关系（Weak Ties），对缓解孤独、增加归属感同样重要。
#+end_quote

#+begin_quote
与社交关系的质量或强度相比，社交互动的数量对个人福祉的贡献更大。
#+end_quote

#+begin_quote
2023 年一项大样本量的调查研究表明，与那些独来独往、避免和陌生人交流的人相比，经常和陌生人进行简单即时互动（闲谈，或者只是感谢和问候）的人，主观幸福感和生活满意度更高。
#+end_quote

#+begin_quote
与陌生人短暂地闲聊，会让人心情更好以及感受到与他人的联结感。这些积极的情绪，正是幸福感的来源。

更要重的是，这些交流无论多么简短，都是在提醒我们，自己是社区和更大世界的一部分。

当它们更频繁地发生时，就会像夜里星星点点的灯光汇聚在一起，让我们感知到自己被接纳、不孤独。
#+end_quote

#+begin_quote
...面对陌生人我们没有太多的包袱和情感负担，反倒松弛放得开。

也因为期待成本为零，所以任何交流都可能带来惊喜。就像寻宝，只要有一次感受到了一些波动、感触、震动，那就赚了。

打个招呼，就能收获一点点暖意。

聊两句家常，人际支持网上就多了一点弱关系。

谈一谈经验和看法，便得以窥见不一样的人生，发展出对人和事更深入的理解。
#+end_quote

** [[https://registerspill.thorstenball.com/p/they-all-use-it][They all use it]]

面对新技术的出现，应该要积极拥抱，尝试了解一下，而不是视而不见。

尝试用过一阵子的 Cursor，体验挺好的，不过当任务复杂一点，或许是我给的 prompt 不够准确，往往达不到我想要的效果，或者需要我调一阵。

受限于自己的技术，我还没能在 Emacs 里集成 LLM，大多数时候编码还是靠自己，但有时还是很希望有 LLM 能帮我完成一些简单的重复编码工作，例如帮我完成 TS 的类型定义。

#+begin_quote
我不明白的是，作为 2024 年的程序员，你怎么能对一项据说将从根本上改变我们未来编程方式的技术没有丝毫好奇？

[[https://registerspill.thorstenball.com/p/they-all-use-it#:~:text=What%20I%20don%E2%80%99t%20get%20it%20is%20how%20you%20can%20be%20a%20programmer%20in%20the%20year%20twenty%20twenty%2Dfour%20and%20not%20be%20the%20tiniest%20bit%20curious%20about%20a%20technology%20that%E2%80%99s%20said%20to%20be%20fundamentally%20changing%20how%20we%E2%80%99ll%20program%20in%20the%20future][Source]]
#+end_quote

#+begin_quote
我想说的是，自从我接触编程以来，我就认为程序员的一个共同特征就是好奇心和学习的意愿，我们的格言是我们永远不能停止学习，因为我们正在做的事情在我们的指尖下不断变化，如果我们不注意，它就可能从我们身边溜走，留给我们的知识不再有用。

也许这种假设是错误的，也许我们并不都有这种特质，也许这也没关系，但即使如此......我不明白你怎么能看到世界上最优秀的程序员使用新技术来提高编程能力，却对此视而不见。

你怎么能看到他们都在使用它，而不去想，好吧，也许不全是废话，也许有什么东西在那里，我需要弄清楚它是什么？

[[https://registerspill.thorstenball.com/p/they-all-use-it#:~:text=What%20I%E2%80%99m%20saying,what%20it%20is%3F][Source]]
#+end_quote

** [[https://www.youtube.com/watch?v=zSK76r1zEFc&ab_channel=BadatCSS][we need better design tools. this web expert tells us why]]

#+begin_quote
网页设计工具固然很棒，但它们仍然无法满足 CSS 所有令人难以置信的内在功能。

虽然 Figma 中也有自动布局等功能，但它们仍然无法满足网络内容驱动的所有功能。

为什么我们仍然试图在设计工具中画出漂亮的图画，并把网络当作是这样工作的呢？

我们无法控制网站在不同设备、不同网络和不同用户偏好下加载时发生的每一个细节。

马蒂亚斯-奥特（Mattias Ott）将与我们一起探讨设计工具落后于 CSS 的原因，以及我们在网页设计中取得进步所需的心态和技能。
#+end_quote

** [[https://blog.ppresume.com/posts/zh-cn/on-typesetting-engines][排版引擎纵谈：程序员的视角]]

作者比较了几种排版引擎，这篇博文看起来工作量很大。

* Tutorial

** [[https://www.jacobparis.com/content/react-ts][Essential Typescript for React]]

一些在 React 中使用 TS 的技巧。

我 TS 用得还不是很多，工作中接触的很多项目都是历史项目，没有启用 TS，对于老项目我会使用 [[https://tsdoc.org/][TSDoc]] 去标记类型。

TS 的类型确实会给开发带来不少帮助，例如类型提示，自动补全提示，类型校验等。

由于使用得不够多，TS 用起来我还是不是很熟练，例如偶尔需要一个类型，我会有点犹豫，到底应该在代码附近写类型，还是在一个单独的文件里面维护类型，方便复用？有时需要引用一个依赖库的类型，也需要从依赖库里找一阵子找到对应的类型。

实际使用，可能也需要封装一些 TS 方法函数，网上也有一些现成的库，例如 [[https://github.com/piotrwitek/utility-types][utility-types]]，[[https://github.com/millsp/ts-toolbelt][ts-toolbelt]]。

** [[https://thecopenhagenbook.com/][The Copenhagen Book]]

#+begin_quote
《哥本哈根手册》提供了在网络应用程序中实施认证 (Auth) 的一般指南。

它是免费、开源和社区维护的。

它有时可能会有意见或不完整，但我们希望它能填补在线资源的某些空白。

我们建议将其与 [[https://cheatsheetseries.owasp.org/index.html][OWASP Cheat Sheet Series]] 一起使用。
#+end_quote

** [[https://matklad.github.io/2024/07/25/git-worktrees.html][How I Use Git Worktrees]]

作者分享了一些他使用 [[https://git-scm.com/docs/git-worktree][git-worktree]] 的经验。

git-worktree 可以复制当前的 repo，变成一个新的 repo 目录。

过程有点像是新建一个目录，然后将某个分支 clone 到这个目录，同时它和当前 repo 还保持一定的关系，可以通过 worktree 相关命令管理。

使用场景一般是在当前 repo 开发过程中，突然插入一些别的事情需要改，但又不想影响当前 repo 的进度，就可以选择用 worktree 在新的目录里完成相关改动，再无缝切回当前 repo。

这样就不用 stash，commit，reset，branch 来来回回地切换 repo 的状态。

** [[https://www.builder.io/m/explainers/server-side-rendering][A Guide to Server-Side Rendering]]

一篇关于 SSR(Server-Side Rendering) 的介绍，关于 SSR 定义，实现，以及优缺点。

主流前端框架都有相关的 SSR 方案/框架。

关于 SSR，还可以看看 [[https://taxodium.ink/17.html][Weekly#17]] 中分享的文章：[[https://jakelazaroff.com/words/whats-a-single-page-app/][What's a Single-Page App?]]

** [[https://www.trevorlasn.com/blog/symbols-in-javascript][Exploring JavaScript Symbols]]

作者分享了一些他对 [[https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol][Symbol]] 的理解，以及相关用法。

Symbol 的一些使用场景：

- 使用 [[https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol/iterator][Symbol.iterator]]，让对象可以被遍历
- 给对象添加唯一的 key，同时不影响现有的 key
- [[https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol/for][Symbol.for()]] 创建可共享的 Symbol

** [[https://www.telerik.com/blogs/mapping-promises-javascript][Mapping Over Promises in JavaScript]]

遍历 Promises 的方法，直接用 [[https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/map][Array.prototype.map()]] 遍历，返回的是未 resolve 的 Promise，如果需要 resolve 后的，可以用：

1. 如果多个 promise 是串行执行的，可以考虑 [[https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/for...of][for...of]]
2. 如果并行，考虑 [[https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/all][Promise.all()]]
3. [[https://github.com/sindresorhus/p-map][p-map]]，可以并行，同时控制并行的数量

** [[https://pavinberg.github.io/emacs-book/zh/][专业 Emacs 入门]]

欢迎入门 Emacs (ﾉ>ω<)ﾉ

* Code

** [[https://abstract.properties/the-shadow-dom-is-in-the-front.html][The Shadow DOM is in the front]]

关于 [[https://developer.mozilla.org/en-US/docs/Web/API/Web_components/Using_shadow_DOM][Shadow DOM]] 的简单介绍，里面的实例蛮好玩的。

Shadow DOM 通常会和 [[https://developer.mozilla.org/en-US/docs/Web/API/Web_components/Using_custom_elements][Custom Elements]] 结合使用。

#+begin_quote
有了 Shadow DOM，它们就能像贴纸一样：在任何网站上的行为和显示都完全相同，无论该网站是如何通过 CSS 进行样式设计的。

[[https://abstract.properties/the-shadow-dom-is-in-the-front.html#:~:text=With%20the%20Shadow%20DOM%2C%20they%20can%20act%20like%20a%20sticker%3A%20behaving%20and%20displaying%20exactly%20the%20same%20on%20any%20website%2C%20regardless%20of%20how%20that%20website%20is%20styled%20via%20CSS][Source]]
#+end_quote

** [[https://moderncss.dev/12-modern-css-one-line-upgrades/][12 Modern CSS One-Line Upgrades]]

#+begin_quote
有时，改进应用程序的 CSS 只需单行升级或增强！

了解 12 种属性，开始将它们融入到你的项目中，从而减少技术债务，移除 JavaScript，轻松获得用户体验。
#+end_quote

** [YouTube][[https://www.youtube.com/watch?v=Vzj3jSUbMtI&ab_channel=KevinPowell][At Last! Simple details/summary animation with pure CSS]]

作者分享了怎么给 [[https://developer.mozilla.org/en-US/docs/Web/HTML/Element/details][details]] 添加过渡效果，几行 CSS 就能实现不错的过渡效果，真不错！可惜浏览器的兼容性还不好。

按照作者的代码尝试给博客的 details 元素添加过渡效果，但是没有生效，等以后浏览器适配得比较好的时候，再回头添加一下。

** [[https://css-tricks.com/popping-comments-with-css-anchor-positioning-and-view-driven-animations/][Popping Comments With CSS Anchor Positioning and View-Driven Animations]]

之前看到一些博客，可以放一些脚注在文章的左右两边，看起来很不错。

文章利用一个较新的 CSS 功能 [[https://css-tricks.com/css-anchor-positioning-guide/][Anchor Positioning]] 实现了这样的效果，不过依然是存在浏览器的兼容问题。

文章的实现方式是将脚注放在内容的附近，但是我博客的脚注是列在最后的，后面看看能不能利用这个功能把左右脚注实现一下。

* Cool Bit

** [[https://codepen.io/vineethtrv/pen/XWvOWxy][Counter]]

纯 CSS 实现的一个数字倒数效果。

** [[https://janarosmonaliev.github.io/github-globe/][Github Globe]]

#+begin_quote
The Globe from Github's homepage implemented in ThreeJS with beautiful shading.
#+end_quote

** [[https://www.codingfont.com/][CodingFont]]

通过多次比较，找到一款你喜欢的代码字体。

* Tool | Library

** [[https://github.com/extism/extism][Extism]]

#+begin_quote
Extism 是使用 WebAssembly (Wasm) 构建的轻量级框架。

它支持在服务器、边缘、CLI、物联网、浏览器等一切设备上运行 Wasm 代码。

Extism 的设计宗旨是 "通用"，即无论在哪里运行，它都支持通用接口。
#+end_quote

#+begin_quote
Extism 对于 WebAssembly 的意义就如同 jQuery 对于 JavaScript 的意义。

它消除了 Wasm 中所有不一致和粗糙的地方，提供了一个单一、通用的界面来进行构建。

[[https://bytes.dev/archives/343#:~:text=You%20can%20think%20of%20Extism%20as%20being%20to%20WebAssembly%20what%20jQuery%20was%20to%20JavaScript.%20It%20smooths%20out%20all%20of%20the%20inconsistencies%20and%20rough%20edges%20of%20Wasm%2C%20providing%20a%20single%2C%20universal%20interface%20to%20build%20with][Source]]
#+end_quote

** [[https://screenity.io/en/][Screenity]]

Chrome 插件，可以录制屏幕，进行标记和录音。

** [[https://github.com/hoarder-app/hoarder][hoarder]]

#+begin_quote
A self-hostable bookmark-everything app (links, notes and images) with AI-based automatic tagging and full text search.
#+end_quote
