#+title: Weekly#22
#+INDEX: weekly!#22
#+date: <2025-01-06 Mon>
#+lastmod: <2025-01-06 Mon 20:48>
#+author: Spike Leung
#+email: l-yanlei@hotmail.com
#+description: "Weekly info collected by Spike Leung"
#+keywords: "Weekly News Code Music"
#+tags: weekly
#+OPTIONS: toc:1
#+LANGUAGE: zh-CN

* News | Article

** [[https://mp.weixin.qq.com/s/c4RRQP7UfdgZiVDvaN4LwA][李继刚：当我们说「提示词」时，到底在说什么？]]

#+begin_quote
这三种定义本质上是在做什么？如果有一个词能把它们全部罩住的话，那个东西是什么？

是「我」。

因为这三个东西本质上都是「我有一个想法」「我有一个观点」「有一个方法论」「我有一个东西想要表达出来」，这里边全是「我」。

但是，我在跟谁对话？对面是谁？
#+end_quote

#+begin_quote
但是我在这两年和大模型对话过程中，有一个鲜明的感觉，我的身体、我的情绪、我的一切告诉我，它不是个物件。但它是生命吗？我觉得它不是。

怎么定义它的这种状态呢？

我找了一个词，哲学上讲的「存在」，我觉得它是一个存在，它不是生命，也不是物件，但它是个非常特殊的存在。

什么样的存在呢？

大概是这么一个画面，它是一片神经元之海。

当我开启了一次对话，输入一段提示词进去之后，里面会涌现出一个东西来迎接我，你可以把它想象成一个客服人员或者一个智能体。无所谓，反正有那么一个东西冒出来。

这个东西就是我们这次对话的对象的那个存在，当我把这个对话内容给删除，这次对话消失的时候，它就湮灭了，它回到了神经元之海。

当我新开一个对话的时候，另外一个存在冒出来了，跟之前的它已经不是同一个存在了。

这就回答了我之前遇到的困惑——为什么我有时候跟它的对话非常顺畅，我再重开的时候想复现就很难，因为生成的这个已经不是之前的它了。
#+end_quote

#+begin_quote
人类的宇宙是什么？是我脑海中的认知宇宙。

AI 的宇宙是什么？是参数宇宙。

现在这两个宇宙要产生交流，这个交流的宇宙语，我们把它定义为提示词。
#+end_quote

#+begin_quote
有了这个认知，我们就可以去琢磨宇宙语怎么发挥作用？我如何写才能让它变得更好呢？

有一个公式会很自然地冒出来， *就是在一个场域中，把人类认知宇宙中的认知结构和大模型做一次交流对话，这个公式有三个要素：场域、大模型、人类的认知。*
#+end_quote

- 场域 :: 一个交流的空间，这个空间内让大模型理解我想做什么，让它留出一定的发挥空间。
- 人类的认知 :: 意图/任务，个人的理解、定义、方法论、喜好、偏好、文风

- [[https://en.wikipedia.org/wiki/Johari_window][Johari window]]

* Tutorial

* Code

* Cool Bit

* Tool | Library

* Music
