#+title: Weekly#31
#+INDEX: weekly!#31
#+date: <2025-04-13 Sun>
#+lastmod: <2025-04-13 Sun 14:51>
#+author: Spike Leung
#+email: l-yanlei@hotmail.com
#+description: "Weekly info collected by Spike Leung"
#+keywords: "Weekly News Code Music"
#+tags: weekly
#+OPTIONS: toc:1
#+LANGUAGE: zh-CN
#+startup: content indent

#+begin_quote
你可以这么想，就当是很长很长的假期。

（很长的假期？）

不需要总是尽全力冲刺的，人总有不顺利的时候，或者疲倦的时候。

这种时候，可能我的比喻有点奇怪，就把它当成是神赐给我们的假期。

不必勉强冲刺，不必努力加油，一切顺其自然。

（然后呢？）

就会好起来的。

（真的吗？）

大概。

[[https://www.bilibili.com/video/BV1iZ4y1S79P?t=1164.9][Source]]
#+end_quote

* News | Article

** [[https://blog.julik.nl/2025/03/a-little-adventure-in-modern-frontend][A Supermarket Bag And a Truckload Of FOMO]]

作者写的应用了集成了 Tailwind，之所以用 Tailwind，它比较流行 (all the cool kids dot it)。

但是 Tailwind 升级后带来的问题让作者折腾了很久，浪费了他本来可以用来开发应用功能的时间，最后他选择了移除 Tailwind。

他的结论是，不要因为害怕跟不上潮流而去用一些自己不熟悉的技术，而应该用自己熟悉的，稳定的技术。

另外作者还说，在社区中可能还会有一些“影响者”不断布道什么才是好的，什么是不好的，你应该如何如何，看多了你可能会怀疑自己的一些决定到底对不对。

你应该适当屏蔽这些声音，专心做自己的开发。

#+begin_details
#+html: <summary>摘录</summary>

#+begin_quote
我们有时使用技术并不是因为我们需要它。

也不是因为我们想要它。

而是因为我们有 FOMO (Fear Of Missing Out，害怕错过)。

要么 - 我们害怕不“跟上潮流”而变得“无法被雇佣”，要么 - 我们害怕在今天的市场中不够“聪明”。

成为一个优秀的软件开发者的一部分就是要“了解最新动态” - 你不必使用所有的技术，但 - 在网络世界中，你确实需要至少对事物的运作有一些基本的理解。

有时，我们甚至会有同事 ⸺ 因为他们不知道更好的选择 ⸺ 开始轻轻地催促我们去探索我们不知道的东西。

这样的催促实际上可能会变成强迫 ⸺ 然后变成群体压力 ⸺ 如果你看到有一种技术选择并不高效、不优秀，并且不适合 ⸺ 但你仍然不得不使用它。

使用而不喜欢是不够的。

[[https://blog.julik.nl/2025/03/a-little-adventure-in-modern-frontend#:~:text=And%20it%20is,not%20considered%20enough.][Source]]
#+end_quote

#+begin_quote
使用你已经熟悉的东西。考虑你的最终目标。

是学习某个技术吗？还是构建一个应用并获得实际用户？不要将两者混合。

使用那些已经融入你指尖的东西，除非你有空间/时间去冒险。

[[https://blog.julik.nl/2025/03/a-little-adventure-in-modern-frontend#:~:text=Use%20what%20you%20already%20know%20know%20well.%20Think%20about%20your%20end%20goal.%20Is%20it%20to%20learn%20%24tech%3F%20Or%20is%20it%20to%20build%20an%20app%20and%20get%20actual%20users%3F%20Do%20not%20blend%20the%20two.%20Use%20something%20that%E2%80%99s%20already%20melted%20into%20your%20fingers%2C%20unless%20you%20have%20space%20for%20going%20on%20adventures.][Source]]
#+end_quote
#+end_details

** Git 20 岁

Git 已经 20 岁了，这周看到 2 篇相关文章：

- [[https://github.blog/open-source/git/git-turns-20-a-qa-with-linus-torvalds/][Git turns 20: A Q&A with Linus Torvalds]]

#+begin_details
#+html: <summary>摘录</summary>

#+begin_quote
我会做一些对我有用的事情，我不会在乎其他人。

[[https://github.blog/open-source/git/git-turns-20-a-qa-with-linus-torvalds/#:~:text=I%20can%E2%80%99t%20use%20CVS%20because%20I%20hate%20it%20with%20a%20passion%2C%20so%20I%E2%80%99ll%20do%20my%20own%20thing.%20I%20couldn%E2%80%99t%20use%20BitKeeper%2C%20obviously%2C%20anymore.%20So%20I%20was%20like%2C%20okay%2C%20I%E2%80%99ll%20do%20something%20that%20works%20for%20me%2C%20and%20I%20won%E2%80%99t%20care%20about%20anybody%20else.][Source]]
#+end_quote

#+begin_quote
这对我来说很重要，因为这实际上是一个生活质量的问题。

这是那种事情，如果一切都是即时的，一旦出现错误，你会立即看到结果，然后继续进行并修复它。

而我之前查看的一些其他项目每个补丁需要大约半分钟，这对我来说是不可接受的。

[[https://github.blog/open-source/git/git-turns-20-a-qa-with-linus-torvalds/#:~:text=Exactly.%20And%20that,acceptable%20to%20me.][Source]]
#+end_quote

#+begin_quote
我已经做了 35 年的 Linux，第一年它就满足了我所有的需求，对吧？

而我继续在内核方面工作的原因是，A，硬件不断发展，内核当然需要与之发展。但 B，是其他人的需求。

在我的一生中，我从来不需要内核所具备的所有功能。

但我对内核感兴趣，35 年后我仍在做这个。

当谈到 Git 时，Git 在第一年内就满足了我的需求。

实际上，主要是在头几个月。

当它满足了我的需求时，我失去了兴趣。

因为在内核方面，我真的对它们的工作原理很感兴趣，这就是我所做的。

但在 SCM (Source Code Management) 方面，我就没什么兴趣了。

[[https://github.blog/open-source/git/git-turns-20-a-qa-with-linus-torvalds/#:~:text=But%20honestly%2C%20I,at%20all%20interested.][Source]]
#+end_quote

#+begin_quote
不，不，我是从另一个角度看待这个问题。

所有我必须做的项目，都是因为我找不到别人做得更好的东西。

但我更喜欢其他人为我解决问题。

所以我必须想出一个项目实际上是世界的失败 —— 而在过去的 20 年里，世界对我来说并没有失败。

[[https://github.blog/open-source/git/git-turns-20-a-qa-with-linus-torvalds/#:~:text=No%2C%20no%2C%20I,years%20for%20me.][Source]]
#+end_quote
#+end_details

- [[https://blog.gitbutler.com/20-years-of-git/][20 years of Git. Still weird, still wonderful.]]
  + 重要的是要理解这就是 Git 创建的原因。它并不是为了真正成为一个版本控制系统，而是从根本上来说，是为了提供一种更好的方式来处理补丁和压缩包 —— 快照一组文件并显示可以讨论的差异。
  + GitHub 的 [[https://cameronmcefee.com/work/the-octocat/?ref=blog.gitbutler.com][吉祥物章鱼 (Octocat)]] 出自 Git 邮件列表的 [[https://lore.kernel.org/git/7vhdhgeuj1.fsf@assigned-by-dhcp.cox.net/?ref=blog.gitbutler.com#:~:text=These%20three%20steps%20are%20recorded%20as%20separate%20commits%20(in%0Asequence%2C%20not%20Octopus)][一次讨论]]。

顺便分享 2 个小游戏：

- [[https://epicdevbattlesofhistory.com/][EPIC DEV BATTLES OF HISTORY]] - 用 GitHub 贡献记录和别人进行对战，我的等级只到 LVL 59。
- [[https://justinpaulson.github.io/git_game_show/][GIT GAME SHOW]] - 把 Git 仓库的提交记录作为数据，玩一些小游戏，例如猜一猜某行代码是谁提交的；提交信息填空等。

** [[https://antfu.me/posts/hello-tokyo][Hello Tokyo!]]

[[https://github.com/antfu][antfu]] 从巴黎换到日本东京生活了，大佬不仅技术好，摄影技术也很不错，[[https://www.xiaoyuzhoufm.com/episode/67b41df8606e5c594031b4e8][听播客]]了解到他大学还是摄影社的。

antfu 的博客看起来挺舒服的，日文的标注，人/组织的头像显示都很不错。

** [[https://phys.org/news/2025-04-odds-asteroid-briefly-threatened-earth.html][Rising odds asteroid that briefly threatened Earth will hit moon]]

之前 [[https://taxodium.ink/24.html#:~:text=2032%20%E5%B9%B4%E5%B0%8F%E8%A1%8C%E6%98%9F%E6%92%9E%E5%87%BB%E5%9C%B0%E7%90%83%E7%9A%84%E6%A6%82%E7%8E%87%E6%98%AF%201.6%25%20%E3%80%82][weekly#24]] 中分享过有一个小陨石可能会撞击地球，现在概率达到了 3.1%，还有 4% 的概率可能会撞击月球。

它的能量足以摧毁一座城市，没人希望它会撞击地球，但有人希望它撞击一下月球也不错。

#+begin_quote
虽然没有人希望需要在潜在的巨大破坏性小行星 2024 YR4 上测试地球的防御，但许多科学家希望它能撞击月球。

“从科学的角度来看，获得观察到一次可观的月球撞击的机会确实是一个有趣的情景，”莫伊斯尔说。

这可能提供一系列“对行星防御目的有价值”的信息，他补充道。

英国肯特大学的太空科学家马克·伯切尔告诉《新科学家》，月球撞击将是“一次伟大的实验和一个完美的机会”。

他补充道：“在地球上，望远镜肯定能看到，我会说，双筒望远镜也可能看到。”

[[https://phys.org/news/2025-04-odds-asteroid-briefly-threatened-earth.html#:~:text=While%20no%20one,it%2C%22%20he%20added.][Source]]
#+end_quote

** [[https://endler.dev/2025/best-programmers/][The Best Programmers I Know]]

作者总结了一些优秀程序员的特质。

本来想摘抄一下，但发现差不多全文摘抄了，我觉得我的总结也是多余，所以推荐阅读一下原文～

正如作者的第一段所说：“[...]直接去源头。通常情况下，它出乎意料地易于获取且写得很好。”

** [[https://briefer.cloud/blog/posts/look-the-data/][A feel for the data]]

作者分析了几种图表：直方图、箱线图、小提琴图、条形图、散点图、热力图、折线图等。

不同图表适合呈现不同的信息，阅读文章，你可以了解到这些图表合适的使用场景。

不管是什么图表，它们都能让人直观地看到一些信息，作者还建议一些在阅读图表时需要关注的内容。

#+begin_details
#+html: <summary>摘录</summary>

#+begin_quote
无论使用哪种图表，以下是需要关注的内容：

- 什么是典型的？哪些数值常见，数据在哪里聚集，哪里又变得稀疏？
- 有什么异常？是否存在离群点 —— 远离其他点的数据？它们是错误，还是值得进一步调查的现象？
- 数据的形状是否符合我的预期？注意偏斜、空隙和多个峰值。真实世界的数据很少是平滑的。
- 是否存在明显的分组？数值是否自然地分成几个簇？你能区分它们，还是它们相互重叠？
- 变量之间如何共同变化？一个变量上升时另一个变量下降吗？关系是线性的、曲线的还是噪声较多的？
- 缺少了什么？是否有本应有数据的位置是空的？有没有某些类别或范围显得异常安静？

你越多练习发现这些点，它们跳出来的速度就越快 —— 远在你运行任何数字之前。

这就是绘图的真正力量：它让你的大脑在工具介入之前就有东西可以抓住。

[[https://briefer.cloud/blog/posts/look-the-data/#:~:text=Here%27s%20what%20to,even%20get%20involved.][Source]]
#+end_quote
#+end_details

** [[https://www.thecoder.cafe/p/100-go-mistakes][So, I Wrote a Book]]

作者写了一本书《[[https://www.amazon.com/100-Mistakes-How-Avoid-Them/dp/1617299596][100 Go Mistakes and How to Avoid Them]]》，这是作者第一次出书，文章记录了作者写作的动机，过程和他的感悟。

从书里可以了解到作者从写书到出版，中间会经历什么过程，文章整体读起来也不错，推荐看看。

作者是因为写了一些关于如何避免 Go 的错误的博客，然后意外发现阅读量还挺大，于是他积累了更多的相关内容，最后决定写成书。

#+begin_details
#+html: <summary>很长的摘录</summary>


#+begin_quote
[...]

所以我的想法是：继续收集错误，看看会怎样。

也许某个时候，我可以写一个包含我所有发现的 GitHub 仓库？

快进到 2020 年 11 月。自我发布博客文章已经过去 16 个月了，到那时，我已经收集了 100 个 Go 语言的错误。

在这期间，我主要从以下几个来源收集错误：

- 在工作中（说实话，我自己也是一个重要的灵感来源！）
- 在各种研究和博客文章中
- 在不同的开源项目中

在这个阶段，我对我的项目感到更加自信。

当然，一个开源仓库可能很棒，但我想：为什么不出一本书呢？

作为一个热爱阅读和写作的人，我一直梦想着出版自己的作品。

[[https://www.thecoder.cafe/p/100-go-mistakes#:~:text=Fast%20forward%20to,publishing%20my%20own.][Source]]
#+end_quote

#+begin_quote
一开始，Manning 让我深入思考他们所称的最低合格读者 (MQR, Minimum Qualified Reader)。

简而言之，读者需要具备什么最低水平的知识或经验才能阅读你的书？

这听起来可能是个基本问题，但那时我甚至都没考虑过。

接下来的几周里，我不断完善我的 MQR，目标读者是已经了解 Go 语言的人。

这意味着大约 15% 的内容可以直接扔进垃圾桶，因为它们太基础了。

[[https://www.thecoder.cafe/p/100-go-mistakes#:~:text=At%20the%20very,just%20too%20basic.][Source]]
#+end_quote

#+begin_quote
在那之前，我已经在各种博客上写作了大约十年，但在线写作讲究直接，因为大多数人没有时间。

写书则不同。

人们是经过深思熟虑才决定买你的书。

现在，你的任务是带领他们到一个有价值的地方。

如果这需要时间（意味着更多的文字），那就这样吧。

[[https://www.thecoder.cafe/p/100-go-mistakes#:~:text=Before%20that%2C%20I,so%20be%20it.][Source]]
#+end_quote

#+begin_quote
如果你收到一条评论，你必须回应它，即使它对你来说似乎不重要。

如果一个人提出了这个问题，想象一下当成千上万的人阅读你的书时会怎样。

[[https://www.thecoder.cafe/p/100-go-mistakes#:~:text=If%20you%20get%20one%20comment%2C%20you%20must%20address%20it%2C%20even%20if%20it%20doesn%E2%80%99t%20seem%20important%20to%20you.%20If%20one%20person%20raised%20it%2C%20imagine%20when%20thousands%20of%20people%20read%20your%20book.][Source]]
#+end_quote

#+begin_quote
有一点需要注意：从作者的角度来看，书籍在此阶段基本完成。

你仍然可以添加一些小内容，但出版社希望锁定第一个版本。

那是因为即使添加一个新的段落，也意味着该部分需要重新进行整个流程。

这就是为什么出版社坚持要固定版本。

达到那个阶段是一个重要的里程碑。

用 Gene Fowler 的一句名言来表达我当时的感受：

*一本书永远不会完成；它只是被放弃了。*

真正的问题是：你怎么能说一本书已经完成了？

比如，我本可以在这里改进一个图表，那里调整一个例子，重新措辞一句话，或者完善一个结论。

但这种循环可能会永无止境。

到了某个阶段，你只能认为这个版本是最终版，进入下一个阶段，从某种意义上说，放弃你的书。

这是一种很难受的感觉，但事情就是这样发展的。

[[https://www.thecoder.cafe/p/100-go-mistakes#:~:text=One%20thing%20to,%E8%BF%99%E6%A0%B7%E5%8F%91%E5%B1%95%E7%9A%84%E3%80%82][Source]]
#+end_quote

#+begin_quote
到今天，我从这本书中赚了大约 47,000 美元（税前）。

如果考虑所花费的时间，保守估计为 2,000 小时，那么每小时大约赚 23 美元。

有两种方式来看待那个小时费率。

一种是认为这个收入相比软件工程师的收入相当低。我本可以投入 2000 小时做一些有偿的技术工作，可能赚得更多。

另一种看法则是不必太在意这个。

当然，我赚的钱也不少（说实话，支付了不少假期费用），但我想传达的主要信息是：

如果你是新作者，不要想着写书是为了发财。

[[https://www.thecoder.cafe/p/100-go-mistakes#:~:text=To%20this%20day,%E6%98%AF%E4%B8%BA%E4%BA%86%E5%8F%91%E8%B4%A2%E3%80%82][Source]]
#+end_quote
#+end_details
* Tutorial | Resource
** [[https://health.art/][Health Art]]

最近上线的一个健康生活指南。

#+begin_quote
Health Art 致力于将前沿的健康科学知识转化为实用的生活指南。

我们深入研究并提炼来自 [[https://www.hubermanlab.com/][Huberman Lab]]、[[https://peterattiamd.com/][Peter Attia]] 等世界顶级健康专家的研究成果和建议。

为中文读者提供科学、实用的健康优化方案。
#+end_quote

#+begin_quote
1. 保证充足的8小时睡眠机会

- @@html:<mark>睡眠视为 "不可协商" 的健康基础，而非可选的奢侈品</mark>@@
- 记住：睡眠是健康的基础，营养和运动建立在这个基础之上
- 即使只少睡 2 小时（从 8 小时减至 6 小时），可能损失高达 70% 的 REM 睡眠

2. 建立严格的睡眠规律性

  - 每天相同时间上床和起床，包括周末
  - 这是睡眠四大支柱（规律性、连续性、数量、质量）中最重要的一项
  - 制定反向睡眠计划：从起床时间倒推，确保8小时睡眠窗口
#+end_quote
** [[https://ooh.directory/][ooh.directory]]

一个可以搜集了很多博客的网站，收集的博客都是有订阅源的，且保持一定更新的。

你也可以向他提交自己的博客。
** [[https://www.innopreneur.io/wp-content/uploads/2025/04/22365_3_Prompt-Engineering_v7-1.pdf][Prompt Engineering]]

一份关于 Prompt Engineering 的 Google 文档。

#+begin_quote
提示应简洁、清晰，便于你和模型理解。

通常，如果对你来说已经令人困惑，模型也可能会感到困惑。

尽量不要使用复杂的语言，也不要提供不必要的信息。
#+end_quote

#+begin_quote
不断增长的研究表明，在提示中关注积极的指令 (Instructions) 比过度依赖限制 (Constraints) 更有效。

这种方法符合人类的喜好，人更喜欢被请求而不是被要求。

指令直接传达所需结果，而限制可能让模型猜测什么允许。

指令提供灵活性并鼓励在定义的边界内发挥创造力，而限制可能限制模型的潜力。

另外，限制清单之间可能会互相冲突。

限制在某些情况下仍然有价值。

为了防止模型生成有害或偏见的内容，或者当需要严格的输出格式或风格时。

*如果可能的话，使用积极的指令：不要告诉模型不做什么，而是告诉它该做什么。*

这样可以避免混淆并提高输出的准确性。
#+end_quote
** [[https://github.com/goldbergyoni/nodejs-testing-best-practices][Node.js Testing Best Practices]]

#+begin_quote
超越 Node.js 测试的基础。

包括一份超级全面的最佳实践清单和一个示例应用。
#+end_quote
** [[https://seis.pointlessprojects.com/][Seis Colores]]

#+begin_quote
当我还小的时候，妈妈告诉我可以选择我房间的颜色。

我选择了深蓝色。

在大学时，我的房东也告诉我同样的话，我选择了明亮的橙色。

在一个充满白色墙壁的国家里，我觉得自己很特别。

2015 年，我第一次来到墨西哥。

墨西哥人不经别人同意，就选择鲜艳的颜色来粉刷他们的房子。

我爱上了这里。

每次经过一座色彩斑斓的房子时，我都感到受到启发。

就这样，Seis Colores 诞生了。

[[https://seis.pointlessprojects.com/about#:~:text=When%20I%20was,Colores%20was%20born.][Source]]
#+end_quote
** [[https://www.bigbookofr.com/][Big Book of R]]

R 语言书籍合集。

* Code Related
** [[https://git.apcacontrast.com/documentation/APCAeasyIntro][The Easy Intro to the APCA Contrast Method]]

在无障碍方面，最广为人知的应该是 [[https://www.w3.org/TR/WCAG22/][Web Content Accessibility Guidelines (WCAG) 2.2]]（Web 内容无障碍指南）了。

为了让读者看清楚页面的文字，WCAG 定义了 [[https://www.w3.org/TR/WCAG22/#contrast-minimum][最低颜色对比度]]：

- [[https://www.w3.org/TR/WCAG22/#contrast-minimum][Level AA]]：文本和文本图像的视觉呈现对比度至少为 *4.5:1* ，如果是字体比较大[fn:1]，则至少应该为 *3:1* 。
- [[https://www.w3.org/TR/WCAG22/#contrast-enhanced][Level AAA]]：文本和文本图像的视觉呈现对比度至少为 *7:1* ，如果是字体比较大，则至少应该为 *4.5:1* 。

但是 WCAG 2.x 诞生于智能手机和平板电脑出现之前的时代，对于现在来说不够用了，尤其是在暗黑模式下，即使设置了 4.5:1 的对比度，可能也看不清。

#+CAPTION: 这是一张在暗黑模式下的图，整个图片背景都是黑色的。左边是 WCAG 规范的文字示例，右边是 APCA 规范的文字示例，他们都展示了各自不同对比度，不同字号下的字体表现。APCA 在暗黑模式下看得更清楚一些。(From git.apcacontrast.com)
https://git.apcacontrast.com/images/DarkModeComparev2_2022.png

而 WCAG 3 的一个提案 [[https://github.com/Myndex/SAPC-APCA][APCA (Accessible Perceptual Contrast Algorithm)]] (可访问感知对比算法) 则更好地解决了颜色对比度的问题。

APCA 提出了 *明亮对比度 (Lightness contrast，Lc)* ，基于 Lc 去定义颜色，就可以保证在文字在暗黑模式下也能轻松阅读。

#+CAPTION: WCAG 和 APCA 不同值下的文字呈现对比，可以看到在暗的背景下，APCA 的表现更好。(From git.apcacontrast.com)
https://git.apcacontrast.com/images/ColumnCompareAll400.png

Lc 分成几个等级，[[https://git.apcacontrast.com/documentation/APCA_in_a_Nutshell#:~:text=Use%2DCase%20%26%20Size%20Ranges][你可以参照用途定义，使用不同的等级]]。

官方也[[https://git.apcacontrast.com/documentation/thirdpartytools][提供了工具]]，用于查看颜色的 Lc 值。

另外推荐看一下 [[https://www.smashingmagazine.com/2022/09/realities-myths-contrast-color/][The Realities And Myths Of Contrast And Color]]，文章从人如何感受色彩，到如何让文本容易阅读，讲得很细致。

#+begin_details
#+html: <summary>摘录</summary>

#+begin_quote
像颜色一样，对比并不是绝对意义上的“真实”，它是一种感知。

它是你的大脑对周围视觉信息差异的解释。

对比并不是两个颜色之间差异的简单度量。

像所有感知一样，两种颜色之间的对比度对环境非常敏感。

这意味着周围的其他物体会影响你的视觉感受。

线条粗细或文字重量和大小的“空间特性”决定了我们的对比敏感度。

这些是我们对明暗视觉对比感知的主要因素。（有时称为亮度对比）

为了可读性，我们需要充足的明度对比，而不考虑色相中的颜色。

色彩对比，即色相/饱和度，对可读性没有主要影响。

但充足的明暗对比能实现最佳的阅读速度和理解力。

这对于小号正文字体尤为重要，比如列或块状文本。

超过某个阈值后，关键对比恒定性可能会生效。

这意味着超过关键对比的增加不会带来更好的可读性。

[[https://git.apcacontrast.com/documentation/APCAeasyIntro#:~:text=Like%20color%2C%20contrast,of%20text%20%26%20background.][Source]]
#+end_quote

#+begin_quote
色盲和可读性：虽然色觉障碍（CVD）会影响区分某些颜色的能力，但对于常见类型的 CVD，亮度感知与标准视觉相同。

因此，在可读性方面，绿盲（deutan）、红盲（protan）、蓝盲（tritan）类型对亮度对比的需求与标准视觉相同。

唯一的例外是红色与黑色的搭配，因为患有红盲（protan）形式的 CVD 者对红色不敏感。

因此，红色与黑色的对比度在红盲者眼中大大降低，红/黑组合作为文本或语义非文本应避免使用。

[[https://www.smashingmagazine.com/2022/09/realities-myths-contrast-color/#:~:text=Color%20Insensitive%20and,semantic%20non%2Dtext.][Source]]
#+end_quote

#+begin_quote
为了强调，我要重申，@@html:<mark>字体的粗细和大小在可读性对比中远比光度和颜色的差异或比率更为重要。</mark>@@

在这个示例图中，(设置了多个轮廓) 所有轮廓 (outline) 使用的颜色都是相同的，具有 3:1 的对比度比率。

#+CAPTION: 示例图: 首先是细的 1 像素轮廓，然后是 2 像素轮廓，接着如你所见的 3 像素轮廓，描边开始侵入字母内部，所以在最后一个示例中，4 像素轮廓时，我们将描边设置为仅向外，这也增加了内部字体的粗细。（From archive.smashing.media）
https://archive.smashing.media/assets/344dbf88-fdf9-42bb-adb4-46f01eedd629/8a7d6371-669b-4a1a-8c2e-d536c4065dee/10-realities-myths-contrast-color.png

在每种情况下，使用的颜色完全相同，但随着轮廓变厚，每一行的空间频率降低，因此对比度更强，比上面一行更容易阅读。

[[https://www.smashingmagazine.com/2022/09/realities-myths-contrast-color/#:~:text=To%20emphasize%2C%20I%E2%80%99ll,inner%20font%2Dweight.][Source]]
#+end_quote
#+end_details
** [[https://webkit.org/blog/16547/better-typography-with-text-wrap-pretty/][Better typography with text-wrap pretty]]

使用 ~text-wrap: pretty~ 可以改善文本换行的效果，避免一些过短的行。

文章也比较了 ~text-wrap: pretty~ 和 ~text-wrap: balance~ ：

#+begin_quote
- ~pretty~ 可以应用于页面上的任何内容——正文、标题、说明文字、导语等。

  看看它的效果如何，如果你喜欢这个效果就用它。

  如果你有非常长的段落（或者更准确地说：没有任何段落分隔的长正文，想象成成百上千行的文本），请先测试性能。

- ~balance~ 应该用于你希望所有行长度相同的任何地方——尤其是标题和说明文字等。

  而且你不介意整体行组比其容器窄。

  不要在长篇文本中使用它；那样没有意义。

  [[https://webkit.org/blog/16547/better-typography-with-text-wrap-pretty/#text-wrap-pretty:~:text=pretty%20can%20be,doesn%E2%80%99t%20make%20sense.][Source]]
#+end_quote
** [[https://blog.css-weekly.com/top-5-css-navigation-menu-mistakes][Top 5 CSS Navigation Menu Mistakes]]

作者整理了一些导航栏按钮的常见问题：

- 点击区域太小
- 使用 flex 布局但是没有使用 gap，而是利用很多的 margin
- 下拉菜单的区域不友好，当用户离开主菜单时，下拉菜单很容易关闭，需要覆盖用户可能使用的空白区域
- 下拉菜单关闭没有延迟，容易让用户反复点击主菜单
- 锚点跳转没有动画，相对生硬
* Cool Bit
** [[https://www.tokyoweekender.com/entertainment/middle-aged-man-trading-cards-go-viral-in-japan/][Middle-Aged Man Trading Cards Go Viral in Rural Japan Town]]

#+CAPTION: 大叔卡牌列表，里面有很多张卡片，每张卡片中都是一个大叔的照片，还有一些属性描述。（图片引自 Tokyo Weekender）
https://www.tokyoweekender.com/wp-content/uploads/2025/03/ojisan-01.jpg.webp

日本的一个社区设计了一套“大叔”卡牌 (Ojisan trading card game) 让孩子们收集，他们的目的加强社区中孩子和老一辈人之间的联系。

卡片上的大叔，有点是消防员，有的是荞麦大叔，还有狱警等等。很有爱。

#+begin_quote
以防火墙卡为例。

它的主角是本田先生（74 岁），一位曾经的消防队长，他帮助保护这个小镇安全达数十年。

还有荞麦大师竹下先生（81 岁），他经营着一个本地的荞麦面制作班，现在在镇上的年轻人中享有传奇地位。

[...]

一张名为“等离子导体”的卡片，展示了一位微笑的、戴着眼镜的叔叔，旁边是一个灯泡的图像，是电属性。

在卡片底部，有一行文字解释他可以毫无失败地修理任何电器。
#+end_quote

#+begin_quote
游戏的创作者是宫原恵理，赛道庄社区委员会的秘书长。

“我们想加强社区中孩子与老一辈之间的联系。这里有很多了不起的人。我觉得没人知道他们真是太可惜了，”

她在接受富士新闻网络（FNN）采访时说道。

“自从这个卡牌游戏走红以来，很多孩子开始把这些人视为英雄人物。”
#+end_quote

** [[https://app.radiooooo.com/][Radiooooo, The Musical Time Machine]]

在 v2ex 某个帖子上看到的分享，蛮有趣的网站，可以让你选择地区和年份，探索不同风格的音乐。

#+begin_quote
Radiooooo 是一个于 2013 年诞生的项目，由一小群朋友组成的家庭梦想而成，他们既是 DJ 也是音乐爱好者，决定分享他们的唱片收藏和多年来研究的成果，让所有人都能享受。
#+end_quote

** [[https://nownownow.com/about][nownownow.com]]

一般个人网站都会有一个“关于”页，同理，也可以有一个“现在”页，用来分享你最近过得怎么样 ⸺ /想想你会告诉一个你一年没见的朋友什么。/

我也为博客添加了一个[[file:now.org][“现在”页]]。

#+begin_details
#+html: <summary>摘录</summary>


#+begin_quote
所以，一个网站上有一个链接，上面写着“现在”，它会链接到一个页面，告诉你这个人在生活中此刻关注的内容。

简而言之，我们称之为“现在页面”。

虽然通常会将网页地址设置为“/now”，就像其他例子中的“/about”和“/contact”一样，但 URL 可以是任何东西。

[[https://nownownow.com/about#:~:text=So%20a%20website,could%20be%20anything][Source]]
#+end_quote

#+begin_quote
社交媒体更新不就是这样吗？

不。如果我想知道某人最近过得怎么样，看到他们上周去度假、对新闻感到不安，或者甚至找到了新工作并没有帮助我。这并不是全貌。

/想想你会告诉一个你一年没见的朋友什么。/

比如，

“仍然住在达拉斯，但考虑搬到奥斯汀。

现在在 ABC 工作。

真的开始喜欢骑自行车。

孩子们分别是 3 岁和 6 岁。

我读了很多佩玛·乔德朗的书，尤其是听很多爵士钢琴，特别是布拉德·梅尔道。

我已经停止接手网页设计客户，因为我更想继续提高我的后端数据库工作。”

这就是现在页面的意义：更大的图景。

[[https://nownownow.com/about#:~:text=No.%20If%20I,the%20bigger%20picture.][Source]]
#+end_quote
#+end_details

** [[https://www.allaboutbirds.org/news/how-to-recognize-woodpeckers-by-their-drumming-sounds/][How to Recognize Woodpeckers by Their Drumming Sounds]]

文章教你如何听声辨啄木鸟，不同啄木鸟品种的琢击频率会不一样。

这是一个关于鸟类的网站，如果对鸟类感兴趣可以浏览一下。

** [[https://blogroll.org/][Ye Olde Blogroll]]

#+begin_quote
嗨，你好，很高兴见到你。

那么为什么是 Blogroll.org？

有人说博客已经死了……它可能缩小了一些，但从未消亡。

在臃肿的搜索引擎和算法社会的孤岛中，发现隐藏的宝石变得越来越困难，这些社会更喜欢你留在其中（以便更好地实现盈利）。

外面仍然有很多东西。

Blogroll.org 是一张活生生的地图， *指引着那些在浩瀚的比特和字节海洋中，独自敲打电子卷轴的孤独灵魂。*

作为一名专业的漫游者，我喜欢自由地漫游万维网，潜入一个又一个超链接的兔子洞。

Blogroll.org 是与您分享这些探索并回馈网络的一种方式。

如果你发现了一个特别有趣的兔子洞，别忘了分享它。

如果你有博客，也可以添加你最喜欢的博客列表！

享受旅程吧，亲爱的漫游者。

这是一场充满未知的冒险，有许多岛屿等待被发现。
#+end_quote

** [[https://garfieldminusgarfield.net/][garfield minus garfield]]

#+begin_quote
《加菲猫减去加菲猫》是一个致力于从加菲猫漫画中去除加菲猫角色的网站，以揭示某位年轻的乔恩·阿布克尔先生的存在主义焦虑。

这是一段深入一个孤独年轻普通人内心的旅程，他在一个宁静的美国郊区与孤独和抑郁进行着一场注定失败的斗争。
#+end_quote
** [[https://github.com/kkuchta/css-only-chat][kkuchta/css-only-chat]]

#+begin_quote
一个真正庞大的异步网页聊天，前端完全不使用任何 JS。
#+end_quote

* Tool | Library
** [[https://gitmcp.io/][GitMCP]]

适用于 GitHub 仓库的 MCP 应用。

#+begin_quote
...它将任何 GitHub 项目（代码库或 GitHub 页面）转变为文档中心。

它允许像 Cursor 这样的 AI 工具访问最新的文档和代码，完美地结束幻觉。
#+end_quote
** [[https://github.com/wanasit/chrono][wanasit/chrono]]

#+begin_quote
Javascript 中的自然语言日期解析器。
#+end_quote
* Emacs
- [[https://flandrew.srht.site/listful/sw-emacs-slug.html#overview][Slug]] 可以将文件名变成一个相对正常的路径。

  #+begin_src emacs-lisp
    (slug-to-ud-09az "The best すし & さしみ 42 € can buy™ [updated: 2042]")
    => "the-best-sushi-and-sashimi-42-eur-can-buy-tm-updated-2042"
  #+end_src

* 一些话 | 摘抄
** [[https://yuxi-liu-wired.github.io/essays/posts/cyc/][Cyc]]

#+begin_quote
常识为什么会有帮助？

Lenat 观察到人类似乎不会像 EURISKO 那样陷入困境。

他得出结论，人类不会精疲力竭，是因为他们拥有大量关于世界的常识知识，可以用来进行类比，那些远距离的奇思妙想，足够多时，能够让他们不断产生真正的新想法。

例如，可以在军事和医疗之间画一条类比线，使医生能够“通过抗生素的包围运动来对抗感染”。

为什么类比会带来真正的新想法？

因为智能是混乱的！

如果一切都如此统一，那么就无法做出遥远的类比——一切几乎已经相同了。

再者，看看所有逻辑人工智能破灭的梦想——它们的尸体告诉我们，没有优雅的智能理论存在。

编程一个真正的人工智能是一项混乱的工作。混乱是一种可怕的力量。

[[https://yuxi-liu-wired.github.io/essays/posts/cyc/#:~:text=Why%20would%20common,the%204th%20lesson.][Source]]
#+end_quote
* 多媒体
- [[https://www.bilibili.com/video/BV16odGYUEMs][你靠算法绝对听不到的 7 首华语神曲丨HOPICO丨citypop]] (18:09)
- [[https://www.bilibili.com/video/BV1ufRXY1E6d][重投一遍，不甘心努力做的视频就这么凉了_哔哩哔哩_bilibili]] (05:29) 手书做的不错。
- [[https://www.bilibili.com/video/BV1kL4y1A77G][【初音未来】「CH4NGE」运动捕捉]] (02:15) 跳舞的老师太帅了。
- [[https://www.bilibili.com/video/BV1kAdhYqEzx][带 66 岁东北叔叔去南方旅行！落地的一刻，被叔叔的反应惊呆了…]] (29:15)
- [[https://www.bilibili.com/video/BV17vRUY1EUa][上海街头开 007 特工超跑，有多帅？]](28:07)

  #+begin_quote
  不仅是城市给我灵感，对话、人们和文化、颜色和声音、气味和风景也会，所有东西都会给我带来灵感。

  因为这个世界一直在变化，我们可以从互联网获得知识，也可以从数字化研究获取，但它不会告诉我，这里的阳光是什么感受，清冷的舒服的微风，咖啡机里刚做的咖啡是什么感受。

  这些都是回忆，这些以前的回忆会给我灵感，我们每次有新的回忆之后就会从中获得启发。

  所以我觉得旅行，见各种各样的人都是息息相关的，这和你自己息息相关，这也会和消费者和客户有关。

  我觉得仅仅是颜色风景和声音，这个星球上到处都有着非常不同的组合，甚至这些树被修剪的方式，没有叶子的树的颜色……

  [[https://www.bilibili.com/video/BV17vRUY1EUa?t=1528.6][Source]]
  #+end_quote
- [[https://www.bilibili.com/video/BV17Z4y1Q7R8][【悠长假期解说 P1】豆瓣评分9.3，无法复刻的日剧经典！]] (40:00 * 6)

  前阵子听到悠长假期里的歌，就搜了一下，想看看名场面，结果搜到了一个解说，顺势看完了。

  很不错的一部日剧，推荐一看。
- [[https://www.bilibili.com/video/BV1eeoVYjEdb][男生出去旅行，到底有多随意]] (03:02) “出来玩，最紧要的是出来”。
- [[https://www.youtube.com/watch?v=m6fjyh0M8x4&ab_channel=%E8%A9%A6%E7%95%B6%E7%9C%9FTrial%26Error][試映劇場《下班勿語》｜試當真]] (06:38)
- [[https://www.youtube.com/watch?v=CZZ31WN6S98&ab_channel=%E8%A9%A6%E7%95%B6%E7%9C%9FTrial%26Error][試映劇場《係咁先啦》｜試當真]] (9:36)
- [[https://www.bilibili.com/video/BV1GMoMYfESS][【Links】跑遍全世界，我搜集到的...]] (14:28) 好看的蓝调时刻。
- [[https://www.bilibili.com/video/BV1xmdUYhEo7][这只羊陪我流浪了 5 年, 告别那天破防了]] (08:11)
- [[https://www.bilibili.com/video/BV1VPoKY9Euu][在西班牙“捡垃圾”给老外品尝，能不能拿把他们馋哭？]]

  #+begin_quote
  厨子想做饭好吃，心里一定是带着爱的。

  不管是对朋友家人的爱，还是对职业的热爱。

  [[https://www.bilibili.com/video/BV1VPoKY9Euu?t=472.1][Source]]
  #+end_quote

* Music

** [[https://music.163.com/#/album?id=258308735][The Cheers Cheers -《Forest of Mine》]]

#+CAPTION: 《Forest of Mine》专辑封面
http://p2.music.126.net/VUVRlIorMUxeCO6TSAXNlA==/109951170331178430.jpg?param=177y177

#+begin_quote
Let it go, oh babe, let it go

Before the candles burn out, I’m on my own

You think your days are gone

but the greatest day has come

Like a broken branch

Sprout anew
#+end_quote

** [[https://music.163.com/#/album?id=267590828][Black Country, New Road -《Forever Howlong》]]

#+CAPTION: 《Forever Howlong》专辑封面
http://p2.music.126.net/qhMCtRw_3Uf_WoaYSuRY0A==/109951170674738110.jpg?param=177y177

这张转我听了很多遍，BC;NR 的其他专辑也很不错，他们的歌曲器乐丰富，旋律也很好听。

这张专辑，无论是编曲，旋律，歌词，翻译都棒。

像是 [[https://music.163.com/#/song?id=2690018997][Forever Howlong]] 这首，中间唱到沉默的时候，会故意停顿一下。

唱到对面的独居老人时，乐器一点点地加入，变得丰富，旋律达到高潮，又慢慢回到安静。

整首歌从“掀开白昼的帷幕”开始，到“合上黑夜的幕帘”，一天过去了，Forever Howlong。

** [[https://music.163.com/#/album?id=267786859][陶喆 -《STUPID POP SONGS》]]

#+CAPTION: 《STUPID POP SONGS》的专辑封面
http://p2.music.126.net/9r50-BhduCERNbyOxx_raw==/109951170722562446.jpg?param=177y177

陶喆的新专辑，预热了很久，也让人期待了很久。

不知道是不是期待比较高，听下来我还是更喜欢他早期的蓝专《[[https://music.163.com/#/album?id=15199][David Tao]]》这张。

新专辑里充满了大爱和小爱，peace and love。

据说专辑里的乐器都是实录的，成本很高，也是比较值得细听的部分。

目前在网易云上需要付费购买才能听，大概 32 元的样子，如果你喜欢陶喆的歌，就支持一下吧～

* Footnotes

[fn:1] [[https://www.w3.org/TR/WCAG22/#dfn-large-scale][大字体 (large-scale)]] 的定义是：至少使用 18 磅 (point) 或 14 磅
加粗字体，或能产生等效大小的中文、日文和韩文（CJK）字体大小。大致对应
是 24px 和 18px。也就是说，font-size 设置为 24px 以上, 或者 font-size
为 18px 以上且加粗，则可以认为是大字体。不同语言的文字可能存在差异，例
如同样的 24px，中文可能比英文小，此时也需要适当增大字号才能符合大字体
的定义。
