#+title: Weekly#38
#+INDEX: weekly!#38
#+date: <2025-06-22 Sun>
#+lastmod: <2025-06-22 Sun 16:57>
#+author: Spike Leung
#+email: l-yanlei@hotmail.com
#+description: "Weekly info collected by Spike Leung"
#+keywords: "Weekly News Code Music"
#+tags: weekly
#+OPTIONS: toc:1 ^:{}
#+LANGUAGE: zh-CN
#+startup: content indent
- 体检
- 离职
- 动画 末日后酒店，星空清理者
- 咖啡
- kindle

* News | Article

** [[https://hedgehogreview.com/issues/after-neoliberalism/articles/on-not-carrying-a-camera][不带相机, 培养记忆而非快照]]

看到美丽的景色，在一些有纪念意义的时刻，人们往往会想用相片或视频记录下来。

可是在拍摄的时候，注意力往往都会集中在如何拍摄好这件事情上，而不是去欣赏和感受当下美丽的事物。

那些记录下来的东西，往往记录完就放在一边，或许以后某个时刻会翻到，或许永远都不会再看一次。

与其如此，不如活在当下，活在此刻，让那些美好的时刻留在记忆里，让那一刻的感动刻回忆里，而不是照片里。

#+begin_details
#+html: <summary>摘录</summary>

#+begin_quote
我在家乡 Chapel Hill 不带相机，虽然手机里有相机，但我只用它拍快照。

自然，有些时刻我也希望自己带着相机。

一次黄昏时分，我在邻里散步，感到空气中有一种奇异的能量涌动，突然，不超过二十英尺远处，一只雄伟的白尾鹿跃过花园围栏，飞奔在渐暗的街道上。

即使那一刻正在发生 ⸺ 这出乎意料的超自然时刻 ⸺ 我也试图把它想象成一张照片。

我们就是这样被教导去思考的。

「哦，我真希望我带了相机！」但这意味着我本应准备好捕捉那一刻，而不是被它惊吓。

_然而，被美丽惊艳是一种独特且极为罕见的人类天赋。_

照片是在我从惊讶中回过神来，开始摆弄相机时才出现的。

[[https://hedgehogreview.com/issues/after-neoliberalism/articles/on-not-carrying-a-camera#:~:text=I%20don%E2%80%99t%20carry,with%20my%20camera.][Source]]
#+end_quote

#+begin_quote
接下来的几天里，我一直在思考我儿子的出生。

_我当时就在房间里，但我真的在那里吗，还是躲在了相机后面？_

我希望医生们尽一切必要的努力让我的孩子安全降生，但我也同样希望他们 ⸺ 这同样重要 ⸺ 不要破坏我的照片。

如果出了什么差错，Susan 绝望地环顾房间寻找我，她会看到一个男人把一个黑色的盒子举到眼前。

这个画面象征性地留在了我的脑海中。

这都是很久以前的事了。

那时我正在学习如何使用相机。

和朋友散步时，我会打断一场愉快的谈话去构图。

我控制不住自己。

那时我还没有形成内在的视角，没有自己独特的观察方式，所以一切在视觉上都显得合理。

_我也还没意识到，一场好的谈话 ⸺ 随着时间推移会越来越少 ⸺ 比眼角余光中看到的有趣对称更重要。_

不过，我的朋友们还是容忍了我的「艺术感」，容忍我突然的走神。

_直到我儿子出生，我才开始衡量当我举起相机对准远处拍摄时，自己和朋友之间产生了多远的距离。_

_在我决定不再随身携带相机与朋友相处的那天，这段距离被我消除了。_

_正如我在回顾展上对质疑我的摄影师所说：「我不能同时做两件事。」_

如今，在我们的智能手机世界里，我的摄影注意事项已经过时，而且坦率地说，是不可理解的。

手机中存储的上万张照片是对我在摄影上的漫不经心的极大反驳。

_这些照片 ⸺ 将我们锁定在某些时刻，通常是精心安排的上镜时刻 ⸺ 可能扭曲我们回忆过去的方式。_

_那些照片之外的空白，可能才是记忆最肥沃的土壤。_

[[https://hedgehogreview.com/issues/after-neoliberalism/articles/on-not-carrying-a-camera#:~:text=Over%20the%20next,ground%20of%20memory.][Source]]
#+end_quote
#+end_details

** [[https://notashelf.dev/posts/curse-of-knowing][The Curse of Knowing How, or; Fixing Everything]]

作者比喻软件开发就像是西西弗斯推着巨石，软件需要不断地改进，修复，但最终还是会腐化。

如果执着于把软件修复到没有任何问题，那可能就会让自己承担太多的责任，而不堪重负。

要学会放手，学会在什么地方停下来，学会让它们保持破碎。

#+begin_details
#+html: <summary>摘录</summary>

#+begin_quote
_就像加缪笔下的西西弗斯一样，我们注定要推动我们自己系统的巨石上山 ⸺ 一次修复，一次重构，一次脚本。_

_但与西西弗斯的故事不同，诅咒不是由神降加于你的。我们自己建造了这块巨石。而且我们还在上山的路上不断打磨它。_

我已经数不清有多少个项目是以 「是的，我可以做得更好」的变体开始的。

- 一个静态站点生成器，因为现有的生成器有太多的主观意见。
- 一款笔记工具，因为我不喜欢其他工具构建元数据的方式。
- 一款 CLI 任务运行器，因为 Make 晦涩难懂，而 Taskfile 简直是 YAML 地狱。
- 一个用 Rust 写的个人维基引擎，然后用 Go 写，然后用 Nim 写，最后又回到 Markdown。
- 一个家庭实验室仪表盘，因为我不喜欢臃肿的 Web 应用。

这个清单还在继续，相信我，它确实在继续。

我的开发目录目前已经接近 30 GB。

如果你问我，我当时是在解决真实、纯粹的问题。

_但事后看来，我也在滋养着别的东西：一种掌控的欲望。_

我构建的每一个新工具都是我拥有的沙盒：没有奇怪的 bug。

没有遗留的限制。

没有我不完全同意的决定。

_当然，直到我变成了遗留问题。_

[[https://notashelf.dev/posts/curse-of-knowing#:~:text=Like%20Camus%E2%80%99%20Sisyphus,became%20the%20legacy.][Source]]
#+end_quote

#+begin_quote
_软件的问题不会永远解决。_

_你写下的每一个解决方案，从它诞生的那一刻起就开始腐朽。_

_不是现在，也不是以后，而是最终。_

库被废弃。API 发生变化。性能出现回退。

你曾经完美的工具悄无声息地坏掉了，因为 libfoo.so 现在变成了 libfoo.so.2。

[[https://notashelf.dev/posts/curse-of-knowing#:~:text=Software%20doesn%E2%80%99t%20stay%20solved.%20Every%20solution%20you%20write%20starts%20to%20rot%20the%20moment%20it%20exists.%20Not%20now%2C%20not%20later%2C%20but%20eventually.%20Libraries%20deprecate.%20APIs%20change.%20Performance%20regressions%20creep%20in.%20Your%20once%2Dperfect%20tool%20breaks%20silently%20because%20libfoo.so%20is%20now%20libfoo.so.2.%202][Source]]
#+end_quote

#+begin_quote
延续用文学引用充实这篇文章的主题，让我引用斯多葛派的 Marcus Aurelius。

_你对自己的心智能力拥有掌控权 ⸺ 而非外部事件。_

意识到这一点，你将找到力量。

_但编程诱使我们相信我们可以控制外部事件。痛苦也正从这里开始。_

这里发生着更深层次的事情。这不仅仅是关于软件。

我相信有时构建东西是我们自我安慰的方式。

我们编写一个新工具或脚本，是因为我们迫切需要一次小小的胜利。

我们写新工具，是因为感到不堪重负。

重构它，不是因为代码凌乱，而是因为你的生活凌乱。

我们追求完美的系统，因为当一切都在旋转时，它给了我们一个可以抓住的东西。

这是我从使用 NixOS 中得到的教训。

我曾写过整个应用程序，只是为了避免思考自己为何不快乐。

编程给你即时反馈。

你运行程序，它就能工作。

或者不工作，你就修复它。

无论哪种方式，你都在做些什么。

那种能动性令人上瘾。

尤其是当生活的其他方面无法提供这种能动性时。

我们编程是因为我们能编，即使不该编。

因为至少它给了我们一个反抗的对象。

[[https://notashelf.dev/posts/curse-of-knowing#:~:text=On%20the%20theme,to%20rebel%20against.][Source]]
#+end_quote

#+begin_quote
_倦怠不仅仅来自过度工作。它来自过度承担责任。_

而编程，一旦深深内化，就会让一切都感觉像是你的责任。

臃肿的网站。低效的脚本。你工作的笨拙入职流程。

你本可以修复它们。那么，为什么你没有呢？

_你非常清楚的事实是，你无法修复所有问题。_

_你知道这一点，无论你的技能水平如何，你一直都知道。_

但试着告诉你大脑中那个将每一个低效视为道德缺陷的部分这点。

_尼采 (Nietzsche) 警告过不要长时间凝视深渊。_

_但他并未警告当深渊是一段 Makefile 或一个三万行代码的 Typescript 项目时会发生什么。_

[[https://notashelf.dev/posts/curse-of-knowing#:~:text=Burnout%20does%20not,code%20Typescript%20project.][Source]]
#+end_quote

#+begin_quote
那么出口在哪里？

这是否类似于 萨特 Sartre 所描绘的地狱，地狱是他人以及他们与你的软件的互动？

还是某种奇怪的反向地狱，人们创造的软件你不得不去互动？

_第一步是认识到并非所有破损的东西都需要你去修复。_

_不是所有工具都需要更换。_

_并非每次糟糕的经历都需要采取行动。_

有时候，仅仅使用那个东西就足够了。

有时候，知道它为什么坏了 ⸺ 即使你不去修理 ⸺ 也已经足够了。

有时候，你能做的最有纪律的事情就是放下那个你知道如何解决的问题。

这其中蕴含着一种力量。

_不是冷漠，不。也不是懒惰。只是 ⸺ 某种克制。_

[[https://notashelf.dev/posts/curse-of-knowing#:~:text=So%20where%20is,Just%E2%80%A6%20some%20restraint.][Source]]
#+end_quote

#+begin_quote
_你学会了编程。你学会了修理东西。但你将学到的最难的事情是，什么时候该让它们保持破碎。_

_也许这才是最具人性的技能。_

[[https://notashelf.dev/posts/curse-of-knowing#:~:text=You%20learn%20how,skill%20of%20all.][Source]]
#+end_quote
#+end_details

** [[https://pudding.cool/2025/06/hello-stranger/][30 minutes with a stranger]]

作者做了一个研究，找了很多人，他们有不同性别、年龄、学历、人种、政治倾向，让他们进行聊天。

一开始大家都觉得会有不好的体验，但聊到后面发现大多都得到了积极的体验，无论两个人有多大的差异。

结论是，大多数情况下，如果和一个陌生人展开一次对话，往往能得到积极的，友好的体验。

作者还分享了一件在地铁中发生的事，一个男孩摔伤了，一边流血一边哭，但是地铁上没人帮他。

于是作者给他递了纸巾，告诉他用纸巾止血。男孩觉得很震惊。

当作者纸巾用完了，这个时候其他人也开始来帮他，提供了消毒纸巾，绷带等。

等作者下车了，后面也依然有人照顾男孩。

面对一个陌生人需要帮助，有的人可能无动于衷，觉得不是自己的事情，也可能嫌麻烦不想提供帮助。

可是，如果那个需要帮助的人是自己呢？

和陌生人展开一次对话，大多数是积极的；和陌生人产生联系，大概率也是积极的。

或许下次碰到有需要的陌生人事，不用担心那么多，而是去接近他，帮助他。

我想，在一个人人互相帮助的世界里，比在一个人人只顾自己的世界里，会更安心和幸福吧。

BTW，网站交互做得很棒，推荐看看原文。

#+begin_details
#+html: <summary>摘录</summary>

#+begin_quote
社会信任对于我们应对未来一些最大的挑战至关重要：民主的侵蚀、人工智能的出现、地球变暖等等。

在 2021 年的一项研究中，研究人员探讨了社会信任为何在个人层面上下降。

他们发现，收入不满、失业经历以及我们对政治机构信心的下降，是信任减少的主要原因。

简而言之，我们创造了一个对大多数人来说不稳定且充满不确定性的世界。

我也有同感。

世界上发生的大事小事让我感到害怕。

我感觉周围的环境在崩塌，安全感在减弱。

我曾看过一些偏远地区的房子，想着和朋友家人一起隐居在那里 ⸺ 在那里我不必依赖陌生人。
#+end_quote

#+begin_quote
几个月前，我乘地铁去上班时，一个 16 岁的男孩在地铁站台滑倒，嘴巴撞到了地面。

他跌跌撞撞地上了车，站在我旁边。

我戴着耳机，试图说服自己这不是我的事。

然后我眼角瞥见他的下巴裂开了；血和泪水顺着他的脸流下来。

我环顾车厢，想找别人帮忙 ⸺ 也许是和孩子打交道的人。

没人抬头看一眼。

于是我从背包里拿出一些纸巾，转向他，告诉他用纸巾按住下巴。

他当时很震惊。

我试着安慰他，告诉他到学校后去医务室。

_我脑海中唯一的想法是：如果那个人是我呢？谁会帮我？大家会像现在这样围观吗？_

但当我用完纸巾止住这个孩子的流血时，车上的人注意到了，递给我消毒湿巾、纸巾和绷带。

我们成功止住了流血。

当我下车时，另一个陌生人站起来，站在孩子身边。

_当我们受伤时，我们不信任身边的人。_

_我们选择躲避，因为我们认为那是唯一的安全方式。_

_我们让陌生人受苦，因为在这种情绪状态下，每个人都是威胁。_

_这意味着我们很难与他人合作，建设我们想要的世界。_

_我们只能蜷缩起来，等待不可避免的反乌托邦到来。_

_但我不想生活在那样的世界里。我想感到安全。我想帮助别人感到安全。_

_我也希望别人能为我做到同样的事情 ⸺ 无论我是不是陌生人。_
#+end_quote
#+end_details

** [[https://www.simplethread.com/learning-to-love-your-legacy-codebase/][Learning to Love your Legacy Codebase]]

作者曾经接手过一个 25 万行代码的历史代码库，尽管刚开始很头疼，但慢慢去理解后，他也能从容地在里面进行修改。

相反，有个团队尝试完全重构，但在作者离开前，新系统都还没能正式交付。

工作几年来，我也接手过不少的历史代码库，往往很多都觉得是一座「屎山」，但有的实现也是能让我学习到很多，也让我敬佩。

历史代码库历经了多年的迭代，一直存活着，创造着它的价值，上面布满了多年来附加在其上的修复和功能留下的伤痕。

在评判、丢弃历史代码之前，花点时间先阅读和了解它，或许它并没有想象的那么糟，甚至会让你产生敬意。

#+begin_details
#+html: <summary>摘录</summary>

#+begin_quote
在那段时间里，我对这个老系统产生了很大的敬意。

_虽然它有很多不完美的地方，但其核心是一个优雅的系统，经历了全球数百万台计算机每天使用所留下的无数伤痕。_

并非所有遗留代码库都是一样的；有些根本无法挽救，有些则建立在已不再支持的过时技术之上。

_但我个人认为，很多旧代码库被丢弃，是因为人们没有花时间去理解它们。_

[[https://www.simplethread.com/learning-to-love-your-legacy-codebase/#:~:text=During%20that%20time,to%20understand%20them.][Source]]
#+end_quote

#+begin_quote
那么，我们如何真正开始深入理解这些遗留系统呢？

_我收到过的关于理解大型旧代码库的最有价值的建议就是拿出调试器，开始逐步执行代码。_

_即使你最喜欢的调试方式是打印语句，实际的调试器仍然是最好的工具，而且每种主流语言都有调试器。_

_一个软件系统是代码逻辑和流经其中的数据的结合体，而调试器是观察两者如何协同工作的最佳方式。_

你几乎可以从任何地方开始。

主入口点会教你很多关于应用程序需要设置什么以及它如何启动和运行的知识。

从最常用的 API 调用之一开始，可以让你了解各个组件是如何连接的。

如果有测试代码，我发现它们总是深入新代码库的绝佳起点。

测试就像叙述者，可以描述它期望代码片段如何表现。

你也可以让你喜欢的生成式 AI 工具为你解释某段代码，但一定要记得随后用调试器逐步执行验证。

_实际上观察代码的行为是无可替代的。_

除了调试器之外，还有其他一些资料可以很好地揭示遗留代码库的工作方式、构建时所受的限制以及其生命周期中遇到的问题。

一些额外的方面可以帮助你更全面地了解情况：

- 最初的需求文档。
- 测试（如果存在的话）。测试有时可以帮助你拼凑出最初的需求以及遇到的问题历史。
- 代码中零星分布的注释。注释可以提供开发过程中发生了什么的见解，有时还能直观反映出当时开发者的思维方式。
- 自述文件、设计文档，甚至是市场推广资料。

_当你开始这段考古般的探索过程时，会有一种发现的感觉，你找到的每一条信息都有助于更好地理解代码库。_

_一旦理解了它，你在添加新功能时会更加无畏。_

_每次修改代码时，也不太可能破坏现有功能。_

_知道在哪里集成新功能以及破坏现有功能的风险，可能是处理遗留代码时最大的两个挑战。_

_期望完全理解一个旧应用程序是不合理的，但你并不需要达到那种熟悉程度，才能有效地贡献和维护它。_

[[https://www.simplethread.com/learning-to-love-your-legacy-codebase/#:~:text=So%20how%20do,and%20maintain%20it.][Source]]
#+end_quote

#+begin_quote
_无论是最滑稽庞大的意大利面条式代码，还是历史上最精心设计的软件，遗留代码都蕴含着大量智慧。_

_一段代码运行的时间越长，它遇到并解决的问题就越多。_

_它可能充满了当时常见但现在大多被遗忘的巧妙性能优化。_

遗留代码可以教你一些你从未见过的算法实现方式，也让你了解别人是如何处理和解决问题的。

[...]

_遗留代码包含了大量关于其所处领域和行业的信息。_

_你可以从中学到很多关于应用程序如何为用户解决问题，以及其领域在应用程序生命周期中可能发生的变化。_

_多年来附加在其上的修复和功能是艰难教训留下的伤痕。_

这些修复和变更的积累既是重写往往失败的原因，也是代码库变得难以管理的原因。

随着时间推移，紧急问题需要对代码进行小幅修改。

这些修改很少有良好的文档记录，并且逐渐积累成为应用程序逻辑的重要部分。

这些改动通常也以一种并未很好融入原始架构的方式编写。

最终结果是大量匆忙实现的功能积累。

这让我们渐渐讨厌与代码库打交道，但它也是应用程序为用户提供价值的重要组成部分。

通过一些努力，你可以开始理解这些部分，并着手寻找让它们变得稍微好一点的方法。

[[https://www.simplethread.com/learning-to-love-your-legacy-codebase/#:~:text=Whether%20it%E2%80%99s%20the,little%20bit%20better.][Source]]
#+end_quote

#+begin_quote
既然我们已经爱上了遗留代码，就无法想象把它扔进垃圾桶重新开始，但说实话，它仍然相当糟糕。

你该如何改进它呢？

_我见过最成功的方法是有目的地用新的功能组件替换旧组件。_

_通过有条不紊地替换这些部分，你可以专注于确保某个小区域保留遗留功能，同时加入一些新的改进功能。_

_这对避免从零重写的常见陷阱大有帮助。_

它让你有机会加入新的测试，而且几乎可以做到对最终用户透明。

这个过程通常被称为忒修斯之船 (Ship of Theseus) 或攀援无花果模式 (Strangler Fig pattern)。

这种方法可能需要很长时间，但通常不会比重写花费更久。

_它还有一个额外好处，就是在编写和集成新代码的同时，现有应用仍能继续运行。_

在我刚才极力主张真正理解你的遗留代码之后，我不得不承认，有些情况下确实无可挽回，你只能重新开始。

这可能是由于平台发生了重大变化，或者技术已经完全过时且不再维护。

_重新开始总是更有趣，但重要的是你必须确信这确实是必要的。_

_同时，你也必须清楚放弃旧系统并构建新系统时将面临的挑战。_

_很有可能你刚刚创造了下一代未来开发者将痛恨多年的遗留代码。_

作为软件开发人员，我们很可能需要处理至少一个甚至多个遗留代码库。

它们庞大且杂乱无章，添加新功能的过程从困难到彻底灾难不等。

_如果你花时间真正深入挖掘并理解代码库，你可能会发现它其实并没有那么糟糕。_

_存在一些方法可以干净利落地添加新功能，而且你还能从中学到很多关于应用领域和构建该应用所用技术的知识。_

_在决定丢弃那些旧代码之前，花点时间更好地了解它，你可能会因此对代码以及最初构建它的人产生新的敬意。_

[[https://www.simplethread.com/learning-to-love-your-legacy-codebase/#:~:text=Now%20that%20we%E2%80%99re,originally%20built%20it.][Source]]
#+end_quote
#+end_details
** [[https://fireborn.mataroa.blog/blog/i-want-to-love-linux-it-doesnt-love-me-back-post-1-built-for-control-but-not-for-people/][I Want to Love Linux. It Doesn’t Love Me Back: Post 1 – Built for Control, But Not for People]]

文章是一个盲人用户对 Linux 可访问性的吐槽。

不知道是不是我自己关注相关的内容，我觉得现在越来越多的网站，操作系统都在关心可访问性的问题。

作为开发者也好，博客作者也好，也应该多考虑可访问性，为用户着想。
** [[https://deplet.ing/the-copilot-delusion/][The Copilot Delusion]]

一篇反对 Copilot 等工具的文章，文风挺喜欢的。

我已经习惯有 LLM 帮助我了，但还是要警惕不要放弃思考，而完全依赖 LLM。

然而这个界限又是模糊的，什么样算是放弃思考依赖 LLM？

只是让 LLM 负责完成那些「无聊的」工作算是依赖吗？

或许从使用 LLM 帮你写代码开始，享受它的便利开始，思考就在缓慢地消亡了。

#+begin_details
#+html: <summary>摘录</summary>

#+begin_quote
首先声明：我喜欢写代码。不是监督。

不是像个呆滞的硅基实习生一样盯着一个被阉割的合成聊天机器人，试图记起 ~std::move~ 到底是干什么的。

我不想当那个肉体中层经理，去审查某个神经网络做梦般的 ~switch~ 语句。

我想造东西。真正的东西。奇怪的东西。那种 *燃烧起来* 的系统。

_「但我只是用 AI 写模板代码！」你一边抱着你的 Co-Pilot 订阅一边呜咽。_

_听听你自己说的话。_

_如果你每天都在写同样的模板代码，像个工业时代的齿轮猴子，那就自己自动化它。_

_写个库。发明个宏。找回点尊严。_

如果 AI 帮你做了「无聊的部分」，那你到底还剩下什么活可干？

摆弄滑块？在推理魔法运行时按图索骥？

[...]

_你想真正与代码建立联系？_

_那得靠自己。你得深入钻研。_

凌晨三点和段错误搏斗。

你在公寓里踱步，喃喃自语指针运算。

你看完 /Handmade Hero/ 直到弄懂为止。

你写自己的笔记，而不是拍讲义幻灯片假装那算数。

_当你把思考外包出去，也就是把学习外包了。_

你成了一个机械鸟的传声筒，把它捕猎的东西直接吐进你这只小鸟嘴里。

你不懂你的代码，你只是在照看它。

[...]

_问题不仅仅是懒惰。是退化。_

_工程师停止探索。停止改进。停止关心。_

多一层抽象。在渲染循环里多一个懒惰的 fetch 调用。

最终，你生活在技术债务的大教堂里，每个用户都在买单。

每次点击都是对你冷漠的税收，几毫秒，几秒钟不等。

五千万用户一天多了三秒不必要的延迟，因为你想按下 Tab 键而不是写代码？

那几乎是累计浪费了五年的时间。

[...]

你想成为真正的程序员？

动动脑子。尊重机器。

否则就离开驾驶舱。

[[https://deplet.ing/the-copilot-delusion/#:~:text=First%20things%20first,of%20the%20cockpit.][Source]]
#+end_quote

#+begin_quote
听着。

_你是人类。柔软的肉体，腐烂的牙齿，突触通过咖啡因和怨恨驱动着彼此发射电信号。_

但你 ⸺ 即使在最疲惫、缺觉、眼圈发黑的状态下 ⸺ 你仍然可以尝试。

你可以眯起眼睛看穿层层抽象。

剥开那些漂亮的人体工学、类型安全、纯净、惰性、不变的语法糖，想象编译器吐出的汇编代码的混乱。

你能像第六感一样感知缓存行。

你知道数据想要在哪里。

也知道当你搞砸时硅芯片会变得愤怒。

机器是真实的。

硅是真实的。

DRAM、L1 缓存、伪共享、像掷硬币一样的分支预测器。

这一切都是真实的。

如果你在意，你可以与它们共事。

你可以让你的程序像钢铁巨蛇一样无缝穿梭于内存，几乎没有任何开销。

你可以巧妙地安排预取。

你可以手工设计一个分配策略，让 malloc 显得像小儿科。

你可以真正知道 ⸺ 真正知道 ⸺ 什么时候该捏捏手指关节，写几行肮脏却美丽的内联汇编，直接给你的程序注入兴奋剂，让它焕发光彩。

但是那个机器人呢？

那个机器人呢？

那个机器人根本毫无头绪。

这个机器人完全不懂。

它分不清页面错误和纸割伤。

它会像我两天没睡觉后产生幻觉一样，虚构一个内存模型。

它不会做性能分析。

它看不懂火焰图。

它感受不到在热点循环中浪费 CPU 周期的那种冷酷灼烧感。

它会照搬一个 2008 年 StackOverflow 帖子里一个满头大汗的陌生人的建议，那人当时用的是 Pentium 4、512MB RAM (Random Access Memory) 和一个梦想在做基准测试。

它会说，「这是最优的」，仿佛它懂得什么，仿佛它见过缓存未命中。

它没见过。

你见过。

那个东西会给你喂垃圾。

它会给你伪造的人物传递虚假的智慧，并乞求你信任它。

但如果你想打造一个快速、美观的系统 ⸺ 如果你想雕刻出那种被植入心脏起搏器、导弹制导系统和 M1 tanks 的软件 ⸺ 你最好把那个机器人扔出气闸门，然后自己学习。

也许你永远不会编写让飞机保持飞行的代码。

也许你永远不会推动那些关系到人类生命安全的代码。

没关系，大多数人都不会。

但即使你只是为某个臃肿的企业拼凑另一个 CRUD (Create, Read, Update, Delete) 应用，你仍然欠用户尊重。

_你欠他们尊严。_

_这些用户把他们辛苦赚来的钱交给了你的公司，换取的是一款工具。_

_不是一个卡夫卡式的时间黑洞。_

_不是一个臃肿、卡顿的垃圾火焰，拖垮了运行它的硅芯片。_

他们不是付钱让你在联合办公空间敷衍了事、反复点击标签页。

当你坐在那张带衬垫的椅子里，像在教堂中漂浮，每年烧掉四分之一百万的 VC (Venture Capital) 资金时，你至少可以假装在乎一点。

假装足够久，去做一些分析。

去把渲染时间缩短 200ms。

不要像现代的 Picasso 那样，交付一个破碎的体验。

_这是一份职业。为你一生的工作感到自豪。_

_你通过实践来培养品味。_

_通过经历挫折。_

_通过用精密的工具削减纳秒。_

_通过周一写一个程序，周二重写，周三才意识到它依然糟糕。_

你不会通过问 2025 年的微软小助手 Clippy 如何做你的工作来培养品味。[fn:1]

_在计算历史的长河中，我们仍然满身泥土，用犁耕作着我们的比特。我们骑着马。_

_但我们中的一些人 ⸺ 那些眼睛爆裂、键盘焦黑的人 ⸺ 知道如何打造下一样东西。_

_火车。快艇。纯代码的高超音速喷气机。_

那些还把人工智能当作神谕来使用的人呢？

他们会在那里试图用胶带把马绑在发动机上，纳闷为什么它飞不起来。

说着，「嘿，还是飞不起来……还是飞不起来……还是飞不起来，快修好它。」

[[https://deplet.ing/the-copilot-delusion/#:~:text=Listen.%20You%E2%80%99re%20human,fix%20it%20please.%22.][Source]]
#+end_quote

#+begin_quote
_我最讨厌人工智能及其易用性的一点；那就是黑客精神的缓慢而痛苦的死亡 ⸺ 这不是由战争或匮乏带来的，而是由便利带来的。_

由按钮带来的。由机器人带来的。

_真正的恐怖不在于人工智能会抢走我们的工作，而在于它会吸引那些本来就不想做这份工作的人。_

_那些不在乎质量的人。_

[...]

这里曾经有魔法。这里曾经有疯狂。

_孩子们会熬夜在 IRC 上，眼睛布满血丝，试图在 OpenGL 中渲染一个立方体，而不让他们的未来崩溃。_

_他们在乎。_

_他们会在烤面包机上安装 Gentoo，只为了看看它能否启动。_

_他们熟悉烧坏电压调节器的气味，也知道 /Doom/ 在他们的计算器上降到 10 帧每秒的确切汇编代码行。_

_这些都是「艺术家」。_

_他们写代码就像爵士乐手——充满愤怒、精准和神圣的混沌。_

现在？

我们正在构建一个世界，在那里好奇心一进门就被切断。

某个天生注定要伟大的人，会被告知每天花八小时「审查这份 AI 生成的补丁集」，直到所有的惊奇都变成冷漠。

终端将变成电子表格。调试器将变成棺材。

_因为你不知道自己不知道的东西。这就是残酷的笑话。_

[...]

_将你的思考推迟给机器人，我们都会腐朽。_

[[https://deplet.ing/the-copilot-delusion/#:~:text=The%20thing%20I,we%20all%20rot.][Source]]
#+end_quote
#+end_details
** [[https://moretothat.com/the-arc-of-the-practical-creator/][The Arc of the Practical Creator]]
* Tutorial | Resource
** [[https://samwho.dev/reservoir-sampling/][Reservoir Sampling]]

一篇关于蓄水池抽样的交互式文章，比较清晰易懂。

蓄水池抽样是用于从未知大小的数据量里公平地采样的方法，要保证每个元素被采样的概率相同。

例如从 n 中选择 k 个数据，n 是未知的，需要确保每个元素被选择的概率相同，即 k / n。

在选择数据的时候，可以从 0 ～ n 中选择一个随机数，n 是当前的数据量大小，如果随机数小于 k，则选择当前的数据，否则不选择当前的数据，直到停止选择。
** [[https://www.fffuel.co/tttexture/][tttexture]]

#+begin_quote
免费的脏旧风、复古与混凝土纹理合集。

这套素材来自使用微距镜头拍摄的真实照片，提供了来自老旧墙面、混凝土板和地面的高分辨率真实纹理。

沉浸于真实的脏旧、复古和混凝土叠加效果中，提升您的设计品质。
#+end_quote
* Code Related
** [[https://blog.damato.design/posts/out-of-order/][Out of order]]

作者讨论了 CSS 控制元素顺序的方法，如 [[https://www.joshwcomeau.com/css/stacking-contexts/][z-index]]，DOM 顺序，堆叠上下文等。

其中有些方法会导致一些副作用，例如 z-index 的竞争，意外的堆叠上下文创建等。

#+begin_quote
总之，当你试图使用 CSS 更新元素顺序时，请停下来考虑这些决定的副作用，并参考这里的一些建议，以帮助保持结构的一致性。
#+end_quote

BTW，这个博客挺有趣的，作者给每篇文章都配了一个封面，封面是那种 [[https://en.wikipedia.org/wiki/O%27Reilly_Media][O'Reilly]] 的风格，乍一看我还以作者出了很多本书 _​(:3 」∠)_
** [[https://ruby0x1.github.io/machinery_blog_archive/post/a-taxonomy-of-bugs/index.html][A Taxonomy of Bugs]]

作者整理了对 bugs 进行了分类，并给出了每类 bugs 的应对方法。

#+begin_quote
我对任何错误使用的默认策略是：

1. 尝试找到一种可靠重现该错误的方法，以便我能够
2. 在错误发生时进入调试器，并且
3. 逐行执行代码，
4. 查看它的行为与我预期的行为有何不同。

一旦你理解了代码的实际行为与自己对其行为的心理模型之间的差异，通常就很容易找出问题并加以修复。

[[https://ruby0x1.github.io/machinery_blog_archive/post/a-taxonomy-of-bugs/index.html#:~:text=The%20default%20strategy,and%20fix%20it.][Source]]
#+end_quote
* Cool Bit
** [[https://rms.sexy][Our GNU/Lord and GNU/Savior is 100% sexy!]]

Richard Stallman 的各种工作照，确实很 sexy！也挺酷的，随时随地地工作。

** [[https://p2piano.com][p2piano]]
一个为音乐爱好者打造的协作空间。

可以多人在线一起演奏。
** [[https://radiocast.co/][Radiocast]]

聆听全球各地的电台。

你就是 [[https://music.163.com/#/artist?id=99384][Radiohead]] へ(゜∇、°)へ

** [[https://felixrieseberg.github.io/clippy/][Clippy Desktop Assistant]]

复古造型的 AI 助手，UI 是 1990 年左右的 UI 风格。
** [[https://dbushell.com/2025/05/07/glossary-web-component/][Glossary Web Component]]

作者使用 [[https://developer.mozilla.org/en-US/docs/Web/API/Web_components][Web Components]] 实现了一个术语组件，当悬浮在术语上就会出现一个弹窗解释术语含义，很不错的想法。

想抄过来 (≖ᴗ≖๑)
** [[https://blog.hayman.net/2025/05/06/from-steve-jobs-great-idea.html][From: Steve Jobs. "Great idea, thank you."]]

作者在 [[https://en.wikipedia.org/wiki/NeXT][NeXT]] 工作过，NeXT 计算机上有邮件功能，邮件地址除了默认的地址，还可以申请别名。

尽管有好几个叫 Steve 的人，但没有申请 steve@next.com 的别名，作者也叫 Steve，就申请了试试。

结果收到了很多本来是发给 Steve Jobs 的邮件，吓了作者一跳，不过他都没有看，然后赶紧改了，将其转发到 Steve Jobs 的邮箱，并发邮件向 Steve Jobs 说明了。

然后作者收到了 Steve Jobs 的回信 ⸺ "Great idea, thank you."
** [[https://www.binghamton.edu/news/story/5547/do-your-fingers-wrinkle-the-same-way-every-time-youre-in-the-water-too-long-new-research-says-yes][Research shows fingers wrinkle the same way with every water immersion]]

冷知识，手指泡水后，每次起皱的图案基本是一样的。

起皱的原因是血管在长时间浸泡下会收缩，从而形成皱纹。
** [[https://www.rifters.com/crawl/?p=11511][It Awaits Your Experiments.]]

一个人研究将文字编码在地球上最强悍的微生物 ⸺ [[https://zh.wikipedia.org/wiki/%E6%8A%97%E8%BC%BB%E5%B0%84%E5%A5%87%E7%95%B0%E7%90%83%E8%8F%8C][抗辐射奇异球菌]]上面，而且他成功了。

这意味着这些文字有可能会被一直保留，直到太阳将地球吞没。

#+begin_details
#+html: <summary>摘录</summary>

#+begin_quote
但最终的目标微生物是耐辐射球菌 (Deinococcus radiodurans)：因其是地球上最强悍的微生物之一，被昵称为 「细菌界的康纳」。

用 Bök 自己的话来说：

宇航员害怕它。

生物学家害怕它。

它不是人类。

它孤独地生活。

它在完全黑暗中生长。

它不从太阳获取能量。

它以石棉为食。

它以混凝土为食。

它栖息在约翰内斯堡 Mponeng 矿 104 层的一条金脉中。

它生活在充满砷的碱性湖泊中。

它在沸腾的沥青泻湖中生长。

它在致命的硫化氢瘴气中茁壮成长。

它呼吸铁。

它呼吸锈。

它不需要氧气生存。

它可以在没有水的情况下存活十年。

它能承受 323 开尔文的高温，足以熔化铷。

它可以在盐晶体中沉睡十万年，埋藏在 Death Valley。

它不会在德累斯顿 (Städtbibliothek) 被火焰轰炸时的地狱烈焰中死去。

它暴露在紫外线下也不会燃烧。

它不通过 DNA 繁殖。

它在发胶罐中无声繁殖。

它以聚乙烯为食。

它以碳氢化合物为食。

它栖息在黄石国家公园 (Yellowstone National Park) 大棱镜温泉附近的腐蚀性蒸汽间歇泉中。

[[https://www.rifters.com/crawl/?p=11511#:~:text=Phase%20One%20involved,Yellowstone%20National%20Park.][Source]]
#+end_quote

#+begin_quote
因为现在是 2025 年，他他妈的成功了。

/The Xenotext/ 活生生地存在于耐辐射球菌 (Deinococcus radiodurans) 中：在那个以不锈钢为食、位于切尔诺贝利 4 号反应堆核心、在哥伦比亚号航天飞机轨道再入时爆炸解体中依然存活的不朽微生物强者体内不断复制。

Christian Bök 没有放弃。

Christian Bök 没有失败。

Christian Bök 将活得比文明更久，活得比大多数生物圈本身更久。

我们其他人可能认为，如果我们的作品能流传一百年或三百年，就算实现了艺术上的永生。

Bök 对这种微不足道的野心嗤之以鼻。

他的作品可能会被费米 (Fermi) 外星人在十亿年后最终抵达我们附近时解读出来。

它可能会一直迭代，直到太阳将这颗星球完全吞没。

[[https://www.rifters.com/crawl/?p=11511#:~:text=Because%20now%20it%E2%80%99s,this%20planet%20whole.][Source]]
#+end_quote
#+end_details
** [[https://notes.andymatuschak.org/About_these_notes][Andy Matuschak's working notes.]]

很酷的个人笔记系统，交互也不错。

也想把自己的笔记放到网页上可以方便访问。
** [[https://old.reddit.com/r/AskReddit/comments/2s9u0s/what_do_insanely_wealthy_people_buy_that_ordinary/cnnmca8/][What do insanely wealthy people buy, that ordinary people know nothing about?]]

极其富有的人买些什么，普通人根本不知道？

#+begin_details
#+html: <summary>摘录</summary>

#+begin_quote
我打算排除那些超过 100 亿美元的人群，因为他们过的是国家元首般的生活。

但到了 10 亿美元，生活就变了。

你可以买任何东西。任何东西。

大致来说，你可以买到这些：

- *通道 (Access)。*

  你现在只需让你的员工联系任何人，你就会收到回电。

  [...]

  对亿万富翁所在政党的几乎任何参议员 (Senator) / 州长 (Governor) 也是如此（因为在大多数情况下，他是重要捐赠者）。

  你会偶尔和国家元首见面，并与他们进行真正的对话。

  这就导致了 ⸺

- *影响力 (Influence)。*

  没错，你可以买到影响力。

  作为亿万富翁，你有很多方式去影响公共政策和公众辩论，而且你会利用这些方式。

  这并不是出于什么邪恶目的。

  我认识的那些人都对自己的理念充满热情，试图做他们认为最好的事情（就像你会做的一样）。

  [...]

  你拥有的影响力有时候会让人飘飘然。

- *时间 (Time)。*

  没错，你可以买时间。你根本不用等任何东西。

- *体验 (Experiences)。*

  梦想它，你就能拥有它。

  [...]

  你唯一的限制就是你的想象力。因为捐款/费用能请到任何人。

  买东西也是一样。

  喜欢钢琴？那拥有一台 Mozart 用来作曲的钢琴怎么样？

  这就是你能做到的那种事情。

- *影响力 (IMPACT)。*

  你的钱真的可以改变世界，改变生命。

  想到这点几乎让人难以承受。

  一整个村庄永远有干净的水？小意思。

  一个垂死的孩子需要移植？见鬼……你完全可以建一家医院，资助一个地区来解决这个问题。

- *尊重 (RESPECT)。*

  在这个层级你得到的尊重简直是爆棚。

  你几乎是每个圈子里的 「大佬」。

  州长们都敬仰你。

  财富 500 强的 CEO 们都看你一眼。

  总统和国王都把你当成同辈。

- *视角 (PERSPECTIVE)。*

  我接触过的最富有的人年收入大约 4 亿美元。

  我之前根本无法理解这个数字，直到我这样想：好 ⸺ 我们拿一个年收入 4 万美元的人来对比。

  这是 1 万倍的差距。

  现在用他的视角来看价格。

  一辆新兰博基尼 (Lambo) ⸺ 23.5 万美元变成 23.5 美元。

  国际头等舱机票？1 万美元变成 1 美元。

  [...]

  几乎没有什么是你买不到的，除了……

- *爱 (Love)。*

  抱歉听起来老套，但在这个层级几乎不可能有正常的情感关系。

  _当你从未被要求为别人牺牲任何东西时，很难去为别人牺牲。_

  钱能解决一个人的所有问题，所以你就提供它，因为还有太多别的事情要做。

  你的时间非常宝贵，以至于你得精打细算。

  这让你和人之间的联系变得疏远。

[...]

看到这些并没有让我想进入顶级圈子。

_不同的人生有同样的情感难度：几个月前我在一个派对上第一次见到了 Sylvester Stallone。_

人很好，有一个漂亮又聪明的妻子和辉煌的事业。他有一个早逝的特殊需求儿子。

_没人是全能的。没人。_

[[https://old.reddit.com/r/AskReddit/comments/2s9u0s/what_do_insanely_wealthy_people_buy_that_ordinary/cnnmca8/#:~:text=ones%20they%20are.-,%241billion,special%20needs%20son%20who%20died%20young.%20Nobody%20has%20it%20all.%20Nobody.,-permalink][Source]]
#+end_quote
#+end_details
** [[https://timeless][timeless]]

#+begin_quote
世界上有各种各样的公交车，而我们拥有其中最优质的精选。

我们热爱并精心维护它们，也非常乐意与您分享。
#+end_quote
* Tool | Library

* Emacs

* 一些话 | 摘抄

** 费曼

#+begin_quote
If you're not having fun, you're not learning. There's a pleasure in finding things out.

如果你玩得不开心，那你就没在学东西。发现新事物本身就是一种乐趣。
#+end_quote

** [[https://www.centauri-dreams.org/2025/05/06/is-planet-nine-alone-in-the-outer-system/][Is Planet Nine Alone in the Outer System?]]

#+begin_quote
罗伯特·布朗宁 (Robert Browning) 曾说：「啊，但人的追求应超出他的掌握，否则天堂有何用？」

这是一个振奋人心的想法，但我们并不总是知道应该追求什么。

[[https://www.centauri-dreams.org/2025/05/06/is-planet-nine-alone-in-the-outer-system/#:~:text=It%20was%20Robert%20Browning%20who%20said%20%E2%80%9CAh%2C%20but%20a%20man%E2%80%99s%20reach%20should%20exceed%20his%20grasp%2C%20or%20what%E2%80%99s%20a%20heaven%20for%3F%E2%80%9D%20A%20rousing%20thought%2C%20but%20we%20don%E2%80%99t%20always%20know%20where%20we%20should%20reach.][Source]]
#+end_quote

** [[http://incompleteideas.net/IncIdeas/KeytoAI.html][Self-Verification, The Key to AI]]

#+begin_details
#+html: <summary>摘录</summary>


#+begin_quote
我声称拥有的见解是， _成功的人工智能的关键在于它能自行判断自己是否正常工作。_

在某种程度上，这是一个务实的问题。

如果人工智能无法自行判断是否正常工作，那么就必须由某个人来做出评估并进行必要的修改。

能够自我评估的人工智能或许能够自行进行修改。

验证原则：

_人工智能系统只有在能够自行验证知识的情况下，才能创造和维护知识。_

[[http://incompleteideas.net/IncIdeas/KeytoAI.html#:~:text=The%20insight%20that,that%20knowledge%20itself.][Source]]
#+end_quote

#+begin_quote
[...]

在所有这些情况下，我们都可以问：该人工智能系统能否验证它自身的知识，还是需要人类介入来检测错误和意外的相互作用，并进行修正？

只要是后者，我们就永远无法构建真正庞大的知识系统。

它们总是脆弱且不可靠，规模也受限于人类自身能够监控和理解的范围。

_「永远不要编写超过你理解能力的程序」_

[[http://incompleteideas.net/IncIdeas/KeytoAI.html#:~:text=Finally%2C%20let%20us,than%20your%20head%22][Source]]
#+end_quote
#+end_details

** [[https://potetm.com/devtalk/stability-by-design.html][Stability by Design]]

#+begin_details
#+html: <summary>摘录</summary>

#+begin_quote
我们为什么总是在不断更改名称？

一旦你注意到这个趋势，就再也无法忽视了。

我们从数据库中取出记录，第一件事是什么？重命名它的字段。

然后我们通过几个转换步骤，这些步骤无一例外地会再次重命名它们。

接着我们以 JSON 格式传输数据，当然，这又要求我们再次重命名它们。

然后我们在单页应用 (SPA, Single-Page Application) 中加载它们，嗯，传输过来的名字显然不行。最好再重命名一次。

这简直是疯狂，但这正是我们创造的世界。

[[https://potetm.com/devtalk/stability-by-design.html#:~:text=Why%20are%20we,world%20we%20created.][Source]]
#+end_quote

#+begin_quote
简而言之，Clojure 生态系统异常稳定，因为我们避免破坏已有功能。

我们不重命名命名空间。

我们不重命名函数。

我们不重命名关键字。

我们既不增加所需的数据，也不减少输出的数据。

如果我们想到更好的做法，我们会创建一个新函数、新命名空间，甚至是一个全新的库。

[[https://potetm.com/devtalk/stability-by-design.html#:~:text=In%20short%2C%20the,whole%20new%20library.][Source]]
#+end_quote
#+end_details

** [[https://www.sung.codes/blog/2017/throwaway-code-dont-recycle-throw-away][Throwaway Code: Don't recycle, throw it away!]]

#+begin_quote
遇到编码问题时，尽可能多练习一次性代码。

你只是学习概念，然后将代码丢弃。

[[https://www.sung.codes/blog/2017/throwaway-code-dont-recycle-throw-away#:~:text=When%20having%20a,throw%20it%20away.][Source]]
#+end_quote

** [[https://will-keleher.com/posts/its-not-worth-the-time-yet.html][XKCD's "Is It Worth the Time?" Considered Harmful]]

#+begin_details
#+html: <summary>摘录</summary>

#+begin_quote
我有时会看到有人引用 XKCD 的 [[https://xkcd.com/1205/][Is It Worth the Time]] 来反对自动化那些手动做更快的事情，而我认为这种想法是错误的。

_自动化简单的事情是培养技能、思维方式和肌肉记忆，从而自动化复杂事情的途径。_

_有些情况下，唯一重要的是任务能快速完成；在这种情况下，手动操作可能更合理！_

_但很多时候，尝试自动化能培养技能和能力，这些在以后会非常有用。_

除了提升个人能力，追求自动化还是构建重视自动化的工程文化的重要部分。

_重视自动化的工程文化会发现减少重复劳动和加快项目进度的机会，而其他工程文化可能会错过。_

我希望拥有一种工程文化，庆祝团队学会自动化某件事的时刻，即使自动化这件事花的时间远超过直接完成它。

能力的积累胜过短期速度的损失。

所以，下次当你想要重写一个只在代码库中使用了三个地方的函数的参数顺序时，不如花时间去研究正则表达式。

下次当你意识到忘记运行某个必要命令时，花费不合理的努力让这个命令自动运行。

下次当你有某件事情只需要每年做一次时，花点时间构建工具来让自己更轻松。
#+end_quote
#+end_details

** [[https://news.harvard.edu/gazette/story/2025/05/when-graphic-design-saves-lives/][When graphic design saves lives]]

#+begin_quote
在海报这个有限的空间里 ⸺ 以及你希望吸引某人注意的有限时间内 ⸺ 设计师需要传达一个简单明了的信息。

文字太多会让人失去兴趣。

「一个好的海报就是一个重点和一种情感：传递者希望你记住的内容，而情感帮助你记住它，」Yarnell 说，他同时也是哈佛 T.H. Chan 公共卫生学院社会与行为科学的讲师。

「最佳情况是，有通向更多信息的途径。过去是电话号码，然后变成了网站，现在可能是 QR code。」

[[https://news.harvard.edu/gazette/story/2025/05/when-graphic-design-saves-lives/#:~:text=In%20the%20small,a%20QR%20code.%E2%80%9D][Source]]
#+end_quote

** [[https://www.marginalia.nu/log/a_119_pdf/][PDF to Text, a challenging problem]]

#+begin_quote
从 PDF 中提取文本信息比看起来要困难得多。

_问题的关键在于，该文件格式根本不是文本格式，而是一种图形格式。_

_它并不像你想象的那样拥有文本，而更像是将字形映射到「纸张」上的坐标。_

这些字形可能被旋转、重叠，并且顺序混乱，几乎没有附带任何语义信息。

_你应该对这样一个事实感到敬畏：你可以在你喜欢的查看器（或浏览器）中打开 PDF 文件，按下 ctrl+f，然后搜索文本。_

[[https://www.marginalia.nu/log/a_119_pdf/#:~:text=Extracting%20text%20information,search%20for%20text.][Source]]
#+end_quote

** [[https://www.nybooks.com/articles/2025/05/29/the-connoisseur-of-desire-the-annotated-great-gatsby/][The Connoisseur of Desire]]

#+begin_quote
这里摘自他的第一部小说 /This Side of Paradise/ (1920) ，是 Amory Blaine ⸺ 一位刚从普林斯顿毕业的「年轻自负者」 ⸺ 与 Rosalind Connage 之间的初吻。

Rosalind 是个拥有「永远令人想吻的嘴唇」的女孩，因某次违规被 Spence 学校开除，但她不记得或不愿意记得那次违规的具体原因：

他：但是你会 ⸺ 吻我吗？还是你害怕？

她：我从不害怕 ⸺ 但你的理由太牵强了。

他：Rosalind，我真的很想吻你。

她：我也是。

（他们吻了 ⸺ 坚定而彻底。）

他：屏息片刻后 ⸺ 那么，你的好奇心满足了吗？

她：你的呢？

他：没有，只是被激起了。

[[https://www.nybooks.com/articles/2025/05/29/the-connoisseur-of-desire-the-annotated-great-gatsby/#:~:text=Here%2C%20from%20his,it%E2%80%99s%20only%20aroused.][Source]]
#+end_quote

** [[https://blog.samaltman.com/the-gentle-singularity][The Gentle Singularity]]

#+begin_quote
我们已经越过了事件视界；起飞已经开始。

人类正接近构建数字超级智能，至少到目前为止，这比看起来应该的要少得多的怪异。

[...]

展望未来，这听起来难以理解。

但经历其中，可能会觉得令人印象深刻但可控。

_从相对论的角度看，奇点是逐步发生的，融合也是缓慢进行的。_

_我们正在攀登指数技术进步的长弧线；向前看总是显得陡峭，回头看却平缓，但它是一条平滑的曲线。_

[[https://blog.samaltman.com/the-gentle-singularity#:~:text=Looking%20forward%2C%20this,actually%20been%20like.)][Source]]
#+end_quote
** [[https://moretothat.com/envy/?][Envy Is the Cancer of the Soul]]

#+begin_quote
这里我们得出嫉妒的第一条规则：

你会嫉妒那些已经达到你期望状态，但又不是太遥远的人。

那些距离太远的人，会成为灵感的来源，而非嫉妒的对象。

[[https://moretothat.com/envy/?#:~:text=And%20here%20we,inspiration%2C%20not%20envy.][Source]]
#+end_quote

#+CAPTION: 在图的最底部有一个表示自己，在他上面扩散出很多其他人，表示别人。按照和自己的距离，分成了三个圈子，第一个圈子距离最近，是蓝色的，表示和自己相似的人；第二个圈子是红色的，表示自己嫉妒的人；第三个圈子是绿色的，表示崇拜的人。 (图片来源：moretothat.com)
https://moretothat.com/wp-content/uploads/2021/03/C05-Inspiration-and-envy.png
** [[https://charity.wtf/2025/06/08/on-how-long-it-takes-to-know-if-a-job-is-right-for-you-or-not][On How Long it Takes to Know if a Job is Right for You or Not]]

#+begin_details
#+html: <summary>摘录</summary>

#+begin_quote
「六个月前我在这家公司担任高级管理职位。

我找这份工作的重点是价值观的契合，从公司使命到领导理念，这里的人在过程中说了所有正确的话。

但就是感觉不到合拍。才六个月，但开始觉得可能行不通了。

我还应该再坚持多久？」

_零。你不应该继续坚持。_

_你已经知道了，而且很早就知道了；情况不会改变。抱歉。 💔_

_我不是说你明天就该辞职，人总得有工资，但你可能应该开始考虑如何处理这个问题并脱身，而不是等着看它是否合适。_

[[https://charity.wtf/2025/06/08/on-how-long-it-takes-to-know-if-a-job-is-right-for-you-or-not/?utm_source=hackernewsletter&utm_medium=email&utm_term=working#:~:text=%E2%80%9CI%20took%20a,a%20good%20fit.][Source]]
#+end_quote

#+begin_quote
每份工作的第一周都是充满焦虑、紧张、自我怀疑以及怀疑周围人的混乱时刻。绝不会是温暖的美好感觉。

但在那些我最终喜欢并长期留下的工作中，焦虑感是「天哪，这些人真酷、真棒、真他妈的有能力，我希望自己能达到他们的期望。」

然后有些工作让我感到的焦虑更像是一种沉重的恐惧感，「天哪，我真希望这只是一次偶发事件，而不是我每天都会遇到的事情。」

[[https://charity.wtf/2025/06/08/on-how-long-it-takes-to-know-if-a-job-is-right-for-you-or-not/?utm_source=hackernewsletter&utm_medium=email&utm_term=working#:~:text=The%20first%20week%20at,will%20encounter%20every%20day.%E2%80%9D][Source]]
#+end_quote

#+begin_quote
公司确实会发生巨大的变化。

但如果没有剧烈的行动 (这可能相当痛苦)，它们往往会沿着当前的轨迹漂移。

[[https://charity.wtf/2025/06/08/on-how-long-it-takes-to-know-if-a-job-is-right-for-you-or-not/?utm_source=hackernewsletter&utm_medium=email&utm_term=working#:~:text=Companies%20can%20and%20do%20change%20dramatically.%20But%20absent%20dramatic%20action%2C%20which%20can%20be%20quite%20painful%2C%20they%20tend%20to%20drift%20along%20their%20current%20trajectory.][Source]]
#+end_quote
#+end_details
** [[https://seths.blog/2025/06/i-made-a-mistake/][“I made a mistake”]]

#+begin_details
#+html: <summary>摘录</summary>

#+begin_quote
_好的决策是基于你当前所掌握的信息进行的计算。_

_如果现实情况与当时的数据指示不同，那并不是一个坏决策。_

_坏决策是不基于可用事实的决策。_

_它陷入了沉没成本或同伴压力等陷阱。_

_坏决策是判断或技能上的错误。_

好的决策者，在面对与你相同的选项时，不会做出你所做的决定。

但好的决策往往可能导致不理想的结果。

乘坐 8:20 的火车是一个好的决定，即使火车发生故障导致你迟到，这仍然是一个好的决定。

买彩票从来都不是一个好的决定。

有时你会中奖，那很好，但根据你买票时掌握的数据，显然有更有利可图的投资方式。

如果你创业了，而一些不太可能发生的事件导致了企业失败，这并不意味着你犯了错误（或做了坏决定）。

明确的是，企业失败了，而你正参与处理这个糟糕的结果。

_言辞很重要。_

_因为我们应该重复我们的正确决定，避免那些本可避免的错误。_

_结果总会发生。_

_但我们只能对我们所知道的（包括概率）做出明智判断，而无法对即将发生的事情做到这一点。_

[[https://seths.blog/2025/06/i-made-a-mistake/#:~:text=Good%20decisions%20are,about%20to%20happen.][Source]]
#+end_quote
#+end_details
* 博客文章推荐

- [[https://justinyan.eth.limo/0B1FC6F7-8936-4F0D-979D-3A1F67FC960B/][最近写的一些短篇]]
- [[https://yinji.org/5541.html][CapWords：写给大朋友和小朋友的英语学习工具]]

* 多媒体
- [[https://www.bilibili.com/video/BV112MyzMEN1][我们去外星球拍了几张照片]] (25:42)
- [[https://www.bilibili.com/video/BV1N5MzzdEMj][9 年后，我终于不再为《爱乐之城》的结局而遗憾]] (10:22)
- [[https://www.bilibili.com/video/BV1fKMBz3EsX][原来这就是 18 岁的她幻想的毕业旅行…]] (14:47) 尼斯，Nice。
- [[https://www.bilibili.com/video/BV1FXMgzTEEX][出国旅行 钱全没了 被陌生女孩救了一命]] (19:00) 好有爱的陌生人。
- [[https://www.bilibili.com/video/BV14KVezWEWx][对话十年前的自己，她问我 iPhone 出到第几代了]] (07:49)
- [[https://www.bilibili.com/video/BV1uJNSzHE8U][【MrBeast首发】25 万美元挑战减肥 90 斤！]] (36:20) 被视频中的教练的故事感动到。
- [[https://www.bilibili.com/video/BV1bcNUzyEuF][卢广仲《才二十三 + 爱爱爱 + 苏丽珍 + 好不容易 + Love Song + 为你写的歌》]] (09:17)
- [[https://www.bilibili.com/video/BV17eKBzKEuZ][我把蔡徐坤请来聊了聊新歌以及...丨HOPICO]] (24:50) [[https://music.163.com/song?id=2708984802][Deadman]] 好听，真让人意想不到。坤在视频里也显得很真诚。
- [[https://www.bilibili.com/video/BV1VqNnzjEdD][没想到你是这样的 Switch 2]] (15:27)
- [[https://www.bilibili.com/video/BV14fKMzqEUT][毕业致谢：从四级没过，到环游世界…关于从未背叛自己的这五年]] (05:32) 人生是荒野，而不是轨道。
- [[https://www.bilibili.com/video/BV11LgkzBE7h][养一只永远不会扫兴的猫是一种什么体验…]] (05:54)
- [[https://www.youtube.com/watch?v=TURkB9zqxa0&ab_channel=JacobCollier][Jacob Collier Improvises the National Symphony Orchestra (Live from the Kennedy Center)]] (18:51) Jacob Collier 和一个交响乐团即兴创造了一首曲子，cool and lovely。

  #+begin_details
  #+html: <summary>评论</summary>

  #+begin_quote
  成为一名杰出的音乐家是一回事。

  站在这样高水平的音乐家面前，面对庞大的观众和 20 台摄像机，同时让你的大脑以一种能够清晰思考、友善有效沟通、明显享受其中的方式运转 ⸺ 并且还能完成创作部分 ⸺ 这才让我感到惊讶。
  #+end_quote

  #+begin_quote
 「哦，是的，我听说过他。他演奏什么乐器？」

 「九十七个人类大脑。」
  #+end_quote
  #+end_details
- [[https://www.ted.com/talks/elizabeth_gilbert_your_elusive_creative_genius?language=en][Elizabeth Gilbert: Your elusive creative genius | TED Talk]] (19:14)

  #+begin_details
  #+html: <summary>摘录</summary>

  #+begin_quote
  _在古希腊和古罗马，人们并不认为创造力来自于人类本身。_

  _人们相信，创造力是一种神圣的守护精灵。_

  _从遥远而不可知的地方来到艺术家身边，带着某种遥远而不可知的目的。_

  希腊人普遍地称这种伴随着创造力的守护精灵为「守护神」。

  当时人们普遍地认为 苏格拉底 就有这样一个守护神，从远处赋予他智慧。

  古罗马人有着相似的观点，他们把这种无形的创造精灵称为「天才」。

  这种观点很妙，因为罗马人并没有认为「天才」是某个特别聪慧的个人。

  他们认为「天才」是某种奇妙的神圣存在。

  他们甚至认为「天才」居住在艺术家工作室的墙壁中，就像小精灵「多比」一样。

  它们会悄悄地钻出来，无形地帮助艺术家创作，并影响作品成败。

  这个观点简直绝了，这就是我在找寻的那个安全距离。

  这就是让人免受作品成败影响的心理保护机制。

  我们都可以理解它的运作模式，不是吗？

  _古代艺术家由这个观点而得到保护，避免了过度自恋。_

  _如果你的作品很伟大，那可不能完全归功于你。_

  因为大家都知道你是在一个无形的「天才」帮助下完成作品的。

  如果你的作品很烂，同样也不全是你的错。

  人人都知道那是因为你的「天才」很差劲。

  这就是西方人在过去很长一段时间里看待创作力的方式。

  _接着文艺复兴来临，一切都变了，人们产生了一个伟大的想法：_

  _「让我们把人类置于宇宙中心，超越众神和神秘未知。」_

  _于是再也没有空间留给传递神圣意志的小精灵。_

  _这就是理性人文主义的开端，人们开始相信创造力完全来源于人类个体本身。_

  _有史以来，人们第一次将某个艺术家称为「天才」，而非拥有一个「天才」。_

  而我要说的是，我认为那是一个巨大的错误。

  _让一个人，区区一个个体 ⸺ 去相信他(她)是承载着神圣、创造、未知和永恒这些事物的源泉与圣器。_

  _无异于要求他(她)吞下太阳，这对于脆弱的个体而言，是太大的责任 。_

  _这彻底地扭曲了一个人的自我认知，并导致对于个人成就无比膨胀的预期。_

  _我认为就是种压力，在过去的 500 年间扼杀了无数艺术家。_
  #+end_quote

  #+begin_quote
  但我想说的是：为何不呢？为什么不换个角度思考呢？

  就各种解释人类变化无常的创作过程的理论而言，这个精灵理论和我听过的所有其他理论一样地合理（或者说一样地无理）。

  这个过程，对于任何一个曾试图创作的人来说，相信在坐各位都曾有这方面的经历，都会知道创作过程并不总是理性的。

  实际上，创作过程有时简直就是超乎常理。

  比方说，我最近见到杰出的美国诗人 Ruth Stone。

  我最近见到杰出的美国诗人 Ruth Stone。

  Ruth 已经九十多岁，她一直是一位诗人。

  她对我说她少年时生活在弗吉尼亚乡间的事情。

  她会在田间劳作着，然后突然听到并感觉到一首诗，从远处冲她而来。

  像一股雷鸣般的气息，朝她倾泻而下。

  她可以感受到它的来临，因为这股力量会撼动她脚下的大地。

  每当此时，她唯一能做的只有一件事，用她的话说，就是「死命地狂奔」。

  她会狂奔回家里，这首诗则会一路追逐着她。

  她需要飞快地找到纸笔，从而在这股力量穿过她时，捕捉住那首诗，把它记在纸上。

  有些时候她则不够快。

  她拼命地跑，还没到家，那首诗已经奔腾而过，于是她便错过了那首诗。

  她说那首诗会继续在田野间穿行，寻找「下一位诗人」。

  在另一些时候，这是最叫我难忘的部分：她说有些时候她几乎就要错过一首诗了。

  她飞奔回家，寻找纸笔。

  而那首诗即将穿越她而去，她在它正要穿过之际抓住了笔。

  然后她会伸出另一只手，抓住那首诗的尾巴。

  把它顺势拉回来，另一只手则一边将诗句誊写在纸上。

  每当这种时候，诗会完好无缺地呈现在纸上，只不过顺序是颠倒的，从最后那个词开始，由后往前，一直到第一个词。

  我听了她的故事后，心想：太不可思议了，这和我的创作过程一模一样！
  #+end_quote

  #+begin_quote
  当然这并非我创作过程的全部，我不是管道，我的工作方式更像是一头骡子。

  我必须每天同一时间起床，然后笨拙地，勤恳地工作。

  不过即使古板如我，偶尔也会意外地得到不可思议的灵感。

  在坐很多人或许也有类似经历。

  你想，即使像我这样墨守成规的人，也会遇到不知何处而来的灵感。

  这到底是怎么回事呢？我们要以怎样的方式看待它，才不会丧失理智呢？

  就我所知的当代艺术家中，将这一问题处理得最好的是音乐家 Tom Waits。

  几年前，我就一个杂志工作采访过他，当时我们谈及了这一问题。

  Tom 是备受创作压力折磨的现代艺术家的典型。

  大半生时间，他都在努力地控制、管理并主宰那不可控的内在创作灵感。

  但随着年纪渐长，他变得沉静内敛了。

  他告诉我说：一天他在洛杉矶高速公路开车，这时发生了一件改变他一生的事情。

  他正在加速前行，突然，他隐约听到了一小段优美的旋律♪♪♫♪♫♪。

  这旋律莫名地进入他的脑海，就像灵感来临时那样，捉摸不定而诱人心弦。

  他急切地想要捕捉它，但是没有办法，他既没有纸笔，也没有录音机。

  他感觉到那种熟悉的创作焦虑又在他体内集聚。

  「我就要失去这个灵感了，然后这首曲子会永世阴魂不散地折磨我」。

  「我根本不行，我做不到」。

  突然，他奇异般地停止了继续抓狂和焦躁情绪，然后做了一件不寻常的事情。

  他抬头望向天空，对它说道：「不好意思，您没看到我正在开车吗？」

  我看上去像是能立马记下一首曲子的样子吗？

  如果你真想在世上流传，另挑个合适的时间再来吧，在我方便的时候。

  或者，你可以今天去骚扰别人，去找 Leonard Cohen 去。

  自从那件事以后，Tom 的整个创作过程改变了。

  不是作品变了，他的作品仍是一如既往的黑暗。

  _但当他把创作天才从自身剥离开来时，伴随着创作过程的严重焦虑也被化解了。_

  _将创作灵感归于自我，只是带来痛苦与麻烦，将它解放出来，倒像是放归原处。_

  _同时他也意识到，他原本无需将创作灵感内化于自身，自我折磨。_

  _创作灵感可以是他和这一外部未知存在之间奇异、奇妙又奇怪的合作关系。_

  那是一个自身以外的存在。
  #+end_quote

  #+begin_quote
  在几个世纪前的北非沙漠里，人们会在月色下举行神圣的歌舞聚会。

  聚会持续数个小时直至天亮。

  那些表演很精彩，因为他们都是很棒的专业舞者。

  偶尔的时候，虽然很少见，但确确实实会发生，某一位舞者会超越当下，超然出世。

  你们应该都知道我说的这种情况，因为大家都曾在某个时刻，见识过那样的表演。

  时间似乎停止了，舞者仿佛穿越了。

  他所做的动作和之前的 1000 场表演并没有什么不同，但所有的一切却奇迹般地统一起来了。

  刹那间，他不再是个普通的凡人，他的生命从内部点燃，从心底发光。

  他被神圣之火照耀。

  当时的人们，清楚地知道这是什么，他们能叫出它的名字。

  他们会拍起手来，开始吟唱：「阿拉，阿拉，阿拉，神啊，神啊，神啊」。

  人人都知道：那是神迹显现。

  有趣的野史是，当摩尔帝国入侵南西班牙时，他们带去了这一习俗。

  于是几世纪来，颂词的发音渐渐改变，从「阿拉，阿拉」变成「欧嘞，欧嘞」。

  如今你仍能在斗牛比赛和弗拉明戈舞中听到这一喝彩声。

  在西班牙，当一个表演者完成了某种不可思议的神奇之举时，人们就会喝彩：「阿拉，欧嘞，欧嘞，阿拉，真伟大，太棒了，不可思议」。

  那就是神迹显现。

  这种方式很好，因为这正是我们需要的。

  对艺术家来说，最棘手的是第二天早上，舞者悠悠转醒。

  发现已经是周二上午11点了，他不再是神迹的显现，而只是那个腰腿不好，终将老去的凡人。

  而且，他或许再也无法达到昨晚那样的高度了。

  也许再也不会有人在他跳舞时喝彩神迹显现。

  他该如何自处呢？

  这是个很棘手的问题，也是创作生涯中最痛苦的自我认知之一。

  但也许，我们原本无需如此痛苦。

  如果你本来就从不曾认为，那无与伦比的艺术作品完全来源于你。

  如果你认为它们是某种神奇的存在，只是暂时借你一用，给你带来精美绝伦的作品，在你完成作品后，继续传递给其他人。

  如果我们这样看待这一问题，一切就都改变了。

  在过去的几个月中，我开始以这种方式看待这一问题，同时从事着我下一本书的写作。

  那本危险的，骇人的，被过度预期的，继我的畅销大作之后的作品。

  而我需要做的，就是不断告诉自己，尤其是在我忧郁焦躁的时候：「不要害怕，不要气馁，只需做好你的那部分工作」。

  _坚守在你的岗位上，无论你的岗位是什么：如果你是舞者，那就跳舞。_

  _如果那个属于你的，神圣却又邪门的精灵决定通过你让神迹显现，哪怕只是短短一瞬，那么，让我们喝彩：欧嘞！_

  _如果没有，那就请继续跳舞，坚守你的岗位，我依然为你喝彩：欧嘞！_

  _我坚信我们必须传授这一理念。_

  _只要你出于热爱与执着，坚守岗位，那你就值得喝彩：欧嘞！_
  #+end_quote
  #+end_details
- [[https://www.bilibili.com/video/BV1iaXXYjEVS][最伟大的动画导演！宫崎骏作品全解读！【电影史话08（上）】]] (1:49:22)
- [[https://www.bilibili.com/video/BV1eFg9zEECR][我们花 4 年，研究了宫崎骏 60 年的职业生涯]] (2:58:42)
- [[https://www.bilibili.com/video/BV17AK2zbEdS][25 年了，还是没人能超越章子怡当年的巅峰成就【美人谱系 09】]] (16:18)

* Music

* Footnotes

[fn:1] 2025 年还真有一个: [[https://felixrieseberg.github.io/clippy/][Clippy Desktop Assistant]]
