#+title: Weekly#38
#+INDEX: weekly!#38
#+date: <2025-06-22 Sun>
#+lastmod: <2025-06-22 Sun 16:57>
#+author: Spike Leung
#+email: l-yanlei@hotmail.com
#+description: "Weekly info collected by Spike Leung"
#+keywords: "Weekly News Code Music"
#+tags: weekly
#+OPTIONS: toc:1 ^:{}
#+LANGUAGE: zh-CN
#+startup: content indent



* News | Article

** [[https://hedgehogreview.com/issues/after-neoliberalism/articles/on-not-carrying-a-camera][不带相机, 培养记忆而非快照]]

看到美丽的景色，在一些有纪念意义的时刻，人们往往会想用相片或视频记录下来。

可是在拍摄的时候，注意力往往都会集中在如何拍摄好这件事情上，而不是去欣赏和感受当下美丽的事物。

那些记录下来的东西，往往记录完就放在一边，或许以后某个时刻会翻到，或许永远都不会再看一次。

与其如此，不如活在当下，活在此刻，让那些美好的时刻留在记忆里，让那一刻的感动刻回忆里，而不是照片里。

#+begin_details
#+html: <summary>摘录</summary>

#+begin_quote
我在家乡 Chapel Hill 不带相机，虽然手机里有相机，但我只用它拍快照。

自然，有些时刻我也希望自己带着相机。

一次黄昏时分，我在邻里散步，感到空气中有一种奇异的能量涌动，突然，不超过二十英尺远处，一只雄伟的白尾鹿跃过花园围栏，飞奔在渐暗的街道上。

即使那一刻正在发生 ⸺ 这出乎意料的超自然时刻 ⸺ 我也试图把它想象成一张照片。

我们就是这样被教导去思考的。

「哦，我真希望我带了相机！」但这意味着我本应准备好捕捉那一刻，而不是被它惊吓。

_然而，被美丽惊艳是一种独特且极为罕见的人类天赋。_

照片是在我从惊讶中回过神来，开始摆弄相机时才出现的。

[[https://hedgehogreview.com/issues/after-neoliberalism/articles/on-not-carrying-a-camera#:~:text=I%20don%E2%80%99t%20carry,with%20my%20camera.][Source]]
#+end_quote

#+begin_quote
接下来的几天里，我一直在思考我儿子的出生。

_我当时就在房间里，但我真的在那里吗，还是躲在了相机后面？_

我希望医生们尽一切必要的努力让我的孩子安全降生，但我也同样希望他们 ⸺ 这同样重要 ⸺ 不要破坏我的照片。

如果出了什么差错，Susan 绝望地环顾房间寻找我，她会看到一个男人把一个黑色的盒子举到眼前。

这个画面象征性地留在了我的脑海中。

这都是很久以前的事了。

那时我正在学习如何使用相机。

和朋友散步时，我会打断一场愉快的谈话去构图。

我控制不住自己。

那时我还没有形成内在的视角，没有自己独特的观察方式，所以一切在视觉上都显得合理。

_我也还没意识到，一场好的谈话 ⸺ 随着时间推移会越来越少 ⸺ 比眼角余光中看到的有趣对称更重要。_

不过，我的朋友们还是容忍了我的「艺术感」，容忍我突然的走神。

_直到我儿子出生，我才开始衡量当我举起相机对准远处拍摄时，自己和朋友之间产生了多远的距离。_

_在我决定不再随身携带相机与朋友相处的那天，这段距离被我消除了。_

_正如我在回顾展上对质疑我的摄影师所说：「我不能同时做两件事。」_

如今，在我们的智能手机世界里，我的摄影注意事项已经过时，而且坦率地说，是不可理解的。

手机中存储的上万张照片是对我在摄影上的漫不经心的极大反驳。

_这些照片 ⸺ 将我们锁定在某些时刻，通常是精心安排的上镜时刻 ⸺ 可能扭曲我们回忆过去的方式。_

_那些照片之外的空白，可能才是记忆最肥沃的土壤。_

[[https://hedgehogreview.com/issues/after-neoliberalism/articles/on-not-carrying-a-camera#:~:text=Over%20the%20next,ground%20of%20memory.][Source]]
#+end_quote
#+end_details


* Tutorial | Resource

* Code Related

* Cool Bit

* Tool | Library

* Emacs

* 一些话 | 摘抄

* 多媒体

* Music
