#+title: Weekly#38
#+INDEX: weekly!#38
#+date: <2025-06-22 Sun>
#+lastmod: <2025-06-22 Sun 16:57>
#+author: Spike Leung
#+email: l-yanlei@hotmail.com
#+description: "Weekly info collected by Spike Leung"
#+keywords: "Weekly News Code Music"
#+tags: weekly
#+OPTIONS: toc:1 ^:{}
#+LANGUAGE: zh-CN
#+startup: content indent



* News | Article

** [[https://hedgehogreview.com/issues/after-neoliberalism/articles/on-not-carrying-a-camera][不带相机, 培养记忆而非快照]]

看到美丽的景色，在一些有纪念意义的时刻，人们往往会想用相片或视频记录下来。

可是在拍摄的时候，注意力往往都会集中在如何拍摄好这件事情上，而不是去欣赏和感受当下美丽的事物。

那些记录下来的东西，往往记录完就放在一边，或许以后某个时刻会翻到，或许永远都不会再看一次。

与其如此，不如活在当下，活在此刻，让那些美好的时刻留在记忆里，让那一刻的感动刻回忆里，而不是照片里。

#+begin_details
#+html: <summary>摘录</summary>

#+begin_quote
我在家乡 Chapel Hill 不带相机，虽然手机里有相机，但我只用它拍快照。

自然，有些时刻我也希望自己带着相机。

一次黄昏时分，我在邻里散步，感到空气中有一种奇异的能量涌动，突然，不超过二十英尺远处，一只雄伟的白尾鹿跃过花园围栏，飞奔在渐暗的街道上。

即使那一刻正在发生 ⸺ 这出乎意料的超自然时刻 ⸺ 我也试图把它想象成一张照片。

我们就是这样被教导去思考的。

「哦，我真希望我带了相机！」但这意味着我本应准备好捕捉那一刻，而不是被它惊吓。

_然而，被美丽惊艳是一种独特且极为罕见的人类天赋。_

照片是在我从惊讶中回过神来，开始摆弄相机时才出现的。

[[https://hedgehogreview.com/issues/after-neoliberalism/articles/on-not-carrying-a-camera#:~:text=I%20don%E2%80%99t%20carry,with%20my%20camera.][Source]]
#+end_quote

#+begin_quote
接下来的几天里，我一直在思考我儿子的出生。

_我当时就在房间里，但我真的在那里吗，还是躲在了相机后面？_

我希望医生们尽一切必要的努力让我的孩子安全降生，但我也同样希望他们 ⸺ 这同样重要 ⸺ 不要破坏我的照片。

如果出了什么差错，Susan 绝望地环顾房间寻找我，她会看到一个男人把一个黑色的盒子举到眼前。

这个画面象征性地留在了我的脑海中。

这都是很久以前的事了。

那时我正在学习如何使用相机。

和朋友散步时，我会打断一场愉快的谈话去构图。

我控制不住自己。

那时我还没有形成内在的视角，没有自己独特的观察方式，所以一切在视觉上都显得合理。

_我也还没意识到，一场好的谈话 ⸺ 随着时间推移会越来越少 ⸺ 比眼角余光中看到的有趣对称更重要。_

不过，我的朋友们还是容忍了我的「艺术感」，容忍我突然的走神。

_直到我儿子出生，我才开始衡量当我举起相机对准远处拍摄时，自己和朋友之间产生了多远的距离。_

_在我决定不再随身携带相机与朋友相处的那天，这段距离被我消除了。_

_正如我在回顾展上对质疑我的摄影师所说：「我不能同时做两件事。」_

如今，在我们的智能手机世界里，我的摄影注意事项已经过时，而且坦率地说，是不可理解的。

手机中存储的上万张照片是对我在摄影上的漫不经心的极大反驳。

_这些照片 ⸺ 将我们锁定在某些时刻，通常是精心安排的上镜时刻 ⸺ 可能扭曲我们回忆过去的方式。_

_那些照片之外的空白，可能才是记忆最肥沃的土壤。_

[[https://hedgehogreview.com/issues/after-neoliberalism/articles/on-not-carrying-a-camera#:~:text=Over%20the%20next,ground%20of%20memory.][Source]]
#+end_quote
#+end_details

** [[https://notashelf.dev/posts/curse-of-knowing][The Curse of Knowing How, or; Fixing Everything]]

作者比喻软件开发就像是西西弗斯推着巨石，软件需要不断地改进，修复，但最终还是会腐化。

如果执着于把软件修复到没有任何问题，那可能就会让自己承担太多的责任，而不堪重负。

要学会放手，学会在什么地方停下来，学会让它们保持破碎。

#+begin_details
#+html: <summary>摘录</summary>

#+begin_quote
_就像加缪笔下的西西弗斯一样，我们注定要推动我们自己系统的巨石上山 ⸺ 一次修复，一次重构，一次脚本。_

_但与西西弗斯的故事不同，诅咒不是由神降加于你的。我们自己建造了这块巨石。而且我们还在上山的路上不断打磨它。_

我已经数不清有多少个项目是以 「是的，我可以做得更好」的变体开始的。

- 一个静态站点生成器，因为现有的生成器有太多的主观意见。
- 一款笔记工具，因为我不喜欢其他工具构建元数据的方式。
- 一款 CLI 任务运行器，因为 Make 晦涩难懂，而 Taskfile 简直是 YAML 地狱。
- 一个用 Rust 写的个人维基引擎，然后用 Go 写，然后用 Nim 写，最后又回到 Markdown。
- 一个家庭实验室仪表盘，因为我不喜欢臃肿的 Web 应用。

这个清单还在继续，相信我，它确实在继续。

我的开发目录目前已经接近 30 GB。

如果你问我，我当时是在解决真实、纯粹的问题。

_但事后看来，我也在滋养着别的东西：一种掌控的欲望。_

我构建的每一个新工具都是我拥有的沙盒：没有奇怪的 bug。

没有遗留的限制。

没有我不完全同意的决定。

_当然，直到我变成了遗留问题。_

[[https://notashelf.dev/posts/curse-of-knowing#:~:text=Like%20Camus%E2%80%99%20Sisyphus,became%20the%20legacy.][Source]]
#+end_quote

#+begin_quote
_软件的问题不会永远解决。_

_你写下的每一个解决方案，从它诞生的那一刻起就开始腐朽。_

_不是现在，也不是以后，而是最终。_

库被废弃。API 发生变化。性能出现回退。

你曾经完美的工具悄无声息地坏掉了，因为 libfoo.so 现在变成了 libfoo.so.2。

[[https://notashelf.dev/posts/curse-of-knowing#:~:text=Software%20doesn%E2%80%99t%20stay%20solved.%20Every%20solution%20you%20write%20starts%20to%20rot%20the%20moment%20it%20exists.%20Not%20now%2C%20not%20later%2C%20but%20eventually.%20Libraries%20deprecate.%20APIs%20change.%20Performance%20regressions%20creep%20in.%20Your%20once%2Dperfect%20tool%20breaks%20silently%20because%20libfoo.so%20is%20now%20libfoo.so.2.%202][Source]]
#+end_quote

#+begin_quote
延续用文学引用充实这篇文章的主题，让我引用斯多葛派的 Marcus Aurelius。

_你对自己的心智能力拥有掌控权 ⸺ 而非外部事件。_

意识到这一点，你将找到力量。

_但编程诱使我们相信我们可以控制外部事件。痛苦也正从这里开始。_

这里发生着更深层次的事情。这不仅仅是关于软件。

我相信有时构建东西是我们自我安慰的方式。

我们编写一个新工具或脚本，是因为我们迫切需要一次小小的胜利。

我们写新工具，是因为感到不堪重负。

重构它，不是因为代码凌乱，而是因为你的生活凌乱。

我们追求完美的系统，因为当一切都在旋转时，它给了我们一个可以抓住的东西。

这是我从使用 NixOS 中得到的教训。

我曾写过整个应用程序，只是为了避免思考自己为何不快乐。

编程给你即时反馈。

你运行程序，它就能工作。

或者不工作，你就修复它。

无论哪种方式，你都在做些什么。

那种能动性令人上瘾。

尤其是当生活的其他方面无法提供这种能动性时。

我们编程是因为我们能编，即使不该编。

因为至少它给了我们一个反抗的对象。

[[https://notashelf.dev/posts/curse-of-knowing#:~:text=On%20the%20theme,to%20rebel%20against.][Source]]
#+end_quote

#+begin_quote
_倦怠不仅仅来自过度工作。它来自过度承担责任。_

而编程，一旦深深内化，就会让一切都感觉像是你的责任。

臃肿的网站。低效的脚本。你工作的笨拙入职流程。

你本可以修复它们。那么，为什么你没有呢？

_你非常清楚的事实是，你无法修复所有问题。_

_你知道这一点，无论你的技能水平如何，你一直都知道。_

但试着告诉你大脑中那个将每一个低效视为道德缺陷的部分这点。

_尼采 (Nietzsche) 警告过不要长时间凝视深渊。_

_但他并未警告当深渊是一段 Makefile 或一个三万行代码的 Typescript 项目时会发生什么。_

[[https://notashelf.dev/posts/curse-of-knowing#:~:text=Burnout%20does%20not,code%20Typescript%20project.][Source]]
#+end_quote

#+begin_quote
那么出口在哪里？

这是否类似于 萨特 Sartre 所描绘的地狱，地狱是他人以及他们与你的软件的互动？

还是某种奇怪的反向地狱，人们创造的软件你不得不去互动？

_第一步是认识到并非所有破损的东西都需要你去修复。_

_不是所有工具都需要更换。_

_并非每次糟糕的经历都需要采取行动。_

有时候，仅仅使用那个东西就足够了。

有时候，知道它为什么坏了 ⸺ 即使你不去修理 ⸺ 也已经足够了。

有时候，你能做的最有纪律的事情就是放下那个你知道如何解决的问题。

这其中蕴含着一种力量。

_不是冷漠，不。也不是懒惰。只是 ⸺ 某种克制。_

[[https://notashelf.dev/posts/curse-of-knowing#:~:text=So%20where%20is,Just%E2%80%A6%20some%20restraint.][Source]]
#+end_quote

#+begin_quote
_你学会了编程。你学会了修理东西。但你将学到的最难的事情是，什么时候该让它们保持破碎。_

_也许这才是最具人性的技能。_

[[https://notashelf.dev/posts/curse-of-knowing#:~:text=You%20learn%20how,skill%20of%20all.][Source]]
#+end_quote
#+end_details

** [[https://pudding.cool/2025/06/hello-stranger/][30 minutes with a stranger]]

作者做了一个研究，找了很多人，他们有不同性别、年龄、学历、人种、政治倾向，让他们进行聊天。

一开始大家都觉得会有不好的体验，但聊到后面发现大多都得到了积极的体验，无论两个人有多大的差异。

结论是，大多数情况下，如果和一个陌生人展开一次对话，往往能得到积极的，友好的体验。

作者还分享了一件在地铁中发生的事，一个男孩摔伤了，一边流血一边哭，但是地铁上没人帮他。

于是作者给他递了纸巾，告诉他用纸巾止血。男孩觉得很震惊。

当作者纸巾用完了，这个时候其他人也开始来帮他，提供了消毒纸巾，绷带等。

等作者下车了，后面也依然有人照顾男孩。

面对一个陌生人需要帮助，有的人可能无动于衷，觉得不是自己的事情，也可能嫌麻烦不想提供帮助。

可是，如果那个需要帮助的人是自己呢？

和陌生人展开一次对话，大多数是积极的；和陌生人产生联系，大概率也是积极的。

或许下次碰到有需要的陌生人事，不用担心那么多，而是去接近他，帮助他。

我想，在一个人人互相帮助的世界里，比在一个人人只顾自己的世界里，会更安心和幸福吧。

BTW，网站交互做得很棒，推荐看看原文。

#+begin_details
#+html: <summary>摘录</summary>

#+begin_quote
社会信任对于我们应对未来一些最大的挑战至关重要：民主的侵蚀、人工智能的出现、地球变暖等等。

在 2021 年的一项研究中，研究人员探讨了社会信任为何在个人层面上下降。

他们发现，收入不满、失业经历以及我们对政治机构信心的下降，是信任减少的主要原因。

简而言之，我们创造了一个对大多数人来说不稳定且充满不确定性的世界。

我也有同感。

世界上发生的大事小事让我感到害怕。

我感觉周围的环境在崩塌，安全感在减弱。

我曾看过一些偏远地区的房子，想着和朋友家人一起隐居在那里 ⸺ 在那里我不必依赖陌生人。
#+end_quote

#+begin_quote
几个月前，我乘地铁去上班时，一个 16 岁的男孩在地铁站台滑倒，嘴巴撞到了地面。

他跌跌撞撞地上了车，站在我旁边。

我戴着耳机，试图说服自己这不是我的事。

然后我眼角瞥见他的下巴裂开了；血和泪水顺着他的脸流下来。

我环顾车厢，想找别人帮忙 ⸺ 也许是和孩子打交道的人。

没人抬头看一眼。

于是我从背包里拿出一些纸巾，转向他，告诉他用纸巾按住下巴。

他当时很震惊。

我试着安慰他，告诉他到学校后去医务室。

_我脑海中唯一的想法是：如果那个人是我呢？谁会帮我？大家会像现在这样围观吗？_

但当我用完纸巾止住这个孩子的流血时，车上的人注意到了，递给我消毒湿巾、纸巾和绷带。

我们成功止住了流血。

当我下车时，另一个陌生人站起来，站在孩子身边。

_当我们受伤时，我们不信任身边的人。_

_我们选择躲避，因为我们认为那是唯一的安全方式。_

_我们让陌生人受苦，因为在这种情绪状态下，每个人都是威胁。_

_这意味着我们很难与他人合作，建设我们想要的世界。_

_我们只能蜷缩起来，等待不可避免的反乌托邦到来。_

_但我不想生活在那样的世界里。我想感到安全。我想帮助别人感到安全。_

_我也希望别人能为我做到同样的事情 ⸺ 无论我是不是陌生人。_
#+end_quote
#+end_details

* Tutorial | Resource
* Code Related
** [[https://blog.damato.design/posts/out-of-order/][Out of order]]

作者讨论了 CSS 控制元素顺序的方法，如 [[https://www.joshwcomeau.com/css/stacking-contexts/][z-index]]，DOM 顺序，堆叠上下文等。

其中有些方法会导致一些副作用，例如 z-index 的竞争，意外的堆叠上下文创建等。

#+begin_quote
总之，当你试图使用 CSS 更新元素顺序时，请停下来考虑这些决定的副作用，并参考这里的一些建议，以帮助保持结构的一致性。
#+end_quote

BTW，这个博客挺有趣的，作者给每篇文章都配了一个封面，封面是那种 [[https://en.wikipedia.org/wiki/O%27Reilly_Media][O'Reilly]] 的风格，乍一看我还以作者出了很多本书 _​(:3 」∠)_

* Cool Bit
** [[https://rms.sexy][Our GNU/Lord and GNU/Savior is 100% sexy!]]

Richard Stallman 的各种工作照，确实很 sexy！也挺酷的，随时随地地工作。

** [[https://p2piano.com][p2piano]]

可以多人在线的
** [[https://radiocast.co/][Radiocast]]

一个为音乐爱好者打造的协作空间。

可以多人在线一起演奏。
** [[https://felixrieseberg.github.io/clippy/][Clippy Desktop Assistant]]

复古造型的 AI 助手，UI 是 1990 年左右的 UI 风格。
* Tool | Library

* Emacs

* 一些话 | 摘抄

** 费曼

#+begin_quote
If you're not having fun, you're not learning. There's a pleasure in finding things out.

如果你玩得不开心，那你就没在学东西。发现新事物本身就是一种乐趣。

⸺ 费曼
#+end_quote

* 博客文章推荐

- [[https://justinyan.eth.limo/0B1FC6F7-8936-4F0D-979D-3A1F67FC960B/][最近写的一些短篇]]

* 多媒体
- [[https://www.bilibili.com/video/BV112MyzMEN1][我们去外星球拍了几张照片]] (25:42)
- [[https://www.bilibili.com/video/BV1N5MzzdEMj][9 年后，我终于不再为《爱乐之城》的结局而遗憾]] (10:22)
- [[https://www.bilibili.com/video/BV1fKMBz3EsX][原来这就是 18 岁的她幻想的毕业旅行…]] (14:47) 尼斯，Nice。
- [[https://www.bilibili.com/video/BV1FXMgzTEEX][出国旅行 钱全没了 被陌生女孩救了一命]] (19:00) 好有爱的陌生人。
- [[https://www.bilibili.com/video/BV14KVezWEWx][对话十年前的自己，她问我 iPhone 出到第几代了]] (07:49)
- [[https://www.bilibili.com/video/BV1uJNSzHE8U][【MrBeast首发】25 万美元挑战减肥 90 斤！]] (36:20) 被视频中的教练的故事感动到。
- [[https://www.bilibili.com/video/BV1bcNUzyEuF][卢广仲《才二十三 + 爱爱爱 + 苏丽珍 + 好不容易 + Love Song + 为你写的歌》]] (09:17)
- [[https://www.bilibili.com/video/BV17eKBzKEuZ][我把蔡徐坤请来聊了聊新歌以及...丨HOPICO]] (24:50) [[https://music.163.com/song?id=2708984802][Deadman]] 好听，真让人意想不到。坤在视频里也显得很真诚。
- [[https://www.bilibili.com/video/BV1VqNnzjEdD][没想到你是这样的 Switch 2]] (15:27)
* Music
