#+title: 亚庇-仙本那一周游
#+INDEX: 亚庇-仙本那一周游
#+date: <2025-08-13 Wed 16:54>
#+lastmod: <2025-08-13 Wed 16:54>
#+author: Spike Leung
#+email: l-yanlei@hotmail.com
#+description: ""
#+tags: blog
#+LANGUAGE: zh-CN

* day1

匆忙收拾了行李，下了点雨，还好出门时又小了。

行李略微超重，15.7kg，想办法匀了一些到身上，但登机的时候并没有称重检查，或许书因为航班的人不多吧。

机场的拉面店吃了碗面，女朋友点的酸菜牛肉面还不错，酸菜牛肉汤的味道够浓郁。

我点了招牌牛肉面，红油版本，比酸菜牛肉贵点，胜在肉多一些。

但是汤感觉很寡淡，像是清汤上滴了一些红油，和我印象中的牛肉面相去甚远。

肉挺大一片，看起来像是叉烧的做法，肉红红的，偏甜口，不太喜欢。

一碗面，最重要的是汤底和面，汤底要足够浓郁，味道能挂在面上；面应该有嚼劲，不坨，更优者，能吃到面香，谷物的香味。

我很喜欢吃日式拉面，原因就在于它的汤底，虽然有些油腻，但味道浓郁。

很久没有坐飞机了，多少有点紧张，脑子里总会想到一些飞机事故，担心会不会出事。

飞机慢慢移动了跑到，停稳之后，突然快速地加速，没多久就飞起来了。有点颠簸，飞机的低鸣催人犯困。

戴上耳机，听着戏子和厨子的《河边的风》，看会儿《我本无意成仙》，困了就睡会儿。

高空上，光线到时很好，kindle 的文字看起来很舒服。

在飞行模式下，网易云无法创建歌单，差评，希望应用能多考虑一下离线使用的场景。

换个歌单，张震岳的跟着感觉走，挺适合旅行听。

飞机快速降落，左边的耳朵开始堵住了，然后痛了起来，不管怎样都恢复不了，持续了很久。

到了机场后上了个洗手间，同一个班次的人都走了，我们自己看指示牌走，看到了星巴克却没看到它边上的离境指示牌，去到了转机的地方被告知怎么走，又再问了个路边的人才搞清楚了方向，总算是出境了。

出境需要拍照和按两个手指的指纹，其他倒是比较顺利。

出来之后先想去 ATM 取了点钱，用的银联卡，虽然有 visa，但是似乎信用卡有更高的一些手续费，或者利息？干脆还是用储蓄卡。取了 500MR，差不多 850 RMB。

看了一些小红书，说会吞卡，还好没发生。要注意的是需要在对应的 APP 打开境外取款的选项。

取钱后先买了水，航空上没有提供饮料，一路下来相当口渴。

之后在 tune talk 办了张电话卡，只有流量，无法打电话，25MR，40G 的流量。

这样总算解决了钱和网络的问题，剩下的一些支付大部分应该可以靠支付宝。

用 grab 打车去酒店，原来在国内无法成功注册 grab，换了电话卡后就成功了，17MR打车到了酒店，在 grab 绑定了支付宝，但司机没用 grab 结账，而是直接让扫码，不过价格是一样的。

去到酒店办理入住，整体还算顺利，只是英语不熟悉，前台说 deposit 没听明白，知道他来了一句押金一百，懂了。等待期间还提供了两杯冰的芒果汁，挺好喝的。

酒店整体还不错，透过窗户能看到日落晚霞。

稍作休息就去吃饭，在 google map 和 grab 翻了翻附近的餐厅，最后是在 google map 上找了一家评分 4.9 的海鲜餐厅，KK Garden Seafood。

走过去不远，但亚庇晚上的灯是那种偏暗的橙色，路上有点黑，开着的店不多，人也不是很多，走在路上还是会有点担心，所幸顺利走到了。

餐厅非常大，露天的，像是农村里摆的酒席一样，非常多的大圆桌，圆桌中间还放了一个舞台，会有一些人演出。

点了帝皇叶，鲜虾，生蚝，米饭还有芒果汁。

生蚝 10 MR 一个，折合人民币大约 17 一个，和国内吃的品种不太一样，肚子没那么肥，裙边更多，所以嚼劲更足，不过调料一般，差强人意。

虾似乎只能按斤点，一斤的虾我们两个人愣是没吃完，剩下了几只。

虾吃着挺新鲜，肉质紧实，做法应该就是炸了一些，撒上了很多细碎的干奶酪，味道吃起来像是咸蛋黄。

最好吃的要素蒜炒帝皇菜，菜又香又脆，味道也很足。芒果汁相当一般，除了冰一无是处，不如酒店给的芒果汁。

吃饭期间舞台也有一些表演，一些鼓点伴奏，几个穿着特色衣服的人在舞动，偶尔吼叫几声，也会邀请观众上去一起跳舞，或者游戏，其中一个拿着长长的吹针吹远处的气球还挺有趣的。吹中了就有欢呼，给参与的食客满满的情绪价值。

饭后找便利店补充一些缺少的物资，google map 一看，便利店不少，但大多快要关门了，也才八点多而已。

找了附近开着的 24 小时的 711，里面远不及深圳的 711，商品的种类不多

。隔壁还有一个本地的超市？叫 99 啥的，东西还更多点。但都没能买到雨伞，驱蚊水，买了些早餐和饮料，换了那双顶脚的拖鞋。

google map 导航去便利店，给的步行路线不对，马路过不去，不容易找到一个人行道，需要按键红绿灯才会变，去的时候按键是好的，回来的那边按键是坏的，宽敞的马路车水马龙，回来横跨马路相当惊险。

* day2

第二天的活动是浮潜，一大早起来吃了点面包和罐装咖啡，七点钟坐上了出发的小巴车去到了码头。

七八点钟，码头上已经不少人了，我们分到了六号船，一船大概有四十来个人，领队是一个叫 snake 小蛇的马来人，也会说中文，随船还有几个小黑，一个船长，几个浮潜教练兼船上的气氛活跃组。

船上要穿厚实的救生衣，非常闷热。船头有一个小的入口，尽管船速比较快，风能贯穿而过，但船内也没有感受到多少风，或许能带走一些热量，但还是有些热。

船开了，小黑们就开始放着动词打次的舞曲，舞动了起来，船上一些 E 人也跟着嗨，隔壁船的小黑也在朝着这边条，黝黑的皮肤，穿着黄色的比基尼，相当妖娆。船上的人也看得开心。虽然我也喜欢热闹，但本身比较拘谨，也无法参与进去，干脆闭眼休息。

偶尔船长还会让船左右侧倾很多，给大家制造一些刺激感。侧倾后，往船尾看，海也倾斜了，仿佛变成了天空。

海很蓝，靠近岸的地方是浅蓝色的，深入一些的海则是深蓝色的，让我想起了表情银行嘿！岛的封面，海水的感觉就和封面挺像的。来到海边，也喜欢听听嘿岛这张专辑。

船开了一个多小时去到了环滩岛，在这里换一下浮潜的衣服，暂作休息。没有什么时间在把岛环绕一下，岛上有洗手间，淋浴，一些休息的亭子，还有便利店，都比较简陋。岛上的沙子是白色的，沙滩整体比较硬，只能踩出很浅的脚印。

换好衣服回到船上，snake 会发放浮潜的设备，浮潜泳镜，呼吸管，和用于呼吸管上的一次性咬嘴，并讲解了如何使用他们。

浮潜泳镜容易起雾，snake 讲了如何解决，一种是啥忘了，只记得他喜欢的方法，吐口水（不是痰）到目镜里用手抹一下就好了，说完他就示范了一下…

呼吸管也可能进水，有三个办法，一个是用力吹出去，一次不行多试几次；一个是浮出水面倒掉，吐掉；而snake最喜欢的方法是直接喝了，不知道真假，不过进水不多倒也不是不行。我第一次浮潜，用的最多的还是第二种。

浮潜点有两个，一个主要看珊瑚，一个主要看鱼群。

先去了看珊瑚，船停泊在浮潜点，会拉一根比较长的安全绳，上面会有一些救生圈，便于一些不会游泳的人可以拉着绳子安全一些。

尽管我不太会游泳，但因为有救生衣，所以倒也不害怕下水，女朋友虽然浮潜过，但本身比较怕水，倒是下去得很犹豫，比较害怕。

下水后凉快了许多，水也不冷。刚开始容易在浮力下仰翻过来，稍微划几下腿就能调整过来，把头埋进海里一看，哇，好漂亮，底下有很多珊瑚，长的有些像卷心菜，白色的，不知道是死了，还是本身就是这个颜色。也有一些鱼，但相对不是很多。

海水本身有推力，就算漂着不动，不一会儿就会漂远，远离了安全绳。因为我不太会游泳，所以还是会有些慌张，埋进去看一阵子，漂一阵子，就要抬起头看看离船有多远，远了就游回去一些。如果真的漂得远，我想应该需要不少力气才能游回来，我大概没有这样的实力。

所幸出发前女朋友在泳池教了我一点蛙泳的技巧，海水浮力也很大，只要不远我还是能游回去的。

因为第一次浮潜，呼吸管还不太会用，游泳也会让呼吸急促，有时嘴里还是会进去一口海水，咸咸的，苦苦的，用力吹不出去，就得浮起来赶紧吐掉，不然呼吸不过来。

下一个浮潜点是看鱼，可以买一些鱼食，就是装在塑料瓶里的面包碎，用的时候灌满水，从瓶底开始挤出来面包，鱼就会过来吃，能聚集不少鱼，就像是在金鱼池子里喂金鱼一样。扎进海里看，感觉就像是扎进了一个布置精美的鱼缸，各种各样的小鱼，有的游得快，有的慢悠悠。

如果水性好，不怕漂远，我挺想就这么漂在海里，直到看厌。

总的来说，浮潜是很有趣的，海底清澈的话能看到很多东西，是一种新奇的体验。

之后回到海岛吃午餐，吃着很一般。饭后洗漱一下，和女朋友在沙滩散散步拍拍照也就回去了，又是一两个小时的路程。

我有高度近视，浮潜没法戴眼镜，就得戴隐形眼镜。这是我第一次戴隐形眼镜，自己还不会戴，是女朋友帮忙的，废了九牛二虎之力才戴上。

隐形眼镜一旦靠近眼睛就忍不住地眨眼，一旦接触眼球还会有异物感，就更抗拒，给女朋友添了不少麻烦，花了十分钟才戴上去。

女朋后买的隐形眼镜是她用过比较好的，我戴上去之后完全没有异物感。戴上后，感觉就和戴上刚配的眼镜一样，很清晰，但又和熟悉的旧眼镜不同，清晰到会觉得有些晃。

很久没试过不戴眼镜也能看清了，有时还会习惯性地推眼镜。

日抛的隐形建议不要佩戴超过八小时，回到酒店后就想先摘下来，摘了半天也摘不下来，女朋友也用手和镊子帮我试过，但我都很害怕弄伤眼睛，我们也看了一些小红书上的技巧，看别人操作很轻巧，比个耶撑开上下眼皮，转动眼睛，眨眼就能脱落，或许是我操作不对，死活不行。

后来先去吃了饭，看到了丁香医生的一篇操作文章，先洗干净手擦干，用左右手的手指掰开眼皮，用食指在隐形眼镜边缘滑动，滑到眼白，眼镜可能也要看向一边，让眼白部分更多，避免伤害到角膜，然后用食指和拇指指腹捏起来。

一直尝试了很多次，总算是取下来了，真担心取不下来损伤眼眼睛。

喜欢隐形眼镜的方便，但不喜欢它的佩戴和摘除，也担心会损伤眼睛，如非必要以后大概不会随便戴，还是有框眼镜舒服。

赶在太阳沉入海底前来到了海边看日落，还挺好看，但不算惊艳，没能看到晚霞将海面染色的画面。和女朋友用富士的一次性胶片机拍了合照，也不知道洗出来会怎么样。

去海滩打车，grab 上那会儿还没绑定支付宝，以为司机那能扫，结果到了要给钱才发现只收现金，尽管我们有，但司机找不开，也没有其他支付手段，他让我们试试找人兑散钱，女朋友去了，想着去酒店里买东西找零，但酒店只能刷卡，回来司机说算了，给他 我们手上的零钱（7MR）就好了，但费用本身是 12 MR，我说不行，下车在在酒店门口碰到了几个马来人，用蹩脚英语说了一下情况，终于换了零钱，付了车费。还问了司机为什么不支持 Alipay，他说要每个月交 50 MR，觉得贵。司机也是挺友好的。

说起来，在 grab 上打的车我觉得都很好，价格是否便宜另说，但车上都挺干净，没有异味，最多有点香薰的味道。司机也不会随便搭话，偶尔我搭话了，他们也都挺友好，可能见我是游客，下车前也会祝我 have a good day。

之后去女朋友在小红书找的饭店吃饭，grill fish，不少本地人在吃，穆斯林也不少。菜单上有很多饮料，但不知道是什么，用蹩脚的英文问点餐的店员，她也很耐心友好的跟我解释，搜索图片告诉我是什么。

来了几天，接触的人当地人不算多，但给我的感觉都是比较友好的。

点了两个菜和一个看起来是饼一样的东西，上菜后发现那个饼原来是一个很大的炸鸡蛋饼。这家店的菜量很大，和东北的菜量有的一比，两个人吃饱了还有一小半。味道 ok，价格也比较实惠。如果来到亚庇这附近推荐一试。

饭后去便利店买了点零食和饮料，我是挺喜欢喝水的，尤其是有味道的水，每到一个新地方，我都想看看有什么没见过的饮料和啤酒，买来试试也是不错的。

身体不好就没买啤酒了，品类也不多，就试了试没见过的罐装咖啡，但味道都差不多，甜不辣鸡的拿铁。

打车回酒店，酒店还提供了健身房和游泳池，去健身房踩单车十公里，出了汗，看了看酒店泳池，是一个露天泳池，看起来比较浅，飘了点小雨，上面空无一人。

* day3

第三天的行程是去红树林看猴子和萤火虫，行程在下午，上午可以睡个懒觉。

前天晚上突然想起都没在这边吃过早餐，想起以前看视频，一些人会专门去当地吃吃早餐。早餐的种类往往也很多，所以何不早起去看看亚庇当地有什么吃。

小红书上找了找大家过来都会去哪里吃早餐，找到一家做烧麦的，一家做汤粉的。

早上闹钟响起，很困实在不想起来，但不起来后面估计也没啥机会去吃早餐了，还是挣扎了起来。

虽然不远，但还是打车去了，横穿马路实在危险。去到烧麦店，点了皮蛋烧麦，腐皮卷，烧麦和一种当地的饮料拉茶，打包带走，因为后面还有粉，现在吃了估计后面就吃不下了，带回去给女朋友当早餐。

拉茶喝了，味道就是淡奶茶的味道，香飘飘奶茶的感觉。又去汤粉店点了粉，叫牛肉叻沙，但吃起来就是沙爹牛肉，汤底是比较浓郁的，是我喜欢的类型。

还点了杯咖啡，这边咖啡有咖啡和咖啡 O，咖啡 O 是不加糖的，不然默认都是加糖，甜不辣鸡。去汤粉店是走路过去的，这边走路还算好走，没有那么多车。

吃完粉就打车回去，又补了会儿觉，吃了打包回来的早餐，但是放了一段时间已经凉了，味道还行，热的时候应该挺好吃。

中午又去早餐的粉店吃了午饭，回来等接送的司机。

一点左右司机来了，是一个华人，还比较健谈，开了一辆小车，除了我们两个，还要再接两个人。

开车大概一个半小时，去到红树林的码头，码头挺好看的，种了很多好看的植物，像是个小花园。

去到先吃了顿下午茶，准备了一些糕点，和饮料，有咖啡和玫瑰饮料，玫瑰饮料粉粉的，味道比较新奇，说不上很好喝。咖啡很热，苦苦的，没有加糖，就和麦当劳的黑咖啡差不多，倒也喜欢。

吃完下午茶，就做船出发，船是两层的，放满了椅子。

红树林分布在河的两岸，河挺宽敞的，能容纳两艘观光船，河水很浑浊，泥黄色的，上面还飘着一些水草和垃圾。

两岸有不少的树，长得很茂密，红树林的根很长，密密麻麻的根伸进河岸扎根。

下午主要行程就是看猴子，一种长鼻猴，船一路行驶，大家两边张望想找到猴子。

偶尔能找到一两只， 找到猴子之后向导要求大家保持安静，不能惊呼，不然会吓跑猴子。

期望中的看猴子是靠的很近，猴子多，能看的很清楚，但实际都距离很远，被很多枝叶挡住了，其实看不太清楚。

不过我对看猴子的兴趣也不是很大，不是非要看到才行。

坐在船上，两边都是红树林，吹着风也很舒服，就这么一路沿河行驶也很好。

可能过去了半个多小时就返航了，沿途也没见到多少猴子。

回去后就差不多吃晚餐了，拿着盘子自己去接菜，味道还行。

晚餐之后再次乘船去渔村（当地人的一个村落）看日落，村落沿着一边河岸分布，通过一些木柱子立在河岸边上，颜色也比较鲜艳，只是因为沿河，看起来有些脏乱，给人一种这里的生活会有些困难的感觉。

日落还不错，甚至还看到了一小截的彩虹，黄昏时分，穆斯林似乎有在日落之后祷告的习惯，远处传来清晰的祷告声，不知道是不是船上有穆斯林，此时船也停着，安安静静地，只有祷告的声音，和黄昏日落还挺搭的，给人一些宁静的感觉。

日落之后就去看萤火虫，此时天也暗了下来，船上有人拿着绿色的灯，模拟雌性萤火虫的发光，吸引雄性的萤火虫（只有雄性的萤火虫才会飞）。

一路行驶，河岸有的树上能看到很多的萤火虫，像是一棵装点后的圣诞树，但萤火虫的光没有那么亮，是一种黄绿色的荧光，拿摄像机都无法拍到。

不同萤火虫的发亮频率不同，有的闪烁的很快，像是在抽风，有的则比较缓慢，有一种呼吸感。

飞起来的萤火虫也是，有的突然闪现，有的则像是水母一样，隔一段时间往前挪动一点。

有的萤火虫从树上飞落，又有点像是落叶的下坠。

萤火虫也不是四处都有，集中在某几个树丛上。

虽然没有夸张到很亮，也是我看过最多的萤火虫了。

实际的萤火虫其实很小，可能就比大米稍微大一点点。

看完了萤火虫也就回到码头了，码头还准备了火花表演，一个人拿着一根绳子一样的火花在甩，转出一个火花圈，黑夜里看起来倒是挺灿烂，不过转了两圈也就结束了。

上个厕所，坐车就回去了。

司机一路上讲了挺多话，还推荐了一家炸鸡店，说是只有沙巴这里才能吃到，比肯德基好吃。开玩笑说离我们住的地方很远，到了指给我们看，其实就在酒店后面。

好奇地点了一些，味道还行，鸡肉比较多汁，（也有柴的），外面的皮相对没有那么厚，要说比肯德基好吃，那倒也算是，但也没有特别惊艳。

第二天要离开亚庇，九点多的飞机去仙本那，飞行时间 50 分钟，回到酒店把行李收拾好，就睡觉了。

* day4

坐飞机
