#+title: 深圳 -> 澳门一日游
#+INDEX: 深圳 -> 澳门一日游
#+date: <2025-02-09 Sun 00:00>
#+lastmod: <2025-02-09 Sun 00:16>
#+author: Spike Leung
#+email: l-yanlei@hotmail.com
#+description: ""
#+tags: blog
#+LANGUAGE: zh-CN

春节假期节后请了两天假，2 月 7 日和 2 月 8 日，想着可以休息一下，不用上四休一再上五这么累。

恰好女朋友也不用上班，就决定出去玩玩，本来计划是去长沙吃吃喝喝，但是看了一下长沙的气温，相当冷，转而找一个近一些的城市玩，最后决定了去澳门和珠海。

* 深圳 -> 澳门

由于行程比较短，我们只带了一些换洗的内衣，洗漱化妆用品，摄影器械，总共两个背包，轻装出行。

从深圳去澳门途径很多，我们选择从深圳的蛇口口岸做邮轮到珠海的横琴口岸，从那里过关。

早起坐地铁去到蛇口，到了邮轮就差不多出发了，邮轮分成二等座和一等座，二等座在一层，一等座在二层，一等座的座位看起来就是宽敞一些。

邮轮的窗户是褐色的，窗外海面反射着早上的阳光，波光粼粼，有点复古梦幻。

邮轮也有乘务人员，和飞机的乘务员很像，服装稍微有差别，邮轮的乘务员穿的是海军大衣，围着红色的围巾，也挺好看的。

我不会晕车晕船，女朋友则不太适应，提前吃了晕车药。

船在海上行驶也比较平稳，没有什么大风大浪，偶尔一两次稍微颠簸一点，还是有挺明显的晃动感，如果频繁的话说不定容易晕船。船行驶的位置离陆地也不是很远，始终能看到陆地，中途经过了珠港澳大桥，大概一个半小时就到达珠海了。

在船上本来想写写 weekly，但是手机没有网络，看了会 Emacs 的文档，看着看着就犯困了。

到达珠海，我们先入住了横琴口岸附近的酒店，整理一些出行的装备，就打车去到横琴口岸准备过海关。

过澳门海关相当快，但我们都忘了提前买流量包，刚过完关，手机流量就断了，糟糕的是我的苹果手机信号还不好，所幸女朋友手机信号好，她买好了流量包给我开热点，我也顺利解决了网络问题。

从横琴口岸出来，有很多免费的巴士可以去热门景点，小红书上称这些巴士为“发财车”，它们是接送游客到酒店和娱乐场（赌场）的。

不过由于女朋友怕晕车，我们选择坐轻轨，横琴线换乘氹仔线去到妈阁，再想办法去到景点附近。

澳门的轻轨不支持乘车码扫码，需要到客服中心购买车票，横琴到妈阁单程是 10 澳币，折合 9 元人民币。

澳门的轻轨和常见的地铁也不一样，它只有两节车厢，看起来比较短，大概只有站台一半左右的长度。车厢比较通透，四面都是玻璃窗，乘坐的人也不多，整体坐起来挺舒适的。

* 澳门

轻轨到达妈阁站，我



* Refs
