#+title:      近期觀影
#+subtitle: 無間道三部曲、醉好的時光、阿波羅 13 號
#+export_file_name: movie-2026-07-22
#+date:       [2026-07-24 Fri 20:00]
#+filetags:   :movie:published:無間道三部曲、醉好的時光、阿波羅13號:
#+identifier: 20260722T222752
#+bind:       denote-directory "~/git/taxodium/posts"
#+description: 近期觀影記录󠄃： 無間道三部曲、醉好的時光、阿波羅 13 號
#+language: zh-CN
#+author: Spike Leung
#+email: l-yanlei@hotmail.com
#+options: ^:{}
#+startup: content hideblocks

*無間道三部曲 (Infernal Affairs)*

Bilibili 上刷到了無間道第一部的片段，就找來看了看，本來只是想重看一遍無間道第一部的，
找資源的時候找到了三部曲，就干脆都看一遍好了。
下載的時候，最想看的第一部迟迟沒下好，就先看了第二部，陰差陽錯地竟然看對了順序。
無間道三部曲，按故事的時間順序排的話，是 [[https://zh.wikipedia.org/wiki/%E7%84%A1%E9%96%93%E9%81%93II][第二部]] ➙ [[https://zh.wikipedia.org/zh-tw/%E7%84%A1%E9%96%93%E9%81%93][第一部]] ➙ [[https://zh.wikipedia.org/wiki/%E7%84%A1%E9%96%93%E9%81%93III%EF%BC%9A%E7%B5%82%E6%A5%B5%E7%84%A1%E9%96%93][第三部]]，其中第一部是最經典也是最好看的。
接下來我會按這個順序簡單講講劇情和感受。

韓琛是一個黑帮小頭目，對黑幫老大倪坤忠心耿耿，也與督察黃志誠相當友好。
但他的妻子 Mary 不甘他屈居倪家之下，就指使手下劉健明去干掉了倪坤，黑帮陷入混亂，
原來的几個黑幫頭目開始蠢蠢欲動，倪坤的次子倪永孝上位，用過人的手段穩住了黑帮，有當新龍頭的架势。

倪坤的私生子陳永仁和倪家關係不好，一心只想當警察，在警校表現优异，但他偽造的家庭背景被查出，被警校革除，
但他仍然一心嚮往能夠擔任警察，於是接受黃志誠督察的特別任務，去黑幫擔任了臥底。
韓琛的手下劉健明也同樣被安排了去警察里當臥底。

倪永孝殺了那几個有反目之心的黑帮頭目，對他忠心的韓琛他也不放過，
最後韓琛和黃志誠達成了合作，解决了倪永孝，而韓琛順势成了最大的黑帮頭目。

以上是第二部，也就是前傳的大致劇情。
里面我覺得演的最好的是扮演倪永孝的吳鎮宇，
而兩個臥底，演陳永仁的余文樂感覺是亳無演技，看著好木訥，
完全看不出來他在警校有多优秀，也看不出來當臥底的機敏，像游离在電影之外；
而演劉健明的陳冠希除了帥也沒啥演技可說。

第二部的劇情會讓我聯想到很多 [[https://zh.wikipedia.org/zh-hant/%E6%95%99%E7%88%B6_(%E9%9B%BB%E5%BD%B1)][教父]] 里的情節：
都是黑老大去世後，儿子接手以凶狠的手段解决了敵人；都有臥底、背叛、炸車的情節。
三部曲中，我覺得第二部不看也不影响無間道要表達的內容。

第一部銜接著第二部的劇情，韓琛成了老大，開始做毒品生意，影片開頭就在講他們在交易，
而警方也在监視他們，準備抓他們個人贜并獲。
陳永仁在韓琛身邊當臥底給警方通風，而劉健明也在警方當臥底給韓琛报信，
在最關鍵的時候劉健明給韓琛附近所有人群發短信「有內鬼，終止交易！」，也是片中的一個名場面。
双方的臥底讓双方的計劃都落空了，双方也都知道了自己手下有內鬼，
接著就開始在內部找內鬼，兩個內鬼之間也在相互試探，嘗試找出對方。
最終兩個內鬼都找到了對方，約在了天台見面，此時韓琛已經死了，
劉健明也沒必要再當臥底，於是他想洗白，做個好人，
但身為警察的陳永仁是不會認同的，他脅持著劉健明，要去揭發他，同時也結束自己多年的臥底生涯。
誰料進入警局的臥底不止一個，另一個臥底過來解决了陳永仁，并希望劉健明以後罩著他，
但劉健明把他也殺了，成功完成了洗白。

第一部里所有角色的演技都很不錯，尤其喜歡飾演陳永仁的梁朝偉。
兩個臥底相互試探的劇情充滿了張力，是很好看的一部。

第三部銜接著第一部的劇情，在第一部里，我想劉健明是希望和陳永仁當朋友的，
兩人都曾經一起在警校訓練，也都很喜歡聴歌，對音響設備有相似的追求，陳永仁的死某種程度上也影響了他。
他向往陳永仁，他臥底的身份和警察的身份開始相互拉扯，
最終人格分裂，把自己当作了陳永仁抓住了身為卧底的劉健明，自己揭發了自己，他嘗試自殺但沒成功，
最後成了殘廢坐在輪椅上一直幻想著自己是陳永仁，一直在分裂的人格中拉扯，墮入了無間道。

第三部觀感一般，因為穿插了不同時間的叙事，加上表現劉健明人格分裂有一些幻想的劇情，
整體看起來會有點亂，劇情的張力也不如第一部。
挺喜歡里面演楊錦榮的黎明，又帥又有演技。

無間道在片頭片尾都引用了一些佛經：

#+begin_quote
《涅槃經》第十九卷：「八大地獄之最，稱為無間地獄，為無間斷遭受大苦之意，故有此名。」

佛曰：「受身無間者永遠不死，壽長乃無間地獄中之大劫。」

「阿者言無，鼻者名間。為無時間，為無空間，為無量受業報之界。」

「無間有三，時無間，空無間，受業無間。犯忤逆罪者永墮此界，盡受終極之無間。」

地藏菩薩本願經卷上：「如是等輩，當墮無間地獄，千萬億劫，以此連綿，求出無期。」
#+end_quote

通過這些經文和電影的劇情，無間道三部曲想講的，
是當一個人背叛了自己，出賣身邊親友，日日活在虛假中時，
就像是墮入了 [[https://zh.wikipedia.org/zh-hant/%E9%98%BF%E9%BC%BB%E5%9C%B0%E7%8D%84][無間地獄]] (也称阿鼻地獄)，一生都在折磨著自己吧。

總的來說，作為犯罪警匪片，無間道三部曲還是不錯的，尤其是第一部。

-----

*[[https://zh.wikipedia.org/zh-hant/%E9%85%92%E7%B2%BE%E8%AE%A1%E5%88%92][醉好的時光]]*

🎵 What A Life - Scarlet Pleasure

這部電影是在李唯的 [[https://blog.wei-lee.me/posts/random-thoughts/2026/07/fun-trivia-and-obscure-concepts/][有趣的小知識或冷門概念]] 里看到的，吸引我去看的是電影里的這段話：

#+begin_quote
人類天生缺乏 0.05% 的血液酒精濃度，
如果將體內酒精濃度持續維持在這個微醺的狀態，
人會更加放鬆、更有靈感，事業和社交等表現都能更好。
#+end_quote

這也讓我想到了 [[https://xkcd.com/323/][一幅關於酒精濃度和編程能力的漫畫]]。

電影的開頭有一句話「青春為何物？南柯一梦罢了。愛情為何物？梦中造物罢了。」
接著是一群高中生在進行一個活動，提著一箱啤酒環湖跑，跑到有長椅的地方要喝一瓶，看誰最先跑完并喝完啤酒，
看著就很青春，如果不是因為年輕身體好，一邊喝大量酒，一邊剧烈運動，說不定會掛掉。
之後鏡頭一轉，聚焦在了四個中年老師身上，他們的教學表現平平，沒什麼激情，和前面青春的學生形成了對比。

主⻆馬丁上課有些不知所云，還被學生投訴了，他有兩個孩子，和妻子也已經沒什麼話題，在他想找妻子聊天時，
妻子也很明顯地在躲避他，總之就是一個看著有些失意無聊的中年男性。

之後馬丁去參加了和另外三個老師的聚會，為其中一位慶祝生日，其中一個人說他看到一個理論，
即「人類天生缺乏 0.05% 的血液酒精濃度，
如果將體內酒精濃度持續維持在這個微醺的狀態，人會更加放鬆、更有靈感，事業和社交等表現都能更好。」
馬丁聴後就想去試試，於是他白天就開始喝酒，并檢測體內的酒精濃度，後來另外三個人知道了也加入了進來，
他們一起制定了計劃，打算來驗証看看這個理論是否成立，他們還會作記录󠄃，看起來就像做严肅的學術研究。

一開始他們都將酒精濃度控制在 0.05%，他們在學校的表現確實更好了，一扫之前的頹態，
馬丁在課堂上更有激情和創意，和妻子的關係也在變好。
他們就想知道如果再提高點酒精濃度會不會更有效呢？
到後面他們還提出了奇點理論，
當酒精濃度超過了某個點說不定會有質變，於是他們四個盡情地喝到了烂醉，
這段喝酒的劇情我還挺喜歡，能感受到他們在釋放自我，在這個過程中他們是享受的，盡興的。

烂醉并沒有帯來更好的改變，其中一個人尿床了，而馬丁則醉倒在路邊，頭撞破了，被儿子拖回了家，丑態百出。
回去後妻子和馬丁談起了他最近的酗酒行為，談話中也揭示了兩人早已無話可說，
而妻子也說出了自己外面有人的秘密，兩人的關係擺在明面上，徹底破裂了。
之後的四人都有些喝酒成癮，難以戒除，事情也被學校發現，其中的体育老師醉酒迟到了，
在會上也是丑態百出，工作也丟了，他似乎也沒有家人，
在一天傍晚，再次喝醉的他，帯著狗一起出航，
不知是失足還是自殺，總之海上的船里就只剩下了他的狗。

馬丁赶走妻子後也後悔了，約了妻子見面想挽回但妻子却不願回頭，他和另外兩位同事安葬了那位體育老師。
之後他們的學生也都順利毕業了，他們三人正好在學生慶祝的碼頭附近的吃飯，
此時馬丁收到了妻子重歸於好的短信，一切似乎在好轉。
吃飯時，他們看到這些充滿朝氣和未來的學生，也參与到慶祝之中，馬丁在其中一邊喝酒，一邊起舞 (這段也很美)，
最後他跃向了大海，影片定格在他跳出去的一刻結束了。

結合影片開頭的那句話，以及影片中經常響起的配樂 Scarlet Pleasure 的 /What A Life/ ，
我想影片想表達的是關於青春和人生激情的。
四個中年男人生活仿佛一坛死水，枯燥乏味，
借由醉酒，他們决定做出一些改變，酒醉後就像青春時一般可以做出許多瘋狂的事，仿佛重新找到了生命的熱度。
但用酒精換來的瘋狂也容易失控，反噬了自己。
喝酒後更好的表現，是他們本來就有能力實現的，并不是酒精帯來的，
酒精只是充當了一個籍口，使他們相信喝了酒之後自己就可以做出改變。
大多數人都會想永葆青春，可誰的青春都會過去，青春的年紀是留不住了，
但青春時那顆熱烈地去活著的心，或許可以保留下來。

出演馬丁的是 [[https://da.wikipedia.org/wiki/Mads_Mikkelsen][Mads Mikkelsen]]，他最出名的角色是 [[https://zh.wikipedia.org/wiki/%E6%B1%89%E5%B0%BC%E6%8B%94_(%E7%94%B5%E8%A7%86%E5%89%A7)][汉尼拔]]，或許不少人都看過。
[[denote:20260309T084611][之前玩死亡擱淺]]，每次 BB 的回憶里都有他，給我的印象是帥和优雅。
我在找資源的時候還找到了一部 [[https://movie.douban.com/subject/37241964/][酒精计划 Pod parou (2025)]]，主要的劇情應該是類似的，但是以女性視角拍攝的。

-----

*[[https://zh.wikipedia.org/wiki/%E9%98%BF%E6%B3%A2%E7%BD%9713%E5%8F%B7_(%E7%94%B5%E5%BD%B1)][阿波羅 13 號]]*

這部電影是在 Hollie 的 [[https://hollie.eilloh.net/posts/this-meme-cant-be-done][This meme can’t be done]] 看到的：

#+begin_quote
Greg 說現在流行一個迷因，你要選出你 21 歲那年最棒的電影，對我來說那是 1995 年。
他把筆電遞給我，瀏覽器視窗停在 1995 年電影的維基百科頁面。

我：《阿波羅 13 號》。簡單。就在前十名裡。毫無疑問。搞定。就這樣。

[[https://hollie.eilloh.net/posts/this-meme-cant-be-done#:~:text=Greg,it][Source]]
#+end_quote

於是我就找來看了看，電影是基於 [[https://zh.wikipedia.org/wiki/%E9%98%BF%E6%B3%A2%E7%BE%8513%E8%99%9F][真實事件]] 改編的，
講述的是阿波羅 13 號計劃登月，但中途出現了意外，登月計劃只能取消，連宇航員們是否能回地球都是問題，
地面中心和宇航員們最終克服了種種困難，最終安全返航。
因為是基於真實事件改編，那些困難以及解决方法都看起來很合理，[[https://zh.wikipedia.org/zh-hans/%E7%81%AB%E6%98%9F%E6%95%91%E6%8F%B4][火星救援]] 也是類似題材的電影，
但困難和解决看起來就有點科幻。
電影其實沒多少太空的場景，大多都是飛船里的畫面，但依然很好地营造出了太空的氛圍。
電影的主角是飾演過 [[https://zh.wikipedia.org/wiki/%E9%98%BF%E7%94%98%E6%AD%A3%E4%BC%A0][阿甘正传]] 的 [[https://en.wikipedia.org/wiki/Tom_Hanks][Tom Hanks]]，阿甘正传里飾演丹中尉的 [[https://en.wikipedia.org/wiki/Gary_Sinise][Gary Sinise]] 也有出演，
而地面指揮中心的負責人則是在 [[https://zh.wikipedia.org/wiki/%E6%A5%9A%E9%97%A8%E7%9A%84%E4%B8%96%E7%95%8C][楚門的世界]] 里飾演导演的 [[https://en.wikipedia.org/wiki/Ed_Harris][Ed Harris]]，也是看到了很多熟悉的面孔。
電影的前期會有些慢熱，後面就越來越吸引人，總的來說是一部很不錯的太空救援電影，推薦一看。
