#+title:      Blaugust 2025 Reflections #2
#+export_file_name: blaugust-2025-reflections-2
#+date:       [2025-09-20 Sat 13:17]
#+filetags:   :blaugust:published:reflection:
#+identifier: 20250920T131718
#+bind:       denote-directory "~/git/taxodium/posts"
#+description: 分享一些从 Blaugust 2025 看到的文章，以及自己的感受
#+language: zh-CN
#+author: Spike Leung
#+email: l-yanlei@hotmail.com
#+options: ^:{} toc:nil
#+startup: content

🎵 Dirty Work - Steely Dan

Blaugust 早就结束了，但是之前订阅了很多 feed，还没怎么看，一直堆在哪里，有两千多条。
打算整理一下 Blaugust 的 feed，移除一些不感兴趣的，有趣的就分享一下。

feed 实在是太多了，可能会分几次分享出来。

或许你可以把它当作是 [[https://www.raptitude.com/2025/06/how-to-surf-the-web-in-2025-and-why-you-should/][网上冲浪]] 的一个起点，去探索自己感兴趣的内容。

* [[https://anerdyfujocries.wordpress.com/2025/08/11/i-got-some-new-travel-oshi/][I got some new travel oshi! | A Nerdy Fujo Cries]]
:PROPERTIES:
:CUSTOM_ID: 89726B04-8D9A-4375-9BFF-2B1C991D70E4
:END:

作者买了一些动漫形象的亚克力立牌和相框，
以前我不知道这些东西有什么用，但看到作者拿着它们拍照，我突然觉得这些物件还挺有趣。

* [[https://amf.didiermary.fr/][African Music Forum]]
:PROPERTIES:
:CUSTOM_ID: 6E0867CB-8C8F-4E88-A2B3-27F3C27456CC
:END:

一个分享非洲音乐的博客，更新还挺频繁的。

* [[https://anarchaeopteryx.bearblog.dev/][An Archaeopteryx]]
:PROPERTIES:
:CUSTOM_ID: 1D9F63E6-94DD-47CC-A986-9BBB00959478
:END:

这个博客的内容我蛮喜欢的，主要还是和生活有关。

喜欢看作者对博客的调整：[[https://anarchaeopteryx.bearblog.dev/blog/?q=bearblog][#bearblog]]，看到好的设计就可以抄一下。

#+begin_quote
我的许多室友癖好之一是，当人们把一些东西放进冰箱「留待以后」时，我们都知道这些东西永远不会被吃掉。
一个汉堡面包，两片不新鲜的面包，一根发黑的香蕉 ⸺ 请直接扔进堆肥箱。
_我知道人们这样做是因为他们真心想利用这些边角料，但你总得在人生的某个阶段有点自知之明吧。_
你上次做香蕉面包是什么时候？特别是如果你是那种「眼不见心不烦」的人。
_我知道人们这样做也是因为他们对食物浪费感到内疚，但我恐怕最终这些东西都会被扔进垃圾桶，_
_而且在此期间你还在浪费能源来冷冻这些东西！_
_这还没算上它占据了本可以存放那些会很快被吃掉的食物的空间的机会成本。_
如果你对冰箱里的所有东西都有计划，并且有执行这些计划的记录，那很好，但这番话是说给其他人听的。
请为我清理一下你的冰箱，扔掉任何超过一年的东西。特别是那些边角料。

[[https://anarchaeopteryx.bearblog.dev/2025-08-11/#:~:text=One%20of%20my,especially%20the%20scraps.][2025-08-11 | An Archaeopteryx]]
#+end_quote

说的可太对了，有时做饭多了，不想浪费也丢到冰箱里，结果可能会放好一阵子，也不想吃，最后还是扔掉。

还是有点自知之明吧，不想吃就扔了，确实是浪费，放久了再扔不也是浪费，只是让自己觉得不那么内疚罢了。

* [[https://jeddacp.me/][august morning.]]
:PROPERTIES:
:CUSTOM_ID: 7873B246-491F-4EE7-B41C-0CA47BE5DA8F
:END:

看了几篇博客文章，主要是一些图片，搭配几句简短的话。图片色彩我喜欢。

+ [[https://jeddacp.me/the-center-of-attention/][The Center of Attention]]
+ [[https://jeddacp.me/the-red-staircase/][The Red Staircase]]
+ [[https://jeddacp.me/reds-java-house/][Red's Java House]]

* [[https://axxuy.xyz/blog/][Axxuy]]
:PROPERTIES:
:CUSTOM_ID: EAD5A1BC-9E7C-4418-869B-125049C6D6D8
:END:

在这个博客看到了很多 [[https://axxuy.xyz/blog/posts/2025/soyouwantatypewriter/][打字机]]，还有一些有趣的东西[fn:1]，大概这就是网上冲浪的乐趣吧。
(可恶，我还在看 A 开头的 feed，还有好多没看= =)

+ [[https://axxuy.xyz/blog/posts/2025/therightfit/][The Right Fit]]

  用打字机写东西，有点复古呀。
  打字机是 Olivetti Lettera 32，Emacs 里有一个模式叫 [[https://github.com/rnkn/olivetti][olivetti-mode]]，名字可能就是来源于打字机吧。

+ [[https://axxuy.xyz/blog/posts/2025/ishouldmention/][I Should Mention]]

  文章提到了 [[https://www.w3.org/TR/webmention/][Webmention]]，我在 [[denote:20250731T161050][移除博客的留言]] 也提到过。
  简单来说，它是一种协议，用于网站之间在互相链接时互相通知，
  它也允许你写一篇博文来回应别人的帖子，并让它自动显示为他们帖子上的评论之类的东西。

  写一篇博文来回应别人的文章，似乎成本有高，但正因如此，回复的质量可能更高吧。

  不过我觉得搭建起来有点麻烦，目前还没有接入。

+ [[https://axxuy.xyz/blog/posts/2023/bench/][Other People Have Loved This Too]]

  #+begin_quote
  我家附近有个公园，一条运河从中穿过。
  最近我偶然走到公园里一个不常去的角落，那里运河拐了个弯，眼前豁然开朗，可以一直望到运河尽头和周围的景色。

  我最初的想法是，这景色真美。
  但当我发现那里有一张正对着美景的长椅时，我感到由衷的喜悦。
  这表明也有其他人认为这景色很美。
  对我来说，那种连接感和共同的欣赏之情，比景色本身给我留下了更深刻的印象。

  如果你用心留意，这世上总有美好的事物。
  #+end_quote

+ [[https://axxuy.xyz/blog/posts/2025/shortposts/][Short Posts Are Great]]

  我也喜欢篇幅比较短的博文，阅读起来比较轻松。

* [[https://clandestini.org/][Clandestini]]
:PROPERTIES:
:CUSTOM_ID: 2E5EE34C-9A73-4913-B7C4-95F816BAEAB8
:END:

博客蛮好看的，作者是葡萄牙人，从文章标题我不太能知道文章是讲什么的，只能打开后翻译看。

从博客文章里抄了个东西 ⸺ 在文章开头放一首推荐的歌，就只是一行文字，
如果读者感兴趣自然会自己搜索来听，不感兴趣也不影响，就是一行文字。

* [[https://dirchansky.com/freetalk/][Dirchansky Freetalk]]
:PROPERTIES:
:CUSTOM_ID: 6F6B2092-E95B-4755-97FB-F9E1E5BF442D
:END:

作者是一名故事讲述者和漫画创作者，他关于 Blaugust 的文章还挺充实的，大多数也是关于生活的。

从作者的文章里看到一篇 [[https://kedara.eu/organising-feeds-permaculture][Organising my feeds using Permaculture principles | Kedara]]，
大概是按照访问频率和喜欢程度对 feed 分类，或许后面整理 feed 的时候可以参考一下。

* [[https://divergentrays.com/][Divergent Rays]]
:PROPERTIES:
:CUSTOM_ID: 948C7A1A-A9FB-47AD-8356-ED2DCF99530B
:END:

作者每周会写一篇总结，分享一些链接、自己的生活、阅读和观看的内容。

在 [[https://divergentrays.com/blog/posts/2025-08-03-Weekly-Wrap-Up-69][Weekly Wrap Up 69]] 里看到了 [[https://www.phallus.is/][冰岛阳具博物馆]]，还挺有趣的。

* [[https://rscottjones.com/getting-some-good-out-of-a-bad-situation/][Getting some good out of a bad situation | rscottjones]]
:PROPERTIES:
:CUSTOM_ID: 00D8AE1D-99AE-4E03-809E-81C5AFC1652B
:END:

#+begin_quote
我真的很喜欢 Robert Birming 这篇关于 [[https://birming.com/2025/09/13/from-problem-to-perk/][将问题转化为优势]] 的短文。
我发现这个想法 ⸺ 将消极转化为积极 ⸺ 是极好的人生建议。
也就是说，它确实是你对待生活最好的方式之一。

[[https://rscottjones.com/getting-some-good-out-of-a-bad-situation/#:~:text=I%20really%20love%20this%20short%20post%20by%20Robert%20Birming%20about%20turning%20a%20problem%20into%20a%20perk.%20I%E2%80%99ve%20found%20that%20idea%E2%80%94turning%20negatives%20into%20positives%E2%80%94to%20be%20excellent%20life%20advice.%20As%20in%2C%20literally%20one%20of%20the%20very%20best%20ways%20you%20can%20approach%20life.][Source]]
#+end_quote

事已至此，不如看开点，或许能开心些。只要你愿意，[[https://www.xiaoyuzhoufm.com/episode/67d58fe25b7593e1dd99c18b#ts=640?s=eyJ1IjogIjYwNWI0MDkyZTBmNWU3MjNiYmYxMmI2ZiJ9][每天都可以是好天气]]。

* [[https://talk.jackalope.city/][jackalope.city]]
:PROPERTIES:
:CUSTOM_ID: 14104C19-285E-4447-B568-7D94AB0B3ED2
:END:

作者在标题上使用 Emoji，区分文章的类型，我觉得想法不错，在 feed 中可以轻松区分哪些是阅读、游戏。

我不太喜欢文章里太多 Emoji，它们太抢眼了，而且有的软件可能渲染 Emoji 有问题，
像我之前在 WSL(Windows Subsystem for Linux) 上用 Emacs，有的 Emoji 会导致 Emacs 渲染异常，删除它们也很困难。

* [[https://www.jayeless.net/][Jayeless.net]]
:PROPERTIES:
:CUSTOM_ID: E72AB8DD-3363-4972-96FD-ACD62337351D
:END:

一个内容很丰富的数字花园。

* [[https://joelchrono.xyz][Joelchrono's Blog]]
:PROPERTIES:
:CUSTOM_ID: 01B1F2C0-9DA8-44D9-8C72-834B0D504DE0
:END:

看了几篇关于 88x31 按钮的文章，蛮有趣的。

- [[https://joelchrono.xyz/blog/more-88x31-buttons][More 88x31 buttons]]

我也收集了一些：[[denote:20250920T123626][88x31 buttons]] (≖ᴗ≖๑)

* Footnotes
:PROPERTIES:
:CUSTOM_ID: E943019F-0387-4B5B-A980-90BA26DBCEEA
:END:

[fn:1] [[https://www.sbnation.com/a/17776-football/chapter-1][17776-football]]
