#+title:      读《悉达多》
#+subtitle: 一首印度的诗
#+export_file_name: siddhartha
#+date:       [2025-11-21 Fri 09:35]
#+filetags:   :201701:hermannhesse:book:published:姜已:德国:赫尔曼黑塞:
#+identifier: 20251121T093529
#+bind:       denote-directory "~/git/taxodium/posts"
#+description: 《悉达多》读后感及摘录
#+language: zh-CN
#+author: Spike Leung
#+email: l-yanlei@hotmail.com
#+options: ^:{}
#+startup: content

[[https://book.douban.com/subject/26980487/][《悉达多》]] 这本书的篇幅不长，坐在高铁上，两三个小时就看完了。
我觉得它和 [[https://book.douban.com/subject/3693974/][《小王子》]] 有点像，差不多的篇幅，都是讲述主角一开始对某些事情感到困惑，
在经历了许多之后，变得释然。
之前还看过黑塞的另一本书 [[https://book.douban.com/subject/4908883/][《荒原狼》]]，某种程度上，我觉得和《悉达多》的主题也是类似的，
都是主角在寻找自我，接纳自我，寻找内心的安宁的过程。
《悉达多》的副标题是「一首印度的诗」，
确实如此，黑塞的文笔、姜乙的翻译让整本书阅读起来有一种诗歌的美感。

-----

悉达多是婆罗门之子，婆罗门是印度的最高种性，他本身就不是一个普通的人。
他长得俊美，人见人爱，谁都喜欢他。
他从小接受婆罗门的教导，掌握了很多知识，在别人眼中，他会成为伟大的贤士、僧侣、婆罗门中的王。

但是悉达多的心中并不安宁，掌握了这么多的知识、前人的智慧，
他依然不明白自己到底是谁、活着的意义是什么，他内心感到非常困惑。

此时，他碰到了几个 [[https://zh.wikipedia.org/zh-hans/%E6%B2%99%E9%96%80][沙门]]，他们是苦行者，
「一种由无声的激情、不顾一切去献身、无情的肉体灭绝构成的灼热气息回旋在在他们周身」。
或许是被沙门的这种气质吸引，觉得可以从他们身上寻找到答案，悉达多决定投身沙门。

投身沙门，意味着他要舍弃婆罗门的地位，他的父亲本来盼望他成为新的婆罗门之王，必然不想让他离开。
但是悉达多去意已决，他一直站着，从白天站到黎明，站到脸色苍白、摇摇欲坠，
最终他的父亲虽然愤怒、不舍，但不忍心看着悉达多受苦，也明白无法留住他，只能选择放手让他去。
临别前，父亲嘱咐他，如果寻到正果就回来与他分享，叫他修习；如果收获幻灭，也要回来，再一起祭奉诸神。
尽管万般不舍，作为一个父亲，还是希望儿子最后能回来。

悉达多成为沙门，算是抛弃了整个家族，没有了牵挂、没有了家庭的束缚，一心一意地寻找自己的道。
他的好基友乔文达也追随了他。

#+begin_details
#+html: <summary>悉达多临行前和父亲的对话</summary>

#+attr_html: :class indent-paragraph
#+begin_quote
“哦，悉达多！”他喊道，“你父亲会允许吗？”
悉达多望向乔文达，觉醒的眼光迅捷如箭般看穿乔文达的心思、他的恐惧和他的默许。

“哦，乔文达，”他轻声道，“我们不必浪费口舌。明日破晓，我即开始沙门的生活。无须再谈论了。”

悉达多走进屋舍时，父亲正坐在树皮编织的席子上。
悉达多站在父亲身后，直至父亲有所察觉。
“是你吗？悉达多。”这位婆罗门道，“说吧，你为何事而来。”

“您允许的话，我的父亲。”悉达多道，
“我来，是为跟您说，我恳请明天离开您的家，加入苦行者的行列。我渴望成为一名沙门。希望您不会阻挠。”

婆罗门沉默良久。星星攀上窗际时，屋内仍寂静无声。
儿子交叉双臂纹丝不动地站着，一言不发。
父亲也纹丝不动，一言不发地坐在席子上。
唯有星斗在空中挪移。
这时，父亲道：“婆罗门不该有激烈恼怒的言辞，但我心中确有不快。从你口中，我不想再听到这一请求。”

婆罗门说毕，缓慢起身。悉达多依旧交叉双臂，纹丝未动。

“你还在等什么？”父亲问。

“这您知道。”悉达多答。

父亲气愤地走出房间，气愤地走去他的床铺躺下身来。

一小时后，无眠的婆罗门起身。
他来回踱步，继而走出房间。
透过窗子，他看见双臂交叉，纹丝未动，依旧伫立着 的悉达多。他浅色的衣衫发着微光。
父亲心生不安，又踱回房间。

又一小时后，无眠的婆罗门再次起身。
他来回踱步，继而走出房间。
月亮当空高悬。
透过窗子，他看见依旧伫立的悉达多，双臂交叉，纹丝未动。
月华照亮他裸露的脚踝。父亲心生忧虑，又踱回房间。

一小时后，两小时后，他不断起身。
透过窗子，他瞭望月光中、星光中、黑暗中的悉达多。
他默默地一次次起身，望向窗外纹丝不动伫立着的儿子。
心中充满恼怒和不安，恐惧和痛苦。

破晓前的最后一小时。他走出房间，看见伫立于眼前的少年高大而陌生。

“悉达多。”他道，“你还在等什么？”

“您知道。”

“你打算一直这样站着等待，直至天明，直至正午，直至夜晚吗？”

“我会站着等待。”

“你会疲惫的，悉达多。”

“我会疲惫。”

“你会睡着的，悉达多。”

“我不会睡着。”

“你会死去的，悉达多。”

“我会死去。”

“你宁愿死去，也不愿服从你的父亲吗？”

“悉达多一向服从他的父亲。”

“那你会放弃你的打算吗？”

“悉达多会做他父亲要求的事情。”

第一缕晨光照进屋舍。
婆罗门看见悉达多的双膝轻微战栗。但他的脸没有战栗。
他的目光专注于远方。
父亲意识到，悉达多已不在他身边。
他已离开家乡，离开他。

父亲抚摩悉达多的肩膀。

“你即将步入林中成为一名沙门。”
他道，“如果在林中，你寻得至高无上的幸福，就回来教我修习。
如果你只收获幻灭，那也回来，我们再一道祭奉诸神。
现在，去和你的母亲吻别，告诉她你的去向。至于我，清晨沐浴的时辰已到，我要去河边了。”

他把手从儿子肩头抽回，走出门去。
悉达多试图移步时身体打了个踉跄。
他控制身体，向父亲鞠躬后，走向母亲，去做父亲吩咐的事。
#+end_quote
#+end_details

成为了门沙，他先是开始斋戒，他每日只进食一次，然后斋戒了十五日、斋戒了二十八日，日渐消瘦。

人活着，不过是吃喝拉撒，对悉达多来说，他可以忍受长达二十八日的斋戒，吃对他来说是很容易解决的事情，
有得吃他就吃点，没得吃他就也可以斋戒度过。
最基本的需要解决了，他也没有家庭的束缚，他其实是非常自在的，可以无拘无束地去思考一切。

这个时候的他，忍受了极其艰苦的斋戒，食欲都能克服的他，对一切都感到不屑。
世界四处都是欲望，他觉得 「一切都是欺骗，都散发着恶臭，谎言的恶臭。
一切欲望、幸福和优美皆为虚幻。一切都在腐朽。
世界是苦涩的。生活即是折磨。」，他此刻唯一的目的就是堕入空无。

沙门讲究苦行、禁欲，悉达多从沙门中学会了诸多克己的方法，但这种禁欲的修行也没有让他感到安宁，
他觉得这不过是另一种逃避，一种对自己的麻醉，徒劳的努力。
那些沙门长老六七十了也没有证道、涅槃，他仿佛看到了沙门的尽头，他觉得继续修习也不过如此。

#+begin_details
#+html: <summary>悉达多和乔文达关于沙门修行的对话</summary>

#+attr_html: :class indent-paragraph
#+begin_quote
达多从沙门处学到很多。他学会诸多克己之方法。
他通过受苦，志愿受苦和战胜疼痛、饥饿、焦渴和疲惫，走向克己。
他通过禅定，通过在一切表象前心神凝定走向克己。
他学会诸多修炼之道。他曾千百次摆脱“我”。
_他曾整时整日停驻在无“我”中。这些修行均从“我”出发，终点却总是回归于“我”。_
尽管悉达多千百次弃绝“我”，逗留在虚无中，化为动物、石头，回归却不可避免。重归于“我”无法摆脱。
在阳光中、月华下，在遮荫处和雨中，他重新成为“我”，成为悉达多，重新忍受轮回赋予的折磨。

乔文达，他的影子，和他生活在一起，也走了同样的路，付出同样的艰辛。
他们在修习和献祭时鲜有交流。偶尔，两人得以同去村落为自己和师父们乞食。

“你怎么看，乔文达？”在一次乞食途中，悉达多问“你认为我们有进步吗？我们实现了目标吗?”

乔文达答：“我们学了不少。我们依然在学。
你将成为伟大的沙门，悉达多。
沙门长老常常赞叹，你学什么都快。
你将成为圣人，哦，悉达多。”

悉达多道：“我并不这么看，我的朋友。
至今我在沙门处学到的东西，乔文达，我本可以更快更便捷地学到。
在花街柳巷的酒馆里，我的朋友，在脚夫和赌徒处，我都能学到。”

乔文达道：“悉达多你是在和我说笑。
你怎么可能在那些贫乏者中学会禅定，学会屏息敛气，学会忍受饥饿和痛苦？”

悉达多轻声道，仿佛自言自语：
_“禅定是什么？什么是脱离肉体？斋戒是什么？什么是屏息敛气？_
_那不过是逃避‘我’，是暂时从‘我’的折磨中逃出来，是对生命的虚无和痛苦的暂时麻醉。_
这种逃避、麻醉，即便是驱牛者也能在客栈中找到。
他只消喝上几杯米酒或发酵的椰子奶就能忘掉自己。
他将感受不到生活的痛苦，他被暂时麻醉，在米酒的杯盏间昏沉入睡。
他同样能获得悉达多和乔文达通过长久修习才获得的弃绝肉体与停留在无‘我’中的感受。
就是这样，乔文达。”

乔文达道：“你这样说，哦，朋友，你当然知道，悉达多不是驱牛车夫，沙门也不是酒鬼。
酗酒者可以被麻醉，他可以获得短暂的逃避和休憩，但当他从幻觉中醒来时会发现一切依旧。
他没有成为智者，没有积累知识，也没有进入更高的境界。”

悉达多含笑道：“我不知道。我从不是酒鬼。
_但是我，悉达多，在修习和禅定中只收获短暂的麻醉。_
我仍似一个在子宫内的婴孩，距离开悟、解脱十分遥远。
这我知道。乔文达，这我知道。”

另一次，悉达多和乔文达一同走出森林，去村落为兄长和师父乞食。
悉达多开口道：“那么，乔文达，我们走对了路吗？我们离知识近了吗?离解脱近了吗?
抑或我们不过是在原地打转——我们原本不是要摆脱轮回吗？”

乔文达道：“我们学了很多，悉达多。许多还需修习。
我们没有打转，我们在攀登，打转如同陀螺，我们却已升了几级台阶。”

悉达多问：“你认为我们景仰的师父，那位沙门长老多大年纪？”

乔文达答：“我猜他六十岁。”

悉达多道：“
_他已六十岁，依然没有证悟涅槃。_
_他将七十岁，八十岁；_
_你和我，我们也同样会变老，也将继续修习、斋戒、冥想。_
_但我们不会证悟涅槃。他不会，我们也不会。_
_哦，乔文达，我想，可能所有沙门都无法证悟涅槃。_
_我们只寻得安慰、麻醉，我们只学了些迷惑自己的把戏。我们根本没有找到那条道中之道。”_

“别这么说。”乔文达道，“不要耸人听闻，悉达多！
这众多热忱、勤奋、圣洁的智者，婆罗门，众多严谨可敬的沙门，众多孜孜以求者，难道都寻不到那道中之道吗？”

悉达多的声音饱含悲痛和嘲讽。
他饱含悲痛和嘲讽地轻声道：“
不久，乔文达，你的朋友将离开这条与你并肩走过的沙门之路。
我忍受焦渴，哦，乔文达，在这条路上，我的焦渴没有获得丝毫缓解。
我一直渴慕知识，充满疑惑。
年复一年，我求教婆罗门，求教神圣的吠陀。
年复一年，我求教虔诚的沙门。
年复一年。
或许，乔文达，或许我去求教 犀鸟或黑猩猩也同样受益，同样获得才智，同样奏效。
长久以来我耗费时间，现在仍未停止耗费，只为了获悉，哦，乔文达，人无法学会任何东西！
_我想，万物中根本没有我们称之为‘修习’的东西。_
_哦，我的朋友，只有一种知识，它无处不在，它就是阿特曼。_
_它存在于‘我’中，存在于‘你中，存在于一切中。_
_因此我开始相信：这种知识最恼人的敌人莫过于求知欲和修习。”_

乔文达停步，举起双手道：“悉达多，不要说这些话吓唬你的朋友！
的确，你的言论让我恐惧。
想想看，如果如你所云，根本不存在‘修习’，
那祈祷的神圣，婆罗门种姓的荣耀和沙门的虔敬将被置于何地！
哦，悉达多，这世间一切圣洁宝贵和令人尊敬的东西又都成了什么哪？”
#+end_quote
#+end_details

此时，后来的 [[https://zh.wikipedia.org/wiki/%E9%87%8A%E8%BF%A6%E7%89%9F%E5%B0%BC][释加牟尼]]，乔达摩出现了（乔达摩本名是「悉达多·乔达摩」），人们传说他就是世尊佛陀，
是那个证道成功的人。于是悉达多和乔文达便一起去看看这个圣人，希望从他身上找到证道的方法。

不过悉达多对乔达摩也不以为然，他觉得自己已经接触了太多的法义，但这些法义也没有让他安宁，
乔达摩说的也不过是另外一些法义，不会有什么差别。

他们见到了乔达摩，确实非同一般，给人一种圆满的感觉。
听了乔达摩的讲义，乔文达觉得这就是他要追随的人，这就是终极的奥义，决定从此追随乔达摩。

但悉达多听完了仍然感到困惑，他承认乔达摩达到了佛陀的圆满，乔达摩的法义是答案，能解释了一切。
但其中没有过程，只知道答案，不经历其中的过程，答案不过也是死记硬背的教条，无法让悉达多感到安宁。

于是他找到了乔达摩，和他进行了对话，希望乔达摩能给他解惑，
但乔达摩没有解释什么，悉达多继续踏上了他的寻道之路。

#+begin_details
#+html: <summary>悉达多和乔达摩的对话</summary>

#+attr_html: :class indent-paragraph
#+begin_quote
悉达多则沉思步入林中。

在路上，他遇见了世尊乔达摩。他恭敬地向世尊问安。
因见世尊目光慈蔼安详，这位青年便鼓起勇气，请求同世尊交谈。世尊默默首肯。

悉达多道：“昨天，哦，世尊，我有幸聆听您奇异的法义。我和我的朋友远道而来听您宣法。
我的朋友将留在此处，他已皈依于您。我却要继续我的求道之路。”

“随你的心意。”世尊谦地说。

“我的话可能太过放肆。”悉达多继续道，
“但如若我不坦率地将我的思想奉告世尊，我便无法离去。世尊佛陀， 您可否再留一步？”

佛陀默默首肯。

悉达多道：“世尊佛陀，您的法义令我钦佩。
它清晰无瑕，证据确凿；您将世界以一条充满因果的永恒的链，一条从未有过任何瑕疵的链，展现在世人面前。
世界从未如此清晰，从未如此不可辩驳地被呈示出来。
婆罗门如若聆听您的法义，看到这个完满融通的世界，
这个无瑕、清澈如水晶、不依赖偶然、不取决于诸神的世界，必定心潮澎湃。
无论世界是善是恶，无论生命自身是苦是乐——这或许悬而未决，
也并非最为本质——但是世界的统一，所有事件的休戚相关，
大小事物席卷于同一潮流中，起源于同一起源，遵循同一生成及灭亡的律法，
已从您完满的宣讲中得到阐明。
哦，功德圆满的佛陀，只是，在您的法义中，在统一、逻辑完善的万物中却存在一个断裂之处。
_这一小小的缝隙让这个统一的世界呈现出些许陌生、些许新奇；_
_呈现出些许迥异于从前，且无法被证实的东西：那就是您的超世拔俗，获得解脱的法义。_
_这个小漏洞，这个小断裂，让永恒统一的世界法则变得破碎，失去效力。_
但愿您能宽恕我所提出的异议。”

乔达摩安静地听着，纹丝未动。
这位功德圆满的觉者以慈蔼、谦和而清晰的声音道：
“你聆听了法义。哦，婆罗门之子，难得你深深地思索法义。
你在法义中发现了一个漏洞，一个缺口。愿你能继续深入地思考。
_但是你这勤勉之人，要警惕多谋善断及口舌之辩。_
_无论辩词美或丑，聪慧或愚蠢，总有人赞许，有人鄙夷。_
_你从我处所听之法义并非我之辩词。它的宗旨并非为求知好学之人闻释世界。_
_它另有他图；它的宗旨乃是济拔苦难。_
这就是乔达摩的法义，别无其他。”

“哦，世尊佛陀，但愿您不怪罪我。”青年人道，
“我并非为争辩与您交谈。您所言极是，辩辞微不足道。
请容我再说：我未曾有刹那怀疑过您。未曾有刹那怀疑过您是佛陀，您已功德圆满。
您已抵达无数婆罗门及婆罗门之子求索之巅峰。您已超拔死亡。
您通过探索，求道，通过深观，禅修，通过认知，彻悟而非通过法义修成正果！
——这就是我的想法，哦，世尊，没人能通过法义得到解脱！
哦，世尊佛陀，您从未以言辞或法义宣讲您在证觉成道之际所发生的事！
世尊佛陀的法义多教人诸善奉行，诸恶莫作。
_在明晰又可敬的法义中不包含世尊的历程，那个您独自超越众生的秘密。_
_这就是我在聆听法义时的思考和认识。_
_这就是我为何要继续我的求道之路——并非去寻找更好的法义，_
_我知道它并不存在——而是为摆脱所有圣贤及法义，独自去实现我的目标，或者去幻灭。_
我将常常怀想今天，哦，世尊佛陀，我将怀想此刻，这个我亲眼见到圣人的时刻。”

佛陀安静地低垂眼帘，他那玄妙莫测的面庞散溢着彻底的安宁。
“愿你的思索，”至尊悠然道，“愿你的思索无误。愿你实现目标！
但请告诉我：你可见到我的僧团? 那些皈依法义 的我的众多弟兄?
你是否认为，陌生的沙门，你是否认为，放弃法义，回到极尽声色的世俗生活对他们更有益处？”

“这样的念头我从未有过！”悉达多高声道。

“愿他们遵循法义，实现宏愿！
_我无权论断他人的生活！唯独对自己的生活必须做出判断。_
_我必须选择，必须放弃。_
_我们沙门寻求弃绝于‘我’，哦，世尊。_
_假如我皈依于您，哦，世尊，我担忧我的‘我’只是表面地、虚假地获得安宁，得到解脱。_
_而事实上，我的‘我’却仍在生存、壮大。_
因为，我会将法义，我的后来者，我对您的爱，以及僧团当作我。”

乔达摩似笑非笑，他的明澈安如磐石。
他善意地凝视这位陌生人且以一种隐微的神情同他道别。

“你很聪明，哦，沙门。”世尊道，“你能言善道，我的朋友。要提防不要太过聪明！”

佛陀缓步离去。他的目光和神秘的微笑永远镌刻在悉达多的记忆中。“
这般目光和微笑我从未见过；如此行走、端坐之人我从未见过。”
他想，“惟愿我也有这般目光及微笑，能如此行走及端坐。
如此自由、神圣、隐晦，又如此坦率。
如孩童，又饱含秘密。
只有潜入自己最深处的人才能有这般诚挚的目光和步伐。无疑，我也将潜入自己之最深处探寻。”

“我见到一个人。”悉达多想，“一个唯一令我垂青之人。他人断不会再令我垂青，再无他人。
也再无法义能吸引我，因为连这人的法义也并未令我屈臣。”

“佛陀劫掠了我。”悉达多想，“他劫掠了我，但他馈赠得更多。
他夺走了我的朋友，那曾经信奉我，如今信奉他的朋友；
那曾经是我的影子，如今是乔达摩的影子的朋友。
而他所馈赠的，则是悉达多，是我的自我。”
#+end_quote
#+end_details

就连佛陀的法义他也不信，那他还能怎么办呢？他要继续寻找，如何寻找？
最终悉达多发现，一直向外求索是没有结果的，任何人的答案都不是自己的答案，
或许自己的经历就是答案，而这么多年以来，一直都是听婆罗门的教导、沙门的教导、佛陀的教导，
全都是些道理，他对自己却一无所知，没有经历过各种生活，
所以他觉得应该活在当下，去感受自己的生活，从中寻找答案。

#+begin_details
#+html: <summary>悉达多的觉醒</summary>

#+attr_html: :class indent-paragraph
#+begin_quote
这位漫步的思考者自问：“
你原先打算从法义里，从师父处学到什么？
你学了很多，却无法真正学到的又是什么？”
_他最终发现：“答案是‘我’。_
_我要学的即是‘我’的意义及本质。_
_‘我’，是我要摆脱、要制胜的东西。_
_‘我’，却是我无法制胜，只能欺罔、逃遁，只能隐藏的东西。_
当真！世上再没什么别的，像我的‘我’这样让我费解。
是‘我’，这个谜，让我活着，让我有别于他人，让我成为悉达多！
_在世上，我最一无所知的莫过于‘我’，莫过于悉达多！”_

这位漫步者被这种思绪捕获。
他驻足，旋即又从这种思绪跃至另一种新的思绪中：
_“我对自己一无所知。一直以来，悉达多于我极为陌生。_
_只因我害怕自己，逃避自己！_
我寻找阿特曼，寻找大梵，我曾渴望的是‘我’被肢解、蜕变，
以便在陌生的内在发现万物核心，发现阿特曼，发现生命，发现神性的终极之物。
可在这条路上，我却迷失了自己。”

悉达多睁大双眼，望向四周，一抹微笑不禁在他脸上荡溢开来。
一种从大梦中彻底苏醒的感觉贯穿他的周身直至脚趾。
他迈开双腿，如同一个完全清楚去向和使命的男人般疾步前行。

“哦，”他深吸了口气，释然道，
“我不会再让悉达多溜走！不会再让阿特曼和尘世疾苦成为我思想和生命的中心。
我再也不会为寻找废墟后的秘密而扼杀自己，肢解自己。
_无论是《瑜伽吠陀》《阿达婆吠陀》，还是其他任何教义我都不再修习。_
_我不再苦修。我要拜自己为师。我要认识自己，认识神秘的悉达多。”_


他环视四周，宛如与世界初逢。
世界是美的，绚烂的；世界是奇异的，神秘的！
这儿是湛蓝，这儿是灿黄，那儿是艳绿。高天河流飘逸，森林山峦高耸。
一切都是美的。一切都充满秘密和魔力。
而置身其中的他，悉达多，这个苏醒之人，正走向他自己。
这初次映入悉达多眼帘的一切，这灿黄和湛蓝，河流和森林，
都不再是摩罗的法术，玛雅的面纱，不再是深思的、寻求圆一的婆罗门所蔑视的现象世界中愚蠢而偶然的纷繁。
蓝就是蓝，河水就是河水。
在悉达多看来，如果在湛蓝中，在河流中，潜居着独一的神性，那这恰是神性的形式和意义。
它就在这儿的灿黄、湛蓝中，在那儿的天空、森林中，在悉达多中。
_意义和本质绝非隐藏在事物背后，它们就在事物当中，在一切事物当中。_

“我曾多么麻木和迟钝！”这位疾步之人心想，
_“如果一个人要在一本书中探寻意义，他便会逐字逐句去阅读它，研习它，爱它；_
_他不会忽视每一个词、每一个字，把它们看作表象，看作偶然和毫无价值的皮毛。_
_可我哪，我这个有意研读世界之书、自我存在之书的人，却预先爱上一个臆想的意义。_
_我忽视了书中的语词。我把现象世界看作虚妄。_
_我视眼目所见、唇齿所尝的仅为没有价值而表面的偶然之物。_
不，这些都已过去。我已苏生。我切实已苏生。今天即是我的生日。”
#+end_quote
#+end_details

于是他让自己走进生活，走进喧闹的世界中，在此之前，他是一个读了万卷书的人，而现在，他还要走万里路。

#+begin_details
#+html: <summary>思想和感官，法义和经验，都值得倾听</summary>

#+attr_html: :class indent-paragraph
#+begin_quote
所有这自古有之的一切，悉达多一直熟视无睹。他从不在场。而现在，他归属其中。
流光魅影在他眼中闪耀，星辰月亮在他心中运行。

在路上，悉达多也忆起他在祇树给孤独园中经历的一切。
他曾在那里聆听佛陀神圣的法义，同乔文达告别，与世尊交谈。
他记起他曾对世尊佛陀说过的字字句句。
他惊讶地意识到，自己所言的“珍宝”，当时无从体会。
_他曾对乔达摩说：佛陀的法义或许并非其最宝贵最神秘的东西。_
_佛陀的彻悟纪事才是无法言说、不可传授的珍宝——这恰恰是他现在要去经验的，他现在才刚刚开始去经验的。_
自然，他历来便知他的自我即阿特曼。自我如大梵般永恒存在。
_然而因他始终试图以思想之网去捕捉自我，而使得自我从未被真正发现。_
自然，肉体并非自我，感官游戏并非自我。如此看来思想也并非自我。才智并非自我。
归纳结论，由旧思想编织新思想的可修习之智慧和技艺并非自我。
不，这一思想境界乃是尘世的。
_如果一个人扼杀了感官意义上的偶然之我，却喂养思想意义上博学多能的偶然之我，他是不会寻得自我的。_
两者，思想和感官，均为美的事物；
两者背后均隐藏终极意义；
两者都值得倾听，值得参与；
两者均不容蔑视亦不必高估。
自两者中均可听到内在的秘密之声。
除非内在声音命令他行动，悉达多别无所求。
除非听凭内在声音的倡导，他绝不停下步履。
为何乔达摩在那个时辰中的时辰，那个他正觉成道的伟大时刻坐于菩提树下？
因为他听见一个声音。一个他内心的声音吩咐他在这棵树下歇息。
他并非凭苦行、献祭、洗礼和祈祷悟道，也不是凭斋戒悟道，不是在睡梦中悟 道。
他听凭了这个声音。如此听凭内心的召唤而非听凭外在的命令是善的。
除了时刻等待这声音的召喚，再没什么行为是必要的。
#+end_quote
#+end_details

途中，他在河边遇到了一个摆渡人，在他那里借宿了一晚，离开时，摆渡人说他们还会相见。

行经一个村舍，他看到了一个年轻妇人在洗衣服，妇人对他进行了挑逗，他亲吻了对方的乳头，
就在他要扑倒对方时，内心说了声「不」，随后性欲就消退了。
或许是对方不够美丽，不足以吸引悉达多？
或许是他刚觉悟，内心还保留着一丝禁欲的想法？
总之他这次忍住了。
这里也再次体现了悉达多的俊美外貌，如果是一个寒酸的沙门，想必妇人也不会想挑逗他。

#+begin_details
#+html: <summary>悉达多看到妇人的片段</summary>

#+attr_html: :class indent-paragraph
#+begin_quote
正午时分，悉达多经过一个村舍。
巷子里的孩子们正在茅屋前追逐嬉闹，玩南瓜子和蚌壳。
他们看见陌生沙门便羞怯着四散开去。
村舍尽头蜿蜒着一条小溪，一位年轻妇人正跪在溪边洗衣。
悉达多上前问好时，妇人抬头嫣然一笑。悉达多见她眉眼盈盈处泛着秋波。
他以途中惯用的方式向妇人问安，并询问距离大城的路程。
这时她起身走向他，年轻的面庞上一副湿润的嘴唇闪着妩媚的光。
她娇羞地问他可否用过饭，问他沙门是否真的在夜晚单独睡在林中，不能和女人同寝。
说着，她用左脚尖抚摩他的右脚并做出《爱经》中称为“爬树”的动作
——这是女人在挑逗男人共赴云雨时所做的动作。
悉达多顿感热血沸腾。
此刻，梦境再次袭来，他朝妇人俯下身去，亲吻她乳房上褐色的乳头。
抬起头时，他看见妇人焦渴地微笑着，满是企盼的双眼细若游丝。

悉达多感到自己的渴望和涌动的性欲。
他至今尚未碰过女人。在准备伸手去握住妇人时，他迟疑片刻。
就在这一刻，他听见内心颤抖的声音说“不”。
顿时，年轻妇人微笑的脸失去了全部魅力。
她在他眼中不过是一只目光迷离的发情母兽。

他亲切地抚摸了她的脸颊，随后移步离开这位失望的妇人，健步踏入竹林。
#+end_quote
#+end_details

接着悉达多来到城里，偶遇了城里的名妓伽摩罗，就想找对方感受一下什么是性爱，说是要向对方学习爱的技巧。
em...如果他不是看了他前面的纠结，会觉得悉达多还挺无耻、恶心的，
不就是看到一个很漂亮的女人，性欲大发，想对方发生关系嘛，还要美其名曰「学习爱的艺术」，实际上就是去嫖。

悉达多去找伽摩罗之前还懂得先将自己收拾一番，显得自己干净，显露自己的俊美。
见到伽摩罗后，言语中，悉达多甚至有要强暴的意思，
但是伽摩罗说，强扭的瓜不甜，想吃甜的就搞到钱再来，有身份了再来。

悉达多不知道怎么搞钱，就问伽摩罗有没有什么路子，感觉还挺厚颜无耻的。
伽摩罗应该也是被悉达多的美貌和知识吸引到，可能觉得有个这样的沙门过来还挺新奇吧，就问他会什么，
他说「我会思考。我会等待。我会斋戒。」，这句话后面也出现了几次，只是顺序会略有不同。

「我会思考。我会等待。我会斋戒。」
会思考，说明悉达多学识丰富，有智慧，脑子灵活；
会等待，说明他很有耐心，不急躁；
会斋戒，意味着吃喝拉撒对他而言都不是问题，没吃的大不了就不吃，
吃喝是动物最基本的需求，既然吃喝不成问题，就没有别的问题了，就算一无所有，他都有退路，大不了就斋戒。
这三者也是相辅相成的，能够斋戒，才能够等待，进而有时间用来思考，而不是拼命地只为了一口饭。

#+begin_details
#+html: <summary>悉达多和伽摩罗的对话</summary>

#+attr_html: :class indent-paragraph
#+begin_quote
悉达多见她如此美丽，心中欢喜。
轿子临近时，他深鞠一躬，接着抬头注视那张靓丽妩媚的脸。
他凝视她高挑眉毛下聪慧的双眼，并嗅到一缕从未闻过的沁人香气。
这位美人微笑颔首后，在仆从的簇拥下转瞬消失在林苑中。

“我尚未入城，”悉达多想，“就天降此等吉兆。”
他感到一阵冲动，想即刻跟入林苑。
但转念又想起男女仆从们曾在门口轻视、怀疑而无礼地打量他。

“我还是个沙门。”他想，“依然还是苦行者和乞丐。我这样的人不该在此逗留，更不该踏入林苑。”他笑了起来。

这时，来了一位路人。
悉达多向他打听这座林苑以及那个女人的名字。
原来，林苑的女主人迦摩罗是城中名妓。
除了这林苑外，她在城里还有一座宅邸。

之后他就怀揣着一个目标进了城。
为了这个目标，悉达多踏遍城邑，走街串巷，累了便安静地伫立在广场或坐在河边的石阶上歇息。
临近傍晚时分，他结识了一位理发店伙计。
他先见他在拱门下阴凉处劳作，又见他去毗湿奴庙祈祷。
悉达多为他讲述了毗湿奴和拉克什米女神的故事。
当晚，悉达多在岸边的船里过夜并于次日一早，在其他客人还没到来前光顾了理发店。
他让那位伙计为他刮了胡须，剪了头发并敷了上好的头油。之后，他去河里沐浴。

当美丽的迦摩罗于午后再次乘轿子回到林苑时，悉达多正站在门口。
他向迦摩罗鞠躬致意并得到这位名妓的回敬。
他向队尾的仆从示意，请求仆从向林苑女主人禀告，有位青年婆罗门渴望与她交谈。
过了一会儿，仆从回来了，他吩咐正在等待的悉达多跟随他默默进了一座亭台。
亭台里，迦摩罗正斜倚在卧榻上。她随即差遣仆从退下。

“你不就是昨天站在外面问候我的人吗？”迦摩罗问道。

“是的，我昨天就见到了你，问候了你。”

“但是昨天你不是留着胡须，长发上还布满灰尘吗？”

“你看得仔细。一切都尽收眼底。
你见到的人是悉达多，为成为沙门而告别故乡的婆罗门之子。
迄今做沙门已三年有余。
但现在我已告别沙门之路，进了这座城。
而你，是我入城之前见到的第一个人。
哦，迦摩罗！我来，是为告诉你这个。你是让悉达多并未低垂眼帘而与之交谈的第一个女人。
今后，如若我遇见漂亮女人，也不会再垂下眼帘。”

迦摩罗微笑着。她一边玩弄手中的孔雀翎摇扇，一边问道：“悉达多只是为了说这个，才来见我吗？”

“是为了说这个。也为感谢你的美貌，迦摩罗。
_如若不冒犯你，我想请求你做我的朋友和老师。因为对你所熟稔的艺术，我一无所知。”_

迦摩罗大笑起来。“从来没有林中沙门来拜我为师！朋友。 也从来没有围着破旧遮羞布、留着长发的沙门来过我这里！
许多青年来拜访我，其中不乏婆罗门之子。
他们可是个个穿华丽的衣裳、考究的鞋子，头发飘香，腰缠万贯。
沙门，那些青年都是置备停当才来见我。”

悉达多道：“我已开始向你学习。昨天已经开始。
我已刮掉胡须，打理头发，抹了发油。我缺少得不多。
你这仙姿佚貌的女人，我缺的不过是华美的衣裳、昂贵的鞋子和饱满的钱袋。
你知道，悉达多曾致力于许多比这区区小事难得多的事业，且已完满。
而我昨日下定决心要做的事，又怎能无法达成——我要成为你的朋友，同你学习欢爱之事！
你将很快知道，迦摩罗，我曾学过比你教的学问更复杂的学问。
那么，悉达多已抹了发油，却仅仅因为没有华美的衣服，没有名贵的鞋子，没有钱财，就无法让你满意吗？”

迦摩罗笑道：“是的，尊敬的人。你不能让我满意。
你必须有衣服，华美的衣服；你必须有鞋子，名贵的鞋子；
你不仅要腰缠万贯，还要为迦摩罗备上礼物。
明白了吗，林中的沙门？这些你记住了吗?”

“我完全记住了。”悉达多大声道，
“从如此美艳的嘴唇里说出的话我怎能不记住！你的嘴唇仿似新鲜开裂的无花果，迦摩罗。
而我的嘴唇也同样又红又嫩。
你将验证，它们是多么般配——但请告诉我，美丽的迦摩罗，你真的不畏惧一个要向你学习欢爱的林中沙门吗？”

“我为何要畏惧一个沙门，一个林中来的愚笨的沙门，一个从胡狼群中来，又根本不知女人为何物的沙门呢？”

_“哦，沙门是强壮的，他无所畏惧。他恐怕会强迫你，美丽的女人。他恐怕会强夺你，给你带来痛苦。”_

“不，沙门，我不怕。
_难道一个沙门或婆罗门会害怕有人来强夺他，侵吞他渊博的学识、他的虔诚和他深奥的思想吗？不会。_
_因为这些只属于他自己。他只会把这些奉献给他想给的人。_
_迦摩罗亦如此，欢爱亦如此。_
_迦摩罗的嘴唇固然美艳嫣红，但你若试图违背迦摩罗的意愿去强吻它，便不会得到一丝甜蜜。_
_尽管那嘴唇深知如何赋予甜蜜！_
勤学的悉达多，你要明白：
_情爱可以乞得，可以购买，可以受馈，也可在陋巷觅得，却唯独不能强夺。_
你想出了一个错误的主意。
哦，如果一个如你般俊美的青年有如此想法的话，就实在太遗憾了。”

悉达多微笑着鞠躬致意：“那的确遗憾。迦摩罗，你说得极对！那将极为遗憾。
不，我不愿放弃你芳唇间任何一滴甜蜜。你也不该放弃我的吻！此事已定：悉达多会再来。
当他拥有了他缺少的华服、鞋子和钱财。但是，甜美的迦摩罗，你可愿再给我一些指示？”

“一些指示？为什么不哪?谁会不愿给一个从荒林狼群中来，又贫穷无知的沙门一些指示？”

“亲爱的迦摩罗，请告诉我：我该去哪里才能尽快寻得这三样东西?”

“朋友，许多人都想知道。你必须去做你会做的事情，以赚得钱财、鞋子和衣裳。
否则一个穷人是不会有钱的。你会什么哪？”

_*“我会思考。我会等待。我会斋戒。”*_
#+end_quote

#+attr_html: :class indent-paragraph
#+begin_quote
“你真幸运。”告别时她道，“一扇扇门为你打开。这是怎么回事？难道你施了法术?”

悉达多道：“昨天我已告诉你，我会思考、等待、斋戒。
你却认为这些没用。其实它们很有用。迦摩罗，你会看到的。
你将看到，林中愚笨的沙门将学会并做出许多旁人不会的漂亮事情。
前天我还是蓬头垢面的乞丐，昨天我就亲吻了迦摩罗；
而很快，我会成为一名商人，拥有财富和一切你看重的东西。”

“好吧。”她表示赞同，“但如果没有我又会怎样？如果我不帮助你，又会怎样？”

“亲爱的迦摩罗，”悉达多说着挺直腰身，“来到你的林苑是我迈出的第一步。
我决心跟你这个美丽的女人学习爱的艺术。
那一刻，我下定决心并知道，我必定会实现愿望。
我也知道，你会帮助我。当我站在林苑外，第一眼见到你时 我就知道。”

“如果我不愿意呢？”

“你会愿意的。
_你看，迦摩罗，如果你将一粒石子投入水中，石子会沿着最短的路径沉入水底。_
_恰如悉达多有了目标并下定决心。_
_悉达多什么都不做， *他等待、思考、斋戒。*_
他穿行于尘世万物间正如石子飞入水底——不必费力，无需扎；他自会被指引，他任凭自己沉落。
目标会指引他，因为他禁止任何干扰目标的事情进入他的灵魂。
这是悉达多做沙门时学到的。
愚人们称其为魔法。
愚人以为此乃魔鬼所为。
其实，魔鬼无所作为，魔鬼并不存在。
每个人都能施展法术。
_每个人都能实现目标，如果他会思考、等待、斋戒。”_

迦摩罗倾听着。她爱他的声音，爱他的目光。

“或许是的，”她轻声道，“如你所说，朋友。
也或许因为悉达多是个俊美的男子，女人们喜爱他的目光，他才好运连连。”

悉达多和她吻别。“但愿如此，我的老师。愿我的目光永远让你欢喜，愿我的好运一直因你而降临！”
#+end_quote
#+end_details

于是伽摩罗把他介绍给了商人，商人给了他一份工作，工作对他而言就是体验生活，用来搞点钱去找伽摩罗，
工作中的得失对他而言无所谓，他在工作，又超然于工作之外，带着一种玩乐的心态。

#+begin_details
#+html: <summary>悉达多和商人的对话，关于斋戒</summary>

#+attr_html: :class indent-paragraph
#+begin_quote
“既然你一无所有，你靠什么生活？”

“我从未想过，先生。三年有余，我一无所有，却从未想过靠什么生活。”

“看来你靠他人钱财为生。”

“看来是。商人也靠他人钱财为生。”

“说得好。但商人却不白拿他人钱财，他以货物交易。”

“世事看似如此。各有索取，各有付出。这是生活。”

“恕我直言：如果你一无所有，你能付出什么？”

“人人都付出他拥有的。武士付出力气，商人付出货物，教师付出学问，农民付出稻谷，渔民付出鱼蟹。”

“非常对。只是，你付出什么？你究竟学过什么?又会什么?”

_“我会思考。我会等待。我会斋戒。”_

“就这些？”

“我想，就是这些！”

“这些有何用处？比如斋戒——斋戒有何益处？”

_“斋戒极好，先生。对于没有食物的人，斋戒最为明智。_
_假如悉达多没学过斋戒，他今天就必须寻找活计。_
_不论在你这里，还是别处。饥饿迫使他行动。_
_而事实上，悉达多能安静地等待。_
_他从不焦急，从不陷于窘迫。_
_即便长时间被饥饿围困，他仍能藐视饥饿。因此，先生，斋戒极好。”_
#+end_quote
#+end_details

他当初是想要感受生活，现在他满足了情欲，有工作，有大量的钱，但他并没有真正地参与其中，
他还是会觉得自己是一个沙门，自己会思考，高别人一等。
工作、周围的人对他而言都是玩乐，他只是一个旁观者。
他在生活，却又没在生活。

他和伽摩罗经常见面，或许伽摩罗对他产生了爱意，甚至想要一个他的孩子，
但伽摩罗感觉到他并没有真正地爱她，他享受和伽摩罗的性爱，但他并不愿意投入感情去爱。
他甚至还嘲讽伽摩罗「你也谁都不爱——否则你怎会将爱当作艺术经营？像你我这类人大概都不会爱。」

#+begin_details
#+html: <summary>悉达多对待工作和爱的态度</summary>

#+attr_html: :class indent-paragraph
#+begin_quote
悉达多学会许多新知。
_他听得多，说得少。_
他牢记迦摩罗的话，在商人面前从未奴颜婢膝。这迫使商人与他平起平坐，甚至对他高看一眼。
迦摩施瓦弥严谨地经营生意，饱含激情。
_悉达多则视一切如游戏。他努力学习规则，内容他并不记挂于心。_

在宅邸中住了不久，悉达多便开始分担迦摩施瓦弥的生意。
每日，他也在约定的时辰，登门拜访美丽的迦摩罗。
他身穿华美的衣裳，足蹬精致的鞋子。
很快，他也在造访时携带礼物。
迦摩罗娇艳聪慧的嘴唇，温柔细腻的双手教会他许多学问。
在欢爱的路上，悉达多仍蹒跚学步。
他时常冒失，求索无厌地跌入情欲深渊。
_而迦摩罗则教会他，不付出情欲就难收获情欲这一《爱经》的根本。_
_每种姿势，每个动作，每次抚摸，每次对视，身体的每个角落都隐藏秘密。_
_这些秘密，为懂得唤醒它的人预备了幸福。_
_她教导他，爱侣在交欢后不得倏忽分离。彼此仍要相互赞叹、抚慰。_
_这样，双方才不会因过度性满足，而产生厌倦、落寞，产生辱弄或被辱弄的不快感受。_
在美丽聪慧的艺术家处，悉达多度过了绝妙时光。
_他成为她的学生、情人、朋友。_
_对于现在的悉达多，生活的意义和价值是能和迦摩罗在一起，而绝非迦摩施瓦弥的生意。_

商人委托悉达多书写重要的信件和契约，他也习惯在紧要事务上同悉达多商议。
很快，他发现悉达多对稻谷、棉布、船务和买卖并不在行。
_他的运气是，和商人相比，他的冷静沉着更胜一筹。_
_和陌生人打交道时，他懂得倾听的艺术，善解人意。_
“这位婆罗门，”迦摩施瓦弥曾对朋友说，“不是真正的商人，也不会成为真正的商人。
在生意上，他从未投入热情。
但是他掌握那些无为而治的成功者的秘密。
或许他福星高照，或许他会施展法术，或许他从沙门处学到了什么。
他似乎总在生意上游戏，从不全情投入，生意从来也无法牵制他。
他从不担心失败，从不为损失烦忧。”

这位朋友建议商人：
“你可将一部分生意交与他替你打理。三分之一的盈利归他所有；
反之，他也须承担同等损失。如此一来，他必会用心些。”

迦摩施瓦弥采纳了这个建议。悉达多则安之若素。
如有盈余，他便取他该得的那份。
如果亏损，他会笑着说：“哎，你看，多么糟糕的交易！”

他显然对生意心不在焉。
一次，他去村落收购大批稻谷。
当他抵达时，稻谷已全部卖给其他商人。
尽管如此，悉达多仍在村落逗留数日。
他宴请农民，送给农民的孩子铜币，参加一次结婚庆典，随后满意而归。

“做得漂亮！”迦摩施瓦弥不情愿地喊道，“但事实上你是个商人。我必须得说！难道你的旅行只是为了赏玩？”

“确实。”悉达多笑道，“我确实为赏玩而去。否则为何？
我见到许多人，欣赏了风景，收获了友谊和信任，结交了朋友。
你看，亲爱的，如果我是你迦摩施瓦弥，见到生意落空，定是气恼地速速返回。
_可事实上，时间和金钱已经蒙受损失。_
_而我享受了几天美妙时光，学到了知识，心情愉快，我和他人均未因我的气恼和草率而受到伤害。_
如果今后我再去那里，或许去收购下季收成，或许因为其他生意，
那里友好的人们必将由于我这次没有表现得急躁和闷闷不乐而热情地款待我。
释怀吧，朋友，不要因责备而伤害自己！
如果有那么一天，你看到悉达多为你带来损失，你只消说一声，悉达多便自行离去。
在那之前，我们还是善待彼此。”

商人也曾徒劳地尝试让悉达多相信，他靠迦摩施瓦弥为生。
_但悉达多认为他靠自己为生。_
_确切地说，他们两人均靠他人为生，靠众人为生。_
悉达多从不过问迦摩施瓦弥的烦恼，而后者则烦恼颇多。
他担心一笔生意行将失败，货物蒙受损失，借贷人无力偿还。
无论如何，迦摩施瓦弥始终无法向悉达多证明，抱怨、急躁、平添皱纹或辗转反侧有何益处。
一次，迦摩施瓦弥提醒悉达多，他的一切知识都是从迦摩施瓦弥处学来。
悉达多反驳道：“最好不要和我开这样的玩笑！
我从你那里学到一篓鱼的售价，借贷他人获得多少利息。这是你的学问。
_我和你从未学过如何思考，尊贵的迦摩施瓦弥，你最好向我学习如何思考。”_

悉达多的确无心生意。做生意的益处，无非是令他有足够的钱财交与迦摩罗。
尽管他获得的远超出他所需要的。
他只是对曾经如同月亮般遥远而陌生的世人，他们的生意、手艺、忧烦，他们的娱乐和蠢行感到既同情又好奇。
虽然他能轻而易举地和他们攀谈，与他们相处，向他们学习，
但他深刻地认识到，将他同世人区分开来的，是他做沙门的经历。
他看见世人以孩童或动物的方式生活，这让他既爱慕又蔑视。
他看见他们为一些在他看来毫无价值的东西，为了钱，为了微不足道的欲望，为了可怜的尊严而操劳、受苦、衰老。
他看见他们彼此责骂、羞辱，看见他们为那些令沙门付之一哂的痛苦恸哭，为那些令沙门不屑一顾的贫乏苦恼。

他接纳人们带来的一切。
他欢迎兜售亚麻的商人，欢迎来向他借贷的人，也愿意长久地倾听乞丐讲述自己潦倒的生活，
尽管他们的生活远不及任何一位沙门的生活贫穷。
他对待富庶的外国商人，和对待替他刮脸的仆人，对待他故意被骗去几个铜板的街头香蕉小贩别无二致。
如果迦摩施瓦弥来找他抱怨，或因一桩生意指责他，
他也会好奇地耐心倾听，表示惊讶，试图理解，对他做适度的让步，接着离开他，去约见下一位需要他的人。
许多人来找他做生意，许多人想蒙骗他，许多人试图探听他，许多人想博得他的同情，许多人想得到他的建议。
他给出建议，表示同情，慷慨解囊，他甚至故意被欺骗。
就像当年他热衷于侍奉诸神和做沙门时一样，他全神贯注，激情饱满地和众人游戏着。

时常，他感到内心深处有一个垂微的声音在轻声提醒，轻声抱怨。轻到几乎无从捕捉。
他开始在某些时刻意识到自己正过着荒谬的生活。
所有这些他做的事情无非是游戏。这游戏令他快活，偶尔让他愉悦。
_但是真实的生活却擦身而过，无法触及。_
如同一个人在玩球，他同他的生意以及周围的人玩耍。
他冷眼旁观，寻得开心。而他的心，他存在的源泉却不在。
那眼泉十分遥远，渐渐消失在视线之外，与他的生活无关。
几次，他为他意识到的这一切感到惊恐。
他希望自己也能满腔热情，全心全意地参与到孩子气的日常行为中。
真正地去生活、去劳作、去享乐，而不只是一位@@html:<em>旁观者</em>@@。

他一直拜访美丽的迦摩罗。
学爱情的艺术，做情欲的礼拜。
在性爱中，付出和索取比在任何别处都更加水乳交融。
他跟她闲谈，向她学习，给她建议，也接受她的忠告。
迦摩罗对他的了解更胜于当年乔文达对他的了解。她跟他更加相像。
有一次，他对她说：“你就像我。你跟大多数人不同。
你是迦摩罗，不是别人。
你随时可抵达内心安静庇护的一隅，如同回家。我亦如此。
只有少数人才有这样的内心，尽管人人都可习得。”

“不是所有人都聪明。”迦摩罗道。

“不。”悉达多道，“聪明并非关键。
迦摩施瓦弥聪明如我，但他心中没有这安静庇护的一隅。
其他人内心虽有，但才智却如孩童。
_大多数人，迦摩罗，仿佛一片落叶，在空中翻滚、飘摇，最后踉跄着归于尘土。_
_有的人，极少数，如同天际之星，沿着固定的轨迹运行。_
没有风能动摇他，他内心自有律法和轨道。
在我认识的沙门和贤士中，有一位即是如此。
他是一位功德圆满的觉者，我永远不会忘记。
他就是乔达摩，世尊佛陀，那位宣法之人。
每天有上千徒众听他宣法，追随他的脚步。
但这些徒众却如同落叶，内心没有自己的教义和律法。”

迦摩罗含笑注视他。“你又提起他。”她道，“你的思想又如同一位沙门了。”

悉达多沉默不语。
接着，他们以迦摩罗熟悉的三十种或四十种不同的体位做爱。
她的身躯像豹子，像猎人的弓弦般柔韧。
跟她鱼水相欢之人，必获得诸多快感，洞悉许多秘密。
她和悉达多长久地做爱。
她引诱他，再推辞他，强逼他，再顺从他，为他高超的技巧雀跃，直至他被完全征服，精疲力竭地躺在她身边。

名妓迦摩罗伏在他身上，久久地凝视悉达多的脸，凝视他疲惫的双睛。

“你是我见过的，”她思索着，“最好的情人。你比别人更强壮，更柔韧，更欲望强烈。
你出色地学会我的艺术，悉达多。
日后，待我年纪大些，我要有一个你的孩子。
然而，亲爱的，你依然是个沙门。
_你并不爱我，也不爱任何人。_
难道不是吗？”

“或许是。”悉达多疲惫地说，“我就像你。
_你也谁都不爱——否则你怎会将爱当作艺术经营？_
_像你我这类人大概都不会爱。_
_如孩童般的世人才会爱。这是他们的秘密。”_
#+end_quote
#+end_details
