#+title:      使用 org-protocol 生成听歌排行
#+export_file_name: use-org-protocol-to-capture-music-rank
#+date:       [2025-09-28 Sun 19:54]
#+filetags:   :emacs:music:orgprotocol:published:
#+identifier: 20250928T195421
#+bind:       denote-directory "~/git/taxodium/posts"
#+description: 结合 Emacs，Tampermonkey，org-protocol 获取听歌排行数据，记录到博客中
#+language: zh-CN
#+author: Spike Leung
#+email: l-yanlei@hotmail.com
#+options: ^:{}
#+startup: content

🎵 鞋底子 + 十八岁 (Outro) - 夏之禹 / 地磁卡

在整理 Blaugust Feed 的时候，看到 Matt 的 [[https://mtwb.blog/music/][Now Playing]] 页面，里面罗列了他的 Top 10 Tracks。

感觉蛮有趣的，于是我也模仿做了一个 [[denote:20250928T170716][听歌排行]] 页面。

我主要使用网易云音乐听歌，它本身就有听歌排行，我要做的就是拉取下来，格式化后记录到博客文章中。

主要用到 [[denote:20250831T162749][Emacs]]、[[https://orgmode.org/worg/org-contrib/org-protocol.html][org-protocol.el]]、[[https://www.tampermonkey.net/index.php][Tampermonkey]]。

#+begin_details
#+html: <summary>关于 org-protocal</summary>

org-protocol 是一种自定义 URL 方案（ =org-protocol://= ），用于在 Emacs 中触发操作。

常见的用法就是浏览器中触发 org-protocol，调用 Emacs 完成一些事情。

macOS 上集成 org-protocol 可以参考 [[https://github.com/xuchunyang/setup-org-protocol-on-mac][Setting Up org-protocol on Mac | xuchunyang]]。
#+end_details

流程是这样的：
1. 登录 [[https://music.163.com/#][网页版的网易云音乐]]，跳转到听歌排行页面。[fn:1]
2. 使用 [[https://www.tampermonkey.net/index.php][Tampermonkey]] 写点 [[https://gist.github.com/Spike-Leung/19986df42333b6419b2eadaa73526d7b][脚本]] 解析排行页面的元素，然后格式化成自己需要的格式。
   （可以借助 [[https://en.wikipedia.org/wiki/Vibe_coding][vibe coding]]）
3. 把格式化后的数据保存到博客文章，我的博客是用 Emacs 和 org-mode 写的，
   可以利用 [[https://orgmode.org/worg/org-contrib/org-protocol.html][org-protocol.el]] 和 org-mode 的 [[https://orgmode.org/manual/Capture.html][capture]] 功能，捕获并写入到我指定的文件里。

    #+begin_details
    #+html: <summary>capture 模版</summary>

    #+begin_src emacs-lisp
      ("m" "Music Rank" entry
       (file+headline "~/git/taxodium/posts/20250928T170716--听歌排行__blackhole_music.org" "每周排行")
       "* %<%Y-%m-%d W%W %A> \n #+begin_details\n#+html: <summary>Top100</summary>\n%i\n#+end_details"
       :jump-to-captured t
       :empty-lines 1
       :prepend t
       :immediate-finish t)
    #+end_src

    - 使用 =file+headline= 指定捕获的位置，放到指定文件的指定标题下
    - 设置捕获的模板，我用一个日期作为标题，记录快照的时间；
      然后把 Tampermonkey 获取到的数据放到一个 =<details>= 元素里
    - 设置 =:prepend t= 使得每次捕获的内容都在前面
    #+end_details

    #+attr_html: :role note
    #+begin_section

    对博客搭建感兴趣可以看看：
    - [[denote:20240927T214034][使用 org-publish 发布博客]]
    - [[denote:20250828T184037][结合 denote 和 org-publish 写博客]]

    关于 capture 的使用，推荐看看 [[https://www.zmonster.me/2018/02/28/org-mode-capture.html][强大的 Org mode(4): 使用 capture 功能快速记录]]。
    #+end_section

或许你不用 Emacs，但获取数据的方法是类似的，只是如何保存你需要考虑一下。

* Footnotes
:PROPERTIES:
:CUSTOM_ID: A241F074-B292-4B75-A871-7C48F01CF8BB
:END:

[fn:1] 听歌排行页面的 URL 是 =https://music.163.com/#/user/songs/rank?id=your_id= ，
我好奇地试了试别的 ID，竟然可以看到其他 ID 的排行。
