#+title:      Quotes
#+export_file_name: quotes
#+date:       [2025-05-03 Sat 21:39]
#+filetags:   :blackhole:quote:
#+identifier: 20250503T213953
#+bind:       denote-directory "~/git/taxodium/posts"
#+description: 一些我喜欢的句子
#+language: zh-CN
#+author: Spike Leung
#+email: l-yanlei@hotmail.com
#+options: ^:{}
#+startup: content indent

#+begin_quote
Read what you love until you love to read.

Do what you love until you love to Do.

阅读你喜欢的书，直到你喜欢阅读。

做你喜欢的事，直到你喜欢去做。
#+end_quote

#+begin_quote
我在大学里得到的最好建议是：“找到最好的老师，上他们所有的课，不管是什么课。”

这个建议也适用于互联网。

⸺ David Perell
#+end_quote

#+begin_quote
恋爱的纪念物从来就不是那些你送给我的珍贵礼物，甚至也不是那些甜蜜的短信和合照。

恋爱最珍贵的纪念物，是你留在我身上的、如同河川留给地形的，你对我造成的改变。

⸺ [[https://movie.douban.com/review/13709343/][坂元恋爱指南：如何和100%合拍的人说再见]]
#+end_quote

#+begin_quote
从今天起，在项目的 README 中增加一个章节：

Is it any good?

yes!

⸺ [[https://news.ycombinator.com/item?id=3067434][Is it any good? yes]]
#+end_quote

#+begin_quote
To make some good progress, you just need to overcome a bit of laziness at the beginning every time.

要取得一些不错的进展，你每次都只需克服一下开始时一点点的懒惰。

#+end_quote

#+begin_quote
Sometimes in life, you just need to say: Don’t know, don’t care, let’s keep going.

有时候在生活中，你只需要说：不知道，无所谓，让我们顺其自然。

⸺ [[https://macadie.info/2023/12/30/emacs-commands-i-got-by-with-for-years/][Emacs Commands I Got By With For Years]]
#+end_quote

#+begin_quote
我的愿望是，想见到你。

就像在冬天想见到晴天一样。

可是如果不是晴天怎么办呢？

那就只有去见你了。

⸺ [[https://www.bilibili.com/video/BV13u4y1a7b1/?spm_id_from=top_right_bar_window_dynamic.content.click&vd_source=f80d9787e4afd6deb997dc42879718d0][今年最浪漫的一期!和菊池桃子约会!丨HOPICO]]
#+end_quote

#+begin_quote
If you think about it, the very best books are really just extremely
long spells that turn you into a different person for the rest of your
life.

如果你仔细想象，最好的书，真的就只是极其漫长的咒语，会让你在剩下的日子里变成另外一个人。

⸺ [[https://bsky.app/profile/thisone0verhere.bsky.social/post/3ld4fibye4s2s][Jonathan Edward Durham]]
#+end_quote

#+begin_quote
当你老了，回顾一生，就会发觉：

什么时候出国读书、什么时候决定做第一份职业、何时选定了对象而恋爱、什么时候结婚、其实都是命运的巨变。

只是站在三岔路口，眼见风云千樯，你作出出抉择的那一日，在日记上，相当沉闷和平凡，当时还以为是生命中普通的一天。

⸺ [[https://book.douban.com/annotation/30993317/][当时只道是寻常]]
#+end_quote

#+begin_quote
人们很少真正告诉你他们真实的想法，甚至有时候，他们认为自己给你讲的是真实的故事，但那也并不是真的，而是其中的一个版本。
#+end_quote
