#+title:      Zine#56
#+subtitle:
#+export_file_name: 56
#+date:       [2026-07-30 Thu 12:33]
#+filetags:   :draft:preview:zine:
#+identifier: 20260730T123355
#+bind:       denote-directory "~/git/taxodium/posts"
#+description: Zine 第 56 期，分享一些看到的文章、资源、电影、书籍
#+language: zh-CN
#+author: Spike Leung
#+email: l-yanlei@hotmail.com
#+options: ^:{} toc:1
#+startup: content hideblocks

* News | Article
:PROPERTIES:
:CUSTOM_ID: 27DEE417-5D0B-4160-A0E5-E9B3E2F439E1
:END:

- [[https://e89295.com/blog/][我的部落格]]

  在 YangBear 的 [[https://yangbear.bearblog.dev/ichigo-ichie/][一期一會]] 里發現了這個博客，我挺喜歡的。
  博客的排版，使用的 HTML 和 CSS
  @@html:<small>@@(有關心無障碍，也用上了更合理的 [[https://developer.mozilla.org/en-US/docs/Web/CSS/Guides/Logical_properties_and_values][CSS logical properties and values]])@@html:</small>@@，
  我從里要抄了 [[https://en.wikipedia.org/wiki/Pull_quote][Pull Quote]] 的實現，
  以前在一些網站𥚃也看到過，但我也沒心動，可能是這個博客排版的好看，這次心動了。

  博客里的一些文章我也喜歡：

  + [[https://e89295.com/blog/2026-01-15.html][我覺得直書的網頁很好]]

    關於作者為啥用直書，直書是很有特色，如果只是看中文還不錯，但是有不少英文時就讀的很難受。
    作者的直書排版在手機上也很不錯，
    +不過在桌面端，鼠標滾輪不响應橫向滾動，總得去拖拽滾動條我覺得不方便。+
    桌面上，因為鼠標滾輪默認是緃向滾動的，如果想控制橫向滾動，要按住 @@html:<kbd>Shift</kbd>@@。
    @@html:<small>(其實我都是改成緃向排版再讀的 (/ω＼) )</small>@@

  + [[https://e89295.com/blog/2026-01-14.html][我覺得註解很好]]

    作者關於注解的一些看法，學到了「夾注」這個說法，就是在正文後面用擴號擴起來的內容
    @@html:<small>(例如這樣)</small>@@ ，我原來也有用到，
    但作者將夾注用 [[https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/small][<small>]] 來標記，語義和顯示上都更好。
    ~<small>~ 更適合的場景是小聲吐槽、寫點碎碎念，如果是補充全称、解釋含義就不用了，直接寫在擴號𥚃就好。

    關於注解，之前我也分享過一些看法： [[denote:20251102T194217][关于 "Give footnotes the boot" 的思考]]。

  + [[https://e89295.com/blog/2026-01-14_1.html][有關破折號該用什麼字元來表示的問題]]

    不知道大家會用什麼，我一般都會用 ⸺ (Two Em Dash) 而不是 —— (分開的兩個 Em Dash)。[fn:1]

    在 Emacs 𥚃輸入 Two Em Dash 很容易，
    用 @@html:<kbd>C-x 8 Enter</kbd>@@ (~insert-char~) 就可以方便插入 Unicode 字符。

    現在網路上也有的人會覺得用破折號有一股 AI 味，可能還會怀疑文章是不是 AI 生成的，
    有的作者為此還放弃使用破折號。
    但我不在乎讀者是怎麼看待破折號的，有的地方就適合用破折號，該用就用。

    See also: [[https://psychotechnology.substack.com/p/em-dashes-are-fucking-amazing][Em dashes are fucking amazing]] by Sasha Putilin

    #+begin_quote
   「但如果我用了破折號，人們會怎麼看我的寫作？如果有人在我的文章中指出來怎麼辦？」。
    _婊子，拜託。你是在為一個除了尋找破折號之外沒別的事可做的網路路人寫作嗎？_

    [[https://psychotechnology.substack.com/p/em-dashes-are-fucking-amazing#:~:text=%E2%80%9CBut,dashes%3F][Source]]
    #+end_quote

  + [[https://e89295.com/blog/2026-02-18.html][有關「她」的問題]]

    #+begin_quote
    不論人字旁的「他」還是女字旁的「她」，右邊都是一個「也」字。
    如果你不知道的話，依據許慎《說文解字》的說法，「也」是一個象形字，畫的是女陰（女性生殖器）。

    [[https://e89295.com/blog/2026-02-18.html#:~:text=%E4%B8%8D%E8%AB%96%E4%BA%BA%E5%AD%97%E6%97%81%E7%9A%84%E3%80%8C%E4%BB%96%E3%80%8D%E9%82%84%E6%98%AF%E5%A5%B3%E5%AD%97%E6%97%81%E7%9A%84%E3%80%8C%E5%A5%B9%E3%80%8D%EF%BC%8C%E5%8F%B3%E9%82%8A%E9%83%BD%E6%98%AF%E4%B8%80%E5%80%8B%E3%80%8C%E4%B9%9F%E3%80%8D%E5%AD%97%E3%80%82%E5%A6%82%E6%9E%9C%E4%BD%A0%E4%B8%8D%E7%9F%A5%E9%81%93%E7%9A%84%E8%A9%B1%EF%BC%8C%E4%BE%9D%E6%93%9A%E8%A8%B1%E6%85%8E%E3%80%8A%E8%AA%AA%E6%96%87%E8%A7%A3%E5%AD%97%E3%80%8B%E7%9A%84%E8%AA%AA%E6%B3%95%EF%BC%8C%E3%80%8C%E4%B9%9F%E3%80%8D%E6%98%AF%E4%B8%80%E5%80%8B%E8%B1%A1%E5%BD%A2%E5%AD%97%EF%BC%8C%E7%95%AB%E7%9A%84%E6%98%AF%E5%A5%B3%E9%99%B0%EF%BC%88%E5%A5%B3%E6%80%A7%E7%94%9F%E6%AE%96%E5%99%A8%EF%BC%89%E3%80%82][Source]]
    #+end_quote

    [[https://zdic.net/hans/%E4%B9%9F#:~:text=%E5%A5%B3,%E9%87%8D%E4%B8%80][查了下確實是]]，我覺得可以投到 [[https://shuaixin.cc/Fun-Fact/][BlogBlog 同樂會：有趣的小知識或冷門概念]]。

- [[https://tracydurnell.com/2026/07/29/ai-or-not/][AI or not?]] by Tracy Durnell

  Tracy 看了本小說，虽然沒有証據，
  但字𥚃行間讓她怀疑像是用 LLM 寫的，那種揮之不去的疑慮破壞了她的閱讀體驗。

  我也有類似的感受，當我察覺到一篇文章可能是用 LLM 生成的，
  我就很多時候讀不下去了，一方面時讀著枯燥，另一方面我覺得作者在糊弄我，
  如果作者不想投入去寫，我也不想認真去讀，
  這樣的文字背後不是一個活生生、有情感的人，
  很難去和作品、和作者建立起關係。

  #+begin_quote
  _關於人類創作的好小說……_
  _重點不在於只有人類才能創作出它，而在於事實上確實是由人類創作出來的。_
  在「線路的那一頭」，真的存在另一個會思考、有情感的意識。
  當你閱讀作品時，你就與他們建立了一種關係。

  [[https://tracydurnell.com/2026/07/29/ai-or-not/#:~:text=%E3%80%8C%E9%97%9C%E6%96%BC%E4%BA%BA%E9%A1%9E%E5%89%B5%E4%BD%9C%E7%9A%84%E5%A5%BD%E5%B0%8F%E8%AA%AA%E2%80%A6%E2%80%A6%E9%87%8D%E9%BB%9E%E4%B8%8D%E5%9C%A8%E6%96%BC%E5%8F%AA%E6%9C%89%E4%BA%BA%E9%A1%9E%E6%89%8D%E8%83%BD%E5%89%B5%E4%BD%9C%E5%87%BA%E5%AE%83%EF%BC%8C%E8%80%8C%E5%9C%A8%E6%96%BC%E4%BA%8B%E5%AF%A6%E4%B8%8A%E7%A2%BA%E5%AF%A6%E6%98%AF%E7%94%B1%E4%BA%BA%E9%A1%9E%E5%89%B5%E4%BD%9C%E5%87%BA%E4%BE%86%E7%9A%84%E3%80%82%E5%9C%A8%E3%80%8E%E7%B7%9A%E8%B7%AF%E7%9A%84%E9%82%A3%E4%B8%80%E9%A0%AD%E3%80%8F%EF%BC%8C%E7%9C%9F%E7%9A%84%E5%AD%98%E5%9C%A8%E5%8F%A6%E4%B8%80%E5%80%8B%E6%9C%83%E6%80%9D%E8%80%83%E3%80%81%E6%9C%89%E6%83%85%E6%84%9F%E7%9A%84%E6%84%8F%E8%AD%98%E3%80%82%E7%95%B6%E4%BD%A0%E9%96%B1%E8%AE%80%E4%BD%9C%E5%93%81%E6%99%82%EF%BC%8C%E4%BD%A0%E5%B0%B1%E8%88%87%E4%BB%96%E5%80%91%E5%BB%BA%E7%AB%8B%E4%BA%86%E4%B8%80%E7%A8%AE%E9%97%9C%E4%BF%82%E3%80%82%E3%80%8D%E2%80%94][Source]]
  #+end_quote

- [[https://walknotes.com/2026/08/01/27-31-july-2026/][27 – 31 July 2026]] by Walknotes

  挺喜歡這樣的生活片段記录󠄃的，讀起來沒那麼流水帳。
  了解到了一個有趣的知識：

  #+begin_quote
 「兔子 兔子 兔子」是部分英語國家的一種迷信，
 人們會在每個月的第一天醒來時說「兔子」、「兔子們」或「白兔」，以確保該月餘下的日子都能有好運。

  [[https://en.wikipedia.org/wiki/Rabbit_rabbit_rabbit][Rabbit rabbit rabbit - Wikipedia]]
  #+end_quote

  可是月初已經過去了我才知道，我現在說還來得及嗎？Rabbit！

- [[https://shkspr.mobi/blog/2026/08/gadget-review-hikmicro-d02-thermal-camera/][Gadget Review: HIKMICRO D02 Thermal Camera]] by Terence Eden

  Terence Eden 對他 HIKMICRO D02 熱像儀的測評文章，
  他還用拍了張自拍，看到留言區有個人說「我必須說，你看起來容光煥發 (radiant)！」，笑死。

- [[https://danq.me/2026/07/02/you-dont-have-to-blog-like-me/][You don’t have to blog like me]] by Dan Q

  只管去寫就好了，不需要像任何人，也不必給自己諸多約束。
  不寫也是沒關系的，總之讓自己自在就好 :)

  文章是以信的形式呈現的，樣式不錯，信紙我「偷」了，或許以後能用上。

- [[https://danq.me/2026/07/09/your-app-could-have-been-a-webpage/][Your ‘App’ Could Have Been a Webpage (so I fixed it for you…)]] by Dan Q

  從 Cytrogen 的 [[https://blog.cytrogen.icu/posts/3456.html#:~:text=%E3%80%8A%E4%BD%A0%E7%9A%84%20App%20%E6%9C%AC%E5%8F%AF%E4%BB%A5%E6%98%AF%E4%B8%80%E4%B8%AA%E7%BD%91%E9%A1%B5%EF%BC%88%E6%89%80%E4%BB%A5%E6%88%91%E5%B8%AE%E4%BD%A0%E4%BF%AE%E5%A5%BD%E4%BA%86%E2%80%A6%E2%80%A6%EF%BC%89%E3%80%8B][想法在丙午瓜秋迭代]] 看到的。

  Webpage 不是挺好的嗎，天然就跨平台，無論什麼系統只要有瀏覧器就能訪問了;
  也不用在手機上裝那麼多 App 占用存儲空間，很多 App 也只是偶尔才會用上一次。

  有的軟件本來 Web 版本挺好的，但有了 App 之後體驗就差了很多，
  當你在手機上訪問時，總要引导你去下 App，否則就各種限制你的使用。
  一個例子就是 Bilibli，手機網頁體驗極差，
  你要關閉好几個彈窗才能開始看視頻，能看了你也不能控制播放器，
  點擊播放器就會暂停然後給你重定向去下載 App，簡直是一坨大便。
  在電脑上用，不登录󠄃時體驗也很差，看一會儿就會提示你快去登录󠄃，不停地打斷你。
  相比之下，YouTube 就好得多，不登录󠄃時，無論手機還是電脑，用起來都沒什麼問題，
  App 下在只在頂部提示一次，用户想用就下，不下載也不會影响網頁體驗。
  @@html:<small>@@(不過有的內容只在 Bilibli 上有，我也還是在用 (×_×))@@html:</small>@@

  App 當然也有好处，可以获得更好的性能、可以利用手機的更多能力、
  支持离綫使用、支持後台常駐、更持久的登录󠄃狀態⋯⋯
  但顯然有的 App 本來用網頁就足够了，
  做成 App 只是為了窃取你更多的信息、給你更多廣告、增加你的遷移成本。

- [[https://ratfactor.com/cards/personal-website][What should a personal website be?]] by Dave Gauer

  和上個連結類似，Dave 的想法也是儘管在你的網站做你喜歡的事。

  #+begin_details
  #+html: <summary>摘录</summary>

  #+begin_quote
  _個人網站首要之務應該是個人化。這意味著，它的結構和內容應該反映出你作為一個人想要呈現的東西。_
  [...]

  在你的網站上為自己做筆記，記錄你最喜歡的軟體的鍵盤快捷鍵或你不想忘記的名言，
  就像一本隨身筆記（wikipedia.org），對你自己來說可以是一個極佳的資源。
  而且其他人也會發現它很有用！
  我一直都這樣使用我自己的網站。
  當我不記得把筆記藏在哪裡時，我就會搜尋它。
  大多數（全部？）主要的搜尋引擎都允許你將結果縮小到某個網域，
  所以我幾乎可以從世界上任何一台電腦上，
  透過像這樣編寫我的搜尋查詢來找到我自己關於某個主題（例如「DWM」）的筆記：
  ~site:ratfactor.com dwm~ ，或者，如果我很懶（我通常都很懶），就只輸入 ~ratfactor dwm~ 。
  _套用 Linus Torvalds 的話說，「上傳你的東西，讓世界其他地方去鏡像它。」_

  _沒有錯誤的答案。_
  如果你想把它做成專業的作品集和履歷，那就去做吧。
  如果你想為你最喜歡的系列叢書或樂團製作粉絲專頁，那就去做吧。
  如果你想寫每日或每週的日誌式條目，把你的想法寫下來，那就去做吧！

  而且隨著時間的推移，我想你會發現我所做的事情：你實際上可以同時做所有這些事情。

  人們通常喜歡看到其他人是全面且各具特色的完整人類。
  （我確實如此，或許現在比以往任何時候都更甚！）
  _如果有人因為你沒有堅持單一的格式或主題而不喜歡你的網站，那麼，他們的意見到底值多少錢，你懂我的意思嗎？_

  [[https://ratfactor.com/cards/personal-website#:~:text=options%2E-,A,saying][Source]]
  #+end_quote
  #+end_details

  #+begin_quote
  如果我只能給你一個建議，那就是你可以隨時回來編輯頁面！你應該編輯頁面。
  擴展內容、改變主意、在靈感湧現時先寫下草稿，之後再完成它。
  實踐 [[https://ratfactor.com/cards/digital-gardening][數位園藝]]。

  [[https://ratfactor.com/cards/personal-website#:~:text=If%20I%20had,Gardening%2E][Source]]
  #+end_quote

  我很喜歡「數位園藝」這個說法，我也會經常編輯我的博客，
  修正錯字、讓某些句子更通順、补充信息以及調整樣式讓博客更好閱讀，確實和園藝很像。

  #+begin_quote
  如果你的建築雜草叢生，人行道破裂（恭喜你，你有絆倒的危險），
  內部也佈滿灰塵，那麼吸引高品質訪客的可能性就會降低。
  這同樣適用於你的網路資產。

  如果你想建立一個會持續回訪的受眾，請確保你的網站、部落格、作品集或相冊處於良好狀態。
  它不需要像素級的完美，但需要顯示出作者仍在經營，並且有理由讓人駐足。

  [[https://den.dev/blog/be-a-property-owner-not-a-renter-on-the-internet/#1-have-your-own-property-on-the-web:~:text=If%20your%20building,in%20good%20shape.][Be A Property Owner And Not A Renter On The Internet]] by Den Delimarsky
  #+end_quote

- [[https://brennan.day/phoneblogging/][Phoneblogging]] by Brennan

  Brennan 分享了一些用手機寫博客的看法，也收集了其他人對此的看法。

  我不用手機寫博客，只會用備忘录󠄃簡單記录󠄃點東西。
  如果只是寫純文本，手機是可以胜任的，但要以 markdown 或 org-mode 格式寫，操作起來就很麻煩。
  所以問題可能是缺少一個交互足够好的，用於寫 markdown 或 org-mode 的應用？

- [[https://trashposts.com/blog/mario-mouse-pointer/][瑪利歐滑鼠指標]] by 廢文小天地

  蠻好玩的。我也改了指針的樣式，讓它變大了不少，不用廢勁去找指針的位置。

- [[https://www.sciencealert.com/humans-can-echolocate-and-it-changes-the-wiring-of-the-brain][Humans Can Learn to Echolocate in Just 10 Weeks, And It Rewires The Brain]] by David Nield

  研究表明，只要 10 周，人類也能掌握回聲定位。

- [[https://itsfridayimnotinlove.substack.com/p/its-friday-im-not-in-love-issue-254][It's Friday I'm (not) in love - Issue #254]] by Alessia Carlozzo

  打算把文章分享的電影 [[https://zh.wikipedia.org/zh-hant/%E6%9B%BE%E7%B6%93%E3%80%82%E6%84%9B%E6%98%AF%E5%94%AF%E4%B8%80][曾經。愛是唯一 (Once)]] 找來看看。

* Cool Bit
:PROPERTIES:
:CUSTOM_ID: FFD649F1-1A78-4DF8-BA99-06F8CFA300C9
:END:

- [[https://www.bbc.co.uk/news/magazine-23536914][Alfredo Moser: Bottle light inventor proud to be poor - BBC News]]

  在房頂上放裝滿水的瓶子，折射太陽光給室內提供照明，想法真好，成本低也環保。
  不過瓶子放久了會積灰吧，時間長了還得上去擦干净？

- [[https://litter.leaflet.pub/][linklog]]

  作者會整理關於某個主題的連結製作成 linklog，例如有 [[https://litter.leaflet.pub/3lwoovsp6xs26][關於鳥的]]，[[https://litter.leaflet.pub/3mdc6dlxpqk2c][關於照片的]]，[[https://litter.leaflet.pub/3mqigkjguw22u][關於地圖的]]。

- [[https://www.spriters-resource.com/][The Spriters Resource]]

  網站上收集了很多游戏相關的圖片資源。

- [[https://www.openculture.com/2026/07/japanese-woodblock-prints-illustrate-the-human-body.html][19th Century Japanese Woodblock Prints Creatively Illustrate the Inner Workings of the Human Body]] by Open Culture

  以創意手法描繪人體內部運作的浮世繪。

- [[https://rubberduck.greg.technology/][rubber duck]]

  #+begin_quote
  和一个穿橡皮鸭装的人说话！看他如何对你说的话作出反应！
  这里并没有真正的交互 —— 视频基本上是设置成对你说话时的停顿“作出反应 ”—— 但这种幻觉奇怪地令人信服。

  [[https://webcurios.co.uk/webcurios-31-07-26/#:~:text=Talk,convincing][Webcurios 31/07/26]] by Matt
  #+end_quote

- [[https://www.augmental.tech/][MouthPad]]

  #+begin_quote
  MouthPad 是一款客製化的口內裝置，能將細微的舌頭與頭部動作轉化為對手機、平板電腦及電腦的精確控制。
  #+end_quote

  之前在 [[https://www.bilibili.com/video/BV1YydJBJEuF?t=248.8][【何同学】为了随地大小坐，我们做了这个]] 也看到類似的工具。

- [[https://photography.mangroveactionproject.org/winners/winners-2026][Mangrove Photography Awards 2026 Winners Gallery]]

  2026 年紅樹林攝影大獎賽獲獎者展廳。

- [[https://michaelnordeman.tumblr.com/][Michael Nordeman Photography]]

  Michael Nordeman 的摄影集，主要是一些動物、昆蟲、自然風㬌。

* Tutorial | Resource
:PROPERTIES:
:CUSTOM_ID: 1C3EFE5D-17BE-4334-B20B-517FE7D63C3A
:END:

- [[https://thirdshire.com/latte-art/][如何用法压壶拉花]] by 白石京(Kyo)

  佩服 Kyo，我也有近似的設備但沒做成，嘗試得也不多。
  能寫出這樣一篇教程，我想是因為喜歡和熱愛。

- [[https://perthirtysix.com/how-the-heck-does-jpeg-work][How The Heck Does JPEG Work? (An Interactive Exploration)]] by Shri Khalpada

  冷知識，
  JPEG 的全称是 Joint Photographic Experts Group (聯合圖像專家小組)，即 1992 年創建該格式的標準委員會。

* Code Related
:PROPERTIES:
:CUSTOM_ID: 19104BD0-3D64-4863-BE2F-F3C4925800C6
:END:

- [[https://stuffandnonsense.co.uk/blog/swapping-a-lightweight-image-for-an-animated-svg/][Swapping a lightweight image for an animated SVG]] by Andy Clark

  作者網站有一些 SVG 動畫，原來不管用户是否能看到都會加載，
  會影响頁面加載性能和降低用户體驗，
  於是他优化了一下，基於媒體查詢决定資源如何加載。

- [[https://csswizardry.com/2026/07/meaasuring-component-performance-with-the-container-timing-api/][Measuring Component Performance with the Container Timing API]] by Harry Roberts

  文章介紹了如何 [[https://github.com/WICG/container-timing][Container Timing API]]，以及如何用它來監測頁面中某個組件的性能。
  目前只有 Chrome 支持這個 API。

- [[https://master.dev/blog/when-you-need-to-make-a-triangle-think-conic-gradients/][When You Need To Make a Triangle, Think Conic Gradients]] by Chris Coyier

  利用 [[https://developer.mozilla.org/en-US/docs/Web/CSS/Reference/Values/gradient/conic-gradient][Conic Gradients]] 繪製三角型。

- [[https://nerdy.dev/css-infinity-use-cases][CSS Infinity Use Cases]] by Adam Argyle

  文章分享了一些 [[https://developer.mozilla.org/en-US/docs/Web/CSS/Reference/Values/calc-keyword#infinity][CSS Infinity]] 的用例，當需要一個極大值時會很方便。

- [[https://github.blog/security/supply-chain-security/disrupting-supply-chain-attacks-on-npm-and-github-actions/][Disrupting supply chain attacks on npm and GitHub Actions]]

  GitHub 整理了近些年出現的供應鏈攻擊，以及 GitHub 對此的應對措施。

  See also:

  - [[https://evilmartians.com/chronicles/the-secure-way-to-release-an-npm-package][The secure way to release an npm package in 2026]]

    主要也是用關於 GitHub 的。

- [[https://blog.jim-nielsen.com/2026/ai-aesthetic/][The AI Aesthetic]] Jim Nielsen

  AI 美學，作者整理了一些常見的 AI 相關的 UI 設計。

* AI Related
:PROPERTIES:
:CUSTOM_ID: FD8CA9D7-995F-467B-8A92-9803EE5553A4
:END:
- [[https://github.com/herdrdev/herdr][herdrdev/herdr]]

  #+begin_quote
  agent multiplexer that lives in your terminal.
  #+end_quote

* Tool | Library
:PROPERTIES:
:CUSTOM_ID: 48C81D70-72E9-4C4D-9305-22D15A2BF1B3
:END:

- [[https://artemis.jamesg.blog/][Artemis]]

  #+begin_quote
  A calm web reader.
  #+end_quote

  之前在 [[denote:20260512T095952::#FF319C35-80BD-4CA6-931E-A102E10B4009][Zine#49::Going back to the morning newspaper model by Chandru]] 分享一種管理訂閱信息的方法，
  裡面提到可以做成像每日报紙一樣的形式，目的是讓訂閱流從無限變成有限，减少看不完的焦慮感，
  而這個應用的 [[https://jamesg.blog/2024/11/30/designing-a-calm-web-reader][設計理念]] 也是類似的。

  另外我看到 Cytrogen 在做 [[https://blog.cytrogen.icu/posts/3456.html#:~:text=%E5%8E%86%E7%A8%8B-,RSS%20%E6%97%A5%E6%8A%A5][日报工具]]，如果你看到的話，或許你也可以試試這個應用。

  我自己倒是沒用日报，日报的目的是限制信息量，减少那種看也看不完的焦慮。
  我目前的做法是在 [[denote:20260618T142353][Elfeed]] 裡限制了只看最近 8 天的內容，內容不會很多，
  每天看一看很快就看完了，有時還會覺得不够看。
  至於 8 天之外的內容，當我不够看時我會擴大點范圍找來看看，
  而我不看的時候它們就安靜地躺在 Elfeed 裡，
  不會出現在我的閱讀頁面，也就不會覺得有太多沒看而感到焦慮。
  在我看來，重點就在於營造這種「有限」，讓自己自在，形式就無所謂了。

- [[https://tryklack.com/][Klack]]

  #+begin_quote
  Satisfying sound with every keystroke.
  #+end_quote

  一個 macOS 應用，模拟機械鍵盤的聲音，提升 MacBook 上的打字體驗。

- [[https://enso.sonnet.io/][Ensō—Write now, edit later.]]

  一個 macOS 上的寫作應用。

  #+begin_quote
  文字會在您輸入時逐漸消失，讓您可以專注於想說的話，而非表達的方式。

  您無法選取或編輯文字，但完成後可以下載並查看。
  #+end_quote

- [[https://wotja.com/app/][Wotja]]

  #+begin_quote
  Wotja is a FREE, powerful & 'AI-free' system for Live Generative Music & MIDI.
  #+end_quote

- [[https://scriptc.dev/][scriptc]]

  #+begin_quote
  TypeScript to Native Compiler.
  #+end_quote

  #+begin_example
  $ cat fib.ts
  function fib(n: number): number {
    return n < 2 ? n : fib(n - 1) + fib(n - 2);
  }
  console.log(fib(30));

  $ scriptc run fib.ts
  832040

  $ scriptc build fib.ts -o fib && ./fib
  832040
  #+end_example

- [[https://canvasui.dev/][Canvas UI]]

  #+begin_quote
  Canvas UI 是一個開源的創意組件庫，所有組件均在畫布（canvas）上繪製。
  真實的 HTML 在 canvas 元素內渲染，並在其上運行 WebGL 效果。
  #+end_quote

- [[https://github.com/openstyles/stylus][openstyles/stylus]]

  #+begin_quote
  Stylus is a browser extension to restyle the websites via CSS themes,
  compatible with Chrome, Firefox, and any Chromium-based browsers.
  #+end_quote

- [[https://github.com/img2threejs/img2threejs][img2threejs/img2threejs]]

  #+begin_quote
  Rebuild the object in a reference image as a
  code-only, procedural, quality-gated, animation-ready Three.js model.
  Token-efficient image-to-3D.
  #+end_quote

* Emacs
:PROPERTIES:
:CUSTOM_ID: 5C5D5D7D-9DCE-4561-9821-E431CA85698C
:END:
- [[https://protesilaos.com/codelog/2026-07-29-emacs-default-minibuffer-completion-overview/][Emacs: default minibuffer completions overview (Emacs 31)]] by Protesilaos

  minibuffer 𥚃的补全我用的是 [[https://github.com/minad/vertico][minad/vertico]]，如果不想依赖擴展，
  Protesilaos 分享了在 Emacs 31 如何用內置的功能去替代 vertico。

  See also: [[https://rahuljuliato.com/posts/completions-buffer-is-now-enough][The Completions Buffer Is Now Enough]] by Rahul
- [[https://protesilaos.com/codelog/2026-07-31-re-linkarzu-what-i-need-from-emacs/][Reply to @linkarzu about ‘What I Need From Emacs’]] by Protesilaos

  #+begin_details
  #+html: <summary>摘录</summary>

  *你不一定需要 Emacs*

  我常對他人說，也會對 Christian 說的是：
  _在投入之前，務必清楚自己「為什麼」想要某樣東西。_
  _這就是你在遇到挫折時仍能堅持下去的動力。_
  _如果沒有這個「為什麼」，幾乎可以肯定你會半途而廢。_

  NeoVim、Kitty 及其相關工具結合起來，幾乎可以提供 Emacs 的所有功能。
  使用者可能會爭論每種方法的優缺點，但我個人認為這會分散注意力，
  因為真正重要的是擁有一個能完成工作的運算環境。
  然而，要點在於，如果 NeoVim 加上額外擴充對你有效，
  那麼切換到 Emacs 並不會讓你真正獲得什麼：這充其量只是平級遷移。

  更重要的是，如果你目前的配置已能滿足所有需求，你就沒有強大的理由，也因此缺乏持續嘗試 Emacs 的動力。
  對我來說也是一樣：Emacs 滿足了我的需求，
  所以我沒有熱情 —— 事實上也沒有好奇心 —— 去花時間研究其他選項。
  也許那些選項非常出色，甚至可以配置得比我的 Emacs 更優越。
  但現有的工具符合我的工作流，所以我沒有情感上的衝力去另尋他路。

  如果沒有「為什麼」，幾乎不可能堅持任何實驗：回歸到你熟悉的狀態永遠看起來更合理。

  [[https://protesilaos.com/codelog/2026-07-31-re-linkarzu-what-i-need-from-emacs/#:~:text=You%20do,with,-%2E][Source]]
  #+end_details
- [[https://ashishpanigrahi.com/blog/o365-offline-email/][Setting up offline email for Microsoft O365 with notmuch and emacs]] by Ashish Panigrahi

  之前想配置 Emacs 來收發邮件，但卡在了 Hotmail 的授權，或許可以再嘗試一下。
  其實不用 Hotmail 就容易得多了。

* 一些话 | 摘抄
:PROPERTIES:
:CUSTOM_ID: 7F3EEEC9-9B61-4DB5-886F-9BF6810642E6
:END:
- [[https://andrewkelley.me/post/dont-take-black-pill.html][Don't Take the Black Pill (Text Adaptation)]] by Andrew Kelley

  #+begin_quote
  作為年長的一代，我們的任務是保護年輕人免受那些企圖利用他們天真的人傷害，
  同時不將我們自己累積的痛苦與憤世嫉俗傳染給他們。

  [[https://andrewkelley.me/post/dont-take-black-pill.html#:~:text=Our%20task%2C%20as%20the%20older%20generation%2C%20is%20to%20shield%20the%20youth%20from%20those%20who%20would%20exploit%20their%20na%C3%AFvet%C3%A9%2C%20without%20infecting%20them%20with%20our%20own%20accumulated%20pain%20and%20cynicism][Source]]
  #+end_quote
* 多媒体
:PROPERTIES:
:CUSTOM_ID: 983B085C-963E-4D6E-B83F-19ACB66F8A2F
:END:

** 视频
:PROPERTIES:
:CUSTOM_ID: EF62A2EA-DEBB-4667-A021-C526C1AFD8DB
:END:
- [[https://www.bilibili.com/video/BV1aP326jEi8/][手绘 469 张！还原 EVA 主题曲]] (02:03) by 棕与灰9
- [[https://www.bilibili.com/video/BV1gYGc6XEQR/][王老菊教你理线大师]] (1:10:54) by 怕上火暴王老菊
- [[https://www.bilibili.com/video/BV1M7Jw6MEYR/][恐怖片，才是最懂当代年轻人的电影！《后室》《痴迷》深度解读]] (14:31) by 切片计划
- [[https://www.bilibili.com/video/BV1jB3q6wEbD/][《痴迷》爆火：为什么"老实人"反而更可怕？【对话导演Curry Barker】]] (10:40) by 切片计划
- [[https://www.bilibili.com/video/BV1NSGA6SEhw/][就是这 5 家公司打造出了所有人都怀念的 80 年代日本音乐?!]] (21:52) by Hopico
- [[https://www.bilibili.com/video/BV1HaG36PEju/][外国鼓手第一次听“山海”]] (46:22) by 即兴鼓研社
* Footnotes
:PROPERTIES:
:CUSTOM_ID: 217BC21F-385A-4C1A-B27E-7DAA4862E546
:END:

[fn:1] [[https://www.w3.org/TR/clreq/#id82][Requirements for Chinese Text Layout - 中文排版需求 / 破折号]]

#+begin_quote
破折号表示语气或声音的延续、语意的转换或行文的补充。
呈现上为一条在水平和垂直方向均位于字面正中的直线，占两个汉字空间。
推荐使用占两个汉字宽度的 ~U+2E3A TWO-EM DASH~ [⸺]，
但通常也使用两个连续的 ~U+2014 EM DASH~ [—]来实现。
#+end_quote

# Local Variables:
# org-cycle-include-plain-lists: integrate
# End:
