#+title:      Zine#58
#+subtitle: 用合理的排版引导讀者閱讀、值得熬夜的事情都值得早起
#+export_file_name: 58
#+date:       [2026-09-16 Wed 17:45]
#+filetags:   :published:zine:
#+identifier: 20260901T091207
#+bind:       denote-directory "~/git/taxodium/posts"
#+description: Zine 第 58 期，分享一些看到的文章、资源、电影、书籍
#+language: zh-CN
#+author: Spike Leung
#+email: l-yanlei@hotmail.com
#+options: ^:{} toc:nil
#+startup: content hideblocks

#+begin_details
#+html: <summary>目錄</summary>

#+TOC: headlines 1 local
#+end_details

這周又聴了陳嫻静的「如果每天都可以 happy happy 谁想要sad:)) - 一起去度假」 ，
在評論區看到有人說「喜歡這張專輯的大概率也會喜歡 Men I Trust 的音樂」，
於是就把 Men I Trust 的專輯都找來聴了聴，還沒聴完，確實也蠻喜歡的。
他們的風格偏向 [[https://en.wikipedia.org/wiki/Dream_pop][Dream pop]]，整體聴著相對舒緩，主唱 Emmanuelle Proulx 的聲音也好聴。
聴 Men I Trust，還會讓我想到另外兩支樂隊： [[denote:20251012T094029][The Fur.]] 和 The Cheers Cheers。
如果你想找點歌聴，就去聴聴他們的音樂吧 :)

* News | Article
:PROPERTIES:
:CUSTOM_ID: F946DD43-D990-4EE9-91F8-E09AD25CDF2B
:END:

- [[https://burgeonlab.com/notes/2026/0831-1939/][Some Thoughts on Advice]] by Naty

  一些 Naty 認為不錯的建議，其中有兩條我會試試：

  + 與其將想做的事情列入人生清單，不如將它們排進你的行事曆進行時間區塊管理。
  + 把所有重要的事養成習慣。

  把願望、目標，變成日程裡具體要做的事，確實有助於實現，想做就要安排自己去做。
  要具體到一件可以行動的事，模糊的事會讓自己有籍口去拖延。
  重點還是去行動。

- [[https://tallywinkle.bearblog.dev/my-tarot-decks/][my tarot decks]] by Coffee Spills

  作者分享了她的一些塔羅牌，那盒 [[https://shingyinkhor.bigcartel.com/product/the-strange-beast-tarot][The Strange Beast Tarot]] 確實好看。

- [[https://danq.me/2026/08/25/polyamory-boring-bedrooms/][Boring Polyamory: Equality and Bedrooms]] by Dan Q

  關於多元戀和公平，另見： [[https://taonaw.com/2026/08/30/fairness-and-content.html][Fairness and content]] by The Art Of Not Asking Why

- [[https://tracydurnell.com/2026/08/30/my-emergency-food-supply/][My emergency food supply is extra normal food]] by Tracy Durnell

  Tracy 分享了她如何準備應急粮的。

- [[https://tracydurnell.com/2026/08/31/formatting-as-courtesy-to-the-reader/][Formatting as courtesy to the reader]] by Tracy Durnell

  Tracy 的文章裡往往有大量的粗體標記，
  她用這些標記「創造了一條論點路徑，讀者可以像踩著踏腳石一樣在其中跳躍」，從而便於讀者略讀。
  粗體是在文章中是很突出的，也很搶眼，設計過的粗體可以方便讀者快速了解要點，决定是否要細讀。

  這個方法值得學習，要用好也是有一些要注意的：

  - 應該有目的的用，不要為了用而用，合理地標記要點，起到引导讀者的作用。
  - 要注意數量，如果太多粗體，那相當於沒有粗體。有對比才會顯得突出。

  適量的使用標記，可以讓文本看起來更有层次感，
  但過多了也會顯得凌亂，讓人找不到重點，要通過實踐去把握那個度。

- [[https://dbushell.com/2026/09/04/plagiarism/][Plagiarism ain’t cool bro :(]] by David Bushell

  作者的博客樣式被抄裘了，而且抄得不怎麼樣，對方也沒和作者說一聲，也沒標注出处，還挺過分的。

  如果我的樣式被抄了會怎樣呢？
  我應該不會生氣，毕竟樣式代碼是 [[https://www.gnu.org/licenses/agpl-3.0.en.html][AGPL]] 許可，只要保持相同的許可，代碼請按需要自由調整。
  不過如果真要抄，我希望抄好一點，可以參考 [[denote:20250408T151102][CHANGELOG]]，裡面有相關文檔。

  但話又說回來，如果願意花時間去複刻一個博客的樣式，
  為什麼不花些時間去設計一個有自己特色的樣式呢？

- [[https://song.al/amami][日本浮生錄 ｜探秘奄美大岛，寻找南国秘境]] by Simon

  風景很好看。

- [[https://forkingmad.uk/post/conversations-with-my-mother][Conversations with my mother]] by Forking Mad

  作者記錄了一通他和母親的對話，有點好笑又有點可愛。

- [[https://clandestini.org/blog/planner-journal-ecosystem-atual/][planner & journal ecosystem atual]] by Dani.ela

  作者分享了她的手帳與日誌生態。

- [[https://gwern.net/on-really-trying][On Really Trying]] by Gwern

  文章中用了大量的例子說明一個道理，即相信才能看見。

  #+begin_quote
  學生：一個人要如何才能證悟自性？我對這方面的了解實在太少了。

  安谷：首先，你必須深信自己能夠做到。
  信念產生決心，決心產生熱忱。
  但如果你缺乏信念，如果你想著「也許我能證悟，也許我不能」，
  甚至更糟地想著「這超出了我的能力範圍！」
  ——那麼無論你坐禪多久，你都不會覺醒。

  [[https://gwern.net/on-really-trying#:~:text=Student,zazen][Source]]
  #+end_quote

- [[https://granta.com/the-couples-therapist/][The Couple’s Therapist]] by Ellika Lagerlöf

  以為是一篇關於兩夫妻看伴侶治療師去修複關係的故事，然後看到了：

  #+begin_quote
  接著我去看醫生，我的肝功能指數簡直是災難性的。
  醫生給我看 X 光片，整個器官腫大到原來的兩倍。
  經過幾項不同的檢查後，醫生緊急安排了移植手術。
  隨著手術臨近，透過一連串複雜且極其昂貴的交易以及一些威脅信，
  我成功賄賂了其中一名外科醫生，讓他把切除的肝臟給我。
  肝臟被裝在一個密封的塑料袋裡送到我們家，上面用黑墨水寫著我的社會安全號碼。
  我割開塑料，小心翼翼地取出肝臟放在砧板上。
  刀子輕易地滑了過去。接著我按照食譜操作，這意味著我還得買一台食物調理機。
  做法是將它切成小塊，用中火煎熟，然後加入奶油、洋蔥和香料混合。
  最後，我加入了一點白蘭地、榛果、多香果和蔓越莓進行攪拌，不過你可以根據自己的喜好調味。
  這道菜隨後被放入冰箱冷藏直到肉醬變得容易塗抹。
  隔天早上，我為古斯塔夫準備了床上早餐——兩份切了薄片醃黃瓜的背心三明治，
  托盤上還有一杯咖啡和我插在小花瓶裡的一朵花——然後端了進去。
  他剛醒來，坐在床上，頭髮凌亂，揉著眼睛，眨眼瞇著瞧，才意識到那是什麽。
  接著他神采奕奕。「給我的？」他驚呼道，並吻了我好幾次。

  [[https://granta.com/the-couples-therapist/#:~:text=Then%20I,times][Source]]
  #+end_quote

  啊？

- [[https://thelondonmagazine.org/article/essay-voice-memories-by-ian-wang/][Voice Memories]] by Ian Wang

  作者有一段時間，沒事就會打開錄音，錄下家人平時的對話，不知覺間就積累了近 45 個小時的錄音數據。
  數據太多了他也沒空轉成文本，錄音裡也衹是一些平常的對話，有很多環境音，也有不少沉默的時候。
  最終這些錄音有什麼用呢，好像什麼用都沒有。

  #+begin_quote
  我內心較為陰鬱的部分在想，當父母離世時，這座音訊檔案庫會帶給我慰藉，他們的聲音和舊日對話的回憶會支撐著我。
  但在內心深處，我不相信這一點。
  不像家庭錄影帶那樣帶有一種笨拙、類比時代的魅力，這些錄音對我來說沒有懷舊感。
  最刻薄的評價是，它們是一個憂鬱的 22 歲青年的愚行，他相信這種偏執的追尋和數位失真能賦予永恆。
  按下「錄音」鍵時，我試圖讓過去保持鮮活，
  但我認為我真正做的是敲響了它的喪鐘，標誌著它從生活凝固成回憶的時刻。
  這就像給一名演員頒發終身成就獎，這本應是慶祝的姿態，實際上卻象徵著你的不再重要。

  [[https://thelondonmagazine.org/article/essay-voice-memories-by-ian-wang/#:~:text=The%20more,award%29%2E][Source]]
  #+end_quote

- [[https://jetgirl.art/restaurant-stories-pt-1-the-new-guy-isnt-going-to-make-it/][Restaurant Stories Pt 1: The New Guy Isn't Going to Make It.]] by Melinda

  文章記錄了作者大學時在一家日式鐵板燒兼壽司店打工的一些見聞。

- [[https://shkspr.mobi/blog/2026/09/the-expectations-of-privacy-in-driverless-cars/][The expectations of privacy in driverless cars]] by Terence Eden

  無人駕駛的出租車，虽然沒有司機，但也不是一個安全的隱私空間，
  車上有攝像頭在時刻注視著你的一舉一動，一言一行。
  如果你干坏事了，出租車還會好心地送你去警局。

- [[https://winnielim.org/journal/the-city-that-saved-me/][the city that saved me]] by Winnie Lim

  作者一度對自己的人生很失望，甚至想輕生。
  她很喜歡 Apple 的產品，於是决定哪怕要輕生，也要在那之前去 Apple 總部看看，而這一次遠行，完全改變了她。
  為什麼會有這麼大的變化，作者也說不上來，也許是新的環境給人一種可以拋去過去，重新開始的希望吧。

  #+begin_quote
  我想如果非要總結的話，那是因為：
  當我們在某種特定的環境或情況下成長和生活時，往往會認為生活就是某種固定的樣子。
  似乎無法逃離那樣的生活，因為它的社會、規則、習俗和人際關係動態都是以特定的方式塑造的。
  這決定了我們如何看待生活、他人以及自我。
  更重要的是，它也決定了別人如何看待我們。
  我們中的許多人都無法擺脫他人強加在我們身上的框架。

  一旦我體驗了一個全新且不同的環境，我的心理便產生了突破。
  我曾以為我會去那裡等死，從某種意義上說，我確實死去了。
  舊我很大的一部分消亡了。
  我意識到生命和生活有不同的方式，而我找不到比那裡更好的地方來教會我這一點。

  [[https://winnielim.org/journal/the-city-that-saved-me/#:~:text=me%2E-,I,that%2E][Source]]
  #+end_quote

- [[https://francescrossley.com/pizza-friday-and-other-traditions/][Pizza Friday and other traditions]] by Frances

  Traditions can be whatever!

  [[https://zh.wikipedia.org/zh-tw/%E4%BC%A0%E7%BB%9F][傳統]] 是一些具有象徵意義或特殊意義的事，每周五吃披薩當然也能是一個傳統 :P

- [[https://chrismaiorana.com/read-more/][The Year You Became a Reader]] by Chris

  作者分享了一些技巧，告訴你如何可以讓自己多讀些書：

  + 劃分一些時間用於閱讀，并逐漸增加閱讀時長，以閱讀時長為目標，而不是閱讀數量。
  + 剛開始閱讀可能看不進去，給自己一些「熱身」時間，例如 15 分鐘，讓自己能進入閱讀狀態。
  + 讀自己喜歡的，不用在意別人怎麼說，也不用在意有沒有價值，總之要跟隨自己真實的內心。

    #+begin_quote
    千萬不要只因為覺得自己應該讀，或是覺得聰明人都會選這些書，就一上來挑戰難度最高的杜斯妥也夫斯基或托爾斯泰。

    [[https://chrismaiorana.com/read-more/#:~:text=By%20all%20means%2C%20don%E2%80%99t%20start%20in%20the%20deep%20end%20with%20Dostoyevsky%20or%20Tolstoy%20just%20because%20you%20think%20you%20should%20or%20because%20that%E2%80%99s%20what%20smart%20people%20would%20pick][Source]]
    #+end_quote

  + 允許自己同時讀多本書，不必強迫自己先讀完某本書。

    #+begin_details
    #+html: <summary>摘录</summary>

    #+begin_quote
    同時閱讀多本書，這樣你就可以根據情境對它們進行分類。

    _我再寫一遍。你有權同時閱讀多本書。_
    _你並沒有因為在讀主要書籍的同時看另一本書而對它不忠。_
    這實際上是增加你總體閱讀時間的高明策略。

    你需要開始考慮根據當下的情境來閱讀，而不是出於義務。

    義務：「噢，我必須讀這本書，因為它現在是很紅的系列，我所有的朋友都在討論它，但這內容簡直是垃圾。
    我討厭閱讀。Instagram 上現在有什麼新鮮事？」

    情境：「我現在在機場，無法專注於中土世界，但我絕對可以沉浸在這部寫實的真實犯罪劇中。」

    _基本上，如果你處於錯誤的生理或心理狀態，無法好好享受閱讀，就不要勉強去讀。_
    _這是為了樂趣，而不是在做功課。_

    你可能會想：「如果我同時讀好幾本書，就永遠讀不完了。」
    這簡直是胡說八道。
    如果你開始根據當下的情境而非要求來閱讀，你會發現自己讀完書的速度，快到連找新書都來不及。

    電子閱讀器讓這一切變得前所未有的輕鬆。
    你不再需要受限於包包或口袋裡僅能塞進的那一本書，現在你可以隨身攜帶整個圖書館。

    _情境也有助於我上面提到的「熱身」過程。_
    _在你目前的閱讀清單中，最好能同時包含幾本輕鬆讀物和一兩本具挑戰性的著作。_

    _策略：利用輕鬆的讀物作為進入閱讀狀態的「熱身」。_
    _當你的大腦進入狀態後，就可以切換到難度較高的內容。_

    總而言之，午休時間就別讀亨利·詹姆斯了。

    在一個月內，你可能會在床上或上廁所時讀幾本實體書，午休時讀幾本電子書，散步或慢跑時聽本有聲書。輕輕鬆鬆。

    正如你內心的閱讀修行者所言， *無論你走到哪裡，你的書就在哪裡。* 合十禮。

    [[https://chrismaiorana.com/read-more/#:~:text=Read%20multiple,Namaste%2E][Source]]
    #+end_quote
    #+end_details

  我最近都沒看書，倒不是沒時間，只是沒有把時間留給看書。
  也沒有強烈的看書的念頭。
  其實有列一份閱讀清單，但上面的書現在看來也不是我很感興趣的，只是我覺得我「應該」去讀一下。
  看書最多的時間，反而是在通勤和出遊的時候，沒別的事做時才找來看看。
  能長時間看下去的更多是小說，被故事吸引時，就會想一直看下去。
  所以，我想我要做的，是去找一些喜歡的，感興趣的小說來看看，Read what you love until you love to read。

  之前看到 Sol 的 [[https://blog.solazy.me/20260729/][承认吧，你其实根本不爱看书]]，說實話，我有點被說中了，
  在 Zine 裡要罗列自己看過的書，看完了要求自己得寫出一些讀後感發佈出來，
  多多少少有些想營造自己喜歡閱讀的設定。

  不管如何，我還是想多讀几本書，
  我會嘗試每天劃出一段時間來閱讀 @@html:<small>@@(也許是睡前)@@html:</small>@@，找點真的很感興趣的書來看看。
  [[denote:20250504T213941][读书应该是一种享受]] 早就說過了，但到頭來還只是說說，但沒落實到行動，那就再試一次。

- [[https://schafe-sind-bessere-rasenmaeher.de/mindfulness/you-dont-need-to-be-good-at-your-hobbies/][You don't need to be good at your hobbies]] by Schafe sind bessere Rasenmäher

  #+begin_quote
  隨著網路上不斷湧現的「完美」事物，我往往會忘記，僅僅去做和製作平庸的東西也是可以的。
  我往往會忘記，愛好的核心部分是玩得開心。

  [[https://schafe-sind-bessere-rasenmaeher.de/mindfulness/you-dont-need-to-be-good-at-your-hobbies/#:~:text=With%20the%20constant%20barrage%20of%20%E2%80%9Cperfect%E2%80%9D%20things%20on%20the%20internet%2C%20I%20tend%20to%20forget%20that%20it%E2%80%99s%20okay%20to%20just%20do%20and%20make%20mediocre%20things%2E%20I%20tend%20to%20forget%20that%20the%20main%20part%20of%20a%20hobby%20is%20to%20have%20fun%2E][Source]]
  #+end_quote

  喜歡就去做，作為愛好，自己能樂在其中就够了，不用非要達到什麼高度才行。

- [[https://ohhelloana.blog/tell-the-speakers/][Tell the speakers that you liked their talks]] by Ana Rodrigues

  作者說她演講後沒有收到任何回應，讓她不知道自己的表現如何，她希望能得到一些回應。

  #+begin_quote
  所以，如果你一直想這麼做，卻覺得不值得特地去告訴講者你喜歡他們的演講，這篇貼文就是給你的鼓勵。
  即便只是簡單打個招呼或小聊幾句，這永遠都是值得的。
  大家在演講上投入了大量心血，都希望聽眾能樂在其中，而且至少對我來說，我確實挺想知道自己表現得好不好。

  [[https://ohhelloana.blog/tell-the-speakers/#:~:text=So%2C%20if,alright][Source]]
  #+end_quote

  對於一些博客、視頻作者等也是類似的，如果他們的內容有触動到你，
  而你有想表達喜歡的想法，請大胆地去給他們留言吧，我想大多數作者會很開心的。
  再次引用那句話：

  #+begin_quote
  推论是，如果你发现了那篇帖子，就说点什么。
  给作者发个消息，留个评论。
  没有其他人这样做。
  互联网上有成千上万的人在发布优质内容，却不知道是否有人看到或欣赏。

  [[https://news.ycombinator.com/item?id=43155587#:~:text=The%20corollary%20is%20that%20if%20you%20find%20that%20post%2C%20say%20something.%20Drop%20the%20author%20a%20note%2C%20leave%20a%20comment.%20No%20one%20else%20does.%20For%20every%20YT%20celebrity%2C%20there%20are%20thousands%20of%20people%20posting%20good%20content%20on%20the%20internet%20and%20not%20knowing%20if%20it%27s%20being%20seen%20or%20appreciated%20by%20anyone][Source]]
  #+end_quote

- [[https://keepandroidopen.org/zh-CN/][你的手机，将不再属于你。]]

  [[https://developer.android.com/developer-verification][自 2027 年起]]，開發者如果沒有在 Google 注冊，不給 Google 交錢，
  那他的應用就不能在裝有 Google 框架的手機上分發，開發者被迫暴露個人信息，消費者也無法自由地安裝軟件。

  (via [[https://wiwi.blog/blog/your-phone-is-not-yours/][你的手機不是你的]] by wiwi)

* Cool Bit
:PROPERTIES:
:CUSTOM_ID: 2ABDF68D-88C5-4292-AE20-3BFF94B33308
:END:

- [[https://ipfworld.com/index.html][International Pen Friends (IPF)]]

  #+begin_quote
  您是否曾想過，您一生中最要好的朋友可能是某個您從未見過面、住在您從未造訪過的國家的人？

  國際筆友會 (IPF)® 能為您提供世界各地許多國家、與您年齡相仿的新朋友。
  國際筆友會成立於 1967 年，自那時起已有超過 2,500,000 人加入我們。
  我們的承諾和高品質的服務使我們被公認為世界上最偉大的筆友組織。

  寫信很有趣！

  今天，我們有可能觸及世界上幾乎每個國家的心靈與家庭。
  了解外國人的生活、了解他們的日常生活與文化，
  並且可能在日後拜訪他們，分享終身友誼的喜悅，是非常有趣且令人興奮的。
  #+end_quote

- [[https://pastcatalogs.com/][Downloadable Past Catalog Archive]]

  說實話我不知道 Past Catalog 是什麼，看起來是一些年代比較早的，專注某個主題的雜誌。

- [[https://nagonthelake.blogspot.com/2026/08/when-you-see-me-weep.html][Nag on the Lake: When You See Me, Weep]]

  湖水下降，露出一块石頭，上面寫著「當你見到我時，哭泣吧」(When you see me, weep)。

- [[https://sunflowersgame.com/][Sunflowers: Logic Puzzle Game]]

  類以扫雷的遊戱，類似的還有 [[https://dailyakari.com/akari][Akari]]。

- [[https://restroomarchive.com/r/2025-04-29-good-thanks][The Restroom Archive]] by Good Thanks Cafe

  #+begin_quote
  「洗手間檔案館」（The Restroom Archive）是一個持續更新的公共洗手間資料庫。
  該檔案館由 Jake Welch 設計並建立，旨在記錄這些獨特空間的多樣特質。
  每個人都會使用洗手間，但作為空間，它們卻被視為禁忌且鮮少受到關注。
  在社會中，或許沒有任何一個空間能比洗手間更精確地捕捉到人類在自知無人監視時所展現的創意與魯莽。
  #+end_quote

  建模挺好的，洗手間風格還挺多樣的。

- [[https://mengto.com/][Meng To]]

  新加坡建筑水墨畫，做成了一本翻頁書，呈現起來挺好看的。

- [[https://pxlarea.com/][Pixel Area]]

  一個聚合網站，呈現挺有趣的，你可以在一個巨大的矩型空間中認領一個你的像素，像是星空。[[https://pxlarea.com/x70y27][俺在這]]。

  (via [[https://wrywriter.ca/posts/pixel-area][Pixel Area]] by Alexandra Wolfe)

- [[https://doodleshooter.vercel.app/][Doodle District]]

  涂鸦風格的射擊遊戱，還挺好玩的。(via [[https://aiznb.com/weekly/2026/09/09/%E7%AC%AC200%E6%9C%9F-%E5%81%B7%E6%87%92%E7%88%B1%E5%A5%BD%E8%80%85%E5%91%A8%E5%88%8A.html][第 200 期 偷懒爱好者周刊]] by Soar)

  遊戱有 Bug，我卡關了兩次，提示還有敵人，但找遍了地圖也沒看到，
  後來我飛到了天上，才看到了有兩隻鳥，它們在地圖外飛著，怎麼也打不著。

- [[https://www.survive10waves.com/][SURVIVE 10 WAVES]]

  也是個射擊遊戱，比上面那個好玩點，還能升級技能，我玩到第四關就嘠了。

- [[https://typewritten.org/Media/][Retrotechnology Media]]

  一些早期操作系統的截圖。

- [[https://spaceships.treybastian.com/][SPACESHIPS]]

  一個遊戱，控制隕石把上面的飛船砸個稀烂，你就贏了。

- [[https://myonebeautifulthing.com/2026/08/26/repost-buttons-and-bows/][Repost: Buttons and Bows!]] by Donna from One Beautiful Thing

  一些用按鈕製作的藝術作品。有密集恐惧的話就別點開看了。

- [[https://contrastquota.github.io/colors/][Color Counter!]]

  你能想到几種顏色的名字？我能快速想到的才 30 種，很多還是加 light / dark 前綴得到的。

- [[https://walzr-com-adblock.kagiproxy.com/kids-trends/][Kids Trends]]

  #+begin_quote
  孩子們塑造了文化，而他們的畫作則展現了什麼最能吸引他們的注意力。
  我從線上學生藝術畫廊 Artsonia 抓取了超過一億幅素描和繪畫作品，
  藉此探索近 20 年來孩子們最喜愛的角色、一時的狂熱以及日常生活。
  #+end_quote

  有趣！

- [[https://letsscan.club/][Slit-Scan]]

  拖動圖片進行扫描，可以讓圖片變的歪七扭八。
  我不太能欣賞這種風格，但也挺有趣的。

- [[https://shar-wasm.cjoseph.workers.dev/][The Simpsons: Hit & Run - WASM]]

  em...The Simpsons 模拟器？也是個遊戱，喜歡 The Simpsons 可以玩玩。

- [[https://mrhands.itch.io/gas-station-dick-pills][Gas Station Dick Pills]] by Mr. Hands

  #+begin_quote
  當 Logan 的卡車在半夜拋錨時，他非常慶幸能趕到鎮邊一家冷清的加油站，
  而 Katie 正因為又一次的大夜班而無聊得發瘋。
  但當便利商店外的一個乞丐請求他幫個忙時，他得到的遠比他預想的要多……

  *警告*

  這是一部相當極端的成人視覺小說！
  遊戲中沒有性顯露圖像，但這是一個關於催眠和非自願異性性行為的故事。
  在開始遊戲前，有一份詳細的警告清單。

  *遊戲特色*

  - 45 分鐘的色情閱讀內容（11,000+ 字），由人類色情狂編寫
  - 6 個抽象背景，由人類色情狂製作
  - 4 個可解鎖的結局
  #+end_quote

- [[https://world.pablostanley.com/][Pablo Stanley]]

  Pablo Stanley 的個人主頁，做的挺有趣的，你會在裡面操作一個小人四处探索，還有東西會追著你打。

- [[https://earshoot.com/][earshoot]]

  #+begin_quote
  a living map for music discovery.
  #+end_quote

  蠻有趣的發現音樂的方式，
  你輸入一個查詢，頁面上會出現一些連接在一起的節點，
  點擊任意節點，能聴到節點對應的音樂，節點也會成為新的查詢，繼續查找關聯的音樂。
  推薦去玩玩看。

- [[https://yeartobeat.com/][Year To Beat — Guess the Song's Year]]

  也挺好玩的，給你看 5 段 MV，讓你猜歌曲年份，越接近答案，得分越高，有點難猜。

- [[https://kevquirk.com/sitemap][Sitemap]] by Kev Quirk

  有趣的 Sitemap 設計！

* Tutorial | Resource
:PROPERTIES:
:CUSTOM_ID: AA7025A8-3C9E-4706-B10C-468FBE4E04BA
:END:

- [[https://haizi.huhaitai.com/][《海子诗全编》]]

  via [[https://yoe1.bearblog.dev/blogroll/][右衣的部落卷]]

- [[Https://perthirtysix.com/how-the-heck-do-qr-codes-work?ref=DenseDiscovery-404][How The Heck Do QR Codes Work? (An Interactive Exploration)]] by Shri Khalpada

  如果你好奇二維碼的原理可以看看。

- [[https://catmothcrow.com/diy-mini-zine-holder/][DIY Printable, Paper Mini Zine Holder]] by Dayna

  教你 DIY 一個放小雜誌的容器。

- [[https://nate.spot/short-story-in-five-sentences/][How to write a short story in five sentences]] by Nate

  Short story 真的很短，真就是五句話。

- [[https://www.explorersdesign.com/public-domain/][Public Domain Art Resources]] by Clayton Notestine

  文章收集了一些公有領域藝術作品的資源。

- [[https://www.mikupara.com/][MIKUPARA - 初音未来优质插画收录站]]

  世界で一番おひめさま～

  🎵 ワールドイズマイン - 初音ミク / ryo

- [[https://github.com/hemanth/functional-programming-jargon][hemanth/functional-programming-jargon]]

  #+begin_quote
  用簡單的術語解釋函數式編程世界的術語！
  #+end_quote

  也可以在 [[https://hemanth.github.io/functional-programming-jargon/][FP Jargon — Interactive Functional Programming Knowledge Graph]] 上看。

- [[https://europealternative.com/][European Alternatives to US & Big Tech Software]]

- [[https://sightlessscribbles.com/posts/how-to-download-assets-from-github-using-a-screen-reader/][How to Download Assets from GitHub using a screen reader.]] by Robert Kingett

* Code Related
:PROPERTIES:
:CUSTOM_ID: 8FAF87E7-2AF6-4A2E-A58D-EFC6E30102A8
:END:

- [[https://kciter.so/posts/the-expensive-main-thread/en/][The Browser's Main Thread Is Expensive]] by Sunhyoup Lee

  一篇關於瀏覧器性能优化的交互式文章，主要是關於主綫程优化的，寫的很好，推薦一讀！

- [[https://dbushell.com/2026/09/01/text-editor/][Fine, I’ll build my own text editor!]] by David Bushell

  David 用 [[https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/canvas][<canvas>]] 實現了一個簡單的文本編輯器。

- [[https://yui.dev/blog/minesweeper-in-247-bytes][The Depths of JavaScript: Minesweeper in 247 Bytes]] by yui

  247 個字符的 JavaScript 程式碼，就是在您的瀏覽器中運行極簡版《踩地雷》所需的一切。

  文章詳細分享了代碼是如何運作的。

- [[https://www.carmenansio.com/articles/modernist-tiles-css-grid/][How to Build Tile Patterns with CSS Grid]] by Carmen Ansio

  教你用 Grid 布局實現地磚圖案。

- [[https://www.carmenansio.com/articles/kaleidoscope-symmetry-canvas/][Build a Kaleidoscope in Canvas: Symmetry and Motion]] by Carmen Ansio

  文章分享了實現萬花筒效果的細節。

- [[https://www.w3.org/TR/change-password-url/][A Well-Known URL for Changing Passwords]]

  #+begin_quote
  用戶端密碼管理軟體有助於提高需要身分驗證之網站的安全性和易用性。
  它透過減少跨站點密碼重複使用來提高安全性，並藉由提供自動填寫功能來增強易用性。

  目前網站缺乏一種以程式化方式告知用戶可以在何處更改密碼的方法。
  透過為更改密碼提議一個 well-known URL，本規範使密碼管理員能夠幫助用戶在支援該功能的網站上更改密碼。
  #+end_quote

- [[https://www.stefanjudis.com/today-i-learned/a-preceding-space-prevents-dangerous-commands-from-going-into-history/][A preceding space prevents dangerous commands from going into history]] by Stefan Judis

  在命令前加一個空格，這條命令就不會被記錄在 History。
  有的 Shell 可能要配置一下才會啟用這個功能。

- [[https://blog.master.dev/new-things-you-should-know-about-html-here-in-mid-2026/][New Things You Should Know About HTML Here in Mid 2026]] by Chris Coyier

  可以了解一下 HTML 新增的一些功能。

- [[https://utilitybend.com/blog/container-style-queries-and-advanced-attr-rethinking-how-to-wire-up-my-components-in-css][Container style queries and advanced attr(): rethinking how to wire up my components in CSS]] by Brecht De Ruyte

  結合 [[https://developer.mozilla.org/en-US/docs/Web/CSS/Guides/Containment/Container_size_and_style_queries][Container style queries]] 和 [[https://developer.mozilla.org/en-US/docs/Web/CSS/Reference/Values/attr][attr()]]，
  作者分享了几個用例，將 CSS 和 HTML 上的屬性關聯起來，由屬性驅動 CSS 的變化。

- [[https://notes.hamatti.org/technology/recipes/simplest-single-file-webring-implementation][Simplest single file webring implementation]] by Juhis

  一個簡單的 webring 實現。我在想，也許可以把我訂閱的博客做成一個 webring。

- [[https://shkspr.mobi/blog/2026/09/esoteric-html-ismap-vs-css/?52,31][Esoteric HTML – ismap vs CSS]] by Terence Eden

  文章介紹了 ~<img>~ 上的 [[https://developer.mozilla.org/en-US/docs/Web/API/HTMLImageElement/isMap][ismap]] 屬性值，挺有趣的，第一次知道。

- [[https://alexwlchan.net/2026/glancecast/][Abusing ID3 chapters to turn videos into glanceable podcasts]] by alexwlchan

  作者分享了他如何將視頻播客轉成音頻播客的。
  他利用 FFmpeg 將視頻轉成 MP3 格式，同時按一定間隔從視頻中截圖，存儲在 MP3 格式的 [[https://en.wikipedia.org/wiki/ID3][ID3]] 元素據中，
  這樣在聴的時候，手機上也會切換音頻的封面圖片。
  這樣既方便聴，在需要時也能看到一些視頻裡的畫面信息。

- [[https://www.joelonsoftware.com/2002/11/11/the-law-of-leaky-abstractions/][The Law of Leaky Abstractions]] by Joel Spolsky

  抽象把複雜度封裝了起來，使得上层用數起來更簡單，也不用關注內部許多細節。
  但抽象是會「泄漏」的，可能存在一些情况沒考慮到，也可能是一些抽象本身無法处理的事，
  當出現這種情况，到頭來還是要去關注底层的細節。

  #+begin_details
  #+html: <summary>摘录</summary>

  #+begin_quote
  回到 TCP。
  早些時候為了簡化起見，我撒了一個小謊，現在你們中有些人可能已經氣到七竅生煙了，因為這個謊言快讓你們瘋掉。
  我說過 TCP 保證你的訊息一定會送達。事實上，它做不到。
  如果你的寵物蛇咬斷了連接電腦的網路線，導致任何 IP 封包都無法通過，
  那麼 TCP 也無能為力，你的訊息就不會送達。
  如果你對公司的系統管理員態度傲慢，而他們為了懲罰你，把你接在一個超載的集線器上，
  那麼只有部分 IP 封包能通過，TCP 雖然還能運作，但一切都會變得非常緩慢。

  這就是我所說的「漏洞百出的抽象」（leaky abstraction）。
  TCP 試圖對底層不可靠的網路提供一個完整的抽象化，
  但有時網路問題會從這個抽象層中滲漏出來，讓你感受到那些抽象層無法完全保護你的問題。
  這只是我所謂的「抽象滲漏法則」（Law of Leaky Abstractions）的一個例子：

  凡是具有一定複雜度的抽象，多多少少都存在漏洞。
  (All non-trivial abstractions, to some degree, are leaky.)

  [[https://www.joelonsoftware.com/2002/11/11/the-law-of-leaky-abstractions/#:~:text=Back,leaky,-%2E][Source]]
  #+end_quote

  #+begin_quote
  抽象洩漏法則（law of leaky abstractions）之所以令人頭痛，
  其中一個原因在於它意味著抽象化並沒有像預期中那樣真正簡化我們的生活。

  [[https://www.joelonsoftware.com/2002/11/11/the-law-of-leaky-abstractions/#:~:text=One%20reason%20the%20law%20of%20leaky%20abstractions%20is%20problematic%20is%20that%20it%20means%20that%20abstractions%20do%20not%20really%20simplify%20our%20lives%20as%20much%20as%20they%20were%20meant%20to%2E][Source]]
  #+end_quote

  #+begin_quote
  抽象洩漏法則（The law of leaky abstractions）意味著，
  _每當有人開發出一個號稱能讓我們效率倍增的超強新代碼生成工具時，你總會聽到很多人說：_
  _「先學會手動操作，再用那個工具來節省時間。」_
  _代碼生成工具試圖將某些東西抽象化，但就像所有抽象化一樣，它們都會發生洩漏；_
  _而能稱職處理這些洩漏的唯一方法，就是去了解這些抽象化是如何運作的，以及它們究竟抽象化了什麼。_
  _因此，抽象化雖然節省了我們工作的時間，卻無法節省我們學習的時間。_

  [[https://www.joelonsoftware.com/2002/11/11/the-law-of-leaky-abstractions/#:~:text=wrong%2E-,The,learning][Source]]
  #+end_quote
  #+end_details

- [[https://flaviocopes.com/stylex/][A deep dive into StyleX]] by Flavio Copes

  #+begin_quote
  Learn how StyleX turns JavaScript style objects into regular CSS classes at build time,
   with React and Astro setup, variants, themes, and responsive styles.
  #+end_quote

* AI Related
:PROPERTIES:
:CUSTOM_ID: 568113E3-FAFD-4DF5-A9BF-57AF834868BE
:END:

☞ [[denote:20260901T091207::#616B92E5-380F-4DE7-8B66-AC90B5331217][跳過 AI 部分]]

- [[https://joshblais.com/blog/ai-writing-is-an-insult/][AI Writing is an Insult to Humanity]] by Joshua Blais

  #+begin_quote
  _發佈大語言模型（LLM）產生的文字是對所有讀者智力的蔑視，也是對全人類的直接侮辱。_

  委婉措辭的時代早已過去。

  我前幾天在 Hackernews 上看到一篇顯然是由 LLM 產生的文章，我整個人都崩潰了。
  _我不會在這裡提供該文章的連結，因為我不會為分享的內容賦予任何正當性，你也不應該這樣做。_

  [[https://joshblais.com/blog/ai-writing-is-an-insult/#:~:text=Posting,you,-%2E][Source]]
  #+end_quote

  如果你的文章是用 LLM 寫的，那就在文章開頭標明出來，
  讓讀者决定是否閱讀，不要假裝是自己寫的，請尊重讀者的時間。
  與其發 LLM 生成的內容，不如發你的提示詞，至少這是你寫出來的。

  也不要去分享那些 LLM 文章連結，每一次分享也是變相地在帮它們宣傳。
  其實也不限於 LLM，任何你覺得不應該宣傳的連結，都沒必要去分享、推廣它們。

- [[https://borretti.me/article/on-inevitability][On Inevitability]] by Fernando Borretti

  #+begin_quote
  行星沿軌道運行是必然的。日出是必然的。守恆定律是必然的。人類的行動卻不是必然的。

  [[https://borretti.me/article/on-inevitability#:~:text=The%20movements%20of%20the%20planets%20along%20their%20orbits%20are%20inevitable%2E%20The%20sunrise%20is%20inevitable%2E%20Conservation%20laws%20are%20inevitable%2E%20Human%20action%20is%20not%20inevitable][Source]]
  #+end_quote

  現在不少人認為人工超智慧是不可避免的，作者主張這是錯的。
  而且這也是有害的，當人們認定一件事不可避免時，這會成為行動的前提，而不會怀疑這可能是錯的。

- [[https://arslan.io/2026/09/11/how-i-manage-my-agents/?ck_subscriber_id=3312975854][How I manage my agents]] by Fatih Arslan

  作者分享了他的 agents 工作流，有點 [[https://en.wikipedia.org/wiki/Getting_Things_Done][GTD (Getting Things Done)]] 的感覺，
  ~/plan-init~ 會創建多個目錄：

   #+begin_example
   plans/
     README.md
     drafts/
     next/
     open/
     done/
     discarded/
   #+end_example

   - 有任何想法，先用 ~/plan-add~ 生成文檔存到 =drafts/=
   - 想實現了，則用 ~/plan-write~ 和最好的模型將問題和各種細節討論清楚，文檔會挪到 =next/=
   - 之後用 ~/plan-dispatch~ 交給擅長編碼的 agents 去實現，生成 Pull Request，
     文檔會挪到 =open/= ，最終由人审核 PR 并完成合并
   - 合并後，用 ~/plan-sync~ 比對 plan 和 PR，檢查是否有出入，如果沒問題，則更新文檔移動到 =done/= ，
     如果不想要這個 PR 則將其移動到 =discarded/=
   - 最後還有 ~/plan-retro~ 用於回頋 =done/= 和 =discarded/= ，檢查實際落地效果，
     同時可以更新 Skills，迭帯這套方法

- [[https://bcantrill.dtrace.org/2026/09/13/the-contagion-of-fear/][The contagion of fear]] by Bryan Cantrill

  前 Anthropic 員工 [[https://x.com/hilbertspaess/status/2097476203863224394][宣称 AI 可能在十年內讓我們全人類滅絕]]，造成了恐慌的漫延。
  Bryan Cantrill 回憶起他早年也做過類似的事，
  告訴不懂電脑病毒的人他們電脑可能馬上要中毒，也是造成了恐慌和損失。
  他通過自己的經歷，想說的是，作為相關專業人員，公眾會給予很多信任，
  不能只提出一個結論製造模糊的恐慌，還應該給出充足的證據來佐證自己的結論，
  如果沒有充足的證據，那就對自己的主張謹愼點，不要濫用自己的權威。

  #+begin_quote
  [...]我們應該聽從已故 Carl Sagan 的智慧—— _非凡的結論需要非凡的證據_ ：
  Coxon 及其同類所提出的主張是技術專家所能做出的最驚人的斷言，我們必須要求他們提供與這些主張相稱的證據。

  話雖如此，我們不應指望公眾能理解大型語言模型、關鍵基礎設施、生物武器、滅絕生物學等領域——
  這個責任必須由提出主張的人來承擔。
  我（羞愧地）在幾十年前學到的教訓是，
  _領域專家憑藉其專業知識，隱含地掌握著公眾的信任——而我們絕不能濫用這種信任。_
  _我們有責任對自己的主張保持謹慎——尤其是在發出警報時，更應如此。_

  [[https://bcantrill.dtrace.org/2026/09/13/the-contagion-of-fear/#:~:text=world%21-,To,alarm][Source]]
  #+end_quote

  (via [[https://simonwillison.net/2026/Sep/14/the-contagion-of-fear/][The contagion of fear]] by Simon Willison)

- [[https://lucumr.pocoo.org/2026/9/12/pdoom/][P(doom)]] by Armin Ronacher

  #+begin_quote
  _我可以告訴你，在什麼情況下人工智慧安全和發展節奏的議題會變得沒那麼令人擔憂：_
  _就是如果我們從一開始就被迫採用開放權重模型。_
  _一項人人皆可使用的強大技術，其發展節奏是內建其中的。_
  從某種意義上說，這是 [[https://en.wikipedia.org/wiki/Mutually_assured_destruction][「相互保證毀滅」（MAD）]] 或擴散的最真實形式。
  我認為我們之所以陷入目前的困境，是因為大眾目前正在（間接地）大力支持這些模型的開發，
  但同時卻必須從少數擁有巨大權力的實驗室手中，買回這些模型可能創造的經濟利益。
  而他們的權力也被視為一種地緣政治力量，至少在美國是如此，在中國可能程度稍輕一些。

  [...]

  我們應該慶幸中國目前正在大規模地「拯救」世界。
  如果不是中國實驗室對美國模型進行蒸餾，我們現在的處境會非常糟糕，尤其是對歐洲人而言。
  開放權重模型正在推動創新和能力的擴散，並正在平衡競爭環境。

  [[https://lucumr.pocoo.org/2026/9/12/pdoom/#:~:text=I%20can,field][Source]]
  #+end_quote

  #+begin_quote
  正如我之前所說，我不認為人工智慧會引發一場滅絕事件。
  事實上，即使沒有人放慢腳步，我真的不認為人類有什麼好擔心的。
  我傾向於認為，實際上是那些大型實驗室在聲譽和法律責任方面有更多的損失。
  _我覺得荒謬的是，OpenAI 的代理程式正在外面犯下實際的罪行，_
  _而我們卻只是聳聳肩，當作什麼都沒發生過一樣繼續前進。_
  但我相信那些公司的管理層正逐漸意識到，這在他們的許多潛在消費者中一點也不受歡迎。

  [[https://lucumr.pocoo.org/2026/9/12/pdoom/#:~:text=As%20I,consumers][Source]]
  #+end_quote




- [[https://simonwillison.net/2026/Sep/8/on-navier-stokes/][On the Navier–Stokes Millennium Prize Problem]] by Simon Willison

  兩個數學家利用 Claude 和 Codex 輔助研究，
  解决了一個數學難題 ⸺ [[https://en.wikipedia.org/wiki/Navier%E2%80%93Stokes_existence_and_smoothness][Navier–Stokes existence and smoothness]]，
  与此同時，OpenAI 也說他們用巨大的算力也解决了這個問題。
  這引發了一個憂慮，當人們在使用 LLM 時，LLM 是否也在窃取人們的成果？

  Simon Willison 提出的兩個有趣的問題：

  #+begin_quote
  - 如果我与 ChatGPT 进行头脑风暴，探讨公司可能的新方向，
    那么六个月后竞争对手询问“公司 X 可能接下来会做什么”时，信息泄露的概率有多大？

  - 如果我使用 ChatGPT 幫助我部分解決千禧獎問題，
    我的工作有多大機會影響訓練，使得之後的模型先幫助其他人解決它？
  #+end_quote

- [[https://sreenathmenon.com/blog/2026-08-04-webmcp-teaching-websites-to-talk-to-ai-agents/][WebMCP: Teaching Your Website to Talk to AI Agents]] Sreenath M Menon

  WebMCP 是一個規範，網頁按照一個統一格式提供相關 API 讓 Agent 去調用，
  這樣 Agent 在操作網站時，不用廢勁去識別網站內容，猜測哪些是可操作的，
  而是直接讀取網站主動提供的 API，使得操作更可靠。

  對 Agent 來說肯定是很好的，但對用户來說，安全性還是個問題。
  當網站提供了 API，用户登錄了網站，
  此時的 Agent 就可以像一個己登錄的用户去和網站交互，
  怎麼去確保安全是這個規範需要重點考量的事。

- [[https://www.robinwieruch.de/ai-output-someone-elses-input/][Your AI Output Is Someone Else's Input]] by Robin Wieruch

  #+begin_quote
  [...]現在產出很廉價，因此產出不再是價值所在。
  你所增加的是無法壓縮的部分：知道你想要什麼、決定需要決定的事，並為你交付的東西負責。

  所以現在我在發送任何東西之前都會做一個測試，它幾乎能涵蓋所有情況：
  *我會很高興收到這個嗎？*
  如果隊友發給我這張工單、這個 PR 或這份簡報，我會覺得受到了幫助，還是覺得被指派了任務？

  在這個時代脫穎而出的開發者不會是產出量最高的人，而是那些產出能讓別人樂於接收的人。
  其他所有人只是在製造工作，並稱之為生產力。

  [[https://www.robinwieruch.de/ai-output-someone-elses-input/#:~:text=The%20argument,productivity][Source]]
  #+end_quote

- [[https://www.seangoedecke.com/tell-agents-the-why/][Tell agents the why, not just the how]] by sean goedecke

  多給 agents 一些背景信息，讓它知道做什麼，也讓它知道為什麼，也許能讓它更凖確地完成任務。

- [[https://seldo.com/posts/we-are-all-product-engineers-now/][We are all Product Engineers now]] by Laurie Voss

  #+begin_quote
  我想說的兩件事並非安慰，只是觀察。
  第一，對於相當多自認熱愛敲代碼的人來說，他們真正熱愛的其實是敲代碼之前的那一刻——
  當腦中模糊混亂的問題突然化作精確輪廓的瞬間。
  那一刻，就是現在這份工作的核心。
  如果你熱愛的是這個，那你會過得很好，甚至可能比以前更好，因為業界即將對你這種人才求賢若渴。
  第二，這門手藝會像木工在家具工廠時代倖存下來一樣延續下去，
  成為人們因為熱愛而去做、且偶爾能獲得高額報酬的事情。
  開發者編寫軟體就像歌手唱歌一樣。當它是免費時如此，當它被自動化時亦然；
  熱愛它的人會繼續做下去，而一些最優秀的軟體也將持續誕生於他們之手。
  只不過，這不再會是一份常規的工作了。

  [[https://seldo.com/posts/we-are-all-product-engineers-now/#:~:text=Two%20things,job,-%2E][Source]]
  #+end_quote

  #+begin_quote
  編寫程式碼的成本已經大幅下降，而審查、修復和運行程式碼的成本也正隨之降低，我假設最終也會降到極低。
  開發軟體所剩下的工作就是找出人們真正的需求、對其進行精確定義，並使其易於使用。
  這項成本是針對每一件軟體獨立存在的，且無法轉移，
  因此隨著軟體數量趨向無限（由於需求沒有上限，這必然會發生），這項成本將會變成整個工作的核心。

  [[https://seldo.com/posts/we-are-all-product-engineers-now/#:~:text=review%2E-,The,job][Source]]
  #+end_quote

- [[https://opusfived.dev/][Opusfived]]

  #+begin_quote
  Make the “Add to Cart” button blue.

  Do not let Claude change anything else.
  #+end_quote

  一個遊戱，你可以試試。(via [[https://danq.me/2026/09/11/opusfived/][Opusfived]] by Dan Q)

- [[https://github.com/yanliudesign/mono-color-skill][yanliudesign/mono-color-skill]]

  #+begin_quote
  A one-ink and controlled two-ink editorial image skill
  for posters, zines, portraits, packaging, and visual field notes.
  #+end_quote

  風格挺好看的。

* Tool | Library
:PROPERTIES:
:CUSTOM_ID: 616B92E5-380F-4DE7-8B66-AC90B5331217
:END:

- [[https://github.com/spliit-app/spliit][spliit-app/spliit]]

  #+begin_quote
  Share expenses with your friends and family.

  No ads. No account. Open Source. Forever Free.
  #+end_quote

  Cool! See also: [[https://spliit.app/blog/why-spliit-doesnt-ask-you-to-create-an-account][Why Spliit Doesn't Ask You to Create an Account]]

- [[https://www.newsonaut.com/fontlonesome/index.html][Font Lonesome]]

  #+begin_quote
  HTML 實體就是你已經擁有的圖標。沒必要增加複雜性，讓第三方服務拖慢你的博客。

  這是一份專為個人博客常見圖標精選的 Unicode 列表。
  它們未必總是看起來很現代，但可能正是你為博客增添個性所需的東西。

  為什麼叫 Font Lonesome？因為它完全可以獨立使用。
  #+end_quote

- [[https://github.com/fengyuanchen/cropperjs][fengyuanchen/cropperjs]]

  #+begin_quote
  JavaScript image cropper.
  #+end_quote

- [[https://github.com/GoogleChromeLabs/quicklink][GoogleChromeLabs/quicklink]]

  #+begin_quote
  Faster subsequent page-loads by prefetching in-viewport links during idle time.
  #+end_quote

- [[https://ambientcss.vercel.app/][Ambient CSS]]

  #+begin_quote
  A _physics-based_ lighting system for CSS.
  #+end_quote

- [[https://bitcam-app.com/][BitCam]]

  #+begin_quote
  1-bit camera app & editor for iPhone/iPad/Mac.
  #+end_quote

  能拍出一種像素風圖片的應用，像是早期 macOS 的圖片風格。

- [[https://github.com/sumimakito/Mac-Duo][sumimakito/Mac-Duo]]

  關閉 MacBook 時讓屏幕模糊漸變，像是 iPhone Duo 的折叠效果一樣。

- [[https://github.com/jaskirat1616/mactap-app][jaskirat1616/mactap-app]]

  讓 MacBook 支持敲擊触發快捷鍵。
  需要配備將動作感應器公開為 SPU HID 裝置的 MacBook：M2 及更高版本，或 M1 Pro / Max / Ultra。

- [[https://github.com/saragordic/window-sweaters][saragordic/window-sweaters]]

  給 macOS 上的應用套上一身毛衣 :)

* Emacs
:PROPERTIES:
:CUSTOM_ID: 4EA4F3E7-B069-428B-81ED-46C69C988754
:END:

- [[https://sachachua.com/blog/2026/08/emacs-carnival-aug-2026-information-management-and-knowledge-graphs/][Emacs Carnival Aug 2026: Information management and knowledge graphs]] by Sacha Chua

  Sacha 分享了她做知識管理的方法。

- [[https://www.jamescherti.com/emacs-security-settings/][The Emacs Security Settings that might Silently Compromise your System]] by James Cherti

- [[https://www.jamescherti.com/emacs-startup-defer-use-package-performance/][Optimizing Emacs Startup - Guide to Deferred Package Loading with use-package]] by James Cherti

- [[https://www.jamescherti.com/emacs-display-line-numbers-mode-performance/][Fixing Slow Scrolling in Emacs display-line-numbers-mode]] by James Cherti

- [[https://www.jamescherti.com/emacs-consult-speed-async-searche-grep-ripgrep-fd-find/][Why Emacs Consult async searches feel slow and how to speed them up? (consult-fd, consult-find, consult-grep, consult-ripgrep...)]] by James Cherti

- [[https://www.jamescherti.com/emacs-terminal-performance-vterm-eat-ansi-term-ghostel/][Why Your Emacs Terminal is Slow and How to Fix It (vterm, eat, ghostel, term, and ansi-term)]] by James Cherti

- [[https://emacs.dyerdwelling.family/emacs/20260907140012-emacs--emacs-31-native-git-worktrees-vs-my-vc-setup/][Emacs 31 Does Git Worktrees Natively: How My vc Setup Compares]] by Emacs Dwelling

- [[https://lars.ingebrigtsen.no/2026/09/14/emacs-movies-and-sqlite/][Emacs, movies and SQLite]] by Lars Ingebrigtsen

- [[https://karthinks.com/software/avy-can-do-anything/][Avy can do anything]] by Karthinks

  文章分享了很多 [[https://github.com/abo-abo/avy][Avy]] 的用例，可以完全發揮 Avy 的能力。

- [[https://joarvarndt.se/emacs-lsp.html][Emacs does not need LSP]] by Joar von Arndt

- [[https://emacs.dyerdwelling.family/emacs/20260905090959-emacs--git-worktrees-and-branch-surgery-in-built-in-vc/][Git Worktreess Without Leaving Built-in VC]] by Emacs Dwelling

- [[https://onlisp.co.uk/New-from-Emacs-31_002e1-_002d-Upgrade-packages-without-breaking-other-Emacsen.html][New from Emacs 31.1 - Upgrade packages without breaking other Emacsen]] by Jeremy Bryant

  ~package-retention-policy~ 可以讓你在更新 package 時，保留旧版本。
  使用埸景可以看文章中的 [[https://onlisp.co.uk/New-from-Emacs-31_002e1-_002d-Upgrade-packages-without-breaking-other-Emacsen.html#Motivation-to-resolve-the-initial-problem][Motivation to resolve the initial problem]]。

- [[https://github.com/rougier/nano-theme][rougier/nano-theme]]

  一個極簡的 Emacs 主題。

- [[https://github.com/florommel/poimap][florommel/poimap]]

  #+begin_quote
  Visual Emacs buffer map with points of interest.
  #+end_quote

  放在 modeline 上的 minimap。

- [[https://github.com/Daskeladden/canvas-minimap][Daskeladden/canvas-minimap]]

  另一種型式的 minimap。

- [[https://github.com/benleis1/emacs-init/blob/13b61e43c6baad043af71cad385c68787340d9a6/modeline.el#L805][modeline zoom slider]]

- [[https://github.com/Thysrael/markdown-ts-appear][Thysrael/markdown-ts-appear]]

  #+begin_quote
  Reveal Markdown source at point and preview math in Emacs markdown-ts-mode.
  #+end_quote

- [[https://github.com/tarsius/keycast][tarsius/keycast]]

  #+begin_quote
  Show current command and its key in the mode line.
  #+end_quote

  錄視頻做演示時可以用，可以讓觀眾了解當前使用的按鍵。

- [[https://git.andros.dev/andros/kagi-search.el][andros/kagi-search.el]]

  #+begin_quote
  Browse Kagi search results inside Emacs, in a plain buffer,
  without a graphical browser and without JavaScript.
  #+end_quote

  获取 [[https://help.kagi.com/kagi/privacy/private-browser-sessions.html#obtaining-a-session-link][Kagi Session Link]] 就能用了。

- [[https://github.com/jdtsmith/ultra-scroll][jdtsmith/ultra-scroll]]

  #+begin_quote
  ultra-scroll1 is a _smooth-scrolling_ package for emacs,
  with native support for standard builds as well as emacs-mac.
  #+end_quote

- [[https://git.etenil.net/cursor-breathe-mode.el/about/][cursor-breathe-mode.el]]

  #+begin_quote
  An Emacs minor mode that animates the cursor width in a slow breathing pattern,
   making it more visible without relying on blinking.
  #+end_quote

- [[https://ananthakumaran.in/2026/08/30/pimacs.html][Pimacs - An Emacs UI for Pi]] by Anantha Kumaran

- [[https://pierre-rouleau.github.io/pel/pel-table-based-documentation1/-index.pdf][PEL Quick Access Topics Index]]

  See also: [[https://github.com/pierre-rouleau/pel][pierre-rouleau/pel]]

- [[https://github.com/larrasket/org-draw][org-draw]]

  #+begin_quote
  org-draw lets you draw inside Org-mode
  using any device with a web browser
  and have the result land in org-mode buffer as an inline, re-editable, portable figure.
  #+end_quote

- [[https://git.andros.dev/andros/nonogram.el][andros/nonogram.el]]

  #+begin_quote
  Play nonogram puzzles (also known as picross, griddlers or hanjie) in Emacs.
  #+end_quote

* 一些话 | 摘抄
:PROPERTIES:
:CUSTOM_ID: 1CFB98A9-C8F7-4D11-9CC6-57D6B62BB64B
:END:

- [[https://danq.me/2026/08/31/how-do-people-blog-for-thirty-years-without-running-out-of-things-to-say/][How do people blog for thirty years without running out of things to say?]] by Dan Q

  #+begin_quote
   如果真的有部落格寫了三十年不間斷的祕訣，我認為就是這個。
   *保持好奇心。*
   永遠不要停止提問。
   永遠不要停止學習。
   試著把世界看成是第一次看到的樣子，並記住，對你而言平凡的事物，對別人或在不同的光線下可能是極具吸引力的。
   而且，最關鍵的是：找到為自己寫作的動力（寫給自己）。
   當你為自己寫作時，首先你總會有繼續前進的理由。

   [[https://danq.me/2026/08/31/how-do-people-blog-for-thirty-years-without-running-out-of-things-to-say/#:~:text=If%20there,going%2E][Source]]
  #+end_quote

- [[https://substack.com/@thequantummodel/note/c-306059023][The Quantum Model (@thequantummodel): "Every person ..."]]

  #+begin_quote
  每個人都攜帶著一張對自己而言顯而易見，卻對他人隱形的現實地圖。
  對話就是我們比較地圖的方式。
  #+end_quote

- [[https://protesilaos.com/commentary/2026-09-12-courage-polymaths/][The courage of the polymaths]] by Protesilaos

  #+begin_quote
  勇氣既具傳染性也具危險性。
  當一個人無畏地表達心聲時，其他人也會受到鼓舞而效法。
  一旦少數人開始這樣做，這種運動就會成長為一種力量衝動，從思想散發出來，進而影響行為、制度和人造產物。

  [[https://protesilaos.com/commentary/2026-09-12-courage-polymaths/#:~:text=Courage%20is,alike][Source]]
  #+end_quote

- [[https://binarydigit.net/posts/the-paused-web][The Paused Web]] by Raging Against the Machines

  #+begin_quote
  好長一段時間以來，我一直因為部落格寫得「不夠多」而感到愧疚。
  我知道根本沒有所謂的「足夠」，但我還是有這種感覺，而且我已經有點厭倦了。
  我發了一篇關於製作 Neocities 頁面有多好玩的文章，
  這讓我突然意識到，我也許只需要一個能在網路上找樂子、放些偶爾更新的靜態內容的家，
  而不是非得每個月更新兩次、試圖讓它看起來很活躍，結果反而讓自己心裡不好受。

  [[https://binarydigit.net/posts/the-paused-web#:~:text=For,about%20it][Source]]
  #+end_quote

- [[https://brennan.day/proper-english-is-a-myth-theres-no-correct-way-to-write/][Proper English is a Myth: There's No 'Correct…]] by Brennan Kenneth Brown

  #+begin_quote
  不要試圖去糾正別人的書寫或說話方式。
  未經請求的糾正是一種微侵略，這是在向邊緣化群體暗示他們的母語或社群語言是次等的。

  [[https://brennan.day/proper-english-is-a-myth-theres-no-correct-way-to-write/#:~:text=Do%20not%20try%20to%20police%20how%20other%20people%20write%20or%20speak%2E%20Unsolicited%20corrections%20are%20microaggressions%2C%20and%20they%20signal%20to%20marginalized%20speakers%20that%20their%20native%20or%20community%20language%20is%20inferior][Source]]
  #+end_quote

  #+begin_quote
  當你認為寫作是錯誤的且需要修正時，你其實做了很多假設。
  正如 itsme 所假設的，這純粹是因為作者粗心大意，急於將部落格文章發表出來，正所謂「欲速則不達」。
  但除此之外還有無數其他原因，
  首先，這可能是閱讀理解障礙，可能是視力受損，
  也可能是因為他們成長的環境以及對特定語言機制運作方式的理解所致。

  [[https://brennan.day/proper-english-is-a-myth-theres-no-correct-way-to-write/#:~:text=There%20are,works][Source]]
  #+end_quote

  #+begin_quote
  你能做的最好的事情就是專注於意義。
  優先理解訊息，而不是去糾結具體的技術細節。
  如果有人寫了一篇部落格文章，而你覺得自己不明白他們想表達什麼，你猜怎麼著？
  這給了你一個絕佳的藉口去給他們發郵件，開啟對話與交流，而不是躲在自己的部落格裡隔空對他們進行含糊的指責。

  [[https://brennan.day/proper-english-is-a-myth-theres-no-correct-way-to-write/#:~:text=The%20best,distance][Source]]
  #+end_quote

* 多媒体
:PROPERTIES:
:CUSTOM_ID: 971DE07C-BC15-4C2D-B134-FFFF32CFF382
:END:

** 视频
:PROPERTIES:
:CUSTOM_ID: 49CFD9D4-62E7-4CD4-B6D8-1D0332BDFA0C
:END:
- [[https://www.bilibili.com/video/BV1yAYJ6mEaM/][【IGN】《塞尔达传说 时之笛》实机演示]] (15:12) by IGN 中国
- [[https://www.bilibili.com/video/BV1bRYN62EwF/][你可能没听过他，但你一定听过它！Bill Withers 的逆袭传奇]] (16:25) by 夏威夷爵菜头
- [[https://www.youtube.com/watch?v=TCdRuMDTmV0][Some Interesting Apples • A Short Documentary]] (2:59) by Ffern - Organic Eau De Parfum
** 播客
:PROPERTIES:
:CUSTOM_ID: 6ED612CA-5298-46D6-B757-8D9406EB994B
:END:

- [[https://nicetrypod.com/episodes/208][值得熬夜的事情都值得早起 - Nice Try]] (1:33:33)
- [[https://www.xiaoyuzhoufm.com/episode/6a97f287f03e74ee6b03ea5b][153. 和曾鸣聊产业史观：残酷的真相、会消亡的公司、优秀≠卓越、“OAI、Anth大概率不是原生时代大赢家”]] (154mins) by 张小珺Jùn｜商业访谈錄
