#+title:      Zine#53
#+subtitle:
#+export_file_name: 53
#+date:       [2026-06-21 Sun 14:22]
#+filetags:   :draft:preview:zine:
#+identifier: 20260621T142251
#+bind:       denote-directory "~/git/taxodium/posts"
#+description: Zine 第 53 期，分享一些看到的文章、资源、电影、书籍
#+language: zh-CN
#+author: Spike Leung
#+email: l-yanlei@hotmail.com
#+options: ^:{} toc:1
#+startup: content hideblocks

* News | Article
:PROPERTIES:
:CUSTOM_ID: 2ABEEA7D-2098-4CED-B823-3007990081CC
:END:
- [[https://anniemueller.com/posts/do-not-bargain-to-be-loved][Do not bargain to be loved]] by annie

  annie 關於什麼是愛的一篇短文。

  #+begin_details
  #+html: <summary>摘录</summary>

  #+begin_quote
  愛存在於所有它出現的場合，並且顯而易見。

  如果它不明顯 ⸺ 如果你無法感覺到它、聽到它、並看到它的行動 ⸺ 它就不存在。

  這看起來像是一條嚴苛的規則，但這是關於愛的唯一規則。

  愛並不混亂。
  愛是清晰的。
  愛是簡單的。
  愛是顯而易見的。
  像天空一樣廣闊，像大山一樣堅固。
  勇敢而誠實，溫柔而堅定。

  你不需要在黑暗的角落裡到處摸索，問道：「是在這裡嗎？是在這裡嗎？」

  你不需要挖掘愛直到手指流血。
  你不需要拆解某些鋒利的東西來獲取那充滿愛的柔軟核心。

  愛不會躲藏。
  愛會出現並停留。
  愛就在當下。

  當你被愛時，你會知道。你會感覺到。它會讓你敞開心扉。
  它賜予你廣闊與親近、自由與安全，兩者並重。
  你不必選擇其一而失去另一。
  愛不會只給你一半。愛是完整的。

  [[https://anniemueller.com/posts/do-not-bargain-to-be-loved#:~:text=it%2E-,Love,loved%2E][Source]]
  #+end_quote

  #+begin_quote
  以下是一些不屬於愛的東西：
  - 親暱
  - 認同
  - 關注
  - 吸引力
  - 讚美
  - 道歉
  - 禮物
  - 性

  愛可能會以這些方式表達。愛可能會給你親暱、關注，以及上述所有。這很美好。

  愛可以為你帶來這些，但它並不壟斷這些。

  認同可能源於逃避衝突。

  關注可能源於嫉妒。

  親暱可能源於孤獨。

  讚美可能源於討好他人的需要。

  禮物可能源於內疚。

  [[https://anniemueller.com/posts/do-not-bargain-to-be-loved#:~:text=Here%20are,guilt%2E][Source]]
  #+end_quote
  #+end_details

- [[https://theidlegazette.beehiiv.com/p/the-idle-gazette-4][The Idle Gazette | 4]] by Leo Umilio

  喜歡文章中關於平躺看夜空的浪漫的描述。

  #+begin_details
  #+html: <summary>摘录</summary>
  #+begin_quote
  本週包含一年中最短的夜晚。
  在一個晴朗的夜晚，無論是今晚還是其他晚上，花點時間仰臥在露天星空下。

  環境條件很重要，所以請容我精確說明。
  要在戶外，而不是在窗邊。
  平躺下來，因為這就是整個機制的關鍵：
  天空不會進入一個站立的人，因為站立是一種帶有意圖的姿勢，而意圖正是我們要放下的東西。
  草地上的毯子、長凳、汽車引擎蓋，或者如果你的地理環境允許的話，屋頂也可以。
  最少三十分鐘，不准使用電子設備，這點你現在應該已經預料到了，
  但我還要加上一條更嚴厲的禁令：
  不准辨認任何東西。那些星座應用程式留在室內，你那想要認出織女星並獲得成就感的念頭也一樣。
  命名是生產力從花園後門溜回來的表現。
  你不是去那裡學習天空，你是去那裡待在天空之下。

  最初的幾分鐘會感到心癢難耐，就像兩週前沒帶手機走路時的那種心癢。
  然後，如果夜晚足夠黑暗，而你又足夠耐心，一件事情就會發生，我不會過分吹噓它，因為它不需要我：
  _天空不再是一個天花板，而變成了一種深度，_
  _而這種深度正以光速進入你的體內，也就是說，這種「無所事事」在這一刻，顯然是相互的。_
  _降落在你身上的光在曆法出現之前就已經離開了其中一些恆星。_
  _它一路跋涉而來，抵達時所發現的，是一個躺在那裡、無所事事的人，而這正是接收它的唯一正確方式。_
  _無限不會闖入忙碌者的世界。_
  _它在等待一個橫臥的人。_

  ⌂ 預計付出：一個晴朗的夜晚、一片草地、些許露水
  ☽ 預計收穫：對自身渺小程度的正確體認

  [[https://theidlegazette.beehiiv.com/p/the-idle-gazette-4#:~:text=PRACTICE%20%E2%9D%A7-,This,dew][Source]]
  #+end_quote
  #+end_details

- [[https://eyu.at/posts/560.202606.html][没能展现神迹, 我很抱歉]] by 鹅玉

  鹅玉的一些工作感想，關於 AI 的部分也是很讓人心塞。
  有的人深信有了 AI 就無所不能，任何困難都可以用一句「不是有 AI 嗎」打發你。

  [[https://correresmidestino.com/dont-you-just-upload-it-to-chatgpt/][“Don’t You Just Upload It to ChatGPT?”]] by Juliette

  這篇也是類似的，當用 AI 需要承擔的責任不在自己身上時，
  有的人就會不負責任的來一句「不是用 AI 就行了嗎」，
  忽視可能存在的複雜性，把一切都想得很簡单。

- [[https://www.thesignalist.io/s/the-dialogue-dividend/][The Dialogue Dividend]] by Jakub Skoczeń

  和人對話，需要組織語言表達清楚，這個過程會促进思考。
  寫作、[[https://zh.wikipedia.org/zh-cn/%E5%B0%8F%E9%BB%84%E9%B8%AD%E8%B0%83%E8%AF%95%E6%B3%95][橡皮鸭調試]] 也有類似的效果，
  但和人對話還能收到對方的反饋，可能會帯來一些思維碰撞，從而產生一些新的思考，這是獨自一人時做不到的。
  除此之外，和人對話，也是在對方這里留下了印象，當日後需要合作時，可能更容易相处 (如果是坏印象另說)。

  #+begin_details
  #+html: <summary>摘录</summary>

  #+begin_quote
  當你大聲說出某些想法時，你就對其作出了承諾。
  原本只是模糊印象的舒適想法必須轉化為句子，而句子是有結構的。
  它們有主語和謂語，並提出可以被評估的主張。
  說話的行為強迫了一種內心獨白從不需要的精確性。

  聽眾會進一步加速這個過程。
  並非因為他們提供答案，而是因為他們有反應。
  眉頭微蹙意味著解釋不夠到位；
  一個問題揭示了你甚至沒意識到的假設；
  當有人說「對，我也見過這種情況」時，這種認同感確認了你正指向真實存在的事物。
  這種反饋循環在對話中實時持續運行，在思維飄得太遠之前糾正其方向。

  當你獨自思考時，這一切都不會發生。

  [[https://www.thesignalist.io/s/the-dialogue-dividend/#:~:text=When%20you%20say,alone][Source]]
  #+end_quote
  #+end_details

- [[https://wiwi.blog/blog/sent-from-my-iphone/][從我的 iPhone 傳送]] by Wiwi Kuan

  原來可以設置的，改了，順便隱藏了头像，界面看起來更簡洁了。

- [[https://www.yozblog.com/posts/you-re-a-bit-tone-deaf/][你音感有點差]] by DrummerYoZ 鼓手柚子

  See also: [[https://wiwi.blog/blog/computer-class-story/][我的電腦課罰站故事]] by Wiwi Kuan

  兩篇都是作者關於小時候被大人隨意否定的經歷。
  大人對於小孩來說，話語的更有重量，聴起來更權威，
  小孩也暂時没什麼分辨能力，就很容易信以為真，被一些否定的話打擊。
  作為一個大人，在面對小孩時，要注意自己的言行，
  很可能自己一句不經意的否定，就給對方帯來了很深的負面影响。
  如果不會好好說話，閉嘴也是不錯的。

- [[https://blog.ikukaroom.com/adult-font/][大人字體]] by ikuka
- [[https://yangbear.bearblog.dev/9563/][芙莉蓮的配樂]] by YangBear
- [[https://yangbear.bearblog.dev/abehiroshi/][阿部寬的官方網頁]] by YangBear

  #+begin_quote
  這個官網簡約的程度已經被日本網友拿來開玩笑說可以當成測自己網路有沒有斷線的方式，
  如果你連阿部寬的官網都打不開，那網路一定是出問題了。
  #+end_quote

  本來想發封邮件給 YangBear，但他没有留下可聯系的方式，
  也看到了他的 [[https://yangbear.bearblog.dev/2455/][留言與寄信]]，大概給他 Email 的話也會有些唐突吧。

- 要不要給作者買咖啡？

  [[https://hakkerman.eu/blog/i-wont-buy-you-a-coffee/][No, I Won't Buy You A Coffee]] by Hakkerman

  Hakkerman 的觀點是，
  我就是不想看广吿才來看獨立博客的，結果又看到獨立博客在討錢 (又是广告, Damn!) 讓作者感到反感。
  其次 Hakkerman 以自己為例，指出大多数獨立博客根本不需要多少運营成本 (我大致認同)，也不需要讀者贊助。
  Hakkerman 認為獨立博客應該用愛發電，不要談錢，不要用資本去污染它。

  這篇文章馬上引來了其他人的討論。

  [[https://brennan.day/yes-buy-them-a-coffee-support-and-mutual-aid-on-the-indieweb/][Yes, Buy Them a Coffee: Support and Mutual Aid on the IndieWeb]] by Brennan Kenneth Brown

  Brennan 認為博客作者大多也是用愛發電的，
  他們在文章底部放一个 Buy Me a Cofee 的連結，也不強制任何人付費，不管你支持与否，文章都在那任你閱讀。

  #+begin_quote
  所以，當有人結束工作回到家，打開手提電腦，
  純粹出於熱愛、出於希望自己的文字能觸動某人的微小期盼而免費寫作，
  並在文末放上一個連結時，我們不應將其視為廣告，而應將其視為一個活生生的人。

  [...]

  但當人們在可以免費閱讀的網誌末尾，請求別人請他們喝杯咖啡時，
  這並非商品化，也不是將愛好轉化為榨取式勞動。
  不，這是一個人在請求另一個人的支持，即使這種支持並非強制要求。

  [[https://brennan.day/yes-buy-them-a-coffee-support-and-mutual-aid-on-the-indieweb/#:~:text=So,requirement][Source]]
  #+end_quote

  Brennan 也指出，每個人的經済條件不同，對一些作者而言，網站的運营成本是有壓力的。

  Brennan 認為人們應該互助，用你的錢去選擇你想拥有/建立的互聯網。
  (就像市面上的產品一般，都是消費者用錢投票篩選出來的)

  #+begin_quote
  慈善是由權力者向下流向被視為「值得」的人，且取決於施予者的條件。
  相反，互助是在彼此流動的，它是橫向的，植根於一種認知：
  _你我的生存是緊密相連的。當我支持你時，我也在建立一個我想生活在其中的世界。_

  [[https://brennan.day/yes-buy-them-a-coffee-support-and-mutual-aid-on-the-indieweb/#:~:text=%E6%85%88%E5%96%84%E6%98%AF%E7%94%B1%E6%AC%8A%E5%8A%9B%E8%80%85%E5%90%91%E4%B8%8B%E6%B5%81%E5%90%91%E8%A2%AB%E8%A6%96%E7%82%BA%E3%80%8C%E5%80%BC%E5%BE%97%E3%80%8D%E7%9A%84%E4%BA%BA%EF%BC%8C%E4%B8%94%E5%8F%96%E6%B1%BA%E6%96%BC%E6%96%BD%E4%BA%88%E8%80%85%E7%9A%84%E6%A2%9D%E4%BB%B6%E3%80%82%E7%9B%B8%E5%8F%8D%EF%BC%8C%E4%BA%92%E5%8A%A9%E6%98%AF%E5%9C%A8%E5%BD%BC%E6%AD%A4%E6%B5%81%E5%8B%95%E7%9A%84%EF%BC%8C%E5%AE%83%E6%98%AF%E6%A9%AB%E5%90%91%E7%9A%84%EF%BC%8C%E6%A4%8D%E6%A0%B9%E6%96%BC%E4%B8%80%E7%A8%AE%E8%AA%8D%E7%9F%A5%EF%BC%9A%E4%BD%A0%E6%88%91%E7%9A%84%E7%94%9F%E5%AD%98%E6%98%AF%E7%B7%8A%E5%AF%86%E7%9B%B8%E9%80%A3%E7%9A%84%E3%80%82%E7%95%B6%E6%88%91%E6%94%AF%E6%8C%81%E4%BD%A0%E6%99%82%EF%BC%8C%E6%88%91%E4%B9%9F%E5%9C%A8%E5%BB%BA%E7%AB%8B%E4%B8%80%E5%80%8B%E6%88%91%E6%83%B3%E7%94%9F%E6%B4%BB%E5%9C%A8%E5%85%B6%E4%B8%AD%E7%9A%84%E4%B8%96%E7%95%8C][Source]]
  #+end_quote

  #+begin_quote
  相信我不必多言，人們賺錢的方式往往會降低其寫作與網站的品質，
  無論是侵入式廣告、不誠實的產品評論，還是激進的聯盟行銷連結。

  正因如此，人們需要以符合倫理、非剝削的方式從作品中獲益。

  [[https://brennan.day/yes-buy-them-a-coffee-support-and-mutual-aid-on-the-indieweb/#:~:text=I%27m%20sure%20I,like][Source]]
  #+end_quote

  [[https://taonaw.com/2026/06/16/why-yes-ill-buy-you.html][Why Yes, I'll Buy You a Coffee]] by TAONAW

  TAONAW 大體同意 Hakkerman，但他并不反對贊助連結，只是贊助連結不要那麼強势、別顯眼得讓人厭惡就好。
  讀者願意贊助，那是一種讀者表達的善意。

  #+begin_quote
  我從不認為這是他們支付的一種報酬，甚至如果你仔細想想，這也不是一種賄賂。
  他們只是善良的人。
  老實說，即使我沒從他們身上拿到一分錢，我也會同樣對待他們，純粹因為他們的人品。
  錢固然不錯，但那個總是要求拿鐵要「比太陽還燙」的 Stacy 呢？無論如何她都能如願以償。
  雖然聽起來很老套，但我喜歡看她臉上的笑容，也喜歡她告訴我的值班主管說我知道該怎麼沖泡。

  今天，當我看到一個帶有 Ko‑Fi 按鈕的博客時，
  只要它不令人反感（我想這就是 Hakkerman 的意思），我都覺得沒問題。
  如果它安靜地待在一旁，
  而不是像那些強行攔截的流氓廣告那樣叫囂著「既然喜歡就點這裡付錢！給我給我！」，那就完全沒問題。
  沒錯，我也曾不時請過幾位博客（和藝術家）喝一兩杯咖啡。

  [[https://taonaw.com/2026/06/16/why-yes-ill-buy-you.html#:~:text=I%20never,times][Source]]
  #+end_quote

  TAONAW 還給博客作者一些建議：

  - 公開網站維护成本，增加透明度，也能讓其他想開始寫網誌的人心裡有個底。
  - 不要乞求，也不要令人反感。
  - 不要做付費訂閱。

    #+begin_quote
    訂閱是一種預付款形式，本質上是勒索。
    它在說：「嘿，你最好再發新文章，我是付了錢的客戶，否則我就走人。」
    #+end_quote

  - 要感謝那些閱讀你網誌的人，而不僅僅是打賞的人。
  - 去享受寫的過程，有没有贊助并不重要。

  說說我的看法，我不討厭博客有類似 Buy me a coffee 的連結（我的博客也有），
  但我不喜歡做的太明顯的，如果做成弹窗，像是乞求一樣，就更不喜歡。
  虽然明顯一些更容易讓人看到，或許更容易有轉化，
  但贊助本身是讀者自願的行為，想贊助的讀者總能找到入口的，完全没必要做得很抢眼。

  在最開始寫博客的時候我也不喜歡放贊助連結，
  就像開源一樣，大多数人的初心只是想分享，而不是為了錢，
  放一個贊助連結，有種背離初心的感覺。
  後面忘了為什麼就加上了，可能是看不少博客都有，也可能是因為更喜歡錢了。
  我也有幻想，如果有人給我贊助，不用很多，一個月能有一杯咖啡錢，然後去免費喝上一杯也不錯呀，
  但事實証明，根本没人贊助。我想原因大概是
  1) 博客的曝光度很小，本來也沒几個人看，其中有贊助想法的就更少了。
  2) 博客的內容并没有好到讓人想表達一下感謝，也是，毕竟很多時候都是自說自話，只管自己寫得開心。
  3) 贊助也没有任何回报。
  第 2 點應該是主要的原因。
  不過我本身也不是為了贊助才寫博客，有當然開心，會感到被肯定和認同；
  没有也无所謂，我也會繼續寫。

  反觀自己，也并没有給多少博主贊助，自己尚且不主動去推動這樣的互助，又怎麼能期待別人呢。
  所以我計劃之後每個月抽出 20 块左右去打賞一些博客，嘗試一段時間。

  我也在做一些贊助，我每個月會分配 10 美元，給兩三個對我帮助很大的開發者贊助；
  也給常逛的 [[https://donate.emacs-china.org/][Emacs China]] 捐贈過；
  前陣子引用了很多 [[https://www.themarginalian.org/][The Marginalia]] 的內容，也贊助了一些，還有 [[https://webweekly.email/archive/][Web Weekly]]。
  說實話，我那點贊助真的不算什麼，或許都不够他們喝杯咖啡，
  但只要贊助的人足够多，對他們還是能帯來一些帮助的，
  我也不是很有錢，些許的贊助就是想向他們表達一下感謝。

  關於贊助回报，我認為既然是贊助，就沒必要期待回报，贊助只是去表達自己的感謝。
  不過博客作者也可以提供一些「福利」，例如冠名 (在開源項目中更常見)，[[https://www.patreon.com/join/mtfront][投票選題]]⋯⋯

  除了用金錢去贊助，如果你喜歡博客的內容，請去吿訴他們，留言、評論、發邮件、帮忙轉發擴散⋯⋯
  同樣也能給這些博主帯來鼓勵。

  最後，我前陣子好像也收到了一位讀者的贊助，這位讀者没有留言，所以我不太確定，
  但支付宝付款碼應該只在博客有，收到轉帳，我就當是贊助了。
  如果這位讀者你看到了，打算留言，歡迎給我發封邮件 :)
  不管如何，非常感謝！

* Cool Bit
:PROPERTIES:
:CUSTOM_ID: 5F4F1568-924B-462F-8493-7A5DC3AAA309
:END:

- [[https://garrit.xyz/posts/2026-06-13-pac-man-but-you-re-the-ghost][Pac-Man, but you're the ghost]] by Garrit

  在糖豆人的游戏里操作幽灵，打敗糖豆人，倒反天罡 :P

- [[https://crankgpt.com/][CrankGPT]]

  Local Human-powered AI ([[https://squeezlabs.github.io/handcrank/][Technical documentation]]).

  人力發電的 AI，看到那个左邊一群人在跑步機上跑步發電，右邊是白領在辦公室用 AI 的視頻，
  有點搞不清他們是認真的，還是來搞笑嘲諷的。

- [[https://silverswanpostclub.neocities.org/][Silver Swan Post Club]]

  #+begin_quote
  這是一份為深信 _信箱_ 仍能帶來快樂的人而精心策劃的月度訂閱。
  在一個奔向數碼化的世界中，
  本俱樂部引以為傲地捍衛 _實體媒介與觸感紀念品_ 的魅力，
  讓你隨時可以握在手中、展示、收藏，並在需要一點魔法時隨時重溫。
  #+end_quote

- [[https://ita.toys/][ita.toys]]

  一個很有特色的網站。

- [[https://secondlina.tumblr.com/post/785918009427542016/no-transphobes-allowed-only-transborbs-check-out][No transphobes allowed, only transborbs.]]

  6 月是 [[https://en.wikipedia.org/wiki/Pride_Month][Pride Month]]，喜歡這幅漫畫。

- [[https://garden-of-flowers.heikkilotvonen.com/][Heikki's Garden of Flowers]]

  #+begin_quote
  Heikki 的花園旨在成為一個涵蓋 _歷史與當代圖像活字印刷作品_ 的全面目錄。
  #+end_quote

- [[https://spacew.com/][Solar Terrestrial Dispatch]]

  37 Years of Space Weather Services.

- [[https://www.notesfromtheroad.com/desertmexico/chili-peppers.html][Chili Peppers of the World]]

  世界辣椒圖鑑。
  一份關於世界辣椒的視覺實地指南，從野生起源到栽培品種，配有 176 幅手繪辣椒插圖。

- [[https://www.nts.live/][NTS]]

  #+begin_quote
  NTS 是一個音樂探索平台，由音樂愛好者為音樂愛好者打造。
  NTS 擁有兩個 24/7 全天候播放的現場廣播頻道，
  以及數十萬小時由人工策劃的節目，是世界上最受推崇的音樂檔案庫之一。
  #+end_quote

- [[https://internetphonebook.net/][Internet Phone Book]]

  Issue two is open for submissions!!

  (ﾉ>ω<)ﾉ

  之前想申請但找不到入口，現在可以申請了！
  不知道能不能通過，如果通過了，号碼會是多少呢？

- [[https://cluesbysam.com/][Clues by Sam!]]

  一個游戏，每張卡片上會有一些綫索，你要基於綫索推理，找出好人和坏人。
  之前在微信小程序上玩過類似的。

* Tutorial | Resource
:PROPERTIES:
:CUSTOM_ID: E7E67C69-7485-41DA-9E34-0CCEE3675926
:END:
- [[https://disable-javascript.org/][Disable JavaScript]]

  關於如何在瀏覧器禁用 JS。

  我現在用 [[https://ublockorigin.com/][uBlock Origin]] 默認禁用了 JS，需要時才允許。
  有一些網站，不允許 JS 完全没法看，那我就不看了。

  See also: [[https://xn--gckvb8fzb.com/disable-javascript-org/][disable-javascript.org]] by マリウス

- [[https://aresluna.org/key-in-sight/][Key, in sight]] by Marcin Wichary

  文章分享了 Marcin Wichary 定制鍵盤的一些經驗，那個只有一個按鈕的鍵盤看起來很不錯。

  #+begin_quote
 所以，我想寫一個小指南，從硬件到軟件，介紹我自己是如何接觸並熟練掌握一些鍵盤技巧的。
 也許這對你也會有幫助？

 這篇文章的目標是：

 - 利用現代鍵盤和數字小鍵盤來處理一些真正實用的事務。
 - 從中發掘樂趣與享受。
 - 在波濤洶湧的港口中，成為一位沉著冷靜的嚮導。

 如果你一直感到好奇但又望而生畏，
 或者如果你有一個小鍵盤或鍵盤上有一堆額外的按鍵，但不知道該拿它們怎麼辦……請繼續讀下去。

 [[https://aresluna.org/key-in-sight/#highlight-reel:~:text=So%2C%20I%20wanted,start%3A][Source]]
  #+end_quote

- [[https://aresluna.org/show-your-hands-honor/][Show your hands honor for the strange power they bring you]] by Marcin Wichary

  論如何設計手指友好的互動體驗。

  文章里有很多交互式的示例，不敢想寫一篇這樣的文章要多久。

- [[https://shkspr.mobi/blog/2026/06/cybersecurity-for-the-paranoid-business-traveller/][Cybersecurity for the paranoid business traveller]] by Terence Eden

  個人往往會成為間諜活動、勒索或其他由國家資助攻擊的目標，
  Terence Eden 整理了 一些給商務旅客網絡安全建議。

  #+begin_details
  #+html: <summary>摘录</summary>

  #+begin_quote
  老兄，你只是一個獲得去異國參加會議機會的中年銷售代表。
  你真的認為那個年輕貌美的對象會被你那些關於中層管理的故事迷住嗎？

  不。

  最好的情況是，那些照片會被用來勒索你。
  最壞的情況是，警方會聲稱對方未成年，並以此那樣來勒索你。

  [[https://shkspr.mobi/blog/2026/06/cybersecurity-for-the-paranoid-business-traveller/#:~:text=Mate,that%20will%20be%20used%20to%20blackmail%20you][Source]]
  #+end_quote

  #+begin_quote
  你的 IT 團隊已經為你提供了一部經過加密且有生物識別保護的手提電腦，對吧？
  但你真的需要那部特定的手提電腦嗎？

  他們應該準備一部廉價的手提電腦，只放入你需要的文檔。當你回到家後，就把它丟掉。

  我是認真的，花 200 英鎊買一部 Chromebook 作為代價，
  以防止你的秘密被竊取或網絡被滲透，是非常划算的。

  [[https://shkspr.mobi/blog/2026/06/cybersecurity-for-the-paranoid-business-traveller/#:~:text=Your%20IT,infiltrated][Source]]
  #+end_quote
  #+end_details

* Code Related
:PROPERTIES:
:CUSTOM_ID: 9FFF27C5-9FF8-4220-AD43-DB607A306E71
:END:

- [[https://shkspr.mobi/blog/2026/06/which-copyleft-licence-is-suitable-for-an-svg/][Which Copyleft Licence is Suitable for an SVG?]] by Terence Eden

  SVG 應該用什麼 License？ 取决於將 SVG 當作什麼。

  如果當作圖像，適合用 Creative Commons；
  如果當作軟件，適合用 GPL。

  Terence 認為 SVG 應該属於軟件，所以更適合用 GPL 相關的 License。

- [[https://webkit.org/blog/18117/the-golden-rule-of-customizable-select/][The golden rule of Customizable Select]]

  這條黄金法則就是: 務必為你的 option 元素提供文字內容或無障礙文字屬性。

- [[https://blog.jim-nielsen.com/2026/a-consistency-of-excellence/][Consistency, But in Excellence Not Appearance]] by Jim Nielsen

  一個常見的 UI 設計原則是一致性。
  但有時會過度追求表面/外觀的一致性而导致設計很乏味，Jim 認為應該多去思考設計的意圖，而不僅是外觀。

  #+begin_quote
  相比之下，卓越更難系統化。
  它需要判斷力、品味、細心、經驗以及對語境的敏感度 ⸺
  這一切都是為了服務於意義和目的，而非表面的相似性。

  當你力求整個系列的一致性時，單個元素就會失去在自身條件下變得卓越和標誌性的能力。
  群體的一致性變成了個人卓越的上限。

  但如果你反其道而行之，將卓越作為每個單獨元素的目標，有趣的事情就會發生： 卓越成為了你一致性的主題。
  這不再是形狀和漸變的一致性，而是品質和意圖的一致性，它服務於比表面視覺效果更深層次的意義和目的。

  與其追求外觀的一致性，我寧願隨時選擇卓越的一致性。

  [[https://blog.jim-nielsen.com/2026/a-consistency-of-excellence/#:~:text=Excellence%2C%20by,appearance][Source]]
  #+end_quote

- [[https://filiph.net/text/pokerd.html][How I built a CLI poker game that you don’t need to install to play]] by Filip Hráček

* AI Related
:PROPERTIES:
:CUSTOM_ID: D12323A4-9288-408C-AB3B-9CEAE34F1768
:END:

- [[https://stratechery.com/2026/anthropics-safety-superpower][Anthropic’s Safety Superpower]] by Ben Thompson

  #+begin_quote
  另一方面，Anthropic 在人才、使命和業務之間達成了完美的契合。
  該公司向研究人員推銷創造「機器之神」的願景，
  並讓他們披上那種關心危險、且足夠聰明能代表人類應對危險的人士外衣；
  而由此產生的每一項政策變動恰好都對業務發展極為有利，這簡直是世界上最美妙的巧合。

  我尊重這種一致性，但也對此感到恐懼。
  我尊重它，是因為它的成效顯而易見；
  最接近的類比可能是 Apple，它總是將每一項利己的行為包裝成是為了用戶著想 ⸺ 而且往往事實的確如此。
  Anthropic 也是如此。
  然而，我所恐懼的是，
  如果一群深信自己最懂的人是在打造一部我可以選擇買或不買的智能手機，那是一回事；
  但如果他們是在打造一種潛力足以與國家力量或巨型企業抗衡、甚至超越其上的超級智能，那就令人擔憂得多。
  _歷史上，那些深信自己知道人類需要什麼的天才人物，其紀錄往往是污穢不堪的，_
  _正因為他們說服了自己其意圖是良善的，從而將那些極其不當的行為合理化。_

  [[https://stratechery.com/2026/anthropics-safety-superpower/#:~:text=Anthropic%2C%20on,not][Source]]
  #+end_quote

- [[https://polar.sh/blog/orbit-llm-safe-design-system][Building an LLM safe design system]] by Polar

  蠻有借鉴價值的文章，簡单來說就是限制 LLM 的選擇從而减少 LLM 的概率性出錯，
  以及用標準 (例如 ESLint) 去約束 LLM 的結果，最終讓 LLM 能够更容易地朝著期望的方向演进。

  #+begin_quote
  *文檔只是建議，CI（持續集成）才是契約。*

  顯而易見的第一步是把規則寫下來。
  在 CLAUDE.md、樣式指南或系統提示詞中寫上「使用我們的灰色，不要用 bg-gray-100」。
  這些我們都有，但它們守不住底線。

  _任何寫在文檔裏的東西都只是概率，而非保證。_
  _LLM 閱讀它，將其與上下文中的其他內容進行權衡，然後在大部分時間裡遵循它。_
  _但「大部分時間」並不構成設計系統。_
  _在成千上萬次的生成中，失誤會不斷累積，最終你還是得手動檢查每一份代碼差異以防偏離規範。_

  因此，我們劃定了一條更強硬的底線，這也是 Orbit 其他部分的依託：
  _真正重要的規則不是用英文寫成的，而是編碼為在 CI 中運行的 ESLint 規則。_
  這給了我們一個確定的契約。

  [[https://polar.sh/blog/orbit-llm-safe-design-system#:~:text=The%20obvious,author][Source]]
  #+end_quote


- [[https://kk.org/thetechnium/why-are-llms-smart/][Why Are LLMs Smart?]] by Kevin Kelly

  LLM 只是基於概率去生成文本，為什麼就表現出了智能，我也對此比较困惑。
  Kevin 的解釋我覺得挺合理的，他說人類的文本中包含了人的智能，而 LLM 則提取了里面的智能，模拟出了智能。

  #+begin_details
  #+html: <summary>摘录</summary>

  #+begin_quote
  其中一个解释是，大型语言模型展现出的基础智能，其实就锁在人类的写作和语言本身之中。
  你可以根据语法规则手册来造句，但要构建一个段落，则需要逻辑、推论和推理。
  此外，正如任何老师都会告诉你的，要写出一篇连贯的文章（即一连串的段落），你需要某种清晰的思维。
  LLM 创作者收集的海量训练材料不仅仅是单词、句子或段落。
  这数万亿个单词嵌入在文章、书籍、论文、咆哮、回复、评论、推文串、
  争论、辩论、故事、传说、叙述、报告和博客中。
  这些以及上百种其他长篇形式，在文字的排列中蕴含了智能。正是语言的架构传达了这种智能。

  一篇优秀的文章，其蕴含的智能远超单个句子。
  一篇科学论文在其结构中包含了科学逻辑 ⸺ 论文本身就是一场带有假设和证据的论证。
  串联式的辩论在文本中包含了律师般的演绎。
  虚构故事在句子中包含了叙事的架构。
  简而言之， *人类的文本包含了人类的思考。*
  当你苦思冥想将论点转化为纸上的文字时，你创作的最终文本也包含了你投入其中的智能。
  你正在阅读的这篇论文全文，既代表了我的思考，也以一种微小但重要的方式，承载了思考本身。
  这种逻辑存在于词语的模式之中。
  因此，整篇文章中词语的顺序和选择都蕴含着智能 ⸺
  而最大的惊喜在于，LLM 可以提取这种智能，模拟它来撰写新文章，并越来越多地将其应用于其他领域。

  [[https://kk.org/thetechnium/why-are-llms-smart/#maincontent:~:text=language-,One,fields][Source]]
  #+end_quote
  #+end_details

- [[https://role-confusion.github.io/][Prompt Injection as Role Confusion]] by Charles Ye, Jasmine Cui, Dylan Hadfield-Menell

  #+begin_quote
  這是該論文的部落格形式報告。
  我們展示了提示詞注入是由大型語言模型（LLM）感知角色的缺陷所驅動的。
  這使我們能夠創造新的攻擊方式、解釋機械解釋性（mech interp）的結果，並預測攻擊何時會成功。
  接著，我們討論了什麼是角色以及它們為何重要，並分享了關於角色科學的研究思路。
  #+end_quote

  把論文用博客形式呈現，好讀了很多，博客本身寫得也不錯，適當的標記使得表達很清晰。

  對於 LLM 來說，文本就是一切，它們基於文本訓練，基於文本思考，基於用戶輪入的文本作出反應。
  在一堆文本中，LLM 通過標簽來區分自己 (=<system>= 、 =<think>= ) 和用戶 (=<user>=)，
  但這些標簽并不能有效讓 LLM 區分自己，正如上面 [[https://kk.org/thetechnium/why-are-llms-smart/][Why Are LLMs Smart?]] 說的，
  LLM 的智能是从人類文本中來的，人類文本中并不會用這些標簽區分自己，而是通過語義去推斷的，
  於是攻擊者就容易偽造文本讓 LLM 誤以為攻擊者的文本是自己的。
  要解决提示詞注入攻擊，需要 LLM 能準確地區分自己和用戶。

- [[https://www.langchain.com/blog/the-art-of-loop-engineering][The Art of Loop Engineering]] by LangChain

  最簡单的 agent 是： 為大型語言模型（LLM）提供上下文，並讓它在循環中調用工具，直到完成任務。
  這是最基本的循環，還可以繼續套上不同层次的循環，從而構建更高效代理。

  + 基础循環
  + 驗證循環，增加了一個評分器，根據準則檢查代理的輸出，如果失敗，則將結果連同反饋一併發回。
  + 事件驅動循環 / 生態循環，將你的代理連接到你的生態系統，使其能夠在後台運行。
  + 爬山演算法迴圈 (Hill climbing loop)，代理自我迭帯，自我改进。

- [[https://tombedor.dev/human-attention-and-human-effort/][If You are Asking for Human Attention, Demonstrate Human Effort]] by Tom Bedor

  #+begin_quote
  我記得第一次經歷這種煩惱。我提出了一個設計，然後一位隊友提示 AI 對其進行評論。
  隊友發給我一份 AI 文件，並附帶免責聲明：
  「我沒有讀過這份文件，所以它可能不完全準確」。
  我的想法是，如果閱讀這份文件不值得你花時間，那為什麼值得我花時間呢？

  因此，我在工作中採納了這個原則：

  *如果你要求人類關注，請展現人類的努力。*

  [[https://tombedor.dev/human-attention-and-human-effort/#:~:text=I%20remember,effort][Source]]
  #+end_quote

- [[https://albertsikkema.com/ai/development/opinion/2026/06/15/why-diy-software-is-great-until-it-is-not.html][Why DIY Software Is Great Until It Is Not]] by Albert Sikkema

  Vide Coding 制作自己用的軟件，解决自己的問題够用了，
  但如果要狀軟件變成可以給他人用的狀態還不够，
  需要考慮未曾想過的邊緣情况，要對他人的數據、金錢和信任負責，要持續維护⋯⋯
  此時人們可能還是會找専業人員來負責，來承擔那些人們不想处理、不擅長处理的事情。

  #+begin_quote
  軟體工程師的角色正在從「編寫程式碼的人」轉變為
  「了解程式碼是否符合用途，並理解為他人開發時隨之而來的法規、合規性、安全性和數據完整性要求的人」。
  這是一個更重大的角色，需要更多的專業知識，
  因為你需要同時理解「已經構建了什麼」以及「應該構建什麼」。

  AI 不會取代軟體工程師，它將改變軟體工程師的工作內容。

  [[https://albertsikkema.com/ai/development/opinion/2026/06/15/why-diy-software-is-great-until-it-is-not.html#:~:text=today%2E-,The,do][Source]]
  #+end_quote

  See also:  [[https://quinnkeast.com/writing/software-is-problem-ownership][What, then, are we paying for?]] by Quinn Keast

  #+begin_quote
  為軟體付費並不是在為解決方案付費。
  而是在付錢讓別人來承擔一個問題。

  [[https://quinnkeast.com/writing/software-is-problem-ownership#:~:text=Paying%20for%20software%20isn%E2%80%99t%20paying%20for%20a%20solution%2E%20It%E2%80%99s%20paying%20for%20someone%20else%20to%20own%20a%20problem][Source]]
  #+end_quote

- [[https://developer.mozilla.org/en-US/blog/introducing-mdn-mcp-server/][Introducing the MDN MCP server]]

- [[https://vickiboykis.com/2026/06/15/running-local-models-is-good-now/][Running local models is good now]] by Vicki Boykis

* Tool | Library
:PROPERTIES:
:CUSTOM_ID: 2C9FACE5-2F16-4CCA-8B74-23EE17ABD688
:END:

- [[https://github.com/argyleink/prop-for-that][argyleink/prop-for-that]]

  #+begin_quote
  Expose what JavaScript knows but CSS can't see — as live CSS custom properties.
  #+end_quote

- [[https://docs.deno.com/runtime/desktop/][Deno Desktop]]

  ~deno desktop~ 是 Deno 開發的 Eletron、Tauri 替代，可以將 Deno 的項目變成一個桌面應用。

  [[https://docs.deno.com/runtime/desktop/#why-deno-desktop][Why deno desktop]]

- [[https://github.com/privatenumber/mac-ocr][privatenumber/mac-ocr]]

  #+begin_quote
  macOS CLI for OCR and searchable PDFs using Apple's Vision framework.
  #+end_quote

- [[https://github.com/ileivoivm/inkField][ileivoivm/inkField]]

  #+begin_quote
   Digital ink painting on WebGL + p5.js —
   records every gesture as JSON and replays them as time-based generative art.
  #+end_quote

- [[https://github.com/aradzie/keybr.com][aradzie/keybr.com]]

  #+begin_quote
  The smartest way to learn touch typing and improve your typing speed.
  #+end_quote

- [[https://github.com/templatical/sdk][templatical/sdk]]

  #+begin_quote
  Open-source drag-and-drop email editor.
  JSON templates, MJML rendering, framework-agnostic.
  Vue + TipTap inside.
  #+end_quote

- [[https://github.com/nodemailer/nodemailer][nodemailer/nodemailer]]

  #+begin_quote
  Send e-mails with Node.JS – easy as cake![fn:1]
  #+end_quote

- [[https://github.com/useplunk/plunk][useplunk/plunk]]

  #+begin_quote
  An open-source, self-hosted alternative to tools SendGrid, Resend or Mailgun.
  #+end_quote

* Emacs
:PROPERTIES:
:CUSTOM_ID: E992EF10-47D0-4026-ACC6-6E0ACDDD8DE9
:END:
- [[https://www.rahuljuliato.com/posts/emacs-31-around-the-corner#][Emacs 31 Is Around the Corner: The Changes I'm Already Daily Driving]] by Rahul

  Rahul 分享了一些 Emacs 31 的更新。

- [[https://www.chiply.dev/post-june-emacs-carnival][Juneau Something? Emacs Teaches You How to Fish!]] by Charlie Holland
- [[https://www.chiply.dev/post-ask-emacs][Emacs Teaches Emacs: The Missing README]] by Charlie Holland

  用 Emacs 學習 Emacs。

- [[https://ray-on-emacs.blogspot.com/2026/06/emacs-carnival-diary-part-1.html][Emacs Carnival: diary, Part 1]] by Raymond Zeitler

- [[https://emacsredux.com/blog/2026/06/20/essential-structured-navigation-and-editing-commands/][Essential Structured Navigation and Editing Commands]] by Bozhidar

- [[https://xenodium.com/ytr-youtube-radio-for-emacs][ytr: YouTube radio for Emacs]] by xenodium

* 一些话 | 摘抄
:PROPERTIES:
:CUSTOM_ID: 49216017-C83C-430F-A50E-7FA2D7151F1B
:END:
- [[https://michal.sapka.pl/2026/ai-in-art/][I'm ok with generated art]] by Michał Sapka

  #+begin_quote
  藝術存在於語境之中。
  一罐字面意義上的大便也是藝術，因為它傳達了作者花時間構思的東西。
  只有人類能夠創造這種語境，因為只有人類能思考出點子並賦予其形式。
  _藝術是與觀賞者的對話，而創作過程本身就是作品的一部分。_

  [[https://michal.sapka.pl/2026/ai-in-art/#:~:text=Art%20is%20in,piece][Source]]
  #+end_quote

- [[https://tracydurnell.com/2026/06/20/horror-romance-mirror-genres/][Horror and Romance as mirror genres]] by Tracy Durnell

  #+begin_quote
  我最近又在思考關於文學類型的話題，思索著 _浪漫小說與恐怖小說是否就像硬幣的兩面。_
  我與一位讀過大量恐怖小說的朋友交換了心得，我們驚訝地發現兩者竟如此互為鏡像。
  這兩種類型都是強大的敘事模式：
  _一種想像可能發生的最壞情況；另一種則想像最好的情況。_

  [[https://tracydurnell.com/2026/06/20/horror-romance-mirror-genres/#:~:text=%E2%9D%A4%EF%B8%8F-,I%E2%80%99ve,best][Source]]
  #+end_quote

- [[https://riverseeber.net/blog/post/big-tech-mutual-aid-and-the-social-web/][Big Tech, Mutual Aid, and the Social Web]] by River

  #+begin_quote
  人們正渴望有一種方法可以逃離大科技公司。
  我們不能因為過於迂腐而浪費當下這個黃金機會。
  我們需要邀請那些不太懂技術的朋友加入社交網絡，而不是用大量的技術術語讓他們感到被排斥。
  給他們最基本的資訊，讓普通人能理解，然後幫助他們開立帳戶。
  我們不能讓這些東西看起來很混亂，否則在我們擺脫大科技公司的過程中，沒有人會願意加入我們。

  [[https://riverseeber.net/blog/post/big-tech-mutual-aid-and-the-social-web/#:~:text=revolution%2E-,People,from%20Big%20Tech][Source]]
  #+end_quote

- [[https://aeon.co/essays/literature-fans-should-welcome-ai-as-a-fellow-wordsmith][Words, words, words]] by Martin Puchner

  #+begin_quote
  讀者反應批判於 1970 和 80 年代在德國和美國興起，它挑戰了傳統觀點。
  傳統觀點認為，文學是由一位（或多位）作者利用不同媒介（手稿卷軸、印刷書籍）創作，
  然後通過中間渠道（圖書館、書店）傳遞給讀者，最後由讀者閱讀。
  德國的沃爾夫岡·伊瑟爾（Wolfgang Iser）和美國的斯坦利·費什（Stanley Fish）等理論家認為，這種看法過於草率。
  _如果假設文學只是被困在書封之間的東西，那就忽略了讀者，_
  _而事實上，讀者正是通過閱讀行為共同創作了文學。_
  _文學並非紙上的文字，而是正在被讀者閱讀的紙上文字。_
  _在最極端的形式下，這意味著文本如何（以及由誰）編寫並不重要，重要的是它如何被閱讀。_
  _閱讀行為就是一切，作者寫下的文字僅僅是閱讀行為發生的藉口。_

  [...]
  那年聖誕節回家時，我向家人和朋友講述了這個令人震驚的主張：
  _文學並非他們自豪地展示在書架上的東西，而是只有在他們開始閱讀時才會產生的東西。_

  [[https://aeon.co/essays/literature-fans-should-welcome-ai-as-a-fellow-wordsmith#:~:text=Reader%2Dresponse,started%20reading][Source]]
  #+end_quote

- [[https://protesilaos.com/politics/2026-06-22-strategic-consequences-us-iran-deal/][On the strategic consequences of the US-Iran deal]] by Protesilaos

  #+begin_quote
  多極世界秩序正不可阻擋地興起。這並不一定意味著世界會變得更美好。
  是的，它標誌著美國主義及更廣泛的西方霸權的終結，
  但同時也敲響了聯合國的喪鐘，至少在實質內容上是如此。
  _國際法將真正讓位於局部性的權力安排，_
  _這些安排將被編纂在國家間的公約中，而不再參考一個凌駕於一切之上的法律框架。_
  _因此，一個日益分裂的世界正降臨在我們面前。_

  [[https://protesilaos.com/politics/2026-06-22-strategic-consequences-us-iran-deal/#:~:text=ignored%2E-,The,us][Source]]
  #+end_quote

- [[https://substack.com/@girl390511/note/c-250961745][girl]]

  #+begin_quote
  i love saying "of course" instead of "you're welcome,"
  like of course i'm helping you that's what i do,
  you were foolish to even consider an alternate dimension in which i'm not helping you.
  you idiot. you absolute buffoon.
  #+end_quote

* 多媒体
:PROPERTIES:
:CUSTOM_ID: 6D8EFC29-8BF8-4B89-8DF2-22994CEB4CFB
:END:
** 书
:PROPERTIES:
:CUSTOM_ID: 8D13A225-9A73-40E4-8636-E871E8AC83D5
:END:
** 影视
:PROPERTIES:
:CUSTOM_ID: 9759F538-9B89-4A5D-991E-B263FD1F7D76
:END:

** 视频
:PROPERTIES:
:CUSTOM_ID: EC297AA9-397A-4BE4-8DEA-27C6170CE479
:END:

- [[https://www.bilibili.com/video/BV15gj767EeK/][散养忏悔录]] (05:16) by 皮欧皮皮
- [[https://www.bilibili.com/video/BV1dTjh6dE12][这个骗子估计晚上睡觉都会想起那几个字，作为一个销冠必须拿的住一切]] (03:02) by 一只鱼雨鱼

** 音乐
:PROPERTIES:
:CUSTOM_ID: 56748DF7-4881-4C32-8746-392CFC64A9C3
:END:

** 游戏
:PROPERTIES:
:CUSTOM_ID: 95ED0F81-4202-4D61-A525-0C3C7055FFF3
:END:

- [[https://www.bilibili.com/video/BV1U6jz6KErp][王老菊教你断剑奇侠·S3-ep00：包氏创业记]] (1:17:38)
- [[https://www.bilibili.com/video/BV1bwj863E1t][王老菊教你断剑奇侠·S3-ep01：小本买卖堂堂正正]] (1:16:32)
- [[https://www.bilibili.com/video/BV1cuj26rEVA][王老菊教你断剑奇侠·S3-ep02：有氧教练]] (1:14:44)
* Footnotes
:PROPERTIES:
:CUSTOM_ID: 84F58099-C2C9-4291-8FF4-439645B1672C
:END:

[fn:1] easy as cake 的意思是「易如反掌」，是 [[https://www.phrases.org.uk/meanings/as-easy-as-pie.html][easy as pie]] 的變體。
