#+title:      讀《13·67》
#+export_file_name: 讀《13·67》
#+date:       [2026-09-28 Mon 09:20]
#+filetags:   :book:published:
#+identifier: 20260927T195641
#+bind:       denote-directory "~/git/taxodium/posts"
#+description: 《13·67》讀後感
#+language: zh-CN
#+author: Spike Leung
#+email: l-yanlei@hotmail.com
#+options: ^:{}
#+startup: content hideblocks

[[https://zh.wikipedia.org/zh-tw/13%C2%B767][《13·67》]] 是 [[https://zh.wikipedia.org/wiki/%E9%99%B3%E6%B5%A9%E5%9F%BA][陳浩基]] 寫的一本推理小說，
書名《13·67》含義是從 2013 年到 1967 年之間的故事，以香港和當時的一些歷史事件為背景。
整本小說由 6 個相對獨立的案件組成，通過反複出現的人物將故事串聯起來，每個獨立案件都挺精采的。
作為一本推理小說，我覺得這几個故事已經挺好的了，看得得過癮，
但小說還在結尾給我一個意想不到的結局，讓這本小說在我心裡又上了一個高度。
從小到大接触了很多香港的警匪片，也去過几次香港，書裡的地點、對話、用語等都給我一種熟悉感。

書裡打動我的，除了精彩的推理故事，還有人物的選擇和坚持：

- 有人只是把員警當作一份換取薪資的職業；有人把員警當作除暴安良、维持正义的神圣工作。
- 有人只因穿同一件制服便当成自己人，盲目支持；有人理性思考，坚守信奉的理念，秉持公羲。
- 有人選擇保护员警的招牌，掩埋事實，利用虚构的事情来巩固市民的信任；
  有人選擇保市民的安全，實事求事，敢於承認錯誤，始終把生命放在更高的位置。

坚持自己的理念有時很不容易，過程中會有很多阻力，也有很多誘惑，有時走著走著，可能就變了樣。
坚持有時也需要極大的勇氣。

#+begin_details
#+html: <summary>書摘</summary>

#+begin_quote
“多做多错，少做少错，不做不错”的说法，不时传进骆督察的耳朵。
骆督察一九八五年投考员警，是因为对员警这“身分”有一份憧憬，
在他眼中，员警是除暴安良、维持正义的神圣工作。
但对不少新入职的后辈来说，员警不是“身分”，只是“职业”，
“嫉恶如仇”、“警恶惩奸”不过是纸上谈兵，
不求把工作做好，但求把工作做完，
保持良好的考评纪录，尽快晋升至安逸高薪的职位，安然待到退休，领取优渥的退休金和长俸。
#+end_quote

#+begin_quote
“直接教唆他人犯罪是最愚蠢的方法。
要令一个人去杀人，只要制造条件，植入一丝恨意，再让那点仇恨慢慢发酵。
到了某个时刻，那股仇恨就会化成杀意，
然后遇上某个机遇，普通人就会变成凶手一当然，以上只是我随便说的意见。”
#+end_quote

#+begin_quote
而关振铎和骆小明两师徒，反而时常在寒冬中喝着冰冻的啤酒，在空旷的球场观众席碰面，
一来他们不怕谈到一些工作上较敏感的情报时被旁人听到，
二来关振铎经常说，在酒吧喝酒太不划算，
反正他们不过是要把酒聊天，到便利商店或是超级市场买几罐特价啤酒，
在球场喝跟在酒吧喝其实没有分别——
“酒吧喝一杯的价钱，可以换成在超市买三罐，我为什么要这么笨让人家赚？
要吃花生的话，去买一包也不过是十元八块吧？”
每次骆小明邀请关振铎上酒吧，师傅都会如此回答。
#+end_quote

#+begin_quote
“可能有，可能没有。”
关振铎摊摊手，笑道：
“案件中的细节，有九成是无用的，但万一错过余下的一成，却往往令案件破不了。”
#+end_quote

#+begin_quote
“可是，我们利用虚构的事情来巩固市民的信任，这份信任还有意义吗？”
#+end_quote

#+begin_quote
放了手便不要回头，回头只会让自己痛苦。
Ellen 的决定是对是错，都是她一个人的责任，你跟她说了，她不听，你就没权利扭转她的想法。
如果你自问是她的朋友，
你只能做的，是在她孤立无援时站在她身旁，而不是硬把自己的价值观塞进对方脑袋。
恋爱中的女人是盲目的，你愈说，她便愈固执。
#+end_quote

#+begin_quote
“我每次经过立法局大楼，我都会抬头看看那女神像。
神像双眼蒙布，是代表法律精神不偏不倚，对所有人都公正严明，
天秤代表法院会公平地衡量罪责，剑则是象征无上的权力。
我一直想，员警就是那把剑，为了消灭罪恶，员警必须拥有强大的力量；
可是，我们不是天秤，判断罪责、刑罚是法院的责任。
我可以用尽一切手段捉拿犯人，诱骗他们招供，
但我所做的，只是把他们送上天秤上，让公义去衡量他们是否有罪。
我们没有权力去决定什么是‘大义’。”
#+end_quote

#+begin_quote
他当然知道听从歹徒所言，不报警独自处理是最愚蠢的做法，
因为无论肉票的家人报不报警，匪徒收赎金后殺人的机率也一样，不过是一半一半。
要跟绑匪周旋，尽力救助人质，有警方作后盾是最保险的做法[...]
#+end_quote

#+begin_quote
“我认同警员要互相扶持，同仇敌忾，
但首要条件是大家有共同的理念，秉持公羲，
单纯因为穿同一件制服便当成自己人，盲目支持？这太愚蠢了。
警队的贪污问題已经大到不能自我疗愈的地步，要清除瘀血，便要靠外力，
我一向很讨厌‘跟车跑’的懦夫做法，
既然挡在车前会被撞，我便在车旁做手脚，偷偷从中破坏，令这台车子被瓦解吧。”
#+end_quote

#+begin_quote
事件扰攘期间，附近的店员店东都探头偷看，我想他们并不是好奇，而是担心发现炸弹，看看要不要逃跑。
警车离开后，现场回复平静，我收拾好碎玻璃，回到原来的位子，继续顾店。
何先生回来时，我只简单报告一下，说员警抓了个出言冒犯的男人，打破了一个瓶子。
何先生叹了一句：“唉，这个时势还是别乱说话，烦恼皆因强出头，保持沉默才能活得长久啊···”

的确是这样吧？保持沉默才能活得长久…不过，会不会沉默下去，到头来默默地遇害呢？
#+end_quote

#+begin_quote
只要你走在街上，便有可能被炸死炸伤，
我本来挺同情工人的，可是，如今我实在无法认同他们，
左派说，这是“以暴易暴”，是“必要之恶”，要对付英国人，一点牺牲是值得的。

我实在无法理解，伤害自己应该保护的人，有什么“值得”。
#+end_quote

#+begin_quote
为了找客户，他每天跑遍香港九龙，所以他遇上示威衡突和炸弹的机会比我大得多。
我跟他说要小心一点，他总会回答：
“阎王叫你三更死，谁敢留人到五更？
怕死的话便赚不了钱，赚不到钱，咱们便会饿死。
横竖都要死，还怕什么？人要冒险，才能得到世间财嘛！”
#+end_quote

#+begin_quote
我们当员警的，有时要挨饿工作，为了追捕犯人可能连半滴水都没得下肚，
但你是市民，没道理要你跟我一样。
其实我也没吃午饭，如果我一个人追查，我便会跳过不吃，这顿饭算是你带挈我的。
#+end_quote

#+begin_quote
“在杂差房被殴打、被拷问是常识，你认为告诉那些家伙，他们会相信吗？
杜自强就是知道你为人正直，在街坊之间有口碑，才指名找你。
可是你因为上级的几句话，便放弃了。
当时你也犹豫过吧？
因为你知道，杜自强跟苏松不一样，他不是狂热者，只是个不幸的人。
可是你无视自己信任的事实，为了保住自己的工作和在警署的人际关系，听从那你不认同的命令。”

“我……我……”阿七无法反驳。

“你为了什么「警队的价值」连命也可以不要，去拆一号车的炸弹。
可是，昨天有两个无辜的小孩，却因为你失去宝贵的性命。
你要保护的，到底是员警的招牌？还是市民的安全？
你效忠的是港英政权，还是香港市民？”
我以平淡的语气问道，
“你，到底为什么要当员警？”
#+end_quote

#+begin_quote
我本来没打算为这部作品写后记或自序的，
因为我想，作品被作者“生”出来后，文本有其生命，读者从它身上看到什么、领略到什么，
是读者的自由，是独一无二的个人经历。
与其由作者说一堆有的没的，不如让读者自行体会。
#+end_quote

#+begin_quote
我不知道，坚强、无私、正义、勇敢、忠诚地為市民服务的员警形象，能否再次建立，让香港的小孩子能再次以警队为荣。
#+end_quote
#+end_details
