#+title:      近期觀影
#+subtitle: 無間道三部曲、醉好的時光、阿波羅 13 號
#+export_file_name: movie-2026-07-22
#+date:       [2026-07-22 Wed 22:27]
#+filetags:   :draft:moive:preview:
#+identifier: 20260722T222752
#+bind:       denote-directory "~/git/taxodium/posts"
#+description: 近期觀影記录󠄃： 無間道三部曲、醉好的時光、阿波羅 13 號
#+language: zh-CN
#+author: Spike Leung
#+email: l-yanlei@hotmail.com
#+options: ^:{}
#+startup: content hideblocks

*無間道三部曲 (Infernal Affairs)*

Bilibili 上刷到了無間道的片段，就找來看了看，本來只是想重看一遍無間道的，
找資源的時候找到了三部曲，就干脆都看一遍好了。
下載的時候，最想看的第一部迟迟沒下好，就先看了第二部，陰差陽錯地竟然看對了順序。
無間道三部曲，按故事的時間順序排的話，是 [[https://zh.wikipedia.org/wiki/%E7%84%A1%E9%96%93%E9%81%93II][第二部]] ➙ [[https://zh.wikipedia.org/zh-tw/%E7%84%A1%E9%96%93%E9%81%93][第一部]] ➙ [[https://zh.wikipedia.org/wiki/%E7%84%A1%E9%96%93%E9%81%93III%EF%BC%9A%E7%B5%82%E6%A5%B5%E7%84%A1%E9%96%93][第三部]]，其中第一部是最經典也是最好看的。

韓琛是一個黑帮小頭目，對黑幫老大倪坤忠心耿耿，也與督察黃志誠相當友好他對倪家忠心耿耿。
但他的妻子 Mary 不甘他屈居倪家之下，就指使手下劉健明去干掉了倪坤，黑帮陷入混亂，
原來的几個黑幫頭目開始蠢蠢欲動，倪坤的次子倪永孝上位，用過人的手段穩住了黑帮，有當新龍頭的架势。
倪坤的私生子陳永仁和倪家關係不好，一心只想當警察，在警校表現优异，但他偽造的家庭背景被查出，被警校革除，
但他仍然一心嚮往能夠擔任警察，於是接受黃志誠督察的特別任務，去黑幫擔任了臥底。
韓琛的手下劉健明也同樣被安排了去警察里當臥底。
倪永孝殺了那几個有反目之心的黑帮頭目，但對他忠心的韓琛他也不放過，
最後韓琛和黃志誠達成了合作，解决了倪永孝，而韓琛順势成了最大的黑帮頭目。

以上是第二部，也就是前傳的大致劇情。
里面我覺得演的最好的是扮演倪永孝的吳鎮宇，
而兩個臥底，演陳永仁的余文樂感覺是亳無演技，
看著好木訥，完全看不出來他在警校有多优秀，也看不出來當臥底的機敏，像游离在電影之外；
而演劉健明的陳冠希除了帥也沒啥演技可說。

第二部的劇情會讓我聯想到很多 [[https://zh.wikipedia.org/zh-hant/%E6%95%99%E7%88%B6_(%E9%9B%BB%E5%BD%B1)][教父]] 里的情節：
都是黑老大去世後，儿子接手以凶狠的手段解决了敵人；都有臥底、背叛、炸車的情節。

三部曲中，我覺得第二部不看也不影响無問道要表達的內容。

第一部銜接著第二部的劇情，韓琛成了老大，開始做毒品生意，影片開頭就在講他們在交易，
而警方也在监視他們，準備抓他們個人贜并獲。
陳永仁在韓琛身邊當臥底給警方通風，而劉健明也在警方當臥底給韓琛报信，
在最關鍵的時候劉健明給韓琛附近所有人群發短信「有內鬼，終止交易！」，也是片中的一個名場面。
双方的臥底讓双方的計劃都落空了，双方也都知道了自己手下有內鬼，接著就開始在內部找內鬼，
兩個內鬼之間也在相互試探，嘗試找出對方。
最終兩個內鬼都找到了對方，約在了天台見面，此時韓琛已經死了，
劉健明也沒必要再當臥底，於是他想洗白，做個好人，
但身為警察的陳永仁是不會認同的，他脅持著劉健明，要去揭發他，同時也結束自的臥底生涯。
誰料原來進入警局的臥底不止一個，另一個臥底過來解决了陳永仁，并希望劉健明以後罩著他，
但劉健明把他也殺了，成功完成了洗白。

第一部里所有角色的演技都很不錯，尤其喜歡飾演陳永仁的梁朝偉。
兩個臥底相互試探的劇情充滿了張力，是很好看的一部。

第三部銜接著第一部的劇情，在第一部里，我想劉健明是希望和陳永仁當朋友的，
兩人都曾經一起在警校訓練，也都很喜歡聴歌，對音響設備有相似的追求，
於是陳永仁的死某種程度上也影響了他。
他向往陳永仁，他臥底的身份和警察的身份開始相互拉扯，
最終人格分裂，把自己当作了陳永仁抓住了身為卧底的劉健明，自己揭發了自己，
也嘗試自殺但沒成功，最後成了殘廢坐在輪椅上一直幻想著自己是陳永仁，一直在分裂的人格中拉扯，墮入了無間道。

第三部觀感一般，因為穿插了不同時間的叙事，加上表現劉健明人格分裂有一些幻想的劇情，
整體看起來會有點亂，劇情的張力也不如第一部。挺喜歡里面演楊錦榮的黎明，又帥又有演技。

無間道在片頭片尾都引用了一些佛經：

#+begin_quote
《涅槃經》第十九卷：「八大地獄之最，稱為無間地獄，為無間斷遭受大苦之意，故有此名。」

佛曰：「受身無間者永遠不死，壽長乃無間地獄中之大劫。」

「阿者言無，鼻者名間。為無時間，為無空間，為無量受業報之界。」

「無間有三，時無間，空無間，受業無間。犯忤逆罪者永墮此界，盡受終極之無間。」

地藏菩薩本願經卷上：「如是等輩，當墮無間地獄，千萬億劫，以此連綿，求出無期。」
#+end_quote

通過這些經文和電影的劇情，無間道三部曲想講的，
是當一個人背叛了自己，出賣身邊親友，日日活在虛假中時，
就像是墮入了 [[https://zh.wikipedia.org/zh-hant/%E9%98%BF%E9%BC%BB%E5%9C%B0%E7%8D%84][無間地獄]] (也称阿鼻地獄)，一生都在折磨著自己吧。

總的來說，作為犯罪警匪片，無間道三部曲還是不錯的，尤其是第一部。

*[[https://zh.wikipedia.org/zh-hant/%E9%85%92%E7%B2%BE%E8%AE%A1%E5%88%92][醉好的時光]]*

*[[https://zh.wikipedia.org/wiki/%E9%98%BF%E6%B3%A2%E7%BD%9713%E5%8F%B7_(%E7%94%B5%E5%BD%B1)][阿波羅 13 號]]*
