#+title:      Re:Bloggers, can we make better titles for our posts?
#+export_file_name: re-bloggers-can-we-make-better-titles-for-our-posts
#+date:       [2026-08-07 Fri 14:14]
#+filetags:   :draft:preview:response:
#+identifier: 20260807T141401
#+bind:       denote-directory "~/git/taxodium/posts"
#+description: 對 Bloggers, can we make better titles for our posts? 的一些回應
#+language: zh-CN
#+author: Spike Leung
#+email: l-yanlei@hotmail.com
#+options: ^:{}
#+startup: content hideblocks

文章包含一些負面情縮，也許會讓你感到不開心，請酌情往下閱讀。

-----

Michael Harley 寫了篇 [[https://michaelharley.net/posts/2026/06/15/bloggers-can-we-make-better-titles-for-our-posts/][Bloggers, can we make better titles for our posts?]]，
請你先去讀一遍原文吧，在這裡等你，几分鐘後再見 :)

-----

歡迎回來！接下來我想分享一些我的感受。

Michael Harley 說博客文章應該用描述性標題，讓人一眼就知關於什麼的，而不是一些不明所以的標題，
例如 「最近的想法...」，是關於的什麼想法，看不出來；
以及討厭標題黨，例如「他這樣做減掉了這麼多體重...」之類的標題。

這我也認同，通過標題能大致知道是關於什麼，如果感興趣就點進去看，不感興趣就可以略過了。
如果標題不明所以，但我又有點好奇，就會糾結要不要點進去看，
而當我點進去看了，發現也沒寫什麼嘛，就會有些失望，甚至是生氣。
當一個作者的訂閱流大多是這樣的，還大量更新，我就會取消訂閱了。
標題黨則是會有一種被欺騙的感覺，標題誘导你點擊，但裡面的內容會讓你後悔花時間去讀，我也很討厭。

我之前寫 Zine，標題是 Zine#X，看名字確實不知道裡面會有什麼，
大概知道是類似雜誌，內容會很雜，
但是我也想不到什麼更好的標題，裡面那麼多東西，你讓我怎麼在標題裡講完。
後來我開始加子標題，把其中我印象深的，或者希望讀者去看的部分寫進去，
其實也有點標題黨的嫌疑，因為我也是希望能够吸引讀者點進來看。
另一個好处也是方便我自己回忆每期 Zine 裡都大概寫了些什麼。
所以，讓模糊的標題多些描述性信息，對作者自己和讀者都是有帮助的。

但是，我也不完全排斥非描述性的標題，如果所有文章的標題都是描述性的，那也太無聊了，
類比書名，如果全都是實用類書籍的名字，不會太無趣了嗎？
如果標題奇奇怪怪，但內容意外的有趣，我會挺喜歡的，糟糕的是那些標題奇怪，內容也不怎麼樣的文章。

但 @@html:<small>@@(又有反轉？)@@html:</small>@@ 話又說回來了，
你是作者，那是你的博客，你愛怎麼寫就怎麼寫，
[[https://danq.me/2026/07/02/you-dont-have-to-blog-like-me/][你不必像別人一樣]]，儘管去寫就好了，寫出你自己的聲音，[[https://ratfactor.com/cards/personal-website#:~:text=There%20is,saying][這裡沒有錯誤答案]]，怎麼折騰都可以。

作為讀者，如果某些內容或某個作者你不喜歡，你就不要去訂閱或者取消訂閱，
看到了也忽略就好了，我們無法改變別人，但可以改變自己。

Michael Harley 的問題在於，
Bubbles 這個博客聚合平台不是他能控制的，會有什麼內容也不是他說了算，
我想如果 Bubbles 上能加一個過濾功能，
就能解决他的問題了，不想看的博客就過濾掉，也就不會看著心煩。
就算 Bubbles 不加這個功能，他也可以用 [[https://github.com/openstyles/stylus][openstyles/stylus]] 或 [[https://www.tampermonkey.net/][Tampermonkey]] 自己實現過濾。
例如，在 stylus 裡，加上這段樣式就可以隱藏某個博客：

#+begin_src css
  .entry:has(
    a[title="some.blog.com"],
    a[title="some.blog.com"],
    a[title="some.blog.com"],
    a[title="some.blog.com"]
  ) {
    display: none;
  }
#+end_src

說實話，Michael Harley 的這篇文章會讓我有些反感，
因為文章給我一種「你們都應該照我說的去做，否則你們都不應讓出現在 Bubbles」的感覺。
也許也他沒有這個意思，但作為讀者，我讀下來會產生這樣的感覺。

作為一個博客聚合平台，它應該盡可能地去包容各種各樣的博客，讓內容變得多樣，哪怕這些博客寫得「不够好」。
如果按個人喜好，這我不喜歡，那我不喜歡，最後平台的內容只會變得單一，反映的只是某個人的偏好。
前陣子中文博客圈裡看到有的聚合平台因為和博客作者不合，就隨便把對方的博客移除了，
某種程度我能理解，自己花精力維护的平台，要去容忍自己不喜歡的內容存在，心裡是會有些不舒服。
可是這樣的平台，就只是維护者自己的後花园罷了，不是一個開放公平的平台。
每個平台都有一些規定，如果博客作者沒有违反相關規定，他就可以繼續留下來，
而不是基於個人喜好行事，我會更喜歡這樣的平台。

回到 Michael Harley 的文章，他對「每週筆記」、「本週回顧」、「每週連結」類的文章也不喜歡，他的建議是：

#+begin_quote
這一點與其說是寫更好的標題，不如說是寫更好的文章。
我想很多人把這些文章當作鍛鍊寫作能力的工具。
我建議一個更好的工具是那個老掉牙的最愛：
寫關於部落格經營的文章，就像我現在正在做的一樣。

[[https://michaelharley.net/posts/2026/06/15/bloggers-can-we-make-better-titles-for-our-posts/#:~:text=them%2E-,This,here][Source]]
#+end_quote

#+begin_quote
如果你想鍛鍊寫作能力並養成習慣，另一個尋找寫作題材的好方法就是回應別人的文章。

這類型的文章比大雜燴式的文章好得多。

[[https://michaelharley.net/posts/2026/06/15/bloggers-can-we-make-better-titles-for-our-posts/#:~:text=%23-,If,posts,-%2E][Source]]
#+end_quote

大雜燴式的文章我自己也寫了不少，Zine 系列，日常系列都是如此，我訂閱的博客裡也有大量這類文章。
這種文章我覺得可以大致分成兩類，
一類是記录󠄃作者生活的，最近做了什麼、看了什麼、玩了什麼，像是公開的周記；
一類是收集連結的，罗列作者最近看到的覺得有趣、有用、有啟發的連結。

從讀者的角度，這類文章我會快速瀏覧一遍，大部分都是略讀，看到感興趣的我就仔細看看，花不了多少時間。
生活類的能讓我看到許多不一樣的生活，讓我感覺作者更像是一個活生生的人，
我還挺喜歡的，如果我看厭了，我取消訂閱就是了。
而我自己的 Zine 就是連結類的，連結類文章就是我的信息來源，我當然也喜歡。

從作者的角度，生活類是作者用來記录󠄃自己生活的，他們
