#+title:      咖啡問卷調查
#+export_file_name: a-coffee-questionnaire
#+date:       [2026-08-04 Tue 23:03]
#+filetags:   :coffee:draft:preview:
#+identifier: 20260804T230307
#+bind:       denote-directory "~/git/taxodium/posts"
#+description: 回答几個關於咖啡的問題
#+language: zh-CN
#+author: Spike Leung
#+email: l-yanlei@hotmail.com
#+options: ^:{}
#+startup: content hideblocks

從 coffee spills 那看到了 [[https://tallywinkle.bearblog.dev/coffee-questionnaire/][a coffee questionnaire]] ⸺ 一個關於咖啡的問卷調查，
我也很喜歡喝咖啡，對咖啡也很 [[https://www.youtube.com/watch?v=tuOflAfYh20][执著]]，所以也來回答一下。

* 每天喝幾杯咖啡？
:PROPERTIES:
:CUSTOM_ID: 7BE8791D-5C78-49F4-9777-CC8710EEC80B
:END:

一般就一杯，貪嘴的話就兩杯。

有一次探店，我試過一天喝了近 5 杯咖啡，喝這麼多咖啡并不會覺得很精神，反而給心臟負擔，會有些不舒服。

* 什麼時候喝咖啡？
:PROPERTIES:
:CUSTOM_ID: 1C131E94-9317-4E87-AAE0-EAD92E906E3E
:END:

在家：

取决於我几點起床，起的早，离中午還有好一段時間，
我會在洗漱之後馬下製作一杯，大多時候是拿鐵，因為裡面有很多奶，就當是早歺了，可能也會順便吃點餅干；
如果起的晚，那一般是在飯後，下午 2 ~ 4 點左右喝，一般不會超過下午 6 點，除非我忍不住。

如果是喝手冲，我會傾向於在下午喝，因為早上剛起來的時候，味覺還沒恢複，什麼味道都喝不出來。
所以早上我喝拿鐵會更多。

上班： 在上班前我基本都會喝上一杯，大概是早上 9 ~ 10 點左右；下午還喝的話，大多數是在午睡前後。

* 你的咖啡都怎麼喝？
:PROPERTIES:
:CUSTOM_ID: 8B80F4F9-4DCF-48B2-B230-3A2FFC90528F
:END:

在家：

大多時候是用摩卡壺做拿鐵，一般是喝熱的。
如果想喝冰的，我會加冰块，但冰块化了會稀釋味道，
現在的做法是把做好的拿鐵直接放進冰箱的冷凍层凍上半小時再喝，
這樣就不會被稀釋了，也能喝到冰的，口感喝起來像便利店裡的瓶装拿鐵。
有時忘了買牛奶，我會把摩卡壺的咖啡液用熱水稀釋成美式；
偶尔也會把咖啡液和穌打水或其他液體混合試試。

偶尔會做手冲喝，但現在對手冲失去熱情了，偶尔冲得好才會覺得


上班： 去瑞幸買拿鐵或美式，有時也會去 Manner。

* 你喜歡咖啡口味的食物嗎？
:PROPERTIES:
:CUSTOM_ID: 6E27BF6E-C15F-4DEB-936F-B830B9D9D5FC
:END:

不討厭，但也說不上很喜歡。

* 喝咖啡時喜歡配什麼食物？
:PROPERTIES:
:CUSTOM_ID: 73D2F8F3-58B8-4600-B0D9-B1A78117791B
:END:

如果是喝手冲，一般不會搭配食物，手冲主要喝的是咖啡的風味，去感受它的酸甜苦和液體質感，
食物的味道會影响咖啡的風味，我會覺得浪費了一杯咖啡。

就看我是不是在意一杯咖啡的味道，如果比較在意，我就不會搭配食物；
如果不在意就無所謂了，此時咖啡對我來說就是一杯解渴用的飲料，也沒有什麼一定要搭配的食物，

* 你有最喜歡的馬克杯嗎？
:PROPERTIES:
:CUSTOM_ID: 20539DB9-08BA-4F77-88C1-9B5A851E5353
:END:

* 為什麼喜歡咖啡？
:PROPERTIES:
:CUSTOM_ID: 03FEF99C-E816-4E0A-B138-23F59015110F
:END:

* 我的咖啡設備
:PROPERTIES:
:CUSTOM_ID: D72E40B2-6196-4E18-8492-72C56BF42D8A
:END:

* 我最常點的三種咖啡
:PROPERTIES:
:CUSTOM_ID: 8C633946-B7D3-4FE2-B58A-B6977A81C133
:END:

一般就點拿鐵，大多時候不會踩雷。
如果有手冲的話也會試試，但我很少喝到做的好的。
最後是美式，就當是有一點味道的水，解喝用，對味道不會有什麼期待。

https://tallywinkle.bearblog.dev/coffee-questionnaire/
https://journal.james-zhan.com/coffee/
https://syls.blog/coffee/
