#+title: Weekly#8
#+date: 2024-09-17T23:38:22+08:00
#+keywords[]:
#+description: ""
#+tags[]: weekly
#+categories[]: weekly
#+autoCollapseToc: true

* News | Article

** [[https://nesslabs.com/burnout-vs-boreout][burnout-vs-boreout]]

=burnout= 指的是被耗尽了，倦怠了； =boreout= 指的是厌倦，觉得无聊。

工作中也出现过被耗尽(burnout)的情况，当时同时需要好几个需求，而且 deadline 都集中差不多的时间。

工作日一直加班到很晚去赶进度，一直被项目催进度，但是工作量在那，还是做不完，只能周末再加班。

本来之前已经加班过一个周末了，一而再地无法安排自己的时间，投身于工作中，最终让我情绪有点崩溃。

有的需求也是一些重复性的工作，不困难，但很繁琐也消耗时间，时间久了也会觉得厌倦(boreout)，做起来没啥动力。

有时不是因为自己没完成工作，而是需要等待别人配合调试，而对方又慢，拖到很晚才调完，

中间其实也没我什么事，就又要加班到很晚，加班也没什么回报，就感觉非常的不值得，身心俱疲。

至于如何调解，只能是周末做点喜欢的事情放空，慢慢让情绪恢复回来。

有时做到一些比较感兴趣的功能，也能恢复一些兴奋和主动，找到写代码的乐趣。

文章提到倦怠首先要认识到是情绪的问题，可能也是源自一种失控感，失去了对自己生活的控制。

这时候就需要去给自己一些空间，去想想现在的状况是不是自己想要，自己想要的是什么；或者找朋友同事沟通一下；以及做一些小的改变去一点点尝试改变现状。

** [[https://larahogan.me/blog/be-a-thermostat-not-a-thermometer/][Be a thermostat, not a thermometer]]

#+begin_quote
我喜欢用温度计和恒温器来比喻这个概念。

如果你在寻找有关某人感受的信号，这就有点像你在试图测量他们的情绪温度。

你就是一个温度计。当他们微妙地散发出奇怪的气息时--他们皱着眉头，

回答你的问题时比平时少说了几句话，等等--你就注意到他们的体温不一样了。

当他们的杏仁核被劫持时，你可能会发现他们的行为发生了很大的变化（他们和你吵架、完全沉默、翘会等等）

--用温度计的比喻来说，他们在发烧，而你发现了这一点。

既然我们知道一个人的行为改变会导致其他人改变他们的行为，我们就可以认为他们就像一个恒温器：

他们在为整个房间设定温度。 即使双方都是无意的。

这就是我们的思维方式：反映别人发出的 "氛围"。
#+end_quote

当你感受到对方情绪变化，可以选择成为"恒温器"，去调整情绪，但这还挺需要技巧的。

** [[https://shankarganesh.blog/2024/08/29/growing-taste-to-build-better-products/][Growing your taste to build better products]]

#+begin_quote
如果你一生只看过两部电影，那么你很可能会认为这两部电影都很不错。

但如果你看过上千部电影，你就会真正懂得如何分辨好坏，以及从糟粕中发现精华。
#+end_quote

接触得多了，就分得出什么是好的，什么是差的。

产品设计，UI 设计，写作，编码也是如此。

** [[https://gabe.rocks/health/non-stop-eating/][Troubles with Food]]

#+begin_quote
+ 不摄入超过所需热量
+ 获取所需的全部营养
在了解以上两点的基础上，我认为最佳途径是尽量从所需的热量中获取最多的营养。
#+end_quote

#+begin_quote
自己做饭能让你更好地（但不是完全地）了解食物的制作过程。

如果一个人要花时间准备饭菜，希望他能节省精力，做出高质量的饭菜，而不是垃圾食品。
#+end_quote

#+begin_quote
...是因为坏习惯会累积，如果你熟悉复利的概念，你就会明白， 即使是微小的偏差，在很长一段时间内也会累积成巨大的问题。

我个人就犯过没有及早正视这些错误的错误，我不得不花费大量精力来扭转这些错误造成的损失。

与经济利益不同，健康问题没有破产，只有死亡。
#+end_quote

#+begin_quote
部分原因在于，我完全不愿意认真研究如何改变这些习惯。

它们在我的生活中根深蒂固，以至于我觉得不可能改变它们，甚至连缓和程度都无能为力。

我相信这在很大程度上是因为随着习惯的累积，你会变得固步自封，即使是一些小事，改变起来也会觉得是一件难以完成的任务。

...我想和大家分享的是，无论你已经走得多远，总有很多事情可以做来扭转局面。
#+end_quote

#+begin_quote
...克服强迫性进食需要直接面对其原因。

原因可能是无聊、压力、痛苦（情绪或身体上的），这些都是处于我这种情况的人不可避免会遇到的慢性问题。

与我处于这种情况的人会理解强迫性进食与情绪性进食是多么紧密地交织在一起。
#+end_quote

#+begin_quote
对我来说，最难的一课就是认识到这是可以改变的。

无论你强迫性回避的情感痛苦来源是什么，我向你保证，只要付出时间和努力，就一定有办法解决它们。
#+end_quote

#+begin_quote
...我几乎完全戒掉了咖啡因。

虽然这对我的工作效率绝对是一个暂时的严重打击，但我可以高兴地说，

我已经反弹回来了。现在，我的工作效率比以往任何时候都高...

奇怪的是，戒掉咖啡因后，我注意到了两件事。

+ 梦境更加详细和生动（原因不明）
#+end_quote

对于一个每天都需要至少一杯咖啡的人来说，咖啡因戒断还是很难受，会头痛。

#+begin_quote
如果上楼梯、走路或搬东西等简单的任务让您觉得几乎完全遥不可及，您就不会想到要四处奔波和进行各种活动。

最终，一旦这些事情看起来遥不可及，它们就会逐渐变成实际上遥不可及。
#+end_quote

#+begin_quote
人不能习惯于安逸，因为随着时间的推移，最轻微的不适也会变得难以忍受。
#+end_quote

#+begin_quote
你必须接受一个事实，那就是很有可能在这一刻，你无法做任何事情来纠正你的状况，相反，你需要集中精力来创造动力。

你的生活就像水中的大型航空母舰。你的体重越重，哪怕是稍稍转过身来都需要更多的时间和努力。

随着时间的推移，你的良好改变会为更好的改变打开更多的大门。

这才是真正的过程，愈合你的低谷，增长你的高潮。当你的航船不再走错方向，而是朝着正确的方向前进时，你会感觉好很多。
#+end_quote

** [[https://justforfunnoreally.dev/][Just for Fun. No, Really.]]

#+begin_quote
与诗人一样，程序员的工作也只是稍稍脱离了纯粹的思考。

他通过发挥想象力，在空中建造城堡。很少有创作媒介如此灵活，如此容易打磨和再加工，如此容易实现宏伟的概念结构....。

然而，程序构造与诗人的文字不同，它是真实的，因为它可以移动和工作，产生与构造本身分离的可见输出。

--Fred Brooks, The Mythical Man-Month
#+end_quote

有时编程确实是一种乐趣，带来成就感和快乐。

但是当做着一些简单机械的重复工作，也会觉得枯燥。（真希望以后都能 AI 处理这部分工作）

** [[https://bootcamp.uxdesign.cc/why-design-systems-can-be-a-hot-mess-and-how-to-deal-with-it-9ead721a2c15][Why Design Systems Can Be a Hot Mess (and How to Deal with It)]]

设计系统由一系列的规则/风格，规范，组件等构成，要避免它变得一团糟，需要所有人都达成共识，持续维护更新，保留一定的灵活性。

除了设计系统，编码规范，文档其实也是同理的，都需要持续维护更新。

#+begin_quote
定期安排审查，确保文档与您最新的 Spotify 播放列表一样新鲜。
#+end_quote

* Tutorial

** [[https://www.susanrigetti.com/physics][So You Want to Learn Physics…]]

物理学学习路径，里面还有关于哲学和数学的学习路径。

** [[https://gvwilson.github.io/sql-tutorial/][An Introduction to SQL for Weary Data Scientists]]

一个 SQL 入门教程。

** [[https://vvyst0z7tes.feishu.cn/wiki/HQuawZepyiwNiNkImw6c00IXnmc][英语学习指南]]

一份飞书文档，学习英语时可以参考。

* Code

** [[https://www.joshwcomeau.com/css/has/][The Undeniable Utility Of CSS :has]]

[[https://developer.mozilla.org/en-US/docs/Web/CSS/:has][:has]] 选择器的介绍和一些用例。

=p + a= 表示的是紧接在 =<p>= 后的 =<a>= ，使用 =:has= 可以将这个顺序反过来。

=p:has(+ a)= 表示的是后面紧跟着 =<a>= 的 =<p>= 。

#+begin_src html
  <html>
    <head>
      <style>
        p:has(+ a) {
          color: pink;
        }
      </style>
    </head>
    <body>
      <p>My blog.</p>
      <a href="https://taxodium.ink/">taoxidium</a>
    </body>
  </html>
#+end_src
#+begin_export html
<iframe style="width:100%" srcdoc=" &lt;html&gt; &lt;head&gt; &lt;style&gt; p:has(+ a) { color: pink; } &lt;/style&gt; &lt;/head&gt; &lt;body&gt; &lt;p&gt;My blog.&lt;/p&gt; &lt;a href=&#34;https://taxodium.ink/&#34;&gt;taoxidium&lt;/a&gt; &lt;/body&gt; &lt;/html&gt; "></iframe>
#+end_export


** [[https://nochlin.com/blog/6-techniques-i-use-to-create-a-great-user-experience-for-shell-scripts][6 Techniques I Use to Create a Great User Experience for Shell Scripts]]

- 详细的错误信息输出和输入验证，便于用户快速发现问题
- 输出样式，设置色彩可以让信息更明显（但是无法显示颜色时(=\033[0m=)，就会有很多影响阅读的东西）
- 执行步骤的输出，打印每一个执行的语句，让用户知道执行到了什么地方
- 使用 =set -e= 和 =set +e= 在需要的地方出现错误后终止代码
- 兼容不同平台的脚本，通过判断平台增加分支处理

** [[https://sinja.io/blog/get-maximum-out-of-your-font][Features of your font you had no idea about]]

平时写 CSS，也就是设置一下 font-family, font-weight, font-size, 但是实际上字体还有很多设置项，可以了解一下。

** [[https://mp.weixin.qq.com/s/TLyQON9Tt_uMUbr5U7Pnyg][暗水印显隐术助力生产排障提效]]

由浅入深讲解如何设置网页水印。

** [[https://ishadeed.com/article/display-contents/][CSS display contents]]

=display: contents;= 的介绍，第一次知道这个值的用法。

它的作用是将包裹元素的盒子“移除”，像是盒子不存在一样，或者可以理解成[[https://ishadeed.com/article/display-contents/#thinking-of-contents-as-ungrouping-of-elements][取消元素的“分组”]]。

#+begin_src html
  <html>
    <head>
      <style>
        .container {
          border: 2px solid pink;
        }
      </style>
    </head>
    <body>
      <div class="container">
        <h1>without display:contents;</h1>
        <p>some content</p>
      </div>
    </body>
  </html>
#+end_src
#+begin_export html
<iframe style="width:100%" srcdoc=" &lt;html&gt; &lt;head&gt; &lt;style&gt; .container { border: 2px solid pink; } &lt;/style&gt; &lt;/head&gt; &lt;body&gt; &lt;div class=&#34;container&#34;&gt; &lt;h1&gt;without display:contents;&lt;/h1&gt; &lt;p&gt;some content&lt;/p&gt; &lt;/div&gt; &lt;/body&gt; &lt;/html&gt; "></iframe>
#+end_export


#+begin_src html
  <html>
    <head>
      <style>
        .container {
         border: 2px solid pink;
         display: contents;
        }
      </style>
    </head>
    <body>
      <div class="container">
        <h1>with display: contents;</h1>
        <p>some content</p>
      </div>
    </body>
  </html>
#+end_src
#+begin_export html
<iframe style="width:100%" srcdoc=" &lt;html&gt; &lt;head&gt; &lt;style&gt; .container { border: 2px solid pink; display: contents; } &lt;/style&gt; &lt;/head&gt; &lt;body&gt; &lt;div class=&#34;container&#34;&gt; &lt;h1&gt;with display: contents;&lt;/h1&gt; &lt;p&gt;some content&lt;/p&gt; &lt;/div&gt; &lt;/body&gt; &lt;/html&gt; "></iframe>
#+end_export

* Cool Bit

** [[https://cyberb.space/notes/2024/how-i-added-maps-to-my-travel-posts/][How I Added Maps to my Travel Posts]]

作者想在博客中插入地图，并且满足三个要求：

- 不依赖第三方
- 构建时才生成
- 手机和电脑上需要看起来一致

主要是用 [[https://d3js.org/d3-geo][d3-geo]] 生成地图的 SVG 然后嵌入到页面中。

** [[https://purplesyringa.moe][purplesyringa]]

作者的博客网站挺好看。

** [[https://avestura.dev/blog/creating-a-git-commit-the-hard-way][Creating a Git commit: The Hard Way]]

用比 =git commit= 更基础的命令提交 git commit。

对于了解 git 的底层原理有帮助。

* Tool | Library

** [[https://www.transparenttextures.com/][Transparent Textures]]

选择颜色，模式，得到对应材质的 CSS 代码。

可能在需要一些材质背景的时候会有用。

* Music

** [[https://music.163.com/#/song?id=2623174984][太阳光明照我心 - 文兆杰]]

#+begin_quote
前途的事说不清

茫茫路何行

太阳光明照我心

敞亮向前进
#+end_quote

太阳照在身上，微风和煦的感觉让人觉得挺舒服和美好的。

有时迷茫，不如出门晒晒太阳散散步，和大自然接触接触，给自己一点放松的空间。

** [[https://music.163.com/#/song?id=64574][我什么都没有(Live) - 陈奕迅]]

#+begin_quote
我没有我没有没有

从乐趣到痛苦到悲欢爱恨全被折扣

...

梦里也会觉得快乐难求

连泪光都光不过黑夜尽头

不过不过我不用难受
#+end_quote

** [[https://music.163.com/#/song?id=2610722693][May A Flower Bloom - 頭士奈生樹]]

一首安静的歌，适合深夜听。
